Repository opensearch-project/documentation-website, pull requests merged in 2022-05, with the labels that each got.

#489 Add documentation for logstash-input-opensearch plugin
  _clients/logstash/read-from-opensearch.md
Labels: upcoming release

#551 Merge 2.0 changes into main
  _config.yml
  _data/alert.yml
  _data/versions.json
  _opensearch/install/plugins.md
  version-history.md
Labels: v2.0.0

#540 Removing deprecated metrics from PA documentation
  _monitoring-plugins/pa/api.md
  _monitoring-plugins/pa/reference.md
Labels: v2.0.0

#512 Remove type from all API requests and responses
  _im-plugin/index-transforms/index.md
  _im-plugin/index-transforms/transforms-apis.md
  _im-plugin/ism/api.md
  _ml-commons-plugin/api.md
  _monitoring-plugins/ad/api.md
  _monitoring-plugins/alerting/api.md
  _opensearch/query-dsl/bool.md
  _opensearch/query-dsl/function-score.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/term.md
  _opensearch/rest-api/document-apis/bulk.md
  _opensearch/rest-api/document-apis/delete-document.md
  _opensearch/rest-api/document-apis/get-documents.md
  _opensearch/rest-api/document-apis/index-document.md
  _opensearch/rest-api/document-apis/multi-get.md
  _opensearch/rest-api/document-apis/update-document.md
  _opensearch/rest-api/explain.md
  _opensearch/rest-api/index-apis/create-index.md
  _opensearch/rest-api/ingest-apis/simulate-ingest.md
  _opensearch/rest-api/multi-search.md
  _opensearch/rest-api/search.md
  _opensearch/ux.md
  _replication-plugin/get-started.md
  _search-plugins/async/index.md
  _search-plugins/knn/api.md
  _security-plugin/access-control/cross-cluster-search.md
  _security-plugin/access-control/field-level-security.md
  _security-plugin/access-control/field-masking.md
Labels: upcoming release, v2.0.0

#496 Add shrink action to Index Management
  _im-plugin/ism/policies.md
Labels: upcoming release, v2.0.0

#561 Query DSL reorg and new TLQ example - linked with PR #483
  _opensearch/query-dsl/full-text.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/term.md
  _security-plugin/access-control/document-level-security.md
Labels: v2.0.0

#513 [issue 450] Deprecate terms
  _clients/data-prepper/data-prepper-reference.md
  _clients/data-prepper/get-started.md
  _clients/data-prepper/pipelines.md
  _dashboards/install/rpm.md
  _im-plugin/ism/policies.md
  _opensearch/cluster.md
  _opensearch/index-templates.md
  _opensearch/install/docker-security.md
  _opensearch/install/rpm.md
  _opensearch/query-dsl/full-text.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/term.md
  _opensearch/rest-api/cat/cat-allocation.md
  _opensearch/rest-api/cat/cat-cluster_manager.md
  _opensearch/rest-api/cat/cat-field-data.md
  _opensearch/rest-api/cat/cat-health.md
  _opensearch/rest-api/cat/cat-nodeattrs.md
  _opensearch/rest-api/cat/cat-nodes.md
  _opensearch/rest-api/cat/cat-pending-tasks.md
  _opensearch/rest-api/cat/cat-plugins.md
  _opensearch/rest-api/cat/cat-recovery.md
  _opensearch/rest-api/cat/cat-shards.md
  _opensearch/rest-api/cat/cat-snapshots.md
  _opensearch/rest-api/cat/cat-tasks.md
  _opensearch/rest-api/cat/cat-thread-pool.md
  _opensearch/rest-api/cat/index.md
  _opensearch/rest-api/cluster-health.md
  _opensearch/rest-api/cluster-settings.md
  _opensearch/rest-api/cluster-stats.md
  _opensearch/stats-api.md
  _security-plugin/access-control/document-level-security.md
  images/cluster.png
Labels: upcoming release, v2.0.0

#584 Add Node APIs [Edits to Lukas Vlcek]
  _opensearch/rest-api/cluster-stats.md
  _opensearch/rest-api/ingest-apis/index.md
  _opensearch/rest-api/nodes-apis/index.md
  _opensearch/rest-api/nodes-apis/nodes-hot-threads.md
  _opensearch/rest-api/nodes-apis/nodes-info.md
Labels: v2.0.0, 4 - Editorial Review

#521 Introduce Nodes APIs
  _opensearch/rest-api/cluster-stats.md
  _opensearch/rest-api/ingest-apis/index.md
  _opensearch/rest-api/nodes-apis/index.md
  _opensearch/rest-api/nodes-apis/nodes-hot-threads.md
  _opensearch/rest-api/nodes-apis/nodes-info.md
Labels: v2.0.0

#600 Removed OpenDistro from GET command (Issue #580)
  _security-plugin/access-control/api.md
Labels: 3 - Tech Review

#542 Add doc on action rollover min_primary_shard_size
  _im-plugin/ism/policies.md
Labels: v2.0.0

#420 Documentation for security roles to be used for DLS parameter substit…
  _security-plugin/access-control/document-level-security.md
Labels: upcoming release

#601 2.0 Release changes
  _config.yml
  _dashboards/install/plugins.md
  _data/alert.yml
  _data/versions.json
  _opensearch/install/plugins.md
  version-history.md
Labels: v2.0.0, 5 - Done and ready to merge

#602 Add Breaking Changes for 2.0
  breaking-changes.md
Labels: v2.0.0, 5 - Done and ready to merge

#611 Fix date on 2.0 version history
  version-history.md
Labels: v2.0.0

#586 Adding content for the new Notifications plugin
  _config.yml
  _im-plugin/ism/policies.md
  _monitoring-plugins/alerting/monitors.md
  _notifications-plugin/api.md
  _notifications-plugin/index.md
Labels: upcoming release, v2.0.0

#610 Add Circuit Breaker option to JS client
  _clients/javascript.md
  _opensearch/install/compatibility.md
Labels: v2.0.0

#609 Add OpenSearch Java Compat for 2.0 [Edit to Dblock]
  _opensearch/install/compatibility.md
Labels: v2.0.0, 3 - Tech Review

#604 doc-level monitor API - findings index and search API
  _monitoring-plugins/alerting/api.md
  _monitoring-plugins/alerting/monitors.md
Labels: v2.0.0
