Repository opensearch-project/documentation-website, pull requests merged in 2022-09, with the labels that each got.

#1040 Adds 1.3.4 to version history
  version-history.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#1053 Correct documentation to clarify which permissions are needed for cross-cluster search
  _opensearch/rest-api/search.md
  _security-plugin/access-control/cross-cluster-search.md
Labels: API, backport 1.3, backport 2.0, security, backport 2.1, backport 2.2

#1039 Add documentation for the plugins.security.cache.ttl_minutes property
  _security-plugin/configuration/configuration.md
  _security-plugin/configuration/yaml.md
Labels: 3 - Tech Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2

#1070 Change "user names" to "usernames" per editor in tarball guide
  _opensearch/install/tar.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1, backport 2.2

#1054 Adds disclaimer about Maven coords URL formation and details about local zip files
  _opensearch/install/plugins.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1, backport 2.2

#1004 Fix innerproduct function to match Dot Product
  _search-plugins/knn/knn-score-script.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#1094 script api documentation
  _opensearch/rest-api/_script-apis/create-stored-script.md
  _opensearch/rest-api/_script-apis/delete-script.md
  _opensearch/rest-api/_script-apis/exec-stored-script.md
  _opensearch/rest-api/_script-apis/get-script-contexts.md
  _opensearch/rest-api/_script-apis/get-stored-script.md
  _opensearch/rest-api/_script-apis/index.md
Labels: backport 1.3, backport 2.0, v2.3.0, backport 2.1, backport 2.2

#1105 Updated API endpoint for testing
  _opensearch/install/rpm.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#1091 custom json model for anomaly detector
  _monitoring-plugins/ad/index.md
Labels: 3 - Tech Review

#1088 Add removed security permissions
  _security-plugin/access-control/permissions.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#1113 Creates standalone pages for OpenSearch Dashboards RPM/YUM Installation
  _dashboards/install/rpm.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#1134 Moves PA plugin info to the correct page
  _monitoring-plugins/pa/index.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#1043 Docker installs - update yaml file note for new downloads
  _opensearch/install/docker.md
Labels: 4 - Doc Review, installation

#1158 Issue1157 - correcting links on scripts-api index page
  _opensearch/rest-api/_script-apis/index.md
Labels: 2 - In progress, backport 1.3, backport 2.0, v2.3.0, backport 2.1, backport 2.2

#1151 Rename cluster.initial_master_nodes environment setting in sample docker compose file
  _opensearch/install/docker.md
Labels: backport 2.0, backport 2.1, backport 2.2

#1071 Edits to PR #804, TLS settings
  _security-plugin/configuration/security-admin.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#1155 Fixes the metrics-pipeline to use otel_metrics_source
  _clients/data-prepper/pipelines.md
Labels: backport 2.0, backport 2.1, backport 2.2

#1180 Renames async search settings
  _search-plugins/async/settings.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#1168 Add the two clear cache APIs
  _opensearch/rest-api/index-apis/clear-index-cache.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#1163 Publish segment replication experimental feature documentation
  _opensearch/segment-replication/configuration.md
  _opensearch/segment-replication/index.md
Labels: v2.3.0

#1195 Create drag and drop wizard documentation
  _dashboards/drag-drop-wizard.md
  images/drag-and-drop-viz-select.png
  images/drag-drop-generated-viz.png
  images/drag-drop-ui.png
  images/enable-experimental-viz.png
  images/stack-managment-settings.png
Labels: 6 - Done but waiting to merge

#1179 Adds documentation page for remote-backed storage
  _opensearch/remote.md
Labels: 4 - Doc Review

#1146 Add home page and experimental features section
  Gemfile
  _dashboards/drag-drop-wizard.md
  _opensearch/segment-replication/configuration.md
  _opensearch/segment-replication/index.md
  breaking-changes.md
  images/1_search.png
  images/2_monitoring.png
  images/3_security.png
  images/4_tracking.png
  images/Flight-data.png
  index.md
  version-history.md
Labels: 4 - Doc Review

#1197 Adds 2.3 release
  _config.yml
  _data/alert.yml
  _data/versions.json
Labels: 4 - Doc Review, v2.3.0

#1202 Rotates style guide tone table to increase readability
  STYLE_GUIDE.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#1206 Fix home page and experimental feature warnings
  _opensearch/remote.md
  _opensearch/segment-replication/configuration.md
  _opensearch/segment-replication/index.md
  index.md
Labels: backport 2.3

#1194 Update docker compose
  _opensearch/install/docker.md
Labels: backport 2.0, backport 2.1, backport 2.2

#1176 Remove _mappings from create mapping url
  _opensearch/supported-field-types/join.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#1056 Rename prepper to processor in pipeline configuration sample for Data Prepper
  _clients/data-prepper/pipelines.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1214 Clear cache API - additional edits
  _opensearch/rest-api/index-apis/clear-index-cache.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1239 Issue1238 - Update segment replication feedback link
  _opensearch/segment-replication/configuration.md
  _opensearch/segment-replication/index.md
Labels: 2 - In progress, 4 - Doc Review, v2.4.0, backport 2.3

#1014 fix aliases example for shrink policy action
  _im-plugin/ism/policies.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1247 Fix home page
  index.md
Labels: backport 2.3

#1250 Fixes enabling drag and drop
  _dashboards/drag-drop-wizard.md
  images/drag-and-drop-viz-select.png
  images/enable-experimental-viz.png
  images/stack-management-settings.png
  images/stack-managment-settings.png
Labels: backport 2.3

#1253 [Bug] Fix broken cross-ref links in the docs
  _monitoring-plugins/pa/index.md
  _opensearch/install/index.md
  _opensearch/install/tar.md
  _opensearch/query-dsl/full-text.md
  _opensearch/rest-api/_script-apis/create-stored-script.md
  _opensearch/rest-api/snapshots/get-snapshot-repository.md
  _opensearch/rest-api/snapshots/restore-snapshot.md
  _opensearch/snapshots/snapshot-restore.md
  _opensearch/ux.md
  _search-plugins/querqy/index.md
  _security-plugin/configuration/disable.md
Labels: 4 - Doc Review, backport 2.1, backport 2.2

#1257 Changed image in drag and drop
  images/drag-drop-generated-viz.png
Labels: backport 2.3

#1245 Change remote store documentation to reflect all the config options
  _opensearch/remote.md
Labels: backport 2.3

#1278 Fixes link to dashboards landing page
  _dashboards/install/docker.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1261 add backlink from config to cluster settings API
  _opensearch/configuration.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1279 Edits to PR #805
  _security-plugin/configuration/configuration.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1229 [Doc] add terms for site search to return pages correctly for bool and range queries
  _opensearch/query-dsl/bool.md
  _opensearch/query-dsl/term.md
  _opensearch/supported-field-types/range.md
Labels: 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1017 Add the Kubernetes Operator install instructions
  _clients/k8s-operator.md
Labels: backport 2.0, backport 2.1, backport 2.2

#1111 Add PPL and SQL section
  _ml-commons-plugin/index.md
  _observability-plugin/app-analytics.md
  _observability-plugin/event-analytics.md
  _observability-plugin/index.md
  _observability-plugin/operational-panels.md
  _observability-plugin/ppl/datatypes.md
  _observability-plugin/ppl/endpoint.md
  _observability-plugin/ppl/functions.md
  _observability-plugin/ppl/protocol.md
  _observability-plugin/ppl/settings.md
  _opensearch/data-streams.md
  _search-plugins/sql/aggregations.md
  _search-plugins/sql/cli.md
  _search-plugins/sql/datatypes.md
  _search-plugins/sql/endpoints.md
  _search-plugins/sql/full-text.md
  _search-plugins/sql/functions.md
  _search-plugins/sql/identifiers.md
  _search-plugins/sql/index.md
  _search-plugins/sql/limitation.md
  _search-plugins/sql/monitoring.md
  _search-plugins/sql/ppl/functions.md
  _search-plugins/sql/ppl/index.md
  _search-plugins/sql/ppl/syntax.md
  _search-plugins/sql/protocol.md
  _search-plugins/sql/response-formats.md
  _search-plugins/sql/settings.md
  _search-plugins/sql/sql-full-text.md
  _search-plugins/sql/sql-ppl-api.md
  _search-plugins/sql/sql/aggregations.md
  _search-plugins/sql/sql/basic.md
  _search-plugins/sql/sql/complex.md
  _search-plugins/sql/sql/delete.md
  _search-plugins/sql/sql/functions.md
  _search-plugins/sql/sql/index.md
  _search-plugins/sql/sql/jdbc.md
  _search-plugins/sql/sql/metadata.md
  _search-plugins/sql/sql/odbc.md
  _search-plugins/sql/sql/partiql.md
  _search-plugins/sql/troubleshoot.md
  _search-plugins/sql/workbench.md
Labels: 5 - Final Editorial Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1277 [Doc] update geoJSON example file to prevent errors
  _dashboards/geojson-regionmaps.md
  images/county-region-map.png
  images/county-regionmap.png
  images/import-geojson-file.png
  images/import-vector-map.png
  images/upload-success.png
Labels: 4 - Doc Review, backport 2.2, backport 2.3

#1301 updated doc to include configuration instructions for CORS headers
  _opensearch/configuration.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1315 Adds step to restart OS after applying security changes
  _opensearch/install/tar.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.3

#1263 Documentation for new parameters in logstash-output-opensearch 2.0.0
  _clients/logstash/ship-to-opensearch.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1265 Refactors transform APIs
  _im-plugin/index-transforms/transforms-apis.md
Labels: 5 - Final Editorial Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1255 Provide users with warning about special characters in query DSL and API query fields
  _opensearch/query-dsl/index.md
  _security-plugin/access-control/api.md
  _security-plugin/access-control/document-level-security.md
Labels: backport 1.3, backport 2.0, security, backport 2.1, backport 2.2, backport 2.3

#1328 Add wait_for_completion to API documentation
  _opensearch/rest-api/document-apis/update-by-query.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1348 Cleans up formatting
  index.md
Labels: 4 - Doc Review, backport 2.3
