Repository opensearch-project/documentation-website, pull requests merged in 2022-06, with the labels that each got.

#624 Added master_timeout parameter to CAT segments
  _opensearch/rest-api/cat/cat-segments.md
Labels: v2.0.0, 3 - Tech Review

#622 Makes CAT child pages expandable
  _opensearch/rest-api/cat/cat-aliases.md
  _opensearch/rest-api/cat/cat-allocation.md
  _opensearch/rest-api/cat/cat-cluster_manager.md
  _opensearch/rest-api/cat/cat-count.md
  _opensearch/rest-api/cat/cat-field-data.md
  _opensearch/rest-api/cat/cat-health.md
  _opensearch/rest-api/cat/cat-indices.md
  _opensearch/rest-api/cat/cat-nodeattrs.md
  _opensearch/rest-api/cat/cat-nodes.md
  _opensearch/rest-api/cat/cat-pending-tasks.md
  _opensearch/rest-api/cat/cat-plugins.md
  _opensearch/rest-api/cat/cat-recovery.md
  _opensearch/rest-api/cat/cat-repositories.md
  _opensearch/rest-api/cat/cat-segments.md
  _opensearch/rest-api/cat/cat-shards.md
  _opensearch/rest-api/cat/cat-snapshots.md
  _opensearch/rest-api/cat/cat-tasks.md
  _opensearch/rest-api/cat/cat-templates.md
  _opensearch/rest-api/cat/cat-thread-pool.md
Labels: v2.0.0, v1.3.0, 3 - Tech Review

#635 Changed parameter to allow_no_indices
  _opensearch/rest-api/search.md
Labels: v2.0.0, v1.3.0, 3 - Tech Review

#650 Added cancel_after_time_interval
  _opensearch/rest-api/multi-search.md
  _opensearch/rest-api/search.md
Labels: v2.0.0

#629 Updated the readme with Alice's name
  README.md
Labels: 5 - Done but waiting to merge

#677 Add version 2.0.1
  _config.yml
  _opensearch/install/plugins.md
  version-history.md
Labels: backport 2.0

#683 #682: Fixing docker image name.
  _clients/data-prepper/pipelines.md
Labels: backport 1.3, backport 2.0

#691 for cluster manager term update
  _opensearch/rest-api/cat/cat-templates.md
  _security-plugin/access-control/multi-tenancy.md
Labels: documentation, backport 2.0

#696 Update serach.remote with cluster.remote
  _security-plugin/access-control/cross-cluster-search.md
Labels: backport 2.0

#698 Add back Data Prepper 1.4 docs
  _clients/data-prepper/data-prepper-reference.md
  _clients/data-prepper/pipelines.md
Labels: 3 - Tech Review, backport 2.0

#701 Data Prepper 1.5.0 documentation
  _clients/data-prepper/data-prepper-reference.md
  _clients/data-prepper/pipelines.md
Labels: backport 1.3, backport 2.0

#715 Changed headings back to sentence
  _clients/data-prepper/data-prepper-reference.md
Labels: backport 2.0

#717 Fixed hyperlinks in Data Prepper reference
  _clients/data-prepper/data-prepper-reference.md
Labels: backport 2.0

#726 Fixed broken links in cat*.md, api.md and monitoring.md
  _monitoring-plugins/alerting/api.md
  _monitoring-plugins/alerting/monitors.md
  _opensearch/rest-api/cat/cat-aliases.md
  _opensearch/rest-api/cat/cat-allocation.md
  _opensearch/rest-api/cat/cat-cluster_manager.md
  _opensearch/rest-api/cat/cat-count.md
  _opensearch/rest-api/cat/cat-field-data.md
  _opensearch/rest-api/cat/cat-indices.md
  _opensearch/rest-api/cat/cat-nodeattrs.md
  _opensearch/rest-api/cat/cat-nodes.md
  _opensearch/rest-api/cat/cat-pending-tasks.md
  _opensearch/rest-api/cat/cat-plugins.md
  _opensearch/rest-api/cat/cat-recovery.md
  _opensearch/rest-api/cat/cat-repositories.md
  _opensearch/rest-api/cat/cat-segments.md
  _opensearch/rest-api/cat/cat-shards.md
  _opensearch/rest-api/cat/cat-snapshots.md
  _opensearch/rest-api/cat/cat-tasks.md
  _opensearch/rest-api/cat/cat-templates.md
  _opensearch/rest-api/cat/cat-thread-pool.md
Labels: 3 - Tech Review, backport 1.3, backport 2.0

#708 Updated the header on the Doc site with new navigation
  _includes/header.html
Labels: backport 2.0

#742 Update default index name to .kibana instead of .opensearch-dashboards
  _security-plugin/access-control/multi-tenancy.md
Labels: v2.0.0, 3 - Tech Review, backport 1.3, backport 2.0
