Repository opensearch-project/documentation-website, pull requests merged in 2022-08, with the labels that each got.

#841 Clarified wording for upgrade approaches and added link reference to …
  _upgrade-to/index.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review

#748 Added reference to RFC2818 along with guidance to add subjectAltNames…
  _security-plugin/configuration/generate-certificates.md
Labels: 3 - Tech Review, backport 1.3, backport 2.0, v-All

#835 Add issue template default states
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: 3 - Tech Review

#761 Add refresh param to documentation
  _opensearch/rest-api/document-apis/index-document.md
Labels: backport 1.3, backport 2.0

#852 fixing typo shard indexing
  _opensearch/shard-indexing-settings.md
Labels: 6 - Done but waiting to merge, backport 1.3, backport 2.0

#839 “fix#829-PreAgg-field_doc_count”
  _opensearch/bucket-agg.md
Labels: v2.2.0

#860 Revert "“fix#829-PreAgg-field_doc_count”"
  _opensearch/bucket-agg.md
Labels: 6 - Done but waiting to merge, v2.2.0

#859 Added async search plugin security info
  _search-plugins/async/security.md
Labels: 6 - Done but waiting to merge, v2.2.0, backport 1.3, backport 2.0

#712 Added supported field types
  _opensearch/supported-field-types/alias.md
  _opensearch/supported-field-types/autocomplete.md
  _opensearch/supported-field-types/binary.md
  _opensearch/supported-field-types/boolean.md
  _opensearch/supported-field-types/completion.md
  _opensearch/supported-field-types/date.md
  _opensearch/supported-field-types/geo-point.md
  _opensearch/supported-field-types/geo-shape.md
  _opensearch/supported-field-types/geographic.md
  _opensearch/supported-field-types/index.md
  _opensearch/supported-field-types/ip.md
  _opensearch/supported-field-types/join.md
  _opensearch/supported-field-types/keyword.md
  _opensearch/supported-field-types/nested.md
  _opensearch/supported-field-types/numeric.md
  _opensearch/supported-field-types/object-fields.md
  _opensearch/supported-field-types/object.md
  _opensearch/supported-field-types/percolator.md
  _opensearch/supported-field-types/range.md
  _opensearch/supported-field-types/rank.md
  _opensearch/supported-field-types/search-as-you-type.md
  _opensearch/supported-field-types/string.md
  _opensearch/supported-field-types/text.md
  _opensearch/supported-field-types/token-count.md
Labels: backport 1.3, backport 2.0

#866 Task consumer integration
  _opensearch/logs.md
  _opensearch/rest-api/tasks.md
Labels: 6 - Done but waiting to merge, v2.2.0

#864 Add Logistic and RCF algorthims
  _ml-commons-plugin/algorithms.md
Labels: upcoming release, 6 - Done but waiting to merge, v2.2.0

#856 Added replica count enforcement
  _opensearch/cluster.md
Labels: upcoming release, 6 - Done but waiting to merge, v2.2.0

#837 “fixfor#791_k-NN-ANN”
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/index.md
  _search-plugins/knn/jni-libraries.md
  _search-plugins/knn/knn-index.md
Labels: documentation, enhancement, 6 - Done but waiting to merge, v2.2.0

#833 Added .net clients
  _clients/OSC-dot-net.md
  _clients/OSC-example.md
  _clients/OpenSearch-dot-net.md
  _clients/dot-net-conventions.md
  _clients/dot-net.md
  _clients/index.md
Labels: 6 - Done but waiting to merge

#807 How to upload a custom vector map .json for Dashboards
  _dashboards/geojson-regionmaps.md
  images/import-vector-map.png
Labels: 6 - Done but waiting to merge, v2.2.0

#870 Fix#829 pre agg doc count field
  _opensearch/bucket-agg.md
Labels: 6 - Done but waiting to merge, v2.2.0

#871 Add feature attribution documentation
  _monitoring-plugins/ad/index.md
  images/ad.png
  images/feature-contribution-ad.png
  images/feature-output-ad.png
  images/multi-category-ad.png
Labels: upcoming release, 5 - Final Editorial Review, v2.2.0

#883 Fixed typo
  _clients/dot-net.md
Labels: 4 - Doc Review, backport 2.1

#889 Use "processor" instead of "prepper" for Data Prepper
  _clients/data-prepper/pipelines.md
Labels: backport 2.0, backport 2.1

#903 Simplified the Issue Template
  .github/ISSUE_TEMPLATE/issue_template.md
  Gemfile
Labels: 4 - Doc Review

#895 Further edits for API Guide
  STYLE_API_TEMPLATE.md
Labels: API, 4 - Doc Review

#915 changed wording of getting started with application analytics
  _observability-plugin/app-analytics.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1

#920 added batch mode to plugin install documentation
  _opensearch/install/plugins.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1

#931 Fix backport from PR 929
  _opensearch/install/plugins.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1

#934 Add upsert description to Update document API information
  _opensearch/rest-api/document-apis/update-document.md
Labels: v2.2.0, backport 1.3, backport 2.0, backport 2.1

#911 Fix792 rollup enhancements
  _im-plugin/index-rollups/index.md
Labels: 6 - Done but waiting to merge

#912 Fix setting name for LDAP custom attribute filter
  _security-plugin/configuration/ldap.md
Labels: backport 1.3, backport 2.0, backport 2.1

#873 add files for snapshot creation
  _opensearch/rest-api/snapshots/create-repository.md
  _opensearch/rest-api/snapshots/create-snapshot.md
  _opensearch/rest-api/snapshots/delete-snapshot-repository.md
  _opensearch/rest-api/snapshots/delete-snapshot.md
  _opensearch/rest-api/snapshots/get-snapshot-repository.md
  _opensearch/rest-api/snapshots/get-snapshot-status.md
  _opensearch/rest-api/snapshots/get-snapshot.md
  _opensearch/rest-api/snapshots/index.md
  _opensearch/rest-api/snapshots/restore-snapshot.md
  _opensearch/rest-api/snapshots/verify-snapshot-repository.md
Labels: 2 - In progress, 4 - Doc Review

#940 Resolve issue #879
  _opensearch/query-dsl/full-text.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1

#957 Added list of plugins that can be installed by name
  _opensearch/install/plugins.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1

#962 Moved guidance on passing env vars as args to Configuration page
  _opensearch/configuration.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1

#963 Relocate perf analyzer installation steps to the appropriate page
  _monitoring-plugins/pa/index.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1

#892 Update documentation from opensearch_security_roles to opendistro_sec…
  _security-plugin/configuration/yaml.md
Labels: backport 2.0, backport 2.1, backport 2.2

#783 Add examples for bulk script & upsert updates
  _opensearch/rest-api/document-apis/bulk.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#982 Removes References to OpenDistro
  _security-plugin/access-control/permissions.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2

#973 API Template Organization – Response fields to bottom of layout
  STYLE_API_TEMPLATE.md
Labels: API

#999 Adds link to Maven repo and updates plugins list with Geospatial
  _opensearch/install/plugins.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1, backport 2.2

#981 Fix example using custom_attr_whitelist and custom_attr_maxval_len in…
  _security-plugin/configuration/ldap.md
Labels: backport 1.3, backport 2.x

#1019 resolve_hostname should be singular
  _security-plugin/configuration/tls.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#919 Missing documentation for the plugins.security.allow_default_init_securityindex property
  _security-plugin/configuration/configuration.md
  _security-plugin/configuration/yaml.md
Labels: backport 1.3, backport 2.0, security, backport 2.1, backport 2.2

#881 Tarball installation guide refactor
  _opensearch/install/tar.md
Labels: backport 1.3, backport 2.0, v-All, backport 2.1, backport 2.2

#1041 Reformats plugins page, adds more explanations, and adds Maven coordinates help
  _opensearch/install/plugins.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v-All, backport 2.1, backport 2.2

#1047 created page and documentation for querqy plugin
  _search-plugins/querqy/index.md
Labels: v1.3.0, backport 1.3, 4 - Doc Review, installation
