Repository opensearch-project/documentation-website, pull requests merged in 2022-07, with the labels that each got.

#711 Add Execute Command to API documentation.
  _ml-commons-plugin/algorithms.md
  _ml-commons-plugin/api.md
Labels: v2.1.0, backport 2.0

#760 fixes#706condensed-header
  _dashboards/branding.md
  images/DBs-Condensed.jpeg
  images/DBs-Traditional.jpeg
Labels: v2.1.0, backport 1.3, backport 2.0

#758 Added note about lack of downgrade support to the install landing page
  _opensearch/install/index.md
Labels: backport 1.3, backport 2.0

#771 Revert header change, since it's 2.1-specific
  _dashboards/branding.md
Labels: backport 2.0

#776 Rectify rpm installation for dashboards
  _opensearch/install/rpm.md
Labels: bug, v2.1.0, backport 2.0, backport 2.1

#757 Snapshot management
  _im-plugin/ism/policies.md
  _monitoring-plugins/alerting/settings.md
  _opensearch/snapshots/index.md
  _opensearch/snapshots/sm-api.md
  _opensearch/snapshots/sm-dashboards.md
  _opensearch/snapshots/snapshot-management.md
  _opensearch/snapshots/snapshot-restore.md
  _security-plugin/access-control/multi-tenancy.md
  _security-plugin/access-control/users-roles.md
  _upgrade-to/index.md
  _upgrade-to/snapshot-migrate.md
  images/SM-state-machine.PNG
Labels: v2.1.0, 5 - Done but waiting to merge

#782 Add Snapshot IRSA insturctions
  _opensearch/snapshots/snapshot-restore.md
Labels: v2.1.0

#740 Add documentation issue template
  .github/issue_template.md
Labels: 3 - Tech Review

#813 Updated Terms.md wording
  TERMS.md
Labels: 3 - Tech Review

#824 Added example commands and note about versions and the ECR repo
  _opensearch/install/docker.md
Labels: backport 1.3, backport 2.0, v-All

#787 Add ML node settings and dynamic node description
  _ml-commons-plugin/index.md
  _opensearch/cluster.md
  _opensearch/rest-api/cat/cat-nodes.md
Labels: v2.1.0, 4 - Doc Review
