Repository opensearch-project/documentation-website, pull requests merged in 2022-03, with the labels that each got.

#431 Update documentation in Data Prepper refernece
  _clients/data-prepper/data-prepper-reference.md
Labels: upcoming release

#456 Initial 1.3 updates
  _config.yml
  _data/alert.yml
  _data/versions.json
  _opensearch/install/plugins.md
  version-history.md
Labels: upcoming release, work in progress, v1.3.0

#458 Add Cluster Metrics instructions
  _monitoring-plugins/alerting/api.md
  _monitoring-plugins/alerting/monitors.md
Labels: upcoming release, v1.3.0

#443 [1.3] Add Observability changes
  _observability-plugin/ppl/commands.md
  _search-plugins/sql/datatypes.md
Labels: upcoming release, v1.3.0

#440 Custom branding fixes
  _dashboards/branding.md
Labels: upcoming release, v1.3.0

#446 Added new continuous parameter to transforms
  _im-plugin/index-transforms/index.md
  _im-plugin/index-transforms/transforms-apis.md
Labels: upcoming release, v1.3.0

#447 Added show policy to ISM explain
  _im-plugin/index-transforms/index.md
  _im-plugin/index-transforms/transforms-apis.md
  _im-plugin/ism/api.md
  _search-plugins/knn/approximate-knn.md
Labels: upcoming release, v1.3.0

#455 Added responses from validate API
  _monitoring-plugins/ad/api.md
Labels: v1.3.0

#459 Documented JDK compatibility for version 1.3.0.
  _opensearch/install/compatibility.md
Labels: v1.3.0
