Repository opensearch-project/documentation-website, pull requests merged in 2022-11, with the labels that each got.

#1751 Add min_rollover_age transition condition to documentation
  _im-plugin/ism/policies.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, hacktoberfest-accepted

#1767 Adds get settings
  _api-reference/index-apis/get-settings.md
Labels: 4 - Doc Review, backport 2.3

#1765 Adds to templates API
  _opensearch/index-templates.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1766 Adds to mappings API
  _opensearch/mappings.md
Labels: 4 - Doc Review, backport 2.3

#1764 Adds to alias documentation
  _api-reference/alias.md
  _opensearch/index-alias.md
Labels: 4 - Doc Review, backport 2.3

#1549 Configuring Dashboards multi-authentication sign-in window
  _security-plugin/configuration/multi-auth.md
  _security-plugin/configuration/openid-connect.md
  _security-plugin/configuration/saml.md
  _security-plugin/configuration/yaml.md
Labels: enhancement, dashboards, security, v2.4.0

#1711 [DOC:] New content and new page: Discover main page and multiple data sources
  _dashboards/discover/index.md
  _dashboards/discover/multi-data-sources.md
  images/discover-index.png
  images/multi-data-sources-1.png
  images/multi-data-sources-10.png
  images/multi-data-sources-11.jpg
  images/multi-data-sources-12.jpg
  images/multi-data-sources-2.png
  images/multi-data-sources-3.png
  images/multi-data-sources-4.png
  images/multi-data-sources-5.png
  images/multi-data-sources-6.png
  images/multi-data-sources-7.png
  images/multi-data-sources-8.png
  images/multi-data-sources-9.png
Labels: 6 - Done but waiting to merge

#1796 Added Sigv4 Section to JavaScript Client
  _clients/javascript/index.md
Labels: backport 2.3

#1485 Migrating from open distro data prepper
  _clients/data-prepper/migrate-open-distro.md
  _clients/data-prepper/pipelines.md
Labels: 5 - Final Editorial Review, backport 2.0, backport 2.1, backport 2.2, backport 2.3, data-prepper

#1806 Adds GeoJSON format to geopoint
  _opensearch/supported-field-types/geo-point.md
Labels: 4 - Doc Review, v2.4.0

#1761 Adds GeoHex grid documentation
  _opensearch/bucket-agg.md
  _opensearch/geohexgrid-agg.md
  _opensearch/metric-agg.md
  _opensearch/pipeline-agg.md
Labels: 3 - Tech Review, v2.4.0

#1753 Adds Point in Time documentation
  _api-reference/nodes-apis/nodes-stats.md
  _opensearch/point-in-time-api.md
  _opensearch/point-in-time.md
  _security-plugin/access-control/users-roles.md
Labels: 4 - Doc Review, v2.4.0

#1795 [DOC] [v2.4.0] Update documentation for Searchable Snapshot Feature
  _opensearch/snapshots/searchable_snapshot.md
  _opensearch/snapshots/snapshot-restore.md
Labels: 5 - Final Editorial Review, v2.4.0, snapshots

#1791 update image for Dashboards Alerting plugin
  _monitoring-plugins/alerting/index.md
  images/dashboards-nav.png
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1487 Logstash migration guide
  _clients/data-prepper/configure-logstash-data-prepper.md
  _clients/data-prepper/migrate-open-distro.md
Labels: 5 - Final Editorial Review, backport 2.0, backport 2.1, backport 2.2, backport 2.3, data-prepper

#1820 Fixes links
  _dashboards/run-queries.md
  _opensearch/supported-field-types/geo-shape.md
  _opensearch/supported-field-types/xy-shape.md
Labels: 4 - Doc Review, v2.4.0

#1794 Rework Clients, Tools, and Data Prepper section
  _clients/data-prepper/pipelines.md
  _config.yml
  _data-prepper/configure-logstash-data-prepper.md
  _data-prepper/data-prepper-reference.md
  _data-prepper/get-started.md
  _data-prepper/index.md
  _data-prepper/migrate-open-distro.md
  _data-prepper/pipelines.md
  _tools/cli.md
  _tools/grafana.md
  _tools/index.md
  _tools/k8s-operator.md
  _tools/logstash/advanced-config.md
  _tools/logstash/common-filters.md
  _tools/logstash/execution-model.md
  _tools/logstash/index.md
  _tools/logstash/read-from-opensearch.md
  _tools/logstash/ship-to-opensearch.md
  _upgrade-to/index.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1821 Adds Windows security documentation
  _security-plugin/configuration/index.md
  _security-plugin/configuration/security-admin.md
  _security-plugin/configuration/tls.md
  _security-plugin/configuration/yaml.md
Labels: 3 - Tech Review, v2.4.0

#1840 [DOC] [v2.4.0] Update documentation for Searchable Snapshot Feature - editorial changes
  _opensearch/snapshots/searchable_snapshot.md
Labels: v2.4.0, snapshots

#1808 [DOC]: Update Wizard naming convention
  _dashboards/drag-drop-wizard.md
  _dashboards/visbuilder.md
  images/drag-and-drop-viz-select.png
  images/drag-drop-ui.png
  images/vis-builder-1.png
  images/vis-builder-2.png
Labels: 6 - Done but waiting to merge

#1836 Fix merge conflict typo in Data Prepper
  _data-prepper/configure-logstash-data-prepper.md
Labels: 4 - Doc Review, backport 2.3

#1813 Im plugin index rollup
  _im-plugin/index-rollups/index.md
Labels: backport 2.0, index-management, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1842 Fix bug where pipelines repeats on the same page
  _data-prepper/pipelines.md
Labels: backport 2.3, data-prepper

#1769 Adds execute script API
  _api-reference/script-apis/exec-script.md
Labels: backport 2.3

#1839 Update data prepper get started.md
  _data-prepper/get-started.md
Labels: 6 - Done but waiting to merge, backport 2.0, backport 2.1, backport 2.2, backport 2.3, data-prepper

#1790 Adds search backpressure documentation
  _api-reference/nodes-apis/nodes-stats.md
  _opensearch/search-backpressure.md
  _opensearch/segment-replication/index.md
Labels: 4 - Doc Review, v2.4.0

#1786 Add documentation for aggregate view of saved objects by tenant in Dashboards
  _security-plugin/access-control/index.md
  _security-plugin/audit-logs/index.md
  _security-plugin/multi-tenancy/mt-agg-view.md
  _security-plugin/multi-tenancy/multi-tenancy-config.md
  _security-plugin/multi-tenancy/tenant-index.md
  images/Security/Tenant_column.png
  images/Security/actions.png
  images/Security/agg-view-saved-objects.png
  images/Security/switch_tenant.png
  images/Security/ten-filter-results.png
Labels: enhancement, security, v2.4.0

#1801 Adds search relevance documentation
  _search-plugins/search-relevance/index.md
  images/search_relevance.png
Labels: v2.4.0

#1857 Fixes merge error
  _data-prepper/migrate-open-distro.md
Labels: backport 2.3

#1814 Search with k-NN filters
  _search-plugins/knn/api.md
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/filter-search-knn.md
  _search-plugins/knn/jni-libraries.md
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/knn-score-script.md
  _search-plugins/knn/painless-functions.md
  _search-plugins/knn/performance-tuning.md
  _search-plugins/knn/settings.md
  images/hsnw-algorithm.png
  images/knn-two-filters.png
Labels: v2.4.0

#1860 Fixes Docker command with custom file path
  _opensearch/install/docker.md
Labels: backport 1.3, backport 2.0, Closed - Complete, backport 2.1, backport 2.2, backport 2.3

#1771 Added instructions for enabling opensearch as a service with systemd
  _opensearch/cluster.md
  _opensearch/install/tar.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1874 Fixes wording for the overview of creating a service for use with systemd
  _opensearch/install/tar.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1752 Adds search documentation
  _opensearch/search/autocomplete.md
  _opensearch/search/did-you-mean.md
  _opensearch/search/highlight.md
  _opensearch/search/index.md
  _opensearch/search/paginate.md
  _opensearch/search/sort.md
  _opensearch/supported-field-types/completion.md
  _opensearch/supported-field-types/nested.md
  _opensearch/ux.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1826 Adds cluster manager task throttling documentation
  _opensearch/cluster-manager-task-throttling.md
Labels: 6 - Done but waiting to merge, v2.4.0

#1825 Adds windows installation documentation
  _dashboards/install/windows.md
  _opensearch/install/compatibility.md
  _opensearch/install/windows.md
Labels: 3 - Tech Review, v2.4.0

#1866 For [Doc] Alerting plugin RBAC - backend roles usage
  _monitoring-plugins/alerting/api.md
  _monitoring-plugins/alerting/security.md
  _security-plugin/access-control/api.md
Labels: 4 - Doc Review, v2.4.0

#1887 Add 2.4 doc release notes
  release-notes/opensearch-documentation-release-notes-2.4.0.md
Labels: 4 - Doc Review, v2.4.0

#1856 Adds plugin compatibility
  _dashboards/install/plugins.md
  _opensearch/install/plugins.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, v2.4.0, backport 2.1, backport 2.2, backport 2.3

#1886 Adds version 2.4 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, v2.4.0, backport 2.1, backport 2.2, backport 2.3

#1885 Adds 2.4.0 version
  _config.yml
  _data/versions.json
Labels: v2.4.0

#1904 Renames text reanalysis
  _opensearch/search/highlight.md
Labels: backport 2.3, backport 2.4

#1881 Adds consistency to installation documentation
  _opensearch/install/rpm.md
  _opensearch/install/tar.md
  _security-plugin/configuration/ldap.md
  _security-plugin/configuration/saml.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#1913 Remove compatibility override from breaking changes
  breaking-changes.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#1937 Adds execute script API
  _opensearch/rest-api/_script-apis/exec-script.md
Labels: backport 1.3, backport 2.0, backport 2.1

#1951 Adds Point in Time to pagination methods
  _opensearch/search/autocomplete.md
  _opensearch/search/paginate.md
Labels: backport 2.4

#1953 Multi-tenancy aggregate view for saved objects - post release fixes
  _security-plugin/multi-tenancy/mt-agg-view.md
Labels: security, backport 2.4

#1880 Add model serving framework instructions
  _ml-commons-plugin/api.md
  _ml-commons-plugin/model-serving-framework.md
Labels: 4 - Doc Review, v2.4.0

#1882 Add Neural Search section
  _config.yml
  _neural-search-plugin/index.md
  _opensearch/install/plugins.md
Labels: 4 - Doc Review, v2.4.0, backport 2.4

#1959 Small typos in Neural Search
  _neural-search-plugin/index.md
Labels: backport 2.4

#1903 Adds searching data section
  _opensearch/search/autocomplete.md
  _opensearch/search/did-you-mean.md
  _opensearch/search/highlight.md
  _opensearch/search/index.md
  _opensearch/search/paginate.md
  _opensearch/search/sort.md
  _opensearch/supported-field-types/completion.md
  _opensearch/supported-field-types/nested.md
  _opensearch/ux.md
Labels: backport 1.3, backport 2.0

#1962 Update plugin documentation to reference the CAT API
  _opensearch/install/plugins.md
Labels: API, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#1956 Editorial review for Model Framework and Neural Search
  _ml-commons-plugin/api.md
  _ml-commons-plugin/model-serving-framework.md
  _neural-search-plugin/index.md
Labels: 4 - Doc Review, backport 2.4

#1901 fix#939-sec-analytics
  _opensearch/install/plugins.md
  _security-analytics/api-tools/alert-finding-api.md
  _security-analytics/api-tools/detector-api.md
Labels: backport 2.4

#1824 Add documentation for Security Analytics plugin
  _config.yml
  _opensearch/install/plugins.md
  _security-analytics/api-tools/alert-finding-api.md
  _security-analytics/api-tools/detector-api.md
  _security-analytics/api-tools/index.md
  _security-analytics/api-tools/mappings-api.md
  _security-analytics/api-tools/rule-api.md
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/sec-analytics-config/index.md
  _security-analytics/usage/alerts.md
  _security-analytics/usage/detectors.md
  _security-analytics/usage/findings.md
  _security-analytics/usage/index.md
  _security-analytics/usage/overview.md
  _security-analytics/usage/rules.md
  images/Security/Rules.png
  images/Security/alert_notify.png
  images/Security/alert_rules.png
  images/Security/custom-rule.png
  images/Security/date-pick.png
  images/Security/detector-action.png
  images/Security/detector-details.png
  images/Security/detector-details2.png
  images/Security/detector_rules.png
  images/Security/field_map.png
  images/Security/find-date-pick.png
  images/Security/finding-list.png
  images/Security/get-started.png
  images/Security/quickset.png
  images/Security/rule-dup2.png
  images/Security/rule-dup3.png
  images/Security/rule-menu.png
  images/Security/rule_name_delete.png
  images/Security/rules-dup1.png
  images/Security/secanalytics-det-nav.png
  images/Security/select_rules.png
  images/Security/threat-detector.png
Labels: 3 - Tech Review, 4 - Doc Review, v2.4.0, Needs SME

#1979 Add 2.4 content links to Version History
  _dashboards/discover/multi-data-sources.md
  _ml-commons-plugin/model-serving-framework.md
  _neural-search-plugin/index.md
  _opensearch/install/plugins.md
  version-history.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#927 API documentation to enable audit logging
  _security-plugin/access-control/api.md
Labels: backport 1.3, backport 2.0, security, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#1987 Adds the JDK 8 support drop
  breaking-changes.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#1739 Adds a quickstart guide
  _opensearch/install/quickstart.md
  assets/examples/docker-compose.yml
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2027 Removes bullet points and the term "guide" from quickstart.md
  _opensearch/install/quickstart.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2020 cluster.initial_master_nodes is no longer present in the documentatio…
  _upgrade-to/upgrade-to.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#1859 Minor edit for readability.
  _data-prepper/index.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#1914 Removes max_primary_shard_size parameter
  _api-reference/index-apis/shrink-index.md
Labels: 4 - Doc Review, backport 2.3, backport 2.4

#2012 Adds OpenSearch Intelligent Ranking plugin
  _search-plugins/search-relevance/index.md
  images/search_relevance.png
Labels: backport 2.4

#2050 Fixes Quickstart guide links so that links go to the raw JSON instead of a web page
  _opensearch/install/quickstart.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2052 Changes section heading in search relevance
  _search-plugins/search-relevance/index.md
Labels: backport 2.4

#2063 Add ML commons settings
  _ml-commons-plugin/cluster-settings.md
Labels: 4 - Doc Review, backport 2.4

#2070 Fixed cluster manager setting
  assets/examples/docker-compose.yml
Labels: 6 - Done but waiting to merge

#2066 Fix Profile API table
  _ml-commons-plugin/api.md
Labels: 4 - Doc Review, backport 2.4

#2064 Update multi-tenancy route to match name change
  _observability-plugin/notebooks.md
  _security-plugin/configuration/yaml.md
  _security-plugin/index.md
Labels: 4 - Doc Review, backport 2.4
