Repository opensearch-project/documentation-website, pull requests merged in 2022-12, with the labels that each got.

#2080 Create OpenSearch documentation main section
  _data-prepper/configure-logstash-data-prepper.md
  _data-prepper/get-started.md
  _neural-search-plugin/index.md
  _opensearch/rest-api/nodes-apis/nodes-stats.md
  _opensearch/search/autocomplete.md
  _security-analytics/sec-analytics-config/index.md
  _tools/logstash/ship-to-opensearch.md
  about.md
  breaking-changes.md
  index.md
  quickstart.md
  version-history.md
Labels: 4 - Doc Review, backport 2.3, backport 2.4

#2081 Fix typo in sec-analytics-config/index.md for Security Analytics
  _security-analytics/sec-analytics-config/index.md
Labels: backport 2.4

#2088 Restore ISM policy page to 1.3
  _im-plugin/ism/managedindexes.md
  _im-plugin/ism/policies.md
Labels: API, index-management

#2085 Adds compatible cluster API field parameters to cluster API page
  _api-reference/cluster-settings.md
Labels: API, backport 1.3, backport 2.0, configuration, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2089 Added doc for Ruby Sigv4
  _clients/ruby.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2130 Add installation and configuration section
  _api-reference/cluster-settings.md
  _api-reference/nodes-apis/nodes-info.md
  _config.yml
  _dashboards/browser-compatibility.md
  _dashboards/index.md
  _dashboards/install/index.md
  _install-and-configure/configuration.md
  _install-and-configure/index.md
  _install-and-configure/install-dashboards/docker.md
  _install-and-configure/install-dashboards/helm.md
  _install-and-configure/install-dashboards/index.md
  _install-and-configure/install-dashboards/plugins.md
  _install-and-configure/install-dashboards/rpm.md
  _install-and-configure/install-dashboards/tar.md
  _install-and-configure/install-dashboards/tls.md
  _install-and-configure/install-dashboards/windows.md
  _install-and-configure/install-opensearch/ansible.md
  _install-and-configure/install-opensearch/docker.md
  _install-and-configure/install-opensearch/helm.md
  _install-and-configure/install-opensearch/index.md
  _install-and-configure/install-opensearch/plugins.md
  _install-and-configure/install-opensearch/rpm.md
  _install-and-configure/install-opensearch/tar.md
  _install-and-configure/install-opensearch/windows.md
  _observability-plugin/trace/ta-dashboards.md
  _opensearch/install/compatibility.md
  _opensearch/install/important-settings.md
  _opensearch/install/index.md
  _security-plugin/configuration/disable.md
  _tools/index.md
  _tools/logstash/ship-to-opensearch.md
  quickstart.md
Labels: 4 - Doc Review, backport 2.3, backport 2.4

#2090 Adds documentation for ISM error prevention
  _im-plugin/ism/error-prevention/api.md
  _im-plugin/ism/error-prevention/index.md
  _im-plugin/ism/error-prevention/resolutions.md
Labels: API, index-management, backport 2.4

#2136 CAT API inclusive language update
  _api-reference/cat/cat-allocation.md
  _api-reference/cat/cat-nodeattrs.md
  _api-reference/cat/cat-nodes.md
  _api-reference/cat/cat-repositories.md
  _api-reference/cat/cat-shards.md
  _api-reference/cat/cat-thread-pool.md
Labels: API, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#1947 Add Expression syntax to doc website repo.
  _data-prepper/expression-syntax.md
Labels: 4 - Doc Review, data-prepper

#2134 Adds geo-bounding box query documentation
  _opensearch/query-dsl/geo-bounding-box.md
  _opensearch/supported-field-types/geo-point.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2071 Add opensearch-py-ml documentation
  _clients/opensearch-py-ml.md
Labels: backport 2.4

#2151 Fix table formatting on CAT allocation page
  _api-reference/cat/cat-allocation.md
Labels: API, 4 - Doc Review, backport 2.3, backport 2.4

#2160 Revert SAML troubleshooting page to _opendistro route to match existing route
  _troubleshoot/saml.md
Labels: security, 4 - Doc Review, backport 2.2, backport 2.3, backport 2.4

#1977 Add Log analytics to doc website repo
  _data-prepper/log-analytics.md
  _data-prepper/pipelines.md
  images/data-prepper/log-analytics/log-analytics-components.png
  images/data-prepper/log-analytics/log-ingestion-fluent-bit-data-prepper.png
Labels: data-prepper

#2167 Semantic change in concepts section
  _data-prepper/index.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2168 Editorial feedback for Expression syntax
  _data-prepper/expression-syntax.md
Labels: 5 - Final Editorial Review

#2172 Correct table formatting for cluster settings page
  _api-reference/cluster-settings.md
Labels: API, 4 - Doc Review, backport 2.3, backport 2.4

#2158 Correct API endpoints for CAT API reference
  _api-reference/cat/cat-allocation.md
  _api-reference/cat/cat-count.md
  _api-reference/cat/cat-field-data.md
  _api-reference/cat/cat-indices.md
  _api-reference/cat/cat-recovery.md
  _api-reference/cat/cat-templates.md
  _api-reference/cat/cat-thread-pool.md
Labels: API, 4 - Doc Review, backport 2.3, backport 2.4

#2192 Update Points of Contact on readme
  README.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2177 Fix Neural search pipeline example
  _ml-commons-plugin/cluster-settings.md
  _neural-search-plugin/index.md
Labels: 4 - Doc Review

#2214 Fix description of cosinesimil distance function
  _search-plugins/knn/approximate-knn.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2141 Adds high-level Python client documentation
  _clients/python-high-level.md
  _clients/python-low-level.md
  _clients/python.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2258 Added warning about restoring opendistro_security index through snapshot restore
  _opensearch/snapshots/snapshot-restore.md
Labels: 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2264 Updates site UI changes
  _layouts/default.html
  _sass/custom/custom.scss
  assets/js/copy-button.js
  assets/js/feedback.js
  assets/js/link-feedback.js
  assets/js/listener.js
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2295 Site final backport 2.2
  _layouts/default.html
  _sass/custom/custom.scss
  assets/js/copy-button.js
  assets/js/feedback.js
  assets/js/link-feedback.js
  assets/js/listener.js
Labels: backport 2.0, backport 2.1

#1402 [DOC] New content: New web page for visualize section
  _dashboards/visualize/viz-index.md
  images/TSVB-1.png
  images/area-chart-1.png
  images/bar-chart-1.png
  images/bar-horizontal-1.png
  images/controls-1.png
  images/data-table-1.png
  images/gauge-1.png
  images/heat-map-1.png
  images/line-1.png
  images/map-1.png
  images/markdown-1.png
  images/metric-chart-1.png
  images/pie-1.png
  images/timeline-1.png
  images/vega-1.png
  images/viz-type-UI.png
  images/word-cloud-1.png
Labels: backport 1.3, backport 2.0, v2.5.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2073 Restructure Data Prepper plugins documentation
  _data-prepper/configuration/buffers/bounded-blocking.md
  _data-prepper/configuration/buffers/buffers.md
  _data-prepper/configuration/data-prepper-configuration.md
  _data-prepper/configuration/pipelines-configurtion-options.md
  _data-prepper/configuration/processors/add-entries.md
  _data-prepper/configuration/processors/aggregate.md
  _data-prepper/configuration/processors/copy-values.md
  _data-prepper/configuration/processors/csv.md
  _data-prepper/configuration/processors/date.md
  _data-prepper/configuration/processors/delete-entries.md
  _data-prepper/configuration/processors/drop-events.md
  _data-prepper/configuration/processors/grok.md
  _data-prepper/configuration/processors/json.md
  _data-prepper/configuration/processors/key-value.md
  _data-prepper/configuration/processors/lowercase-string.md
  _data-prepper/configuration/processors/otel-trace-raw.md
  _data-prepper/configuration/processors/processors.md
  _data-prepper/configuration/processors/rename-keys.md
  _data-prepper/configuration/processors/routes.md
  _data-prepper/configuration/processors/service-map-stateful.md
  _data-prepper/configuration/processors/sinks.md
  _data-prepper/configuration/processors/split-string.md
  _data-prepper/configuration/processors/string-converter.md
  _data-prepper/configuration/processors/substitute-string.md
  _data-prepper/configuration/processors/trim-string.md
  _data-prepper/configuration/processors/uppercase-string.md
  _data-prepper/configuration/sinks/file.md
  _data-prepper/configuration/sinks/opensearch.md
  _data-prepper/configuration/sinks/pipeline.md
  _data-prepper/configuration/sinks/sinks.md
  _data-prepper/configuration/sinks/stdout.md
  _data-prepper/configuration/sources/http-source.md
  _data-prepper/configuration/sources/otel-metrics-source.md
  _data-prepper/configuration/sources/otel-trace.md
  _data-prepper/configuration/sources/s3.md
  _data-prepper/configuration/sources/sources.md
  _data-prepper/data-prepper-reference.md
  _data-prepper/get-started.md
  _data-prepper/migrate-open-distro.md
  _data-prepper/pipelines.md
Labels: 3 - Tech Review, data-prepper

#2277 Correct the spelling of the Galician analzyer.
  _opensearch/query-dsl/text-analyzers.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2315 Fix Sinks and Sources in Data Prepper config
  _data-prepper/configuration/sinks/file.md
  _data-prepper/configuration/sinks/opensearch.md
  _data-prepper/configuration/sinks/pipeline.md
  _data-prepper/configuration/sinks/stdout.md
  _data-prepper/configuration/sources/http-source.md
  _data-prepper/configuration/sources/otel-metrics-source.md
  _data-prepper/configuration/sources/otel-trace.md
  _data-prepper/configuration/sources/s3.md
  _data-prepper/configuration/sources/sources.md
Labels: 4 - Doc Review

#2314 Minor ToC edits.
  _data-prepper/configuration/data-prepper-configuration.md
  _data-prepper/configure-logstash-data-prepper.md
  _data-prepper/expression-syntax.md
  _data-prepper/get-started.md
  _data-prepper/log-analytics.md
  _data-prepper/migrate-open-distro.md
  _data-prepper/pipelines.md
Labels: 4 - Doc Review
