Repository opensearch-project/documentation-website, pull requests merged in 2022-10, with the labels that each got.

#1020 RPM/Yum Installation Enhancements
  _opensearch/install/rpm.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#1316 Add rank eval documentation
  _opensearch/rest-api/rank-eval.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1368 Update of source parameter in documentation
  _opensearch/rest-api/document-apis/update-document.md
Labels: backport 1.3, backport 2.0, Closed - Complete, backport 2.1, backport 2.2, backport 2.3

#1339 Add documentation for reload_searchIanalyzer api
  _opensearch/rest-api/reload-search-analyzer.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1370 Adding documentation for dangling index api
  _opensearch/rest-api/index-apis/dangling-index.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1413 Fixed liquid syntax for RPM install which fixes the yum repo command paths
  _opensearch/install/rpm.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1405 Added cluster permissions to cluster permissions list.
  _security-plugin/access-control/permissions.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1333 Fixes aggregate function page
  _search-plugins/sql/aggregations.md
  _search-plugins/sql/sql/aggregations.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1404 Update docs for Data Prepper 2.0
  _clients/data-prepper/data-prepper-reference.md
  _clients/data-prepper/get-started.md
  _clients/data-prepper/pipelines.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1389 Add maintainers.md
  maintainers.md
Labels: 4 - Doc Review

#1434 Addressing the loss of Open Sans on the documentation website.
  _sass/custom/custom.scss
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1371 Add ism rollup to documentation
  _im-plugin/ism/policies.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1441 Changes build.sh permission from 644 to 755
  build.sh
Labels: 6 - Done but waiting to merge

#1447 Fixes KNN search formulas
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-score-script.md
Labels: 6 - Done but waiting to merge, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1451 Updating Querqy documentation for OS 2.3
  _search-plugins/querqy/index.md
Labels: 4 - Doc Review, backport 2.3

#1356 Fix cat/templates doc
  _opensearch/rest-api/cat/cat-templates.md
Labels: backport 2.3

#1367 Update multi-tenancy.md
  _security-plugin/access-control/multi-tenancy.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1470 Adds 1.3.6 to 2.3 version history
  version-history.md
Labels: backport 2.3

#1369 Adds nodes stats API
  _opensearch/rest-api/nodes-apis/index.md
  _opensearch/rest-api/nodes-apis/nodes-hot-threads.md
  _opensearch/rest-api/nodes-apis/nodes-info.md
  _opensearch/rest-api/nodes-apis/nodes-stats.md
Labels: 5 - Final Editorial Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1489 [DOC] Update Dashboards plugin page to match core plugin format.
  _dashboards/install/plugins.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, hacktoberfest-accepted

#1501 Fixes broken links in docs page main branch
  _clients/k8s-operator.md
  _dashboards/index.md
  _opensearch/install/rpm.md
  _opensearch/query-dsl/term.md
  _opensearch/supported-field-types/range.md
  _opensearch/ux.md
  _search-plugins/sql/full-text.md
  _search-plugins/sql/sql/basic.md
Labels: 4 - Doc Review

#1358 Refactors JS client helper documentation
  _clients/cli.md
  _clients/go.md
  _clients/grafana.md
  _clients/index.md
  _clients/java-rest-high-level.md
  _clients/java.md
  _clients/javascript/helpers.md
  _clients/javascript/index.md
  _clients/k8s-operator.md
  _clients/logstash/index.md
  _clients/php.md
  _clients/python.md
  _clients/ruby.md
Labels: backport 2.3

#1510 Data Prepper 2.0 documentation
  _clients/data-prepper/data-prepper-reference.md
  _clients/data-prepper/get-started.md
  _clients/data-prepper/index.md
  _clients/data-prepper/pipelines.md
  _opensearch/ux.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, data-prepper

#1305 Build out overview for Security plugin documentation
  _security-plugin/index.md
Labels: security, 4 - Doc Review

#1376 new Text analyzers page + Lang analyzer section
  _opensearch/query-dsl/full-text.md
  _opensearch/query-dsl/text-analyzers.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1498 Fixes learning rate and momentum definitions
  _ml-commons-plugin/algorithms.md
Labels: backport 2.3

#1534 Fixes geo parameter and examples
  _opensearch/supported-field-types/geo-point.md
  _opensearch/supported-field-types/geo-shape.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1318 Performance analyzer documentation updates
  _monitoring-plugins/pa/index.md
Labels: backport 2.0, performance, backport 2.1, backport 2.2, backport 2.3

#1546 Changes learning rate description
  _ml-commons-plugin/algorithms.md
Labels: backport 2.3

#1435 Adds the path and http methods section to API style guide
  STYLE_API_TEMPLATE.md
Labels: 4 - Doc Review

#1550 Fix typo in Data Prepper doc
  _clients/data-prepper/index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1560 Add documentation for nodes api
  _opensearch/rest-api/nodes-apis/nodes-reload-secure.md
  _opensearch/rest-api/nodes-apis/nodes-usage.md
Labels: API, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1562 Left justify text in table on home page
  index.md
Labels: 4 - Doc Review, backport 2.3

#1561 Resize images on home page
  images/1_search.png
  images/2_monitoring.png
  images/3_security.png
  images/4_tracking.png
Labels: backport 2.3

#1577 add editorial changes for 1376-text analyzers
  _opensearch/query-dsl/text-analyzers.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1528 clarify how boolean query rules operate
  _opensearch/query-dsl/bool.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1593 Relocate legacy kibana names note to Configuration pages
  _security-plugin/configuration/index.md
Labels: backport 1.3, backport 2.0, security, backport 2.1, backport 2.2, backport 2.3

#1565 Adds get script language API
  _opensearch/rest-api/_script-apis/get-script-contexts.md
  _opensearch/rest-api/_script-apis/get-script-language.md
Labels: 5 - Final Editorial Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1608 Provides a more specific example header
  _opensearch/supported-field-types/text.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1594 Steve-O-Murphy analyzer apis documentation
  _opensearch/rest-api/analyze-apis/index.md
  _opensearch/rest-api/analyze-apis/perform-text-analysis.md
  _opensearch/rest-api/analyze-apis/terminology.md
Labels: API, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1626 fix new error causing heading to get added to a callout
  _opensearch/query-dsl/text-analyzers.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1633 Fix typo on Drag and Drop page
  _dashboards/drag-drop-wizard.md
Labels: backport 2.3

#1452 Putting all the Docker install material on a single page
  _opensearch/install/docker-security.md
  _opensearch/install/docker.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1636 Edit LDAP documentation for custom_attr_allowlist
  _security-plugin/configuration/ldap.md
Labels: 3 - Tech Review, security

#1644 Add disclaimer about remote fs usage and an example of setting env var
  _opensearch/install/compatibility.md
Labels: 2 - In progress, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1625 [DOC] New documentation: Self-host maps server
  _dashboards/selfhost-maps-server.md
Labels: 3 - Tech Review, 4 - Doc Review

#1662 Added to first paragraph to highlight the difference between transport and REST layer
  _security-plugin/configuration/tls.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1403 Added second paragraph to Stack traces option
  _opensearch/common-parameters.md
Labels: 3 - Tech Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1678 Change securityadmin.sh doc default port to 9200
  _security-plugin/configuration/security-admin.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1691 Fixes dev tools link
  _dashboards/run-queries.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1600 add note for supported units of min_index_age in ISM policies document
  _im-plugin/ism/policies.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, hacktoberfest-accepted

#1720 Adds note about duplicating java opts in multiple places
  _opensearch/install/important-settings.md
Labels: 3 - Tech Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1601 updates for index template v2
  _opensearch/index-templates.md
Labels: 1 - Backlog, index-management

#1658 Add filter_path parameter and restructure article
  _opensearch/common-parameters.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, hacktoberfest-accepted

#1740 update frontmatter for parent name to include all CAT API pages in left nav menu
  _api-reference/cat/cat-aliases.md
  _api-reference/cat/cat-allocation.md
  _api-reference/cat/cat-cluster_manager.md
  _api-reference/cat/cat-count.md
  _api-reference/cat/cat-field-data.md
  _api-reference/cat/cat-health.md
  _api-reference/cat/cat-indices.md
  _api-reference/cat/cat-nodeattrs.md
  _api-reference/cat/cat-nodes.md
  _api-reference/cat/cat-pending-tasks.md
  _api-reference/cat/cat-plugins.md
  _api-reference/cat/cat-recovery.md
  _api-reference/cat/cat-repositories.md
  _api-reference/cat/cat-segments.md
  _api-reference/cat/cat-shards.md
  _api-reference/cat/cat-snapshots.md
  _api-reference/cat/cat-tasks.md
  _api-reference/cat/cat-templates.md
  _api-reference/cat/cat-thread-pool.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#1719 Add ldap-example-v2.zip file to documentation-website repository
  ldap-example-v2.zip
Labels: 2 - In progress, backport 1.3, backport 2.0, security, backport 2.1, backport 2.2, backport 2.3

#1749 Update snapshot documentation with storage_type option
  _opensearch/snapshots/snapshot-restore.md
Labels: v2.4.0, snapshots

#1698 Add connection pooling settings to LDAP documentation
  _security-plugin/configuration/ldap.md
Labels: enhancement, security, v2.4.0

#1754 [Bug] Fix broken link to Bulk APIs page
  _dashboards/run-queries.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#1762 Revert "Add connection pooling settings to LDAP documentation"
  _security-plugin/configuration/ldap.md
Labels: security, v2.4.0

#1760 Move LDAP example zip file to assets > example folder for 2.3.0.
  assets/examples/ldap-example-v2.zip
Labels: 2 - In progress, security
