Repository opensearch-project/documentation-website, pull requests merged in 2023-02, with the labels that each got.

#2515 Security Analytics—additional updates following 2.5 release
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/sec-analytics-config/index.md
  _security-analytics/usage/alerts.md
  _security-analytics/usage/detectors.md
  _security-analytics/usage/findings.md
  _security-analytics/usage/overview.md
  _security-analytics/usage/rules.md
Labels: xx-documentation, v2.5.0, backport 2.5

#2536 Add warning about regex experession in ML
  _ml-commons-plugin/cluster-settings.md
Labels: 4 - Doc Review, backport 2.4, backport 2.5

#2568 Replace forum link with new link to dedicated Security Analytics forum
  _security-analytics/index.md
Labels: xx-documentation, backport 2.5

#2573 Cluster API TOC update
  _api-reference/cluster-api/cluster-allocation.md
  _api-reference/cluster-api/cluster-awareness.md
  _api-reference/cluster-api/cluster-decommission.md
  _api-reference/cluster-api/cluster-health.md
  _api-reference/cluster-api/cluster-settings.md
  _api-reference/cluster-api/cluster-stats.md
  _api-reference/cluster-api/index.md
Labels: API, backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, Quick fix, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2519 Adds max_shard_size parameter to shrink API
  _api-reference/index-apis/shrink-index.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2584 Adds max_shard_size to 1.3
  _api-reference/index-apis/shrink-index.md
Labels: backport 2.0, backport 2.1

#2580 Fix link in docker.md referencing About Security in OpenSearch page
  _install-and-configure/install-opensearch/docker.md
Labels: backport 1.3, backport 2.0, security, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2571 Adds 1.3.8 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2577 Add redirects for recent TOC changes
  _api-reference/cluster-api/cluster-settings.md
  _dashboards/discover/index-discover.md
  _dashboards/discover/time-filter.md
  _dashboards/quickstart-dashboards.md
  _security/access-control/index.md
  _security/configuration/generate-certificates.md
  _security/configuration/index.md
  _security/configuration/security-admin.md
  _security/configuration/tls.md
  _security/configuration/yaml.md
  _security/index.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2557 Adds warning to Java high-level REST client
  _clients/java-rest-high-level.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2615 Resolve backport 2.3 issue
  _dashboards/discover/dql.md
  _dashboards/discover/time-filter.md
  _dashboards/get-started/quickstart-dashboards.md
  _dashboards/index.md
  images/dashboards/add-panel.png
  images/dashboards/add-sample-data.png
  images/dashboards/dashboard-flight-quickstart.png
  images/dashboards/discover-quickstart.png
  images/dashboards/dql-interface.png
  images/dashboards/dql-query-result.png
  images/dashboards/dql-sample-dataset.png
  images/dashboards/dql-search-field.png
  images/dashboards/filter-data-discover.png
  images/dashboards/start-end-time.png
  images/dashboards/time-filter-popup.png
  images/dashboards/time-range.png
  images/dashboards/viz-panel-quickstart.png
  images/dashboards/viz-type-UI.png
  images/edit-filter.png
  images/interact-filter-dashboard.png
  images/last-7--days.png
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#2373 Add Peer Forwarder to doc website repo
  _data-prepper/peer-forwarder.md
Labels: 4 - Doc Review, data-prepper

#2630 Adds important callout
  _sass/custom/custom.scss
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2641 Adds warning to versions that are not latest
  _includes/warning.html
  _layouts/default.html
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#2640 Backport 2573 and fix dead links
  _api-reference/cluster-api/cluster-allocation.md
  _api-reference/cluster-api/cluster-health.md
  _api-reference/cluster-api/cluster-settings.md
  _api-reference/cluster-api/cluster-stats.md
  _api-reference/cluster-api/index.md
  _api-reference/multi-search.md
  _api-reference/search.md
  _install-and-configure/configuration.md
  _monitoring-plugins/alerting/monitors.md
Labels: bug, API, backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3

#2628 [DOC] Restructures Dashboards TOC
  _dashboards/admin-ui-index/index.md
  _dashboards/branding.md
  _dashboards/discover/index-discover.md
  _dashboards/maps-plugin.md
  _dashboards/maptiles.md
  _dashboards/quickstart-dashboards.md
  _dashboards/reporting.md
  _dashboards/visualize/area.md
  _dashboards/visualize/gantt.md
  _dashboards/visualize/geojson-regionmaps.md
  _dashboards/visualize/maptiles.md
  _dashboards/visualize/selfhost-maps-server.md
  _dashboards/visualize/visbuilder.md
  _dashboards/visualize/viz-index.md
  _dashboards/visualize/viz-types.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#1873 Add Trace analytics page to doc website repo
  _data-prepper/trace-analytics.md
  images/data-prepper/trace-analytics/trace-analytics-components.png
  images/data-prepper/trace-analytics/trace-analytics-feature.jpg
Labels: data-prepper

#2673 [DOC] Backport/backport 2628 to 2.4
  _dashboards/branding.md
  _dashboards/discover/dql.md
  _dashboards/discover/time-filter.md
  _dashboards/dql.md
  _dashboards/gantt.md
  _dashboards/get-started/quickstart-dashboards.md
  _dashboards/index.md
  _dashboards/maps-plugin.md
  _dashboards/maptiles.md
  _dashboards/reporting.md
  _dashboards/selfhost-maps-server.md
  _dashboards/visbuilder.md
  _dashboards/visualize/area.md
  _dashboards/visualize/geojson-regionmaps.md
  _dashboards/visualize/maptiles.md
  _dashboards/visualize/viz-index.md
  _dashboards/visualize/viz-types.md
  images/dashboards/add-panel.png
  images/dashboards/add-sample-data.png
  images/dashboards/dashboard-flight-quickstart.png
  images/dashboards/discover-quickstart.png
  images/dashboards/dql-interface.png
  images/dashboards/dql-query-result.png
  images/dashboards/dql-sample-dataset.png
  images/dashboards/dql-search-field.png
  images/dashboards/filter-data-discover.png
  images/dashboards/start-end-time.png
  images/dashboards/time-filter-popup.png
  images/dashboards/time-range.png
  images/dashboards/viz-panel-quickstart.png
  images/dashboards/viz-type-UI.png
  images/edit-filter.png
  images/interact-filter-dashboard.png
  images/last-7--days.png
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#2671 [DOC] Update TOC subpages
  _dashboards/discover/dql.md
  _dashboards/discover/multi-data-sources.md
  _dashboards/discover/time-filter.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2676 [DOC] Resolve backport 2.3
  _dashboards/branding.md
  _dashboards/gantt.md
  _dashboards/geojson-regionmaps.md
  _dashboards/maps-plugin.md
  _dashboards/maptiles.md
  _dashboards/reporting.md
  _dashboards/selfhost-maps-server.md
  _dashboards/visualize/area.md
  _dashboards/visualize/maptiles.md
  _dashboards/visualize/viz-index.md
  _dashboards/visualize/viz-types.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#2668 Center site layout
  _sass/custom/custom.scss
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2698 [Backport 2.2] Update Exploring data subpages
  _dashboards/discover/dql.md
  _dashboards/discover/time-filter.md
Labels: backport 1.3, backport 2.0, backport 2.1

#2661 Explains the keep_alive parameter for PIT
  _opensearch/point-in-time-api.md
  _opensearch/point-in-time.md
Labels: backport 2.4, backport 2.5

#2701 Revise rules for the use of enable and disable
  STYLE_GUIDE.md
  TERMS.md
Labels: 4 - Doc Review

#2658 Replace `IndexRequest.Builder.value()` call with call to `.document()`
  _clients/java.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2555 Refactors the clients index page
  _clients/index.md
  _clients/javascript/index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2717 Refactors clients index page for 2.2
  _clients/index.md
  _clients/javascript/index.md
Labels: backport 1.3, backport 2.0, backport 2.1

#2721 Commented out empty metrics and configuration sections.
  _data-prepper/pipelines/configuration/buffers/bounded-blocking.md
Labels: data-prepper

#2726 Fix ML commons typo
  _ml-commons-plugin/api.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2354 Adds video capability
  _includes/youtube-player.html
  _sass/_web-embed.scss
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2755 Backport 2.4 Update search telemetry title (#2753)
  _dashboards/search-telemetry.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#2762 [DOC] Updates title
  _dashboards/search-telemetry.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2764 Backports backport 2762 to 2.3
  _dashboards/search-telemetry.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#2766 Backports backport 2762 to 2.1
  _dashboards/search-telemetry.md
Labels: backport 1.3, backport 2.0

#2750 Update run-queries.md
  _dashboards/run-queries.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#2787 Updating Data Prepper links to point to doc website.
  _data-prepper/getting-started.md
  _data-prepper/managing-data-prepper/core-apis.md
  _data-prepper/managing-data-prepper/monitoring.md
  _data-prepper/migrating-from-logstash-data-prepper.md
Labels: data-prepper

#2544 Adds documentation site banner
  _includes/banner.html
  _includes/feedback.html
  _sass/custom/custom.scss
  assets/js/listener.js
  images/graphic-bg.jpg
  index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2816 Add banner to 2.2
  _includes/banner.html
  _includes/feedback.html
  _sass/custom/custom.scss
  assets/js/listener.js
  images/graphic-bg.jpg
  index.md
Labels: backport 1.3, backport 2.0, backport 2.1

#2812 Updated source authentication links.
  _data-prepper/pipelines/configuration/sources/http-source.md
  _data-prepper/pipelines/configuration/sources/otel-metrics-source.md
  _data-prepper/pipelines/configuration/sources/otel-trace.md
Labels: data-prepper

#2826 Checking in file to overwrite monitoring page.
  _data-prepper/managing-data-prepper/monitoring.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, data-prepper, backport 2.4, backport 2.5

#2844 Backport PR 1873
  _data-prepper/trace-analytics.md
  images/data-prepper/trace-analytics-components.png
  images/data-prepper/trace-analytics-feature.jpg
Labels: backport 2.0, backport 2.1

#2847 Fix links for Data Prepper trace analytics
  _data-prepper/trace-analytics.md
Labels: backport 2.0, backport 2.1

#2829 Remove Rally link
  _tuning-your-cluster/cluster.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2871 Fixing Data Prepper Monitoring page in TOC
  _data-prepper/managing-data-prepper/monitoring.md
  _data-prepper/monitoring.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, data-prepper, backport 2.4

#2885 Fixes graphics links and level 3 headings
  _dashboards/visualize/viz-index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2888 Adds security note to reporting CLI download page
  _dashboards/reporting-cli/rep-cli-install.md
Labels: 4 - Doc Review, backport 2.5

#2564 Add guide for migrating from Elasticsearch 7.10 to OpenSearch 1.x (latest)
  _install-and-configure/upgrade-opensearch/index.md
  _install-and-configure/upgrade-opensearch/rolling-upgrade.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2824 Correct description of encryption functionality managed by Security
  _security/index.md
  _troubleshoot/index.md
Labels: 3 - Tech Review, backport 1.3, backport 2.0, security, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2904 Refactor the Query DSL section
  _im-plugin/index-rollups/index.md
  _observing-your-data/alerting/monitors.md
  _opensearch/query-dsl/compound/bool.md
  _opensearch/query-dsl/compound/index.md
  _opensearch/query-dsl/full-text/index.md
  _opensearch/query-dsl/full-text/query-string.md
  _opensearch/query-dsl/function-score.md
  _opensearch/query-dsl/geo-and-xy/geo-bounding-box.md
  _opensearch/query-dsl/geo-and-xy/index.md
  _opensearch/query-dsl/geo-and-xy/xy.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/span-query.md
  _opensearch/query-dsl/term-vs-full-text.md
  _opensearch/query-dsl/term.md
  _opensearch/query-dsl/text-analyzers.md
  _opensearch/reindex-data.md
  _opensearch/search/autocomplete.md
  _opensearch/supported-field-types/date.md
  _opensearch/supported-field-types/range.md
  _search-plugins/knn/filter-search-knn.md
  _search-plugins/sql/full-text.md
  _search-plugins/sql/sql/basic.md
  _tuning-your-cluster/availability-and-recovery/snapshots/sm-api.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2927 Add guidance to plugin documentation for role based access control
  _observing-your-data/ad/security.md
  _observing-your-data/alerting/security.md
  _search-plugins/async/security.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2947 Fix dead links and Observing TOC
  _dashboards/reporting.md
  _dashboards/visualize/area.md
  _dashboards/visualize/maptiles.md
  _dashboards/visualize/selfhost-maps-server.md
  _data-prepper/common-use-cases/trace-analytics.md
  _install-and-configure/upgrade-opensearch/index.md
  _observing-your-data/notebooks.md
  _observing-your-data/notifications/index.md
  _opensearch/query-dsl/full-text/index.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2941 Add comment field to feedback panel
  _includes/banner.html
  _includes/feedback.html
  _sass/custom/custom.scss
  assets/js/listener.js
  images/graphic-bg.jpg
  images/graphic-bg.png
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2962 Move background size to css
  _includes/banner.html
  _sass/custom/custom.scss
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2964 Moved index_template permission to cluster section
  _security/access-control/permissions.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2996 Adds query DSL section to 2.3
  _im-plugin/index-rollups/index.md
  _observing-your-data/alerting/monitors.md
  _opensearch/query-dsl/compound/bool.md
  _opensearch/query-dsl/compound/index.md
  _opensearch/query-dsl/full-text/index.md
  _opensearch/query-dsl/full-text/query-string.md
  _opensearch/query-dsl/function-score.md
  _opensearch/query-dsl/geo-and-xy/geo-bounding-box.md
  _opensearch/query-dsl/geo-and-xy/index.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/span-query.md
  _opensearch/query-dsl/term-vs-full-text.md
  _opensearch/query-dsl/term.md
  _opensearch/query-dsl/text-analyzers.md
  _opensearch/reindex-data.md
  _opensearch/search/autocomplete.md
  _opensearch/supported-field-types/date.md
  _opensearch/supported-field-types/range.md
  _search-plugins/sql/full-text.md
  _search-plugins/sql/sql/basic.md
  _tuning-your-cluster/availability-and-recovery/snapshots/sm-api.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#2998 Adds query DSL section to 2.1
  _im-plugin/index-rollups/index.md
  _observing-your-data/alerting/monitors.md
  _opensearch/query-dsl/compound/bool.md
  _opensearch/query-dsl/compound/index.md
  _opensearch/query-dsl/full-text/index.md
  _opensearch/query-dsl/full-text/query-string.md
  _opensearch/query-dsl/function-score.md
  _opensearch/query-dsl/geo-and-xy/geo-bounding-box.md
  _opensearch/query-dsl/geo-and-xy/index.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/span-query.md
  _opensearch/query-dsl/term-vs-full-text.md
  _opensearch/query-dsl/term.md
  _opensearch/query-dsl/text-analyzers.md
  _opensearch/reindex-data.md
  _opensearch/search/autocomplete.md
  _opensearch/supported-field-types/date.md
  _opensearch/supported-field-types/range.md
  _search-plugins/sql/full-text.md
  _search-plugins/sql/sql/basic.md
  _tuning-your-cluster/availability-and-recovery/snapshots/sm-api.md
Labels: backport 1.3, backport 2.0

#2999 Adds query DSL section to 2.0
  _im-plugin/index-rollups/index.md
  _observing-your-data/alerting/monitors.md
  _opensearch/query-dsl/compound/bool.md
  _opensearch/query-dsl/compound/index.md
  _opensearch/query-dsl/full-text/index.md
  _opensearch/query-dsl/full-text/query-string.md
  _opensearch/query-dsl/function-score.md
  _opensearch/query-dsl/geo-and-xy/geo-bounding-box.md
  _opensearch/query-dsl/geo-and-xy/index.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/span-query.md
  _opensearch/query-dsl/term-vs-full-text.md
  _opensearch/query-dsl/term.md
  _opensearch/query-dsl/text-analyzers.md
  _opensearch/reindex-data.md
  _opensearch/search/autocomplete.md
  _opensearch/supported-field-types/date.md
  _opensearch/supported-field-types/range.md
  _search-plugins/sql/full-text.md
  _search-plugins/sql/sql/basic.md
Labels: backport 1.3

#3004 Changed sample to example in 2.1
  _api-reference/analyze-apis/perform-text-analysis.md
  _api-reference/cluster-api/cluster-health.md
  _api-reference/cluster-api/cluster-settings.md
  _api-reference/index-apis/clear-index-cache.md
  _api-reference/index-apis/dangling-index.md
  _api-reference/index.md
  _api-reference/nodes-apis/nodes-hot-threads.md
  _api-reference/nodes-apis/nodes-info.md
  _api-reference/nodes-apis/nodes-reload-secure.md
  _api-reference/nodes-apis/nodes-stats.md
  _api-reference/nodes-apis/nodes-usage.md
  _api-reference/rank-eval.md
  _api-reference/reload-search-analyzer.md
  _api-reference/script-apis/create-stored-script.md
  _api-reference/script-apis/delete-script.md
  _api-reference/script-apis/exec-script.md
  _api-reference/script-apis/exec-stored-script.md
  _api-reference/script-apis/get-script-contexts.md
  _api-reference/script-apis/get-script-language.md
  _api-reference/script-apis/get-stored-script.md
  _api-reference/snapshots/create-repository.md
  _api-reference/snapshots/create-snapshot.md
  _api-reference/snapshots/delete-snapshot-repository.md
  _api-reference/snapshots/delete-snapshot.md
  _api-reference/snapshots/get-snapshot-repository.md
  _api-reference/snapshots/get-snapshot-status.md
  _api-reference/snapshots/get-snapshot.md
  _api-reference/snapshots/restore-snapshot.md
  _api-reference/snapshots/verify-snapshot-repository.md
  _im-plugin/index-rollups/index.md
  _im-plugin/index-rollups/rollup-api.md
  _im-plugin/ism/api.md
  _monitoring-your-cluster/pa/api.md
  _monitoring-your-cluster/pa/rca/api.md
  _observing-your-data/ad/api.md
  _observing-your-data/alerting/api.md
  _opensearch/aggregations.md
  _opensearch/bucket-agg.md
  _opensearch/common-parameters.md
  _opensearch/data-streams.md
  _opensearch/index-alias.md
  _opensearch/index-data.md
  _opensearch/index-templates.md
  _opensearch/metric-agg.md
  _opensearch/pipeline-agg.md
  _opensearch/popular-api.md
  _search-plugins/async/index.md
  _search-plugins/sql/response-formats.md
  _search-plugins/sql/sql-ppl-api.md
  _search-plugins/sql/troubleshoot.md
  _security/access-control/api.md
  _security/authentication-backends/client-auth.md
  _tuning-your-cluster/availability-and-recovery/stats-api.md
Labels: backport 1.3, backport 2.0

#3007 Add deprecation warning to high-level python client
  _clients/python-high-level.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2992 Add and update documentation for detector APIs in Security Analytics
  _security-analytics/api-tools/detector-api.md
Labels: 4 - Doc Review, backport 2.4, backport 2.5

#3020 Index management TOC and naming change
  _dashboards/im-dashboards/datastream.md
  _dashboards/im-dashboards/forcemerge.md
  _dashboards/im-dashboards/index-management.md
  _dashboards/im-dashboards/index.md
  _dashboards/im-dashboards/rollover.md
  _dashboards/sm-dashboards.md
  _tuning-your-cluster/availability-and-recovery/snapshots/index.md
Labels: dashboards, Closed - Complete, index-management, backport 2.5

#3021 Update the documentation to describe using symlinks for sharing web identity token file for 'repository-s3' plugin
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: v2.6.0

#3023 Changed format and link of search backpressure
  _tuning-your-cluster/availability-and-recovery/search-backpressure.md
Labels: backport 2.4, backport 2.5

#2940 Add documentation for SSO
  _observing-your-data/sso.md
Labels: release-notes, observability

#3025 Add clarification to language in configuring node certificates documentation
  _security/configuration/tls.md
Labels: backport 1.3, backport 2.0, security, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#3033 Rewords cancellation count
  _tuning-your-cluster/availability-and-recovery/search-backpressure.md
Labels: backport 2.4, backport 2.5

#3035 [Backport 2.5][Manual] Updates the Install TOC + cleanup
  _config.yml
  _upgrade-to/dashboards-upgrade-to.md
  _upgrade-to/docker-upgrade-to.md
  _upgrade-to/index.md
  _upgrade-to/snapshot-migrate.md
  _upgrade-to/upgrade-to.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#3044 Revise cancellation stats description
  _tuning-your-cluster/availability-and-recovery/search-backpressure.md
Labels: backport 2.4, backport 2.5

#2870 format JSON.
  _search-plugins/knn/approximate-knn.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#3061 Corrected docker-compose env variable for 1.3 and fixed a typo in docker-compose.yml
  _install-and-configure/install-opensearch/docker.md
Labels: 4 - Doc Review

#3070 Add example Docker deployment script for upgrade testing and validation
  assets/examples/upgrade-demo-cluster.sh
Labels: 4 - Doc Review

#3071 Change Observing your data to Observability
  _config.yml
  _observing-your-data/index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#3066 Add documentation for log type updates in Security Analytics
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/detectors-config.md
  images/Security/automatic-mappings.png
  images/Security/default-mappings.png
  images/Security/detector_rules.png
  images/Security/log-field.png
  images/Security/pending-mappings.png
  images/Security/select_rules.png
Labels: release-notes, v2.6.0

#3079 Updated Observability title
  _observing-your-data/index.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#3081 Update point-in-time.md
  _opensearch/point-in-time.md
Labels: backport 2.4, backport 2.5

#3086 Updated Observability title (#3079)
  _observing-your-data/index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#3080 Change wording for rollover and index
  _dashboards/im-dashboards/datastream.md
  _dashboards/im-dashboards/rollover.md
  images/admin-ui-index/datastreams3.png
  images/admin-ui-index/rollover1.png
  images/admin-ui-index/rollover2.png
  images/admin-ui-index/rollover3.png
  images/admin-ui-index/rollover4.png
  images/admin-ui-index/rollover5.png
Labels: Closed - Complete, index-management

#2987 Add ML Dashboards page
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/ml-dashboard.md
  images/ml/ml-dashboard/deployed-models.png
  images/ml/ml-dashboard/ml-dashboard.png
  images/ml/ml-dashboard/model-node-details.png
  images/ml/ml-dashboard/view-status-details.png
Labels: release-notes, v2.6.0

#2903 Add Maps to Dashboard
  _dashboards/visualize/maps.md
  _dashboards/visualize/viz-index.md
Labels: dashboards, release-notes, v2.6.0

#2989 Revise search backpressure documentation for 2.6
  _tuning-your-cluster/availability-and-recovery/search-backpressure.md
Labels: release-notes, v2.6.0

#3098 Add changes to remote backed storage documentation for 2.6 release
  _tuning-your-cluster/availability-and-recovery/remote.md
Labels: release-notes, v2.6.0

#3083 Add documentation for log type updates in Security Analytics - pt. 2
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/usage/findings.md
  images/Security/findings1.png
  images/Security/findings2.png
  images/Security/findings4.png
Labels: release-notes, v2.6.0

#3100 Add 2.6 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2988 Add 2.6 prebuilt models to Machine Learning
  _ml-commons-plugin/model-serving-framework.md
  _ml-commons-plugin/pretrained-models.md
Labels: release-notes, v2.6.0

#3113 Add 2.6 to version history (#3100)
  version-history.md
Labels: backport 2.3

#3082 Split comments into parts
  assets/js/listener.js
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5
