Repository opensearch-project/documentation-website, pull requests merged in 2023-08, with the labels that each got.

#4660 Remove link list on script API index duplicated in related articles
  _api-reference/script-apis/index.md
Labels: backport 2.9

#4665 fix: mget http method typo
  _api-reference/document-apis/multi-get.md
Labels: backport 1.3, backport 2.9

#4653 Add documentation that fixes incorrect audit log setting names
  _security/audit-logs/index.md
Labels: backport 2.0, security, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#4663 Fix typo(s) and minor text improvements in neural-search page
  _search-plugins/neural-search.md
Labels: backport 2.9

#4640 Update plugins.md in dashboards
  _install-and-configure/install-dashboards/plugins.md
Labels: backport 2.9

#4731 Add `bytes` into "Query parameters" for CAT Segment Replication API
  _api-reference/cat/cat-segment-replication.md
Labels: backport 2.9

#4740 Add 1.3.12 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#4761 Update bulk.md
  _api-reference/document-apis/bulk.md
Labels: backport 2.9

#4768 Fix links
  _analyzers/index.md
  _analyzers/language-analyzers.md
  _analyzers/search-analyzers.md
Labels: backport 1.3, backport 2.9

#4772 Update logs.md
  _monitoring-your-cluster/logs.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#4790 Remove reload_search_analyzers API
  _api-reference/index.md
  _im-plugin/reload-search-analyzer.md
Labels: backport 2.8, backport 2.9

#4813 Restore take and restore snapshots for 2.5
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 2.4

#4814 Add zstd compression content to performance tuning doc
  _tuning-your-cluster/performance.md
Labels: backport 2.9

#4787 Refactor term query documentation
  _field-types/supported-field-types/date.md
  _field-types/supported-field-types/flat-object.md
  _field-types/supported-field-types/range.md
  _query-dsl/full-text/index.md
  _query-dsl/index.md
  _query-dsl/term.md
  _query-dsl/term/exists.md
  _query-dsl/term/fuzzy.md
  _query-dsl/term/ids.md
  _query-dsl/term/index.md
  _query-dsl/term/prefix.md
  _query-dsl/term/range.md
  _query-dsl/term/regexp.md
  _query-dsl/term/term.md
  _query-dsl/term/terms-set.md
  _query-dsl/term/terms.md
  _query-dsl/term/wildcard.md
  _search-plugins/sql/sql/basic.md
  _security/access-control/document-level-security.md
Labels: backport 1.3, backport 2.9

#4822 Update docker.md
  _install-and-configure/install-opensearch/docker.md
Labels: backport 1.3, backport 2.9

#4829 Add documentation to provide a link from detector creation to detection rule creation in using rules docs
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/usage/rules.md
Labels: 4 - Doc Review, security-analytics, backport 2.9

#4836 [DOC] Fix typo in IDs query doc
  _query-dsl/term/ids.md
Labels: backport 1.3, backport 2.9

#4737 Add Kafka source for DP 2.4
  _data-prepper/pipelines/configuration/sources/kafka.md
  _data-prepper/pipelines/configuration/sources/otel-trace.md
  _data-prepper/pipelines/pipelines.md
Labels: 6 - Done but waiting to merge, data-prepper, backport 2.9

#4679 Documentation for bucket ownership features in Data Prepper 2.4
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: 6 - Done but waiting to merge, data-prepper, backport 2.9

#4756 S3 scan docs
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: 5 - Final Editorial Review, data-prepper, backport 2.9

#4710 [DOC} Reconcile Alerting Monitors 2.9 Documentation Changes
  _observing-your-data/ad/index.md
  _observing-your-data/alerting/actions.md
  _observing-your-data/alerting/composite-monitors.md
  _observing-your-data/alerting/index.md
  _observing-your-data/alerting/monitors.md
  _observing-your-data/alerting/per-cluster-metrics-monitors.md
  _observing-your-data/alerting/per-document-monitors.md
  _observing-your-data/alerting/per-query-bucket-monitors.md
  _observing-your-data/alerting/triggers.md
  images/cluster-metrics.png
Labels: 4 - Doc Review, backport 2.9

#4850 Add k-NN vector field type
  _field-types/supported-field-types/index.md
  _field-types/supported-field-types/knn-vector.md
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-index.md
Labels: backport 2.9

#4848 S3 scan doc update
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: backport 2.9

#4859 Removes the Data Prepper csv sink codec
  _data-prepper/pipelines/configuration/sinks/s3.md
Labels: backport 2.9

#4862 Fix typos on S3 sink documentation
  _data-prepper/pipelines/configuration/sinks/s3.md
Labels: backport 2.9

#4854 Updated the intro text for the s3 sink.
  _data-prepper/pipelines/configuration/sinks/s3.md
Labels: backport 2.9

#4705 Add workload section to Benchmarks
  _benchmark/creating-custom-workloads.md
  _benchmark/workloads/corpora.md
  _benchmark/workloads/index.md
  _benchmark/workloads/indices.md
Labels: 5 - Final Editorial Review, backport 2.9

#4880 Update java-rest-high-level.md
  _clients/java-rest-high-level.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#4894 Add new Cohere connector blueprint
  _ml-commons-plugin/extensibility/connectors.md
Labels: backport 2.9

#4638 Add documentation topic to authentication backends section for HTTP basic authentication
  _security/authentication-backends/basic-authc.md
  _security/configuration/api-rate-limiting.md
  _security/configuration/configuration.md
  _security/configuration/yaml.md
Labels: security, backport 2.8, backport 2.9

#4907 Moves the generic sink options into the Sinks documentation
  _data-prepper/pipelines/configuration/sinks/sinks.md
  _data-prepper/pipelines/pipelines-configuration-options.md
Labels: backport 2.9

#4892 Add Index Stats API
  _api-reference/index-apis/stats.md
Labels: backport 1.3, backport 2.9

#4914 Case insensitive parameter for wildcard query
  _query-dsl/term/wildcard.md
Labels: backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#4920 Reformat wildcard query request
  _query-dsl/term/wildcard.md
Labels: backport 2.9

#4879 Add additional technical feedback to workloads
  _benchmark/workloads/corpora.md
  _benchmark/workloads/index.md
  _benchmark/workloads/indices.md
Labels: 4 - Doc Review, backport 2.9

#4299 [DOC] Add ingest processors documentation
  _api-reference/ingest-apis/create-ingest.md
  _api-reference/ingest-apis/create-update-ingest.md
  _api-reference/ingest-apis/delete-ingest.md
  _api-reference/ingest-apis/get-ingest.md
  _api-reference/ingest-apis/index.md
  _api-reference/ingest-apis/ingest-pipelines.md
  _api-reference/ingest-apis/ingest-processors.md
  _api-reference/ingest-apis/pipeline-failures.md
  _api-reference/ingest-apis/processors/append.md
  _api-reference/ingest-apis/processors/bytes.md
  _api-reference/ingest-apis/processors/convert.md
  _api-reference/ingest-apis/processors/csv.md
  _api-reference/ingest-apis/processors/date.md
  _api-reference/ingest-apis/processors/lowercase.md
  _api-reference/ingest-apis/processors/remove.md
  _api-reference/ingest-apis/processors/uppercase.md
  _api-reference/ingest-apis/simulate-ingest.md
Labels: 5 - Final Editorial Review, Content gap, backport 2.9

#4949 [DOC] Fix code example format and typos
  _api-reference/ingest-apis/processors/append.md
  _api-reference/ingest-apis/processors/bytes.md
Labels: API, backport 2.9
