Repository opensearch-project/documentation-website, pull requests merged in 2023-03, with the labels that each got.

#3128 Add formatting fixes for Security Analytics
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/usage/alerts.md
  _security-analytics/usage/detectors.md
  _security-analytics/usage/findings.md
  _security-analytics/usage/overview.md
  _security-analytics/usage/rules.md
Labels: backport 2.6

#2350 [DOC] Create new doc for Dashboard application
  _dashboards/dashboard/index.md
  images/dashboards/configure-bar-viz.png
  images/dashboards/dashboard-UI.png
  images/dashboards/dashboard-adding-panels.png
  images/dashboards/dashboard-basic.png
  images/dashboards/dashboard-combined.png
  images/dashboards/dashboard-customized.png
  images/dashboards/dashboard-index.png
  images/dashboards/discover-index.png
  images/dashboards/edit-viz.png
  images/dashboards/example-dashboard.png
  images/dashboards/new-bar-viz.png
Labels: dashboards, visualizations, backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#3116 Update the create snapshot repository documentation
  _api-reference/snapshots/create-repository.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: API, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, snapshots, backport 2.4, backport 2.5, Sev2, backport 2.6

#3137 Backport PR 3116 to 2.5
  _api-reference/snapshots/create-repository.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#3140 Backport PR 3116 to 2.3
  _api-reference/snapshots/create-repository.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2

#3143 Pr3116backport21
  _api-reference/snapshots/create-repository.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 1.3, backport 2.0

#3144 Backport PR 3116 to 2.0
  _api-reference/snapshots/create-repository.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 1.3

#3170 Remove children from dashboard app
  _dashboards/dashboard/index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3127 Make the left nav uniform color
  _sass/custom/custom.scss
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3134 Add Hugging Face link to ML documentation
  _ml-commons-plugin/pretrained-models.md
Labels: 4 - Doc Review, backport 2.6

#3069 Add query and filter context documentation
  _opensearch/query-dsl/query-filter-context.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3200 Fix links in jdbc and odbc driver pages
  _search-plugins/sql/sql/jdbc.md
  _search-plugins/sql/sql/odbc.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3223 Link fix
  _api-reference/snapshots/create-repository.md
  _api-reference/snapshots/get-snapshot-status.md
  _api-reference/snapshots/restore-snapshot.md
  _api-reference/snapshots/verify-snapshot-repository.md
  _dashboards/im-dashboards/forcemerge.md
  _dashboards/reporting.md
  _install-and-configure/install-dashboards/plugins.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security/access-control/api.md
  _security/configuration/system-indices.md
  _troubleshoot/security-admin.md
  _upgrade-to/upgrade-to.md
  about.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3225 Resolved merge conflicts
  _api-reference/snapshots/get-snapshot-status.md
  _api-reference/snapshots/restore-snapshot.md
  _api-reference/snapshots/verify-snapshot-repository.md
  _dashboards/im-dashboards/forcemerge.md
  _dashboards/reporting.md
  _install-and-configure/install-dashboards/plugins.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security/access-control/api.md
  _security/configuration/system-indices.md
  _troubleshoot/security-admin.md
  _upgrade-to/upgrade-to.md
  about.md
Labels: backport 1.3, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#3226 Resolved merge conflicts
  _api-reference/snapshots/get-snapshot-status.md
  _api-reference/snapshots/restore-snapshot.md
  _api-reference/snapshots/verify-snapshot-repository.md
  _dashboards/reporting.md
  _install-and-configure/install-dashboards/plugins.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security/access-control/api.md
  _security/configuration/system-indices.md
  _troubleshoot/security-admin.md
  _upgrade-to/upgrade-to.md
  about.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#3227 Resolved merge conflicts
  _api-reference/snapshots/get-snapshot-status.md
  _api-reference/snapshots/restore-snapshot.md
  _api-reference/snapshots/verify-snapshot-repository.md
  _dashboards/reporting.md
  _install-and-configure/install-dashboards/plugins.md
  _security/access-control/api.md
  _security/configuration/system-indices.md
  _troubleshoot/security-admin.md
  _upgrade-to/upgrade-to.md
  about.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#3230 Resolved merge conflicts
  _api-reference/snapshots/get-snapshot-status.md
  _api-reference/snapshots/restore-snapshot.md
  _api-reference/snapshots/verify-snapshot-repository.md
  _install-and-configure/install-dashboards/plugins.md
  _security/access-control/api.md
  _security/configuration/system-indices.md
  _troubleshoot/security-admin.md
  _upgrade-to/upgrade-to.md
  about.md
Labels: backport 1.3, backport 2.0

#3231 Fix links to graphics for 1.3
  _dashboards/visualize/viz-index.md
  images/dashboards/TSVB-1.png
  images/dashboards/area-chart-1.png
  images/dashboards/bar-chart-1.png
  images/dashboards/bar-horizontal-1.png
  images/dashboards/controls-1.png
  images/dashboards/coordinate-1.png
  images/dashboards/gantt-chart.png
  images/dashboards/gauge-1.png
  images/dashboards/heat-map-1.png
  images/dashboards/markdown-1.png
  images/dashboards/metric-chart-1.png
  images/dashboards/timeline-1.png
  images/dashboards/vega-1.png
  images/dashboards/vis-builder-2.png
Labels: backport 1.3

#3253 Fix refresh parameter for update by query
  _api-reference/document-apis/update-by-query.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3252 Add descriptions for index codec values
  _api-reference/index-apis/create-index.md
Labels: backport 1.3, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3097 Add Formatting Guide to GitHub
  CONTRIBUTING.md
  FORMATTING_GUIDE.md
  README.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3284 Data Prepper - Getting Started - updates
  _data-prepper/getting-started.md
Labels: 4 - Doc Review

#3285 Change examples to adhere to style guide
  FORMATTING_GUIDE.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#2769 Add documentation for metric ui and prometheus
  _observing-your-data/prometheusmetrics.md
  images/metrics/metrics1.png
  images/metrics/metrics2.png
  images/metrics/metrics3.png
  images/metrics/metricsgif.gif
Labels: dashboards, 6 - Done but waiting to merge, backport 2.4, observability, backport 2.5, Sev1, backport 2.6

#3303 Add Data Prepper home page redirect
  _data-prepper/index.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3199 Changes SSO to SSFO
  _observing-your-data/ssfo.md
Labels: 4 - Doc Review, backport 2.6

#3295 Remove script from gitignore
  .gitignore
Labels: backport 2.5, backport 2.6

#3085 add heading for OpenSearch file system recommendation
  _install-and-configure/install-opensearch/index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3297 More Data Prepper changes
  _data-prepper/getting-started.md
Labels: 4 - Doc Review

#3250 Addd examples on how to connect with Sigv4 for AOS and AOSS
  _clients/OpenSearch-dot-net.md
  _clients/go.md
  _clients/java.md
  _clients/javascript/index.md
  _clients/php.md
  _clients/python-low-level.md
  _clients/ruby.md
  _clients/rust.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3325 Update link to Opensearch Dashboard Plugin
  _install-and-configure/install-dashboards/plugins.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3298 Expand configuration information in Data Prepper Getting started guide.
  _data-prepper/getting-started.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, data-prepper, backport 2.4, backport 2.5, backport 2.6

#3352 Backport data prepper getting started update
  _data-prepper/getting-started.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#1834 add instruction for using parameters and sorting for stored script
  _api-reference/script-apis/create-stored-script.md
  _api-reference/script-apis/exec-stored-script.md
Labels: API, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, Sev3, backport 2.6

#3312 Fix graphics links for v 2.5 and 2.6 documentation
  _dashboards/visualize/gantt.md
  _dashboards/visualize/visbuilder.md
Labels: backport 2.5, backport 2.6

#2791 Updates label format
  _dashboards/reporting.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3365 Backport Data Prepper config doc to 2.5
  _data-prepper/getting-started.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#3366 Backport Data Prepper config doc update to 2.4
  _data-prepper/getting-started.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3

#3367 Backport data prepper config changes to 2.3
  _data-prepper/getting-started.md
Labels: backport 2.0, backport 2.1, backport 2.2

#3369 Backport data prepper config to 2.2
  _data-prepper/getting-started.md
Labels: backport 2.0, backport 2.1

#3371 Backport data prepper config changes to 2.1
  _data-prepper/getting-started.md
Labels: backport 2.0

#3370 Clarify time filter step 1 per external feedback
  _dashboards/discover/time-filter.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3349 Updates read only and rollover sections for ISM
  _im-plugin/ism/policies.md
Labels: API, backport 2.0, index-management, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3350 Update slice parameter with additional information
  _api-reference/document-apis/reindex.md
Labels: API, backport 1.3, backport 2.0, index-management, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3381 Fix curl Unauthorized on windows
  _install-and-configure/install-opensearch/windows.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3052 Add steps for upgrading OpenSearch with Security enabled
  _install-and-configure/upgrade-opensearch/appendix/index.md
  _install-and-configure/upgrade-opensearch/appendix/rolling-upgrade-lab.md
  _install-and-configure/upgrade-opensearch/index.md
  _install-and-configure/upgrade-opensearch/rolling-upgrade.md
Labels: 5 - Final Editorial Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3401 Add coordinate map to 2.x documentation
  _dashboards/visualize/viz-index.md
  images/dashboards/coordinate-1.png
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3433 Fixes change from doc review that broke ToC linking
  _install-and-configure/upgrade-opensearch/appendix/rolling-upgrade-lab.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3444 Add newly approved pre-built models to 2.6
  _ml-commons-plugin/pretrained-models.md
Labels: 4 - Doc Review, backport 2.6

#2950 Add documentation for Mutate strings
  _data-prepper/pipelines/configuration/processors/mutate-string.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, data-prepper, backport 2.4, backport 2.5

#3262 Add reference to hybrid mmap extensions setting in k-NN
  _search-plugins/knn/performance-tuning.md
Labels: backport 2.5, backport 2.6

#3384 Update put-mapping.md: add "dynamic"
  _api-reference/index-apis/put-mapping.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3451 Fix table formatting for http_source doc.
  _data-prepper/pipelines/configuration/sources/http-source.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, data-prepper, backport 2.4, backport 2.5, backport 2.6

#3450 Fix table header in Bounded blocking doc.
  _data-prepper/pipelines/configuration/buffers/bounded-blocking.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, data-prepper, backport 2.4, backport 2.5, backport 2.6

#3467 Add 1.3.9 version to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3494 Add warning banner to querqy page
  _search-plugins/querqy/index.md
Labels: backport 2.4, backport 2.5, backport 2.6

#3520 Use website version for examples
  assets/examples/docker-compose.yml
  quickstart.md
Labels: 4 - Doc Review

#3519 Use website version for examples
  assets/examples/docker-compose.yml
  quickstart.md
Labels: 4 - Doc Review

#3518 Use website version for examples
  assets/examples/docker-compose.yml
  quickstart.md
Labels: 4 - Doc Review

#3517 Use website version for examples
  assets/examples/docker-compose.yml
  quickstart.md
Labels: 4 - Doc Review

#3521 Use website version for examples
  assets/examples/docker-compose.yml
  quickstart.md
Labels: Closed - Complete

#3522 Update example response with latest build
  quickstart.md
Labels: 4 - Doc Review

#3516 Use website version for examples
  assets/examples/docker-compose.yml
  quickstart.md
Labels: 4 - Doc Review

#2944 Change url for opensearch_security.openid.scope configuration setting
  _security/authentication-backends/openid-connect.md
Labels: backport 1.3, backport 2.5, backport 2.6

#2754 Update lambda example in reporting cli doc
  _dashboards/reporting-cli/rep-cli-lambda.md
Labels: backport 1.3, backport 2.5, backport 2.6

#3547 Update to breaking changes topic
  breaking-changes.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3548 Update permissions.md
  _tuning-your-cluster/replication-plugin/permissions.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3251 Add documentation for jwt_clock_skew_tolerance_seconds setting that resolves authentication errors
  _security/authentication-backends/openid-connect.md
  _security/authentication-backends/saml.md
  _security/configuration/configuration.md
Labels: backport 2.0, security, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3615 Fix an error in building an index from a model
  _search-plugins/knn/approximate-knn.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6
