Repository opensearch-project/documentation-website, pull requests merged in 2023-01, with the labels that each got.

#2287 Minor command line fixes
  _data-prepper/get-started.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2242 Adds documentation for Job Scheduler plugin
  _config.yml
  _job-scheduler-plugin/index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2171 Adds date math documentation
  _opensearch/bucket-agg.md
  _opensearch/query-dsl/term.md
  _opensearch/supported-field-types/date.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2060 Creates the Kendra plugin section in Compare Search Results
  _search-plugins/search-relevance/index.md
  images/kendra_query.png
Labels: backport 2.4

#2360 Removes cluster manager task throttling
  _opensearch/cluster-manager-task-throttling.md
Labels: backport 2.4

#2342 Adds Rust client documentation
  _clients/OSC-dot-net.md
  _clients/OSC-example.md
  _clients/OpenSearch-dot-net.md
  _clients/dot-net-conventions.md
  _clients/go.md
  _clients/java-rest-high-level.md
  _clients/java.md
  _clients/javascript/helpers.md
  _clients/javascript/index.md
  _clients/opensearch-py-ml.md
  _clients/php.md
  _clients/python-high-level.md
  _clients/python-low-level.md
  _clients/ruby.md
  _clients/rust.md
  _sass/custom/custom.scss
Labels: 3 - Tech Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2355 Add installation guide for Debian distribution
  _install-and-configure/install-opensearch/debian.md
Labels: Closed - Complete

#2371 Clean up RPM/YUM installation guide
  _install-and-configure/install-opensearch/rpm.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2385 Adds response fields to the cluster health API
  _api-reference/cluster-health.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2401 Remove experimental warning note for Security Analytics 2.5
  _security-analytics/index.md
Labels: 4 - Doc Review, v2.5.0

#1932 Add Core APIs to doc website repo.
  _data-prepper/core-apis.md
Labels: 5 - Final Editorial Review, data-prepper

#1944 Add Logs to doc website repo.
  _data-prepper/logs.md
Labels: 4 - Doc Review, data-prepper

#2407 Add new Rules documentation that covers YAML Editor view
  _security-analytics/usage/rules.md
  images/Security/Rule_details.png
  images/Security/create-a-rule.png
  images/Security/dupe-rule.png
  images/Security/rule_detail_yaml.png
Labels: 4 - Doc Review, v2.5.0, release-notes

#2406 Update opensearch-documentation-release-notes-2.4.0.md
  release-notes/opensearch-documentation-release-notes-2.4.0.md
Labels: 4 - Doc Review

#2403 Adds documentation for Admin UI index operations
  _dashboards/admin-ui-index/index-management.md
  _dashboards/admin-ui-index/index.md
  _dashboards/admin-ui-index/sm-dashboards.md
  images/admin-ui-index/aliases.PNG
  images/admin-ui-index/apply-policy.PNG
  images/admin-ui-index/create-alias.PNG
  images/admin-ui-index/create-template-expanded.png
  images/admin-ui-index/create-template.png
  images/admin-ui-index/reindex-expanded.png
  images/admin-ui-index/reindex.png
  images/admin-ui-index/shrink.png
  images/admin-ui-index/split-expanded.png
  images/admin-ui-index/split.png
  images/admin-ui-index/templates.PNG
  images/admin-ui-index/view-template.png
Labels: index-management, v2.5.0, release-notes

#2411 Fixes allow_partial_pit_creation
  _opensearch/point-in-time-api.md
Labels: backport 2.4

#2415 Adds border to images
  _sass/custom/custom.scss
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2374 Adds Jaeger trace data for analytics documentation
  _observability-plugin/trace/index.md
  _observability-plugin/trace/trace-analytics-jaeger.md
  images/trace-analytics/error-rate.png
  images/trace-analytics/sample-app.png
  images/trace-analytics/select-data.png
  images/trace-analytics/service-trace-data.png
  images/trace-analytics/services-jaeger.png
  images/trace-analytics/throughput.png
  images/trace-analytics/trace-details.png
Labels: 5 - Final Editorial Review, v2.5.0, release-notes

#2376 Adds maps documentation
  _dashboards/maps.md
  images/maps/add-layer.png
  images/maps/custom-map.png
  images/maps/layer-selection-panel.png
  images/maps/maps-default.png
  images/maps/new-layer.png
  images/maps/refresh.png
  images/maps/tooltip.png
Labels: 6 - Done but waiting to merge, v2.5.0, release-notes

#2408 Updates to Security Analytics documentation
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/usage/detectors.md
  _security-analytics/usage/overview.md
  images/Security/get-started.png
  images/Security/overview.png
  images/Security/rule_graph.png
Labels: 4 - Doc Review, v2.5.0, release-notes

#2384 Add GPU acceleration documentation
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/gpu-acceleration.md
  _ml-commons-plugin/model-serving-framework.md
  _neural-search-plugin/index.md
Labels: 6 - Done but waiting to merge, v2.5.0, release-notes, experimental

#2398 Adds cluster health by awareness attribute documentation
  _api-reference/cluster-health.md
Labels: 6 - Done but waiting to merge, v2.5.0, release-notes, experimental

#2363 Updates remote-backed storage documentation
  _opensearch/remote.md
Labels: 6 - Done but waiting to merge, v2.5.0, release-notes, experimental

#2428 Add Query String for rollups
  _im-plugin/index-rollups/index.md
Labels: 6 - Done but waiting to merge, v2.5.0, release-notes

#2427 Adds query string query documentation
  _opensearch/query-dsl/query-string.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2444 Admin UI further editorial updates
  _dashboards/admin-ui-index/index-management.md
  _dashboards/admin-ui-index/sm-dashboards.md
Labels: index-management, 4 - Doc Review

#2445 Adds second image style with no border
  _sass/custom/custom.scss
  index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2440 Adds installation guide for OpenSearch Dashboards debian distribution
  _install-and-configure/index.md
  _install-and-configure/install-dashboards/debian.md
  _install-and-configure/install-dashboards/index.md
  _install-and-configure/install-opensearch/debian.md
Labels: 4 - Doc Review, release-notes

#2422 Update field mapping documentation for Security Analytics
  _security-analytics/sec-analytics-config/detectors-config.md
  images/Security/default-mappings.png
  images/Security/log-field.png
  images/Security/pending-mappings.png
Labels: v2.5.0

#2426 Minor changes to Data Prepper index.md.
  _data-prepper/configuration/pipelines-configuration-options.md
  _data-prepper/configuration/sinks/file.md
  _data-prepper/configuration/sinks/stdout.md
  _data-prepper/core-apis.md
  _data-prepper/getting-started.md
  _data-prepper/index.md
  _data-prepper/log-analytics.md
  _data-prepper/logs.md
  _data-prepper/migrate-open-distro.md
  _data-prepper/migrating-from-logstash-data-prepper.md
  _data-prepper/pipelines.md
Labels: 4 - Doc Review, data-prepper

#2454 Debian OSD Install Guide - Editorial changes
  _install-and-configure/install-dashboards/debian.md
Labels: 4 - Doc Review

#2450 add two new settings for Anomaly Detection 2.5
  _monitoring-plugins/ad/settings.md
Labels: v2.5.0, release-notes

#2442 Add new ML cluster settings for 2.5
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/model-serving-framework.md
Labels: 4 - Doc Review, v2.5.0, release-notes

#2449 Remove Install and Configure home page
  _install-and-configure/configuration.md
  _install-and-configure/index.md
  _install-and-configure/install-dashboards/index.md
  _install-and-configure/install-opensearch/debian.md
  _install-and-configure/install-opensearch/docker.md
  _install-and-configure/install-opensearch/helm.md
  _install-and-configure/install-opensearch/index.md
  _install-and-configure/install-opensearch/rpm.md
  _install-and-configure/install-opensearch/windows.md
  _install-and-configure/plugins.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2438 Add cluster awareness and decommission docs
  _api-reference/cluster-awareness.md
  _api-reference/cluster-decommission.md
  _api-reference/cluster-health.md
  _api-reference/cluster-settings.md
  _api-reference/count.md
  _ml-commons-plugin/cluster-settings.md
Labels: v2.5.0, release-notes

#2458 Adds generated documentation to clients
  _clients/go.md
  _clients/java.md
  _clients/javascript/index.md
  _clients/python-low-level.md
  _clients/ruby.md
  _clients/rust.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2465 Fix links for 2.5 doc changes.
  _api-reference/cluster-health.md
  _clients/index.md
  _clients/opensearch-py-ml.md
  _dashboards/admin-ui-index/sm-dashboards.md
  _dashboards/visualize/maps.md
  _dashboards/visualize/viz-index.md
  _data-prepper/configuration/data-prepper-configuration.md
  _data-prepper/getting-started.md
  _data-prepper/migrating-from-logstash-data-prepper.md
  _data-prepper/pipelines.md
  _install-and-configure/install-dashboards/debian.md
  _install-and-configure/install-dashboards/docker.md
  _install-and-configure/install-dashboards/helm.md
  _install-and-configure/install-dashboards/plugins.md
  _install-and-configure/install-dashboards/rpm.md
  _install-and-configure/install-dashboards/tar.md
  _install-and-configure/install-dashboards/tls.md
  _install-and-configure/install-dashboards/windows.md
  _install-and-configure/install-opensearch/ansible.md
  _install-and-configure/install-opensearch/debian.md
  _install-and-configure/install-opensearch/docker.md
  _install-and-configure/install-opensearch/helm.md
  _install-and-configure/install-opensearch/rpm.md
  _install-and-configure/install-opensearch/tar.md
  _install-and-configure/install-opensearch/windows.md
  _ml-commons-plugin/gpu-acceleration.md
  _opensearch/snapshots/snapshot-management.md
  _tools/cli.md
Labels: 4 - Doc Review, v2.5.0, backport 2.2, backport 2.3, backport 2.4

#2466 Add k-NN filter to neural search
  _neural-search-plugin/index.md
Labels: 4 - Doc Review, v2.5.0, release-notes

#2468 Fix typo in Neural Search
  _neural-search-plugin/index.md
Labels: 4 - Doc Review, v2.5.0

#2437 Adds version history 2.5
  version-history.md
Labels: backport 1.3, backport 2.0, v2.5.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#2436 Adds 2.5.0 version
  _config.yml
  _data/versions.json
Labels: v2.5.0

#2470 Rewords release notes header
  release-notes/opensearch-documentation-release-notes-2.5.0.md
Labels: backport 2.5

#2480 Updates table format for version history
  version-history.md
Labels: backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2018 Add Monitoring to doc website repo
  _data-prepper/monitoring.md
Labels: 4 - Doc Review, data-prepper

#2375 Update docker.md
  _install-and-configure/install-opensearch/docker.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2487 Add additional ML cluster settings
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/model-serving-framework.md
Labels: 4 - Doc Review, backport 2.4, backport 2.5

#2492 Makes version selector sticky
  _sass/custom/custom.scss
Labels: backport 1.3, backport 2.0, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#2513 Adds .net client API documentation link
  _clients/OSC-dot-net.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5
