Repository opensearch-project/documentation-website, pull requests merged in 2023-06, with the labels that each got.

#4162 Add documentation for validating JWT with JWKS
  _security/authentication-backends/jwt.md
  _security/authentication-backends/openid-connect.md
  _security/configuration/configuration.md
Labels: security, release-notes, v2.8.0

#4208 Add documentation for Security Analytics UI updates for 2.8
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/usage/findings.md
  images/Security/automatic-mappings.png
  images/Security/detector-schedule.png
  images/Security/detector_rules.png
  images/Security/pending-mappings.png
  images/Security/select_rules.png
Labels: release-notes, v2.8.0, security-analytics

#4222 Update Data Prepper image
  images/data-prepper-pipeline.png
Labels: 4 - Doc Review, backport 2.7

#4147 Add documentation to support SigV4 serverless service as a data source connection for Dashboards
  _dashboards/discover/multi-data-sources.md
  images/dashboards/SigV4-setup.png
Labels: dashboards, release-notes, v2.8.0

#4228 Update flagged link
  _dashboards/reporting-cli/rep-cli-env-var.md
Labels: backport 2.5, backport 2.6, backport 2.7

#4207 Add refresh, flush, clear cache, and notifications documentation for index management in Dashboards
  _dashboards/im-dashboards/datastream.md
  _dashboards/im-dashboards/index-management.md
  _dashboards/im-dashboards/notifications.md
  images/admin-ui-index/notifications-individual.png
  images/admin-ui-index/notifications.png
Labels: 4 - Doc Review, release-notes, v2.8.0

#4209 Add segment replication cluster-level setting
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: 3 - Tech Review, v2.8.0

#3913 Add documentation for the custom-codecs plugin.
  _api-reference/index-apis/create-index.md
  _install-and-configure/plugins.md
Labels: backport 2.7

#4204 Add search pipeline documentation
  _search-plugins/index.md
  _search-plugins/search-pipelines/filter-query-processor.md
  _search-plugins/search-pipelines/index.md
  _search-plugins/search-pipelines/rename-field-processor.md
  _search-plugins/search-pipelines/script-processor.md
  images/search-pipelines.png
Labels: 4 - Doc Review, release-notes, v2.8.0, experimental

#4210 [DOC] Add backend documentation about configuring ISM notifications
  _im-plugin/notifications-settings.md
Labels: 6 - Done but waiting to merge, release-notes, v2.8.0

#4226 Add cross-cluster search documentation
  _observing-your-data/cross-cluster-replication.md
Labels: 3 - Tech Review, release-notes, v2.8.0

#4241 Add 2.8 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#4218 Updates the supported operating system section of install guide
  _install-and-configure/install-opensearch/debian.md
  _install-and-configure/install-opensearch/index.md
  _install-and-configure/install-opensearch/rpm.md
Labels: backport 1.3, 4 - Doc Review, backport 2.7

#4224 Update version and add link to examples - Javascript client
  _clients/javascript/helpers.md
  _clients/javascript/index.md
Labels: backport 1.3, 4 - Doc Review, backport 2.8

#4238 Updates text and adds more API links
  _api-reference/index.md
Labels: 4 - Doc Review, backport 2.8

#4267 Add documentation for score based password estimator settings
  _security/configuration/yaml.md
Labels: security, backport 2.8

#4291 Update point in time parameter for 2.6
  _search-plugins/point-in-time-api.md
  _search-plugins/point-in-time.md
Labels: backport 2.5

#4288 Updated the 404 message
  404.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#4297 Add info to enable search pipelines
  _search-plugins/search-pipelines/index.md
Labels: backport 2.8

#4287 Add documentation for API rate limiting
  _security/configuration/configuration.md
Labels: security, 4 - Doc Review, backport 2.8

#4232 Updated functions documentation
  _search-plugins/sql/functions.md
Labels: backport 2.8

#4302 Final text for 404
  404.md
Labels: 4 - Doc Review, backport 2.8

#4304 Updates based on feedback in Slack and doc website
  _tuning-your-cluster/index.md
Labels: 4 - Doc Review

#4290 Documents the Data Prepper opensearch sink's template_type parameter.
  _data-prepper/pipelines/configuration/sinks/opensearch.md
Labels: backport 2.8

#4327 Fix example for Security backend configuration
  _security/configuration/configuration.md
Labels: good first issue, security, configuration, 4 - Doc Review, Quick fix, backport 2.8

#4330 Fix TOC for Snapshot topic
  _tuning-your-cluster/availability-and-recovery/snapshots/index.md
Labels: 4 - Doc Review, backport 2.8

#4332 fixsnapshottopics
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
  _tuning-your-cluster/availability-and-recovery/snapshots/sm-api.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-management.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 2.8

#4203 Update searchable snapshot documentation to be more correct
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
Labels: backport 1.3, backport 2.8

#4353 Update plugins.md
  _install-and-configure/install-dashboards/plugins.md
Labels: backport 2.8

#4348 Add date nanoseconds field type
  _field-types/supported-field-types/date-nanos.md
  _field-types/supported-field-types/date.md
  _field-types/supported-field-types/dates.md
  _field-types/supported-field-types/geographic.md
  _field-types/supported-field-types/index.md
  _field-types/supported-field-types/object-fields.md
  _field-types/supported-field-types/rank.md
  _field-types/supported-field-types/string.md
Labels: 3 - Tech Review, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#4223 Add model access control documentation for ML Commons
  _ml-commons-plugin/algorithms.md
  _ml-commons-plugin/api.md
  _ml-commons-plugin/index.md
  _ml-commons-plugin/model-access-control.md
Labels: v2.9

#4363 Fix typo
  _field-types/supported-field-types/nested.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#4343 Update to migration documentation
  _upgrade-to/upgrade-to.md
Labels: 3 - Tech Review

#4352 Correct nested.md example
  _field-types/supported-field-types/nested.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#4410 Updated Prometheus Metrics Documentation
  _observing-your-data/prometheusmetrics.md
Labels: backport 2.7, backport 2.8

#4257 Adds documentation for rest admin api permissions feature
  _security/access-control/api.md
  _security/access-control/permissions.md
Labels: v2.9

#4420 Fix incorrect documentation in index-document.md and update-document.md
  _api-reference/document-apis/index-document.md
  _api-reference/document-apis/update-document.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#4424 Update document and index document changes
  _api-reference/document-apis/index-document.md
  _api-reference/document-apis/update-document.md
Labels: backport 2.5

#4436 Add 1.3.11 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#4451 Update docker version for 2.x
  _install-and-configure/install-dashboards/docker.md
  _install-and-configure/install-opensearch/docker.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#4466 Fix object fields link
  _opensearch/supported-field-types/index.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3
