Repository opensearch-project/documentation-website, pull requests merged in 2023-12, with the labels that each got.

#5771 Fix missing character typo
  _data-prepper/pipelines/configuration/processors/substitute-string.md
Labels: backport 2.11

#5727 Add note about configuring root CA for ldap in both authc and authz
  _security/authentication-backends/ldap.md
Labels: backport 2.11

#5629 Add distributed workload test tutorial
  _benchmark/user-guide/distributed-load.md
Labels: 5 - Final Editorial Review, backport 2.11

#5726 Add remote cluster state documentation
  _tuning-your-cluster/availability-and-recovery/remote-store/index.md
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-cluster-state.md
Labels: 5 - Final Editorial Review

#5791 Fix Benchmark TOC bug
  _benchmark/reference/telemetry.md
Labels: 4 - Doc Review, backport 2.11

#5797 Add line break in remote state doc
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-cluster-state.md
Labels: backport 2.10, backport 2.11

#5801 Remove duplicate setting in dashboard tls
  _install-and-configure/install-dashboards/tls.md
Labels: backport 2.11

#5804 [DOC]Documentation - Enable merge on refresh and merge on commit in Opensearch 2.1.0+
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: backport 2.11

#5768 Add force merge API
  _api-reference/index-apis/force-merge.md
Labels: backport 1.3, backport 2.11

#5824 Force merge API final editorial comment
  _api-reference/index-apis/force-merge.md
Labels: backport 1.3, backport 2.11

#5834 Fix typo from headdump to heapdump
  _benchmark/reference/telemetry.md
Labels: backport 2.11

#5818 Remove requirement to set only run on ML node to false for remote models
  _ml-commons-plugin/index.md
  _ml-commons-plugin/integrating-ml-models.md
  _ml-commons-plugin/remote-models/index.md
Labels: backport 2.11

#5781 [DOC] Add kv processor content gap doc
  _ingest-pipelines/processors/kv.md
  _ingest-pipelines/processors/lowercase.md
Labels: 4 - Doc Review, Content gap, v2.12.0

#5844 Add 1.3.14 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5838 [DOC] Edits to parameter table headings
  _ingest-pipelines/processors/append.md
  _ingest-pipelines/processors/bytes.md
  _ingest-pipelines/processors/convert.md
  _ingest-pipelines/processors/csv.md
  _ingest-pipelines/processors/date.md
  _ingest-pipelines/processors/grok.md
  _ingest-pipelines/processors/ip2geo.md
  _ingest-pipelines/processors/lowercase.md
  _ingest-pipelines/processors/remove.md
  _ingest-pipelines/processors/sparse-encoding.md
  _ingest-pipelines/processors/text-embedding.md
  _ingest-pipelines/processors/text-image-embedding.md
  _ingest-pipelines/processors/uppercase.md
Labels: backport 2.11

#5864 [DOC] Update remote store backpressure default setting
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
Labels: 4 - Doc Review, backport 2.11

#5689 Documentation for Data Prepper's kafka buffer
  _data-prepper/pipelines/configuration/buffers/kafka.md
Labels: 5 - Final Editorial Review, backport 2.11

#5865 Fixing OpenSearch operator helm install
  _tools/k8s-operator.md
Labels: backport 2.11

#5863 Add documentation for known issue with use of custom codecs on version 2.7.0
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: backport 2.7

#5077 update: add wsl commands to set the `vm.max_map_count`
  _install-and-configure/install-opensearch/index.md
Labels: backport 2.11

#4126 Add client compatibility
  _clients/index.md
Labels: backport 1.3, backport 2.11

#5880 Updates navigation header background color
  _includes/header.html
  _sass/_navigation-header.scss
  _sass/custom/custom.scss
Labels: backport-to-all

#5908 Update installing-benchmark.md
  _benchmark/user-guide/installing-benchmark.md
Labels: backport 2.11

#5870 Update remove ingest processor documentation for some metadata fields are not allowed to remove
  _ingest-pipelines/processors/remove.md
Labels: backport 2.11

#5917 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: 4 - Doc Review

#5203 docs: example aws lambda code to initialize client
  _clients/javascript/index.md
Labels: 5 - Final Editorial Review

#5830 Add sections for removing OpenSearch Dashboards Security plugin
  _security/authentication-backends/saml.md
  _security/configuration/disable.md
Labels: security, 4 - Doc Review

#5809 Add operations and schedule sections
  _benchmark/reference/workloads/operations.md
  _benchmark/reference/workloads/test-procedures.md
Labels: 5 - Final Editorial Review, Content gap, backport 2.11

#5942 Fix typo in 'Update settings permission' link
  _security/access-control/permissions.md
Labels: backport 1.3, backport 2.11

#5912 Added documentation for grok_when option
  _data-prepper/pipelines/configuration/processors/grok.md
Labels: 5 - Final Editorial Review, data-prepper

#4474 Fix the wrong formula to calculate the total number of unique entities supported in the anomaly detection plugin
  _observing-your-data/ad/index.md
Labels: 5 - Final Editorial Review, backport 2.11

#5914 Update JWT documentation to recommend only using jwt_header or audit logging not both
  _security/authentication-backends/jwt.md
Labels: backport 1.3, 4 - Doc Review, backport 2.11

#5969 Update dangling-index.md
  _api-reference/index-apis/dangling-index.md
Labels: backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5916 Add Benchmark concepts of service time and latency
  _benchmark/user-guide/concepts.md
  images/benchmark/b-latency-explanation-1.png
  images/benchmark/b-latency-explanation-2.png
  images/benchmark/b-latency-explanation-3.png
  images/benchmark/latency-explanation-1.png
  images/benchmark/latency-explanation-2.png
  images/benchmark/latency-explanation-3.png
  images/benchmark/service-time.png
Labels: 5 - Final Editorial Review, benchmark

#6002 Add an example for restoring a searchable snapshot
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
Labels: 4 - Doc Review, backport 2.11

#6010 Update PPL Kmeans example
  _search-plugins/sql/ppl/functions.md
Labels: 4 - Doc Review, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#6007 Remove beta warning from Java client version 1.2
  _clients/java.md
Labels: 4 - Doc Review

#6008 Remove unavaliable settings in Update Index API
  _api-reference/index-apis/update-settings.md
Labels: backport 1.3, 4 - Doc Review, backport 2.11
