Repository opensearch-project/documentation-website, pull requests merged in 2023-07, with the labels that each got.

#4383 Add warning about plugin permission
  _install-and-configure/plugins.md
Labels: backport 2.7, backport 2.8

#4512 Refactor bucket aggregations section
  _field-types/supported-field-types/date.md
  _query-dsl/aggregations/bucket-agg.md
  _query-dsl/aggregations/bucket/adjacency-matrix.md
  _query-dsl/aggregations/bucket/date-histogram.md
  _query-dsl/aggregations/bucket/date-range.md
  _query-dsl/aggregations/bucket/diversified-sampler.md
  _query-dsl/aggregations/bucket/filter.md
  _query-dsl/aggregations/bucket/filters.md
  _query-dsl/aggregations/bucket/geo-distance.md
  _query-dsl/aggregations/bucket/geohash-grid.md
  _query-dsl/aggregations/bucket/geohex-grid.md
  _query-dsl/aggregations/bucket/geotile-grid.md
  _query-dsl/aggregations/bucket/global.md
  _query-dsl/aggregations/bucket/histogram.md
  _query-dsl/aggregations/bucket/index.md
  _query-dsl/aggregations/bucket/ip-range.md
  _query-dsl/aggregations/bucket/missing.md
  _query-dsl/aggregations/bucket/multi-terms.md
  _query-dsl/aggregations/bucket/nested.md
  _query-dsl/aggregations/bucket/range.md
  _query-dsl/aggregations/bucket/reverse-nested.md
  _query-dsl/aggregations/bucket/sampler.md
  _query-dsl/aggregations/bucket/significant-terms.md
  _query-dsl/aggregations/bucket/significant-text.md
  _query-dsl/aggregations/bucket/terms.md
Labels: backport 2.8

#3665 Add new zip for example SAML configuration files that reflect latest version
  _security/authentication-backends/saml.md
  assets/examples/saml-example-custom.zip
  assets/examples/saml-example.zip
Labels: 2 - In progress, backport 2.0, security, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#4390 Add compound query types documentation
  _query-dsl/query-dsl/compound/bool.md
  _query-dsl/query-dsl/compound/boosting.md
  _query-dsl/query-dsl/compound/constant-score.md
  _query-dsl/query-dsl/compound/disjunction-max.md
  _query-dsl/query-dsl/compound/function-score.md
  _query-dsl/query-dsl/index.md
  _query-dsl/query-dsl/minimum-should-match.md
  images/decay-functions.png
Labels: backport 1.3, backport 2.8

#4530 Add geohash grid aggregation parameters
  _query-dsl/aggregations/bucket/geohash-grid.md
  _query-dsl/aggregations/bucket/geohex-grid.md
  _query-dsl/aggregations/bucket/geotile-grid.md
Labels: backport 1.3, backport 2.8

#4541 Replaces "Stack Management" with "Dashboards Management"
  _security/multi-tenancy/mt-agg-view.md
Labels: v2.9.0

#4550 [DOC] Update Management navigation interface in dashboards for UX revisions and add index management tutorial
  _dashboards/dev-tools/index-dev.md
  _dashboards/dev-tools/run-queries.md
  _dashboards/discover/multi-data-sources.md
  _dashboards/discover/time-filter.md
  _dashboards/im-dashboards/index.md
  _dashboards/im-dashboards/notifications.md
  _dashboards/sm-dashboards.md
  _dashboards/visualize/selfhost-maps-server.md
  _dashboards/visualize/visbuilder.md
  images/dashboards/dev-tools-console.png
Labels: 2 - In progress, v2.9.0

#4548 Add search pipeline metrics to Nodes Stats API
  _api-reference/nodes-apis/nodes-stats.md
Labels: release-notes, v2.9.0, 3 - Done

#4202 Add extensions documentation
  _config.yml
  _developer-documentation/extensions.md
  _developer-documentation/index.md
Labels: 6 - Done but waiting to merge, release-notes, experimental, v2.9.0

#4515 Add obfuscate processor
  _data-prepper/pipelines/configuration/processors/obfuscate.md
  _data-prepper/pipelines/configuration/processors/otel-trace-group.md
Labels: 5 - Final Editorial Review, data-prepper, backport 2.8

#4553 Search pipeline GA documentation
  _search-plugins/search-pipelines/filter-query-processor.md
  _search-plugins/search-pipelines/index.md
  _search-plugins/search-pipelines/rename-field-processor.md
  _search-plugins/search-pipelines/script-processor.md
Labels: 6 - Done but waiting to merge, release-notes, v2.9.0

#4477 Add partial flat object documentation
  _field-types/supported-field-types/flat-object.md
Labels: 6 - Done but waiting to merge, release-notes, v2.9.0

#4542 Add thread level details to _tasks API
  _api-reference/tasks.md
Labels: 6 - Done but waiting to merge, release-notes, v2.9.0

#4475 Add Lucene byte vector documentation
  _search-plugins/knn/knn-index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.9.0

#4024 [DOC] Add documentation for alerting dashboards and visualizations
  _observing-your-data/alerting/dashboards-alerting.md
  images/dashboards/alerting-dashboard.png
  images/dashboards/create-monitor-menu.png
  images/dashboards/edit-icon.png
  images/dashboards/link-icon.png
  images/dashboards/triangle-icon.png
  images/ellipsis-icon.png
Labels: 4 - Doc Review, v2.9.0

#4091 Add anomaly detection visualizations documentation
  _observing-your-data/ad/dashboards-anomaly-detection.md
  images/dashboards/add-detector.png
  images/dashboards/anomaly-detect-dashboard.png
  images/dashboards/ellipsis-icon.png
Labels: 4 - Doc Review, v2.9.0

#4580 [DOC] Add new property setting fast_double_writer to install documentation
  _install-and-configure/install-opensearch/index.md
Labels: 3 - Tech Review, v2.9.0

#4552 Update model access control documentation
  _ml-commons-plugin/api.md
  _ml-commons-plugin/model-access-control.md
Labels: v2.9.0

#4476 Add k-NN Faiss filtering documentation
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/filter-search-knn.md
  images/faiss-algorithm.jpg
Labels: release-notes, v2.9.0

#4517 Add geohash, geotile, and geobounds aggregation on geoshapes documentation
  _query-dsl/aggregations/bucket/geohash-grid.md
  _query-dsl/aggregations/bucket/geotile-grid.md
  _query-dsl/aggregations/metric/geobounds.md
Labels: 4 - Doc Review, release-notes, v2.9.0

#4340 Add S3 sink documentation
  _data-prepper/pipelines/configuration/sinks/file.md
  _data-prepper/pipelines/configuration/sinks/opensearch.md
  _data-prepper/pipelines/configuration/sinks/pipeline.md
  _data-prepper/pipelines/configuration/sinks/s3.md
  _data-prepper/pipelines/configuration/sinks/stdout.md
Labels: 4 - Doc Review, backport 2.8

#4577 Add Spark connector settings
  _search-plugins/sql/settings.md
Labels: 5 - Final Editorial Review, release-notes, v2.9.0

#4416 Rewrite Contributing and readme
  CONTRIBUTING.md
  FORMATTING_GUIDE.md
  README.md
Labels: 5 - Final Editorial Review

#4546 [DOC] Add Integrations new documentation
  _config.yml
  _integrations/index.md
  _observing-your-data/ss4o.md
  _observing-your-data/ssfo.md
  images/integrations/nginx-integration.gif
Labels: 5 - Final Editorial Review, release-notes, v2.9.0

#4421 Adds ZSTD and ZSTD_NO_DICT codecs to core (out of sandbox)
  _api-reference/index-apis/create-index.md
  _install-and-configure/plugins.md
Labels: 6 - Done but waiting to merge, release-notes, v2.9.0

#4586 removing trigger word weapons
  _security/access-control/api.md
Labels: backport 1.3, backport 2.7, backport 2.8

#4525 [DOC] Add new cluster metrics monitor supported APIs
  _observing-your-data/alerting/actions.md
  _observing-your-data/alerting/api.md
  _observing-your-data/alerting/dashboards-alerting.md
  _observing-your-data/alerting/index.md
  _observing-your-data/alerting/monitors.md
  _observing-your-data/alerting/security.md
  _observing-your-data/alerting/triggers.md
  breaking-changes.md
  images/monitors.png
Labels: 5 - Final Editorial Review, release-notes, v2.9.0

#4537 Add document limits to index and bulk pages
  _api-reference/document-apis/bulk.md
  _im-plugin/index.md
Labels: 4 - Doc Review, release-notes, v2.9.0

#4554 Add Connectors and ML updates for 2.9
  STYLE_GUIDE.md
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/connectors.md
  _ml-commons-plugin/gpu-acceleration.md
  _ml-commons-plugin/ml-dashboard.md
  _ml-commons-plugin/ml-framework.md
  _ml-commons-plugin/pretrained-models.md
Labels: 4 - Doc Review, release-notes, v2.9.0

#4499 Add documentation for detector rule creation updates
  _security-analytics/index.md
  _security-analytics/usage/index.md
  _security-analytics/usage/rules.md
  images/Security/Rules.png
  images/Security/condition1.png
  images/Security/create-a-rule.png
  images/Security/details-rule.png
  images/Security/detection1.png
  images/Security/detection2.png
  images/Security/dupe-rule.png
  images/Security/overview-rule.png
  images/Security/rules-dup1.png
Labels: 5 - Final Editorial Review, release-notes, security-analytics, v2.9.0

#4571 Adds info about new codecs
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: 6 - Done but waiting to merge

#4588 Change Neural Search plugin from experimental to GA.
  _search-plugins/neural-search.md
Labels: 5 - Final Editorial Review, release-notes, v2.9.0

#4574 Updated tls.md with 2 different CA settings
  _install-and-configure/install-dashboards/tls.md
Labels: backport 2.8

#4491 [DOC] Add missing plugins.security.ssl.http.enabled for PEM paragraph
  _security/configuration/tls.md
Labels: backport 2.8

#4265 Update SQL limitations page for release 2.8 features
  _search-plugins/sql/limitation.md
Labels: backport 2.8

#4589 Add index codec documentation
  _api-reference/analyze-apis/perform-text-analysis.md
  _api-reference/index-apis/alias.md
  _api-reference/index-apis/clone.md
  _api-reference/index-apis/close-index.md
  _api-reference/index-apis/create-index.md
  _api-reference/index-apis/dangling-index.md
  _api-reference/index-apis/delete-index.md
  _api-reference/index-apis/exists.md
  _api-reference/index-apis/get-index.md
  _api-reference/index-apis/get-settings.md
  _api-reference/index-apis/open-index.md
  _api-reference/index-apis/shrink-index.md
  _api-reference/index-apis/split.md
  _api-reference/index-apis/update-settings.md
  _benchmark/configuring-benchmark.md
  _dashboards/sm-dashboards.md
  _im-plugin/index-codecs.md
  _im-plugin/index-rollups/index.md
  _im-plugin/index-settings.md
  _im-plugin/index-transforms/index.md
  _im-plugin/reindex-data.md
  _tuning-your-cluster/availability-and-recovery/snapshots/index.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: 3 - Tech Review, v2.9.0

#4127 Add documentation to support composite monitors in Alerting
  _observing-your-data/alerting/api.md
  _observing-your-data/alerting/composite-monitors.md
  _observing-your-data/alerting/monitors.md
  images/alerting/comp-details-alerts.png
  images/alerting/extract-q-editor.png
  images/alerting/plus-sign-icon.png
  images/alerting/trash-can-icon.png
  images/alerting/trigger1.png
  images/alerting/vis-editor.png
  images/dashboards/view-monitor-icon.png
Labels: 5 - Final Editorial Review, release-notes, v2.9.0

#4606 Fix links in Alerting documentation and other for 2.9 release
  _observing-your-data/alerting/actions.md
  _observing-your-data/alerting/composite-monitors.md
  _observing-your-data/alerting/monitors.md
  _observing-your-data/alerting/security.md
  _security-analytics/sec-analytics-config/detectors-config.md
Labels: 4 - Doc Review, alerting, v2.9.0

#4590 Add 2.9 version
  _config.yml
  _data/versions.json
Labels: v2.9.0

#4591 Add 2.9 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, v2.9.0, backport 2.7, backport 2.8

#4617 Fix a link name in documentation
  _observing-your-data/alerting/security.md
Labels: 4 - Doc Review, v2.9.0

#4635 Fix correlation engine documentation by removing all instances of the experimental flag for 2.9
  _security-analytics/api-tools/alert-finding-api.md
  _security-analytics/api-tools/correlation-eng.md
  _security-analytics/api-tools/detector-api.md
  _security-analytics/api-tools/mappings-api.md
  _security-analytics/api-tools/rule-api.md
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/correlation-config.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/security.md
  _security-analytics/usage/alerts.md
  _security-analytics/usage/correlation-graph.md
  _security-analytics/usage/detectors.md
  _security-analytics/usage/findings.md
  _security-analytics/usage/overview.md
  _security-analytics/usage/rules.md
  images/Security/sec-analytics/create-corr-rule.png
Labels: security-analytics, backport 2.9

#4641 Fix links for Personalize documentation
  _search-plugins/search-pipelines/personalize-search-ranking.md
  _search-plugins/search-relevance/index.md
Labels: backport 2.9

#4585 Add CIDR and User Agent processors
  _data-prepper/pipelines/configuration/processors/user-agent.md
  _data-prepper/pipelines/expression-syntax.md
Labels: 5 - Final Editorial Review, data-prepper, backport 2.8, backport 2.9

#4654 [DOC] Move Reporting to high-level section in nav menu
  _config.yml
  _reporting/index.md
  _reporting/rep-cli-create.md
  _reporting/rep-cli-cron.md
  _reporting/rep-cli-env-var.md
  _reporting/rep-cli-index.md
  _reporting/rep-cli-install.md
  _reporting/rep-cli-lambda.md
  _reporting/rep-cli-options.md
  _reporting/report-dashboard-index.md
Labels: 4 - Doc Review
