Repository opensearch-project/documentation-website, pull requests merged in 2023-09, with the labels that each got.

#4956 [DOC] Fixed converted date with time_zone
  _query-dsl/term/range.md
Labels: backport 2.9

#4974 Fix S3 table bug
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: backport 2.8, backport 2.9

#4970 Add script score query
  _query-dsl/index.md
  _query-dsl/specialized/index.md
  _query-dsl/specialized/script-score.md
Labels: backport 1.3, backport 2.9

#4994 Typo in convert_entry_type.md
  _data-prepper/pipelines/configuration/processors/convert_entry_type.md
Labels: backport 2.9

#4991 Add Migrations - Capture and Replay release documentation
  _install-and-configure/index.md
  _tools/index.md
  _upgrade-to/index.md
Labels: 5 - Final Editorial Review, backport 2.9

#4976 [DOC] Update segment replication to include alerting plugin limitation
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: 5 - Final Editorial Review, v2.10.0

#4995 Update docs for Remote Segment and Remote Translog store stats surfaced via nodes/indices/cluster stats APIs
  _api-reference/cluster-api/cluster-settings.md
  _api-reference/cluster-api/cluster-stats.md
  _api-reference/index-apis/stats.md
  _api-reference/nodes-apis/nodes-stats.md
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
Labels: 5 - Final Editorial Review, release-notes, v2.10.0

#5015 Changed format in wildcard query request
  _query-dsl/term/wildcard.md
Labels: backport 2.9

#4955 Add cluster setting for shard movement strategy
  _api-reference/cluster-api/cluster-settings.md
Labels: release-notes, v2.10.0

#5036 Add breaking changes documentation for ES 6.8 to OS 1.x migration issues- 1.3 branch
  _upgrade-to/upgrade-to.md
  breaking-changes.md
Labels: breaking, 2 - In progress, backport 1.3, backport 1.2, backport 1.1, migration

#4874 [DOC] Update Dev Tools for navigation changes
  _dashboards/dev-tools/index-dev.md
  _dashboards/dev-tools/run-queries.md
  images/dashboards/dev-tools-console.png
  images/dashboards/dev-tools-ui.png
  images/dashboards/query-request-ui.png
  images/icons/arrow-down-icon.png
  images/icons/play-icon.png
  images/icons/tip-icon.png
  images/icons/wrench-icon.png
Labels: Closed - Complete, v2.10.0

#4951 [DOC] Update Discover index page
  _dashboards/discover/dql.md
  _dashboards/discover/index-discover.md
  _dashboards/discover/multi-data-sources.md
  _dashboards/discover/time-filter.md
  _dashboards/quickstart.md
  images/dashboards/arrange-columns.png
  images/dashboards/data-fields.png
  images/dashboards/dataset-ui.png
  images/dashboards/discover-ui.png
  images/dashboards/discover-visual.png
  images/dashboards/sample-data.png
  images/dashboards/visualize-discover.png
  images/icons/alert-icon.png
  images/icons/calendar-oui.png
  images/icons/clock-icon.png
  images/icons/cross-icon.png
  images/icons/info-icon.png
  images/icons/inspect-icon.png
  images/icons/plus-icon.png
  images/icons/save-icon.png
Labels: 3 - Tech Review, v2.10.0

#5040 Add breaking changes documentation for ES 6.8 to OS 1.x migration issues- 1.2
  _upgrade-to/upgrade-to.md
  breaking-changes.md
Labels: breaking, migration

#4998 [DOC] Add new documentation for IP2Geo
  _api-reference/ingest-apis/processors/ip2geo.md
Labels: v2.10.0

#4969 Add documentation that supports custom log types
  _security-analytics/api-tools/index.md
  _security-analytics/api-tools/log-type-api.md
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/custom-log-type.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/sec-analytics-config/index.md
  _security-analytics/usage/overview.md
  images/Security/c-log-type.png
  images/Security/count.png
  images/Security/detector-overview.png
  images/Security/detector-rules.png
  images/Security/detector_rules.png
  images/Security/overview.png
  images/Security/recent-alerts.png
  images/Security/recent-findings.png
  images/Security/rule_graph.png
  images/Security/secanalytics-det-nav.png
Labels: 5 - Final Editorial Review, release-notes, security-analytics, v2.10.0

#5003 Add documentation for automatic Alerting workflows from detector creation
  _api-reference/cluster-api/cluster-settings.md
  _observing-your-data/alerting/composite-monitors.md
  _security-analytics/sec-analytics-config/detectors-config.md
Labels: 5 - Final Editorial Review, alerting, release-notes, security-analytics, v2.10.0

#5018 Add conversation search documentation
  _ml-commons-plugin/conversational-search.md
Labels: 5 - Final Editorial Review, release-notes, experimental, v2.10.0

#5037 Add segment replication + remote store GA information
  _tuning-your-cluster/availability-and-recovery/remote-store/index.md
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-segment-backpressure.md
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-store-stats-api.md
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: 5 - Final Editorial Review, release-notes, v2.10.0

#5044 Add breaking changes documentation for ES 6.8 to OS 1.x migration issues- 1.1
  _upgrade-to/upgrade-to.md
  breaking-changes.md
Labels: breaking, migration

#4876 [DOC] Create management section and advanced settings documentation
  _dashboards/management/advanced-settings.md
  _dashboards/management/management-index.md
  _dashboards/management/multi-data-sources.md
  images/dashboards/advanced-settings-ui.png
  images/dashboards/dashboards-management-ui.png
Labels: 5 - Final Editorial Review, v2.10.0, Content gap

#5022 Add new Bechmark IA
  _benchmark/index.md
  _benchmark/quickstart.md
  _benchmark/tutorials/index.md
  _benchmark/tutorials/sigv4.md
  _benchmark/user-guide/concepts.md
  _benchmark/user-guide/configuring-benchmark.md
  _benchmark/user-guide/creating-custom-workloads.md
  _benchmark/user-guide/index.md
  _benchmark/user-guide/installing-benchmark.md
  _benchmark/workloads/index.md
  images/benchmark/OSB-workflow.png
Labels: 5 - Final Editorial Review, backport 2.9

#5017 Ml commons
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/extensibility/connectors.md
  _ml-commons-plugin/index.md
  _ml-commons-plugin/model-access-control.md
Labels: 2 - In progress, backport 2.9

#5063 Add 1.3.13 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#5078 Add remote store main page updates. Add shallow snapshots
  _tuning-your-cluster/availability-and-recovery/remote-store/index.md
  _tuning-your-cluster/availability-and-recovery/remote-store/snapshot-interoperability.md
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: 4 - Doc Review, release-notes, v2.10.0

#4985 Add score normalization and combination documentation
  _ml-commons-plugin/api.md
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/model-access-control.md
  _ml-commons-plugin/pretrained-models.md
  _ml-commons-plugin/semantic-search.md
  _query-dsl/compound/bool.md
  _query-dsl/compound/boosting.md
  _query-dsl/compound/constant-score.md
  _query-dsl/compound/disjunction-max.md
  _query-dsl/compound/function-score.md
  _query-dsl/compound/hybrid.md
  _search-plugins/search-pipelines/filter-query-processor.md
  _search-plugins/search-pipelines/index.md
  _search-plugins/search-pipelines/normalization-processor.md
  _search-plugins/search-pipelines/personalize-search-ranking.md
  _search-plugins/search-pipelines/rename-field-processor.md
  _search-plugins/search-pipelines/script-processor.md
  _search-plugins/search-pipelines/search-processors.md
  images/neural-search-ingestion.png
  images/neural-search-query.png
  images/normalization-processor.png
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#5043 Add delimited term frequency token filter documentation
  _analyzers/token-filters/delimited-term-frequency.md
  _analyzers/token-filters/index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#5014 Add a note about zstd incompatibility with k-NN and security analytics
  _im-plugin/index-codecs.md
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#5000 Add custom-codecs to list of bundled plugins
  _install-and-configure/plugins.md
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#4990 Add concurrent segment search documentation
  _api-reference/index-apis/stats.md
  _api-reference/nodes-apis/nodes-stats.md
  _api-reference/profile.md
  _search-plugins/concurrent-segment-search.md
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#4988 Add term frequency functions to score script query
  _query-dsl/specialized/script-score.md
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#4987 Updating the K-NN Filters documentation due to recent enhancements in…
  _search-plugins/knn/filter-search-knn.md
  _search-plugins/knn/settings.md
  images/faiss-algorithm.jpg
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#4971 Add Microsoft Teams webhook support for notifications
  _observing-your-data/notifications/api.md
  _observing-your-data/notifications/index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#4959 Add ext object to search response
  _api-reference/search.md
Labels: 6 - Done but waiting to merge, release-notes, v2.10.0

#5049 Add Benchmark command flags
  _benchmark/commands/command-flags.md
Labels: 4 - Doc Review, backport 2.9

#4972 Add metrics section to benchmark
  _benchmark/metrics/index.md
  _benchmark/metrics/metric-keys.md
  _benchmark/metrics/metric-records.md
  images/benchmark/metric-index-pattern.png
Labels: 5 - Final Editorial Review, backport 2.9

#5084 Add 2.10 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#4946 Add a new table to list and describe supported log types for detector creation
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/correlation-config.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/sec-analytics-config/log-types.md
Labels: security-analytics, 3 - Done, backport 2.10

#5107 Update remote store stats api documentation
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-store-stats-api.md
Labels: backport 2.10

#5100 Add Benchmark results to remote store main page
  _tuning-your-cluster/availability-and-recovery/remote-store/index.md
Labels: backport 2.10

#4544 Add documentation for authorization on the REST layer
  _security/access-control/rest-layer-authz.md
  _security/access-control/users-roles.md
Labels: security, 4 - Doc Review, release-notes, v2.11.0
