Repository opensearch-project/documentation-website, pull requests merged in 2023-05, with the labels that each got.

#3803 Add ML fault tolerance
  _ml-commons-plugin/api.md
  _ml-commons-plugin/cluster-settings.md
Labels: 4 - Doc Review, release-notes, v2.7.0

#3789 Fix REST method names
  _im-plugin/index-alias.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3839 Update segment replication backpressure
  _sass/custom/custom.scss
  _tuning-your-cluster/availability-and-recovery/segment-replication/backpressure.md
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: 6 - Done but waiting to merge, v2.7.0

#3770 Add Search Relevance API documentation
  _search-plugins/search-relevance/index.md
  _search-plugins/search-relevance/stats-api.md
Labels: 6 - Done but waiting to merge, release-notes, v2.7.0

#3769 Add primary shard balancing documentation
  _api-reference/cluster-api/cluster-settings.md
Labels: 6 - Done but waiting to merge, release-notes, v2.7.0

#3714 Add flat object field type
  _field-types/flat-object.md
  _field-types/index.md
  _field-types/join.md
Labels: 6 - Done but waiting to merge, release-notes, v2.7.0

#2937 Add CAT segment replication API
  _api-reference/cat/cat-repositories.md
  _api-reference/cat/cat-segment-replication.md
Labels: 6 - Done but waiting to merge, release-notes, v2.7.0

#3804 Add Maps Stats API documentation
  _dashboards/visualize/maps-stats-api.md
Labels: 6 - Done but waiting to merge, release-notes, v2.7.0

#3920 Remove precision from TERMS and capitalize Logstash
  TERMS.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3814 Add correlation engine to Security Analytics documentation
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/correlation-config.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/usage/alerts.md
  _security-analytics/usage/correlation-graph.md
  _security-analytics/usage/findings.md
  _security-analytics/usage/index.md
  images/Security/corr-details-findings.png
  images/Security/findings1.png
  images/Security/sec-analytics/corr-cards.png
  images/Security/sec-analytics/corr-drill-dn.png
  images/Security/sec-analytics/corr-graph-detail.png
  images/Security/sec-analytics/corr-graph.png
  images/Security/sec-analytics/corr-rule-config1.png
  images/Security/sec-analytics/corr-rule-config2.png
  images/Security/sec-analytics/corr-rule-config3.png
  images/Security/sec-analytics/corr-rule-config4.png
  images/Security/sec-analytics/create-corr-rule.png
Labels: release-notes, v2.7.0, experimental, security-analytics

#3925 Adds per document monitor enhancements for 2.7
  _observing-your-data/alerting/monitors.md
Labels: 4 - Doc Review, v2.7.0

#3918 Add version history 2.7
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#3942 Remove a known limitation from searchable snapshot
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
Labels: backport 2.7

#3948 Remove experimental note from multi data source feature
  _dashboards/discover/multi-data-sources.md
Labels: 4 - Doc Review, backport 2.7

#3949 Fix cookie-splitting setting example for SAML backend documentation
  _security/authentication-backends/openid-connect.md
  _security/authentication-backends/saml.md
Labels: security, 4 - Doc Review, backport 2.7

#3941 Feedback on list-to-map
  _data-prepper/pipelines/configuration/processors/list-to-map.md
Labels: 4 - Doc Review, backport 2.5, backport 2.6, backport 2.7

#3964 Fixes issue in code and add redirects
  _api-reference/index-apis/create-index.md
  _api-reference/index-apis/exists.md
Labels: backport 1.3, backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#3975 More redirect fixes - index and ingestion APIs
  _api-reference/index-apis/clone.md
  _api-reference/index-apis/close-index.md
  _api-reference/index-apis/create-index.md
  _api-reference/index-apis/dangling-index.md
  _api-reference/index-apis/delete-index.md
  _api-reference/index-apis/exists.md
  _api-reference/index-apis/get-index.md
  _api-reference/index-apis/get-settings.md
  _api-reference/index-apis/index.md
  _api-reference/index-apis/open-index.md
  _api-reference/index-apis/put-mapping.md
  _api-reference/index-apis/shrink-index.md
  _api-reference/index-apis/split.md
  _api-reference/index-apis/update-settings.md
  _api-reference/index.md
  _api-reference/ingest-apis/create-update-ingest.md
  _api-reference/ingest-apis/delete-ingest.md
  _api-reference/ingest-apis/get-ingest.md
  _api-reference/ingest-apis/index.md
  _api-reference/ingest-apis/simulate-ingest.md
  _api-reference/search.md
  _api-reference/tasks.md
Labels: 4 - Doc Review, backport 2.7

#3965 CAT API redirects
  _api-reference/cat/cat-aliases.md
  _api-reference/cat/cat-allocation.md
  _api-reference/cat/cat-count.md
  _api-reference/cat/cat-field-data.md
  _api-reference/cat/cat-health.md
  _api-reference/cat/cat-indices.md
  _api-reference/cat/cat-nodeattrs.md
  _api-reference/cat/cat-nodes.md
  _api-reference/cat/cat-pending-tasks.md
  _api-reference/cat/cat-plugins.md
  _api-reference/cat/cat-recovery.md
  _api-reference/cat/cat-repositories.md
  _api-reference/cat/cat-segments.md
  _api-reference/cat/cat-shards.md
  _api-reference/cat/cat-snapshots.md
  _api-reference/cat/cat-tasks.md
  _api-reference/cat/cat-templates.md
  _api-reference/cat/cat-thread-pool.md
  _api-reference/cat/index.md
  _api-reference/document-apis/bulk.md
  _data-prepper/index.md
  _data-prepper/managing-data-prepper/configuring-data-prepper.md
Labels: 4 - Doc Review, backport 2.7

#3989 Add flat object to object field types
  _field-types/object-fields.md
Labels: backport 2.7

#3963 Fix actionsgroups API example response and cleanup topic generally
  _security/access-control/api.md
Labels: backport 2.0, security, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#4004 Add warning for versions that are not maintained
  _includes/warning.html
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#4002 Small fixes and redirects
  FORMATTING_GUIDE.md
  _clients/javascript/index.md
  _clients/python-low-level.md
  _install-and-configure/install-opensearch/docker.md
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: backport 2.7

#4013 More api redirects
  _api-reference/alias.md
  _api-reference/document-apis/delete-by-query.md
  _api-reference/document-apis/delete-document.md
  _api-reference/document-apis/get-documents.md
  _api-reference/document-apis/index-document.md
  _api-reference/document-apis/index.md
  _api-reference/document-apis/multi-get.md
  _api-reference/document-apis/reindex.md
  _api-reference/document-apis/update-by-query.md
  _api-reference/document-apis/update-document.md
  _api-reference/index-apis/put-mapping.md
  _im-plugin/index.md
Labels: 4 - Doc Review, backport 2.7

#4022 More redirect changes and small tweaks
  _api-reference/alias.md
  _api-reference/cluster-api/cluster-allocation.md
  _api-reference/cluster-api/cluster-awareness.md
  _api-reference/cluster-api/cluster-decommission.md
  _api-reference/cluster-api/cluster-health.md
  _api-reference/cluster-api/cluster-settings.md
  _api-reference/cluster-api/cluster-stats.md
  _api-reference/count.md
  _api-reference/index-apis/delete-index.md
  _im-plugin/data-streams.md
  _im-plugin/ism/managedindexes.md
  _im-plugin/ism/settings.md
  _im-plugin/security.md
  _install-and-configure/upgrade-opensearch/index.md
  _monitoring-your-cluster/logs.md
  _monitoring-your-cluster/pa/dashboards.md
  _query-dsl/query-dsl/compound/bool.md
Labels: 4 - Doc Review, backport 2.7

#4028 More redirect changes
  _install-and-configure/install-opensearch/docker.md
  _install-and-configure/install-opensearch/index.md
  _search-plugins/async/security.md
  _security/access-control/cross-cluster-search.md
  _security/access-control/default-action-groups.md
  _security/access-control/document-level-security.md
  _security/access-control/field-level-security.md
  _security/access-control/field-masking.md
  _security/access-control/impersonation.md
  _security/access-control/index.md
  _security/access-control/permissions.md
  _security/access-control/users-roles.md
  _security/authentication-backends/authc-index.md
  _security/authentication-backends/proxy.md
  _tools/logstash/index.md
Labels: 4 - Doc Review, backport 2.7

#4038 fix link to did you mean functionality
  _search-plugins/searching-data/did-you-mean.md
  _search-plugins/searching-data/index.md
Labels: backport 2.5, backport 2.6, backport 2.7

#4039 Update api.md
  _observing-your-data/alerting/api.md
Labels: backport 2.7

#3916 Document Data Prepper circuit breakers.
  _data-prepper/managing-data-prepper/configuring-data-prepper.md
Labels: 4 - Doc Review, backport 2.7

#4029 Add 404 page
  404.md
  index.md
Labels: 4 - Doc Review

#4061 redirect updates
  _observing-your-data/operational-panels.md
  _search-plugins/sql/ppl/functions.md
  _search-plugins/sql/ppl/index.md
  _security/configuration/disable.md
  _tools/logstash/advanced-config.md
Labels: 4 - Doc Review, backport 2.7

#3266 Document class metadata memory reservation impacts
  _install-and-configure/install-opensearch/index.md
Labels: backport 2.7

#4075 Fix typo on on Opensearch-py-ml
  _clients/opensearch-py-ml.md
Labels: 4 - Doc Review, backport 2.7

#3915 Data Prepper documentation for the SNS to SQS fan out pattern in S3
  _data-prepper/common-use-cases/s3-logs.md
Labels: v2.7.0, backport 2.7

#4084 Fix mapping redirect
  _field-types/index.md
Labels: 4 - Doc Review

#4093 More redirects and spelling fixes
  _api-reference/scroll.md
  _clients/java-rest-high-level.md
  _observing-your-data/ad/index.md
  _observing-your-data/ad/security.md
  _observing-your-data/alerting/security.md
  _observing-your-data/alerting/settings.md
  _query-dsl/aggregations/metric-agg.md
  _query-dsl/aggregations/pipeline-agg.md
  _query-dsl/analyzers/language-analyzers.md
  _search-plugins/knn/api.md
  _search-plugins/knn/index.md
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/performance-tuning.md
  _search-plugins/knn/settings.md
  _search-plugins/point-in-time-api.md
  _search-plugins/search-template.md
  _search-plugins/sql/full-text.md
  _search-plugins/sql/functions.md
  _search-plugins/sql/identifiers.md
  _search-plugins/sql/limitation.md
  _search-plugins/sql/monitoring.md
  _search-plugins/sql/ppl/index.md
  _search-plugins/sql/settings.md
  _search-plugins/sql/sql/aggregations.md
  _search-plugins/sql/sql/basic.md
  _search-plugins/sql/sql/complex.md
  _search-plugins/sql/sql/delete.md
  _search-plugins/sql/sql/functions.md
  _search-plugins/sql/sql/index.md
  _search-plugins/sql/sql/jdbc.md
  _search-plugins/sql/sql/metadata.md
  _search-plugins/sql/sql/odbc.md
  _search-plugins/sql/sql/partiql.md
  _search-plugins/sql/troubleshoot.md
  _search-plugins/sql/workbench.md
  _security-analytics/index.md
  _security/audit-logs/field-reference.md
  _security/audit-logs/index.md
  _security/audit-logs/storage-types.md
  _security/authentication-backends/openid-connect.md
  _security/configuration/yaml.md
  _troubleshoot/saml.md
  _tuning-your-cluster/index.md
Labels: 4 - Doc Review, backport 2.7

#4101 Logs wording changes
  _monitoring-your-cluster/logs.md
Labels: backport 1.3

#3771 feat: docker pull opensearch to opensearchproject
  _dashboards/visualize/selfhost-maps-server.md
Labels: backport 2.7

#1855 Describe SAML supported private key format and encryption algorithm
  _security/authentication-backends/saml.md
Labels: backport 2.7

#4085 Update asynchronous search response state values
  _search-plugins/async/index.md
Labels: backport 2.7

#4106 Add 1.3.10 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#4128 Adds list to REST API reference page
  _api-reference/index.md
Labels: 4 - Doc Review, backport 2.7

#4133 Remove Dashboard buttons
  _im-plugin/index.md
  _im-plugin/ism/index.md
  _observing-your-data/index.md
Labels: 4 - Doc Review

#4143 [Backport 1.3] Tweak debian installation for newer debian testing servers
  _install-and-configure/install-dashboards/debian.md
  _install-and-configure/install-opensearch/debian.md
Labels: installation

#4144 [Backport 2.7] Tweak debian installation for newer debian testing servers
  _install-and-configure/install-dashboards/debian.md
  _install-and-configure/install-opensearch/debian.md
Labels: installation

#3693 Update update-by-query.md
  _api-reference/document-apis/update-by-query.md
Labels: backport 2.7

#4161 remove-alias
  _api-reference/index.md
Labels: backport 1.3, 4 - Doc Review, backport 2.7

#4159 updateword
  _api-reference/index-apis/get-settings.md
Labels: backport 1.3, 4 - Doc Review, backport 2.7

#3585 Introduce new 'unsigned_long' numeric field type support
  _field-types/supported-field-types/flat-object.md
  _field-types/supported-field-types/index.md
  _field-types/supported-field-types/numeric.md
  _field-types/supported-field-types/unsigned-long.md
Labels: release-notes, v2.8.0

#4139 [Doc] Fix cosinesimil OpenSearch Score and Distance Function (#4138)
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-score-script.md
Labels: 3 - Tech Review, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#3908 Updated Date and Time Functions List
  _search-plugins/sql/functions.md
Labels: backport 2.7

#4181 Fix link (added slash)
  _api-reference/index.md
Labels: 4 - Doc Review

#4169 Add custom workload tutorial
  _benchmark/creating-custom-workloads.md
  _benchmark/index.md
  _benchmark/installing-benchmark.md
Labels: 5 - Final Editorial Review, backport 2.7

#4173 Add Benchmark command line reference
  _benchmark/commands/compare.md
  _benchmark/commands/download.md
  _benchmark/commands/execute-test.md
  _benchmark/commands/generate.md
  _benchmark/commands/index.md
  _benchmark/commands/info.md
  _benchmark/commands/list.md
Labels: 5 - Final Editorial Review, backport 2.7

#4190 Remove Benchmark home page from nav
  _benchmark/commands/execute-test.md
  _benchmark/index.md
Labels: backport 2.7

#4195 Fixes to redirects
  _api-reference/cat/cat-cluster_manager.md
  _api-reference/document-apis/index-document.md
  _api-reference/document-apis/multi-get.md
  _api-reference/document-apis/reindex.md
  _api-reference/index-apis/put-mapping.md
  _im-plugin/ism/managedindexes.md
  _install-and-configure/configuration.md
  _install-and-configure/install-dashboards/plugins.md
  _observing-your-data/notebooks.md
  _observing-your-data/trace/getting-started.md
  _observing-your-data/trace/index.md
  _observing-your-data/trace/ta-dashboards.md
  _query-dsl/aggregations/pipeline-agg.md
  _search-plugins/index.md
  _search-plugins/knn/jni-libraries.md
  _search-plugins/sql/cli.md
  _search-plugins/sql/index.md
  _search-plugins/sql/ppl/index.md
  _search-plugins/sql/settings.md
  _security/access-control/cross-cluster-search.md
  _security/access-control/default-action-groups.md
  _security/access-control/document-level-security.md
  _security/access-control/field-level-security.md
  _security/access-control/field-masking.md
  _security/access-control/impersonation.md
  _security/access-control/users-roles.md
  _security/audit-logs/field-reference.md
  _security/audit-logs/index.md
  _security/audit-logs/storage-types.md
  _security/configuration/configuration.md
  _security/configuration/system-indices.md
  _tools/logstash/advanced-config.md
  _tools/logstash/common-filters.md
  _tools/logstash/execution-model.md
  _tools/logstash/read-from-opensearch.md
  _tools/logstash/ship-to-opensearch.md
  index.md
Labels: 4 - Doc Review, backport 2.7

#4198 Add redirect to DP Config
  _data-prepper/managing-data-prepper/configuring-data-prepper.md
Labels: 4 - Doc Review, backport 2.7

#4132 Adds new parameter to Clear Index Cache API
  _api-reference/index-apis/clear-index-cache.md
Labels: release-notes, v2.8.0

#4187 Add segement replication upgrade changes for 2.8
  _install-and-configure/upgrade-opensearch/index.md
  _install-and-configure/upgrade-opensearch/rolling-upgrade.md
  _tuning-your-cluster/availability-and-recovery/segment-replication/backpressure.md
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: 3 - Tech Review, release-notes, v2.8.0
