Repository opensearch-project/documentation-website, pull requests merged in 2023-11, with the labels that each got.

#5480 [DOC] Refresh content and update screenshots based on 2.11 views
  _dashboards/discover/index-discover.md
  images/dashboards/add-data-fields.png
  images/dashboards/add-data.png
  images/dashboards/add-sample.png
  images/dashboards/define-search.png
  images/dashboards/discover-app.png
  images/dashboards/discover-index.png
  images/dashboards/discover-ui.png
  images/dashboards/discover-visual.png
  images/dashboards/doc-details.png
  images/dashboards/visualization-flight.png
  images/dashboards/visualize-discover.png
  images/icons/inspect-icon.png
  images/icons/minimize-icon.png
Labels: backport 2.10, backport 2.11

#5485 Fix index patterns to not have children
  _dashboards/management/index-patterns.md
Labels: backport 2.10, backport 2.11

#5488 [DOC]Fix heading level
  _dashboards/discover/index-discover.md
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5492 Corrects setting names for segment replication backpressure
  _tuning-your-cluster/availability-and-recovery/segment-replication/backpressure.md
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5378 [DOC] Add new documentation about Query Workbench
  _dashboards/query-workbench.md
  _search-plugins/sql/index.md
  _search-plugins/sql/ppl/index.md
  _search-plugins/sql/sql-ppl-api.md
  _search-plugins/sql/sql/index.md
  _search-plugins/sql/workbench.md
  images/dashboards/query-PPL-explain.png
  images/dashboards/query-explain.png
  images/dashboards/query-list.png
  images/dashboards/query-workbench-ppl.png
  images/dashboards/query-workbench-query-step2.png
  images/dashboards/query-workbench-ui.png
  images/query-workbench-UI.png
  images/sql.png
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, Content gap, 3 - Done, backport 2.9, backport 2.10, backport 2.11

#5376 [OSCI] Remove Snapshot Material in 1.3 Documentation
  _tuning-your-cluster/availability-and-recovery/snapshots/sm-api.md
Labels: OSCI

#5202 [DOC] data prepper secret extensions
  _data-prepper/managing-data-prepper/configuring-data-prepper.md
  _data-prepper/pipelines/configuration/processors/rename-keys.md
  _data-prepper/pipelines/configuration/sources/opensearch.md
  _data-prepper/pipelines/pipelines.md
Labels: backport 2.11

#5019 [DOC] Add new doc for grok processor
  _ingest-pipelines/processors/grok.md
Labels: backport 2.0, 4 - Doc Review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, Content gap, backport 2.9, backport 2.10, backport 2.11

#5516 Delete _benchmark/workloads/reference directory
  _benchmark/workloads/reference/index.md
  _benchmark/workloads/reference/indices.md
Labels: backport 2.11

#5423 [DOC] Fix rename processor 'otel_trace' to 'otel_traces'
  _data-prepper/common-use-cases/trace-analytics.md
  _data-prepper/managing-data-prepper/core-apis.md
  _data-prepper/managing-data-prepper/peer-forwarder.md
Labels: 4 - Doc Review, OSCI, backport 2.11

#5361 [DOC] Revise step 2 input code example
  _ingest-pipelines/processors/ip2geo.md
Labels: 4 - Doc Review, backport 2.11, documentation

#5113 Redesigned top nav and footer
  _data/alert.yml
  _data/top_nav.yml
  _includes/footer.html
  _includes/header.html
  _layouts/default.html
  _sass/_font-awesome.scss
  _sass/_nested-nav.scss
  _sass/custom/_custom-search.scss
  _sass/custom/custom.scss
  _sass/font-awesome/_bordered-pulled.scss
  _sass/font-awesome/_core.scss
  _sass/font-awesome/_fixed-width.scss
  _sass/font-awesome/_icons.scss
  _sass/font-awesome/_larger.scss
  _sass/font-awesome/_list.scss
  _sass/font-awesome/_mixins.scss
  _sass/font-awesome/_path.scss
  _sass/font-awesome/_rotated-flipped.scss
  _sass/font-awesome/_spinning.scss
  _sass/font-awesome/_stacked.scss
  _sass/font-awesome/_variables.scss
  assets/js/header-nav.js
Labels: 4 - Doc Review

#5457 Adjust Logstash example query quotes
  _tools/logstash/read-from-opensearch.md
Labels: backport 2.11

#5377 [DOC] Add httpclient5 maven dependency
  _clients/java.md
Labels: backport 2.11

#5555 Fix example code for temporary search pipelines
  _search-plugins/search-pipelines/using-search-pipeline.md
Labels: backport 2.9, backport 2.10, backport 2.11

#5562 [DOC] Fix AD-Visualizations integration feature documentation
  _observing-your-data/ad/dashboards-anomaly-detection.md
Labels: xx-documentation, dashboards, Usability, visualizations, anomaly-detection, backport 2.9, backport 2.10, backport 2.11

#5568 Link fix
  _ml-commons-plugin/algorithms.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5580 Update security documentation around username resolution
  _security/authentication-backends/authc-index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5582 Update TLS settings to have brief documentation around the use of encrypted SSL password settings
  _security/configuration/tls.md
Labels: backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5581 Update Security Docs: Clarify Anomaly Detection Access Control
  _observing-your-data/ad/security.md
Labels: backport 2.11

#5567 [Fix typo] Fix typo on java.md sample code
  _clients/java.md
Labels: backport 2.11

#5173 [Doc] new param in rollover action — copy_alias
  _im-plugin/ism/policies.md
Labels: backport 2.11

#5171 [Doc] explain ism_template.priority
  _im-plugin/ism/policies.md
Labels: backport 2.11

#5398 [DOC] Add new documentation for date index name processor
  _ingest-pipelines/processors/date-index-name.md
Labels: 4 - Doc Review, Content gap, backport 2.11

#5611 Change name of normalization processor in text
  _query-dsl/compound/hybrid.md
  _search-plugins/search-pipelines/normalization-processor.md
  _search-plugins/search-pipelines/search-processors.md
Labels: backport 2.10, backport 2.11

#5614 Fix API call to create connector in ml-commons->conversational-search->rag-pipeline
  _ml-commons-plugin/conversational-search.md
Labels: backport 2.11

#5610 Fix model group creation in ml-commons->conversational-search
  _ml-commons-plugin/conversational-search.md
Labels: backport 2.11

#5619 Updated doc_values for fields
  _field-types/supported-field-types/binary.md
  _field-types/supported-field-types/boolean.md
  _field-types/supported-field-types/ip.md
  _field-types/supported-field-types/numeric.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5628 Update cert guidelines
  _security/configuration/generate-certificates.md
Labels: 4 - Doc Review

#5600 Including info on OpenID Additional Parameters
  _security/authentication-backends/openid-connect.md
Labels: 4 - Doc Review, OSCI, backport 2.11

#5164 Add Telemetry devices reference
  _benchmark/quickstart.md
  _benchmark/reference/commands/command-flags.md
  _benchmark/reference/commands/execute-test.md
  _benchmark/reference/summary-report.md
  _benchmark/reference/telemetry.md
  _benchmark/user-guide/creating-osb-workloads.md
  _benchmark/user-guide/telemetry.md
Labels: 4 - Doc Review, benchmark, backport 2.11

#5633 ansible.md : add missing logstash_password variable
  _install-and-configure/install-opensearch/ansible.md
Labels: backport 2.11

#5608 Support URL
  _security/audit-logs/storage-types.md
Labels: 3 - Tech Review, backport 2.11

#5649 Update ml-framework.md
  _ml-commons-plugin/ml-framework.md
Labels: backport 2.11

#5657 Remove redundant line in s3-data-source.md
  _dashboards/management/S3-data-source.md
Labels: backport 2.11

#5665 Data Prepper's s3 source: visibility_duplication_protection
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: backport 2.11

#5663 Add Serverless configuration options for Data Prepper
  _data-prepper/pipelines/configuration/sinks/opensearch.md
  _data-prepper/pipelines/configuration/sources/opensearch.md
Labels: backport 2.11

#5655 Update update-document.md
  _api-reference/document-apis/update-document.md
Labels: backport 2.11

#5650 Fix typo in jwt authentication guide
  _security/authentication-backends/jwt.md
Labels: backport 2.11

#5504 fix java client sample error.
  _clients/java.md
Labels: OSCI, backport 2.11

#5664 Add DynamoDB source
  _data-prepper/pipelines/configuration/sources/dynamo-db.md
Labels: 4 - Doc Review, backport 2.11

#5670 Fix Get Mappings example
  _security-analytics/api-tools/mappings-api.md
Labels: security-analytics, backport 2.11
