Repository opensearch-project/documentation-website, pull requests merged in 2023-10, with the labels that each got.

#5128 [DOC] Move page navigation
  _dashboards/branding.md
  _dashboards/dev-tools/index-dev.md
  _dashboards/im-dashboards/component-templates.md
  _dashboards/im-dashboards/datastream.md
  _dashboards/im-dashboards/forcemerge.md
  _dashboards/im-dashboards/index-management.md
  _dashboards/im-dashboards/index.md
  _dashboards/im-dashboards/notifications.md
  _dashboards/im-dashboards/rollover.md
  _dashboards/management/management-index.md
  _dashboards/search-telemetry.md
  _dashboards/sm-dashboards.md
  images/dashboards/index-management-UI.png
  images/dashboards/snapshot-management-UI.png
  images/dashboards/snapshots-UI.png
  images/icons/star-icon.png
Labels: Quick fix, backport 2.10

#5121 Add documentation about setting a default model for neural search
  _search-plugins/neural-search.md
  _search-plugins/search-pipelines/creating-search-pipeline.md
  _search-plugins/search-pipelines/filter-query-processor.md
  _search-plugins/search-pipelines/index.md
  _search-plugins/search-pipelines/neural-query-enricher.md
  _search-plugins/search-pipelines/personalize-search-ranking.md
  _search-plugins/search-pipelines/rename-field-processor.md
  _search-plugins/search-pipelines/retrieving-search-pipeline.md
  _search-plugins/search-pipelines/script-processor.md
  _search-plugins/search-pipelines/search-pipeline-metrics.md
  _search-plugins/search-pipelines/search-processors.md
  _search-plugins/search-pipelines/using-search-pipeline.md
Labels: release-notes, v2.11.0

#5138 Add experimental label to conversational search
  _ml-commons-plugin/conversational-search.md
Labels: backport 2.10

#5137 Documentation for configurable merge policy
  _api-reference/cluster-api/cluster-settings.md
  _im-plugin/index-settings.md
Labels: release-notes, v2.11.0

#5179 fix semantic search docs search request
  _ml-commons-plugin/semantic-search.md
Labels: backport 2.10

#5162 Add documentation for new recovery setting
  _api-reference/cluster-api/cluster-settings.md
Labels: 4 - Doc Review, release-notes, v2.11.0

#5159 Add docs for Data Prepper dissect processor
  _data-prepper/pipelines/configuration/processors/dissect.md
  _data-prepper/pipelines/configuration/processors/drop-events.md
  _data-prepper/pipelines/configuration/processors/grok.md
  _data-prepper/pipelines/configuration/processors/key-value.md
  _data-prepper/pipelines/configuration/processors/list-to-map.md
Labels: 5 - Final Editorial Review, backport 2.10

#5153 Update Data Prepper key_value processor docs
  _data-prepper/pipelines/configuration/processors/key-value.md
Labels: 5 - Final Editorial Review, backport 2.10

#5122 Add documentation for Data Prepper translate processor
  _data-prepper/pipelines/configuration/processors/otel-metrics.md
  _data-prepper/pipelines/configuration/processors/translate.md
Labels: 5 - Final Editorial Review

#5189 Update example in SigV4 documentation for OpenSearch Benchmark
  _benchmark/tutorials/sigv4.md
Labels: backport 2.10

#5191 Removes warning about alerting and segment replication compatability
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: 4 - Doc Review, release-notes, v2.11.0

#4964 [DOC] Add new documentation for distributed tracing
  _observing-your-data/trace/distributed-tracing.md
Labels: 5 - Final Editorial Review, v2.11.0

#5176 Add updates to creating a detector UX
  _security-analytics/index.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/usage/detectors.md
  _security-analytics/usage/findings.md
  images/Security/automatic-mappings.png
  images/Security/detector-rules.png
  images/Security/pending-mappings.png
Labels: 5 - Final Editorial Review, release-notes, v2.11.0

#5195 Add Conversational Search changes for 2.11
  _ml-commons-plugin/conversational-search.md
Labels: 4 - Doc Review, release-notes, v2.11.0

#5204 Update conversational-search.md
  _ml-commons-plugin/conversational-search.md
Labels: backport 2.10

#5127 [DOC] Add new documentation for data sources
  _dashboards/dev-tools/index-dev.md
  _dashboards/management/S3-data-source.md
  _dashboards/management/accelerate-external-data.md
  _dashboards/management/data-sources.md
  _dashboards/management/index-patterns.md
  _dashboards/management/multi-data-sources.md
  _dashboards/management/query-data-source.md
  images/dashboards/S3-config-UI.png
  images/dashboards/accelerate-data-popup.png
  images/dashboards/add-fields-skipping-index.png
  images/dashboards/covering-index-fields.png
  images/dashboards/covering-index-naming.png
  images/dashboards/data-source-UI.png
  images/dashboards/data-sources-UI.png
  images/dashboards/delete-data-source.png
  images/dashboards/explorer-S3viz-UI.png
  images/dashboards/manage-data-source-UI.png
  images/dashboards/observability-logs-UI.png
  images/dashboards/query-data-sources-UI-2.png
  images/dashboards/query-workbench-S3.png
  images/dashboards/query-workbench-accelerate-data.png
  images/dashboards/run-index-query-workbench.png
  images/dashboards/skipping-index-settings.png
Labels: 4 - Doc Review, v2.11.0

#5168 Add multimodal search/sparse search/pre- and post-processing function documentation
  _api-reference/ingest-apis/processors/sparse-encoding.md
  _api-reference/ingest-apis/processors/text-embedding.md
  _api-reference/ingest-apis/processors/text-image-embedding.md
  _ml-commons-plugin/algorithms.md
  _ml-commons-plugin/api.md
  _ml-commons-plugin/conversational-search.md
  _ml-commons-plugin/extensibility/blueprints.md
  _ml-commons-plugin/extensibility/connectors.md
  _ml-commons-plugin/extensibility/index.md
  _ml-commons-plugin/gpu-acceleration.md
  _ml-commons-plugin/index.md
  _ml-commons-plugin/ml-dashboard.md
  _ml-commons-plugin/ml-framework.md
  _ml-commons-plugin/pretrained-models.md
  _ml-commons-plugin/semantic-search.md
  _query-dsl/specialized/index.md
  _query-dsl/specialized/neural-sparse.md
  _query-dsl/specialized/neural.md
  _search-plugins/neural-multimodal-search.md
  _search-plugins/neural-search.md
  _search-plugins/neural-sparse-search.md
  _search-plugins/neural-text-search.md
  _search-plugins/search-pipelines/neural-query-enricher.md
Labels: 5 - Final Editorial Review, release-notes, v2.11.0

#5143 Add terminate after behavior to concurrent segment search
  _search-plugins/concurrent-segment-search.md
Labels: 6 - Done but waiting to merge, release-notes, v2.11.0

#5120 Add total wait time to thread pool in nodes stats
  _api-reference/nodes-apis/nodes-stats.md
Labels: 6 - Done but waiting to merge, release-notes, v2.11.0

#5124 Remove experimental header from search comparison tool
  _search-plugins/search-relevance/index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.11.0

#5181 Adds documentation for log type categories
  _security-analytics/sec-analytics-config/custom-log-type.md
  _security-analytics/sec-analytics-config/log-types.md
  images/Security/c-log-type.png
Labels: release-notes, v2.11.0

#5208 Add 2.11 to version history
  version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10

#4655 Update snapshot-restore.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5272 Fix the minimum width of the main section of the page
  _sass/custom/custom.scss
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5227 [DOC] Change navigation for better usability
  _api-reference/ingest-apis/index.md
  _config.yml
  _dashboards/branding.md
  _dashboards/dql.md
  _dashboards/search-telemetry.md
  _ingest-pipelines/create-ingest.md
  _ingest-pipelines/delete-ingest.md
  _ingest-pipelines/get-ingest.md
  _ingest-pipelines/index.md
  _ingest-pipelines/pipeline-failures.md
  _ingest-pipelines/processors/append.md
  _ingest-pipelines/processors/bytes.md
  _ingest-pipelines/processors/convert.md
  _ingest-pipelines/processors/csv.md
  _ingest-pipelines/processors/date.md
  _ingest-pipelines/processors/index-processors.md
  _ingest-pipelines/processors/ip2geo.md
  _ingest-pipelines/processors/lowercase.md
  _ingest-pipelines/processors/remove.md
  _ingest-pipelines/processors/sparse-encoding.md
  _ingest-pipelines/processors/text-embedding.md
  _ingest-pipelines/processors/text-image-embedding.md
  _ingest-pipelines/processors/uppercase.md
  _ingest-pipelines/simulate-ingest.md
Labels: backport 2.11

#5129 Logstash tar installation instructions
  _tools/logstash/index.md
Labels: backport 2.11

#5226 Update OpenSearch k-NN Faiss Documentation
  _search-plugins/knn/knn-index.md
Labels: backport 2.10, backport 2.11

#5317 Remove unnecessary clause from Observability documentation
  _observing-your-data/log-ingestion.md
  _observing-your-data/trace/getting-started.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5320 Change k-NN Faiss example method to IVF
  _search-plugins/knn/knn-index.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#5345 Fix conversational search formatting
  _ml-commons-plugin/conversational-search.md
Labels: backport 2.11

#5348 Update concurrent-segment-search.md
  _search-plugins/concurrent-segment-search.md
Labels: backport 2.10, backport 2.11

#5355 Add pretrained model information for neural sparse
  _ml-commons-plugin/ml-framework.md
  _ml-commons-plugin/pretrained-models.md
  _search-plugins/neural-sparse-search.md
Labels: backport 2.11

#5315 [OSCI][DOCS] Solving Incorrect Capitalization of Cluster Manager Node
  images/cluster.png
Labels: backport 2.11

#5352 Update to log-types.md
  _security-analytics/sec-analytics-config/log-types.md
Labels: 4 - Doc Review

#5382 Fix link to lucene filtering implementation
  _search-plugins/knn/filter-search-knn.md
Labels: backport 2.11

#5381 Fix typo by removing .
  _field-types/supported-field-types/knn-vector.md
  _search-plugins/knn/knn-index.md
Labels: backport 2.11

#5383 add pretrained model description and saving disk description
  _ml-commons-plugin/pretrained-models.md
  _query-dsl/specialized/neural-sparse.md
  _search-plugins/neural-sparse-search.md
Labels: backport 2.11

#5395 Fix Benchmark command typo
  _benchmark/user-guide/installing-benchmark.md
Labels: backport 2.11

#5356 update benchmarking sigv4 documentation
  _benchmark/tutorials/sigv4.md
Labels: backport 2.11

#5399 Fix table formatting
  _observing-your-data/alerting/api.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5296 [OSCI][DOC] Correct documentation for CAT repositories
  _api-reference/cat/cat-repositories.md
Labels: OSCI, backport 2.11

#5354 [OSCI][DOC] Fixing error in java client documentation for creating indexes
  _clients/java.md
Labels: OSCI, backport 2.11

#5432 Add forum link to feedback panel
  _includes/feedback.html
  _sass/custom/custom.scss
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#5447 [DOC]Fix duplicative text and merge conflict data
  _dashboards/management/multi-data-sources.md
Labels: backport 2.11

#5429 Fix Sigv4 numbering bug
  _benchmark/tutorials/sigv4.md
Labels: backport 2.11

#5422 [OSCI][DOC] Updating HyphenationCompoundWordTokenFilter docs link from v8.7 to 9.8
  _analyzers/token-filters/index.md
Labels: backport 2.11

#5391 [OSCI][DOC] Update multi-data-sources.md documentation file
  _dashboards/management/multi-data-sources.md
Labels: OSCI

#5353 [OSCI][DOCs] Replacing 'indices' terms for 'indexes' terms ONLY for description texts
  _api-reference/cat/cat-aliases.md
  _api-reference/cat/cat-indices.md
  _api-reference/count.md
  _api-reference/document-apis/bulk.md
  _api-reference/document-apis/delete-by-query.md
  _api-reference/popular-api.md
  _benchmark/user-guide/concepts.md
  _benchmark/user-guide/creating-custom-workloads.md
  _benchmark/workloads/reference/index.md
  _benchmark/workloads/reference/indices.md
  _dashboards/sm-dashboards.md
  _data-prepper/pipelines/configuration/sources/opensearch.md
  _security/access-control/default-action-groups.md
  _security/access-control/permissions.md
  _security/multi-tenancy/multi-tenancy-config.md
  about.md
Labels: OSCI, backport 2.11

#5458 Add forum page click to GA
  _includes/feedback.html
  assets/js/listener.js
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11
