Repository opensearch-project/documentation-website, pull requests merged in 2024-07, with the labels that each got.

#7219 Add Render Template API
  _api-reference/render-template.md
Labels: API, 5 - Final Editorial Review, backport 1.3, backport 2.15

#7391 Update docs for new clause count setting
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: v2.16.0

#7414 Document new ingest and search pipeline allowlist settings
  _ingest-pipelines/processors/index-processors.md
  _search-plugins/search-pipelines/search-processors.md
Labels: 5 - Final Editorial Review, ingestion, v2.16.0

#7513 Add documentation for using rerank and normalization processors together
  _search-plugins/search-relevance/reranking-search-results.md
Labels: backport 2.15

#7236 Update-jwt-docs
  _security/authentication-backends/jwt.md
Labels: 4 - Doc Review, backport 2.14

#7506 Add more information to Python docs
  _clients/python-low-level.md
Labels: clients, 3 - Done, backport 2.15

#7600 Correct step 2 of custom local models
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/custom-local-models.md
  _ml-commons-plugin/pretrained-models.md
Labels: backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#7412 Update options and add more examples for add_entries processor
  _data-prepper/pipelines/configuration/processors/add-entries.md
Labels: 5 - Final Editorial Review, data-prepper 2.8, backport 2.15

#7229 Update multiple data sources and add TSVB and Vega viz types
  _dashboards/visualize/area.md
  _dashboards/visualize/gantt.md
  _dashboards/visualize/geojson-regionmaps.md
  _dashboards/visualize/maps-stats-api.md
  _dashboards/visualize/maps.md
  _dashboards/visualize/maptiles.md
  _dashboards/visualize/selfhost-maps-server.md
  _dashboards/visualize/tsvb.md
  _dashboards/visualize/vega.md
  _dashboards/visualize/visbuilder.md
  images/dashboards/Add_datasource.gif
  images/dashboards/add-sample-data.gif
  images/dashboards/configure-tsvb.gif
  images/dashboards/configure-vega.gif
  images/dashboards/create-datasource.gif
  images/dashboards/make_tsvb.gif
  images/dashboards/tsvb-viz.png
  images/dashboards/tsvb-with-annotations.png
  images/dashboards/tsvb.png
  images/make_vega.gif
  images/vega.png
Labels: backport 2.15

#6248 Add deriving metrics from logs use case to Data Prepper
  _data-prepper/common-use-cases/metrics-logs.md
Labels: Needs SME, data-prepper, Content gap, backport 2.14

#7564 [DOC] Clarify Interaction of JVM Memory Settings via OPENSEARCH_JAVA_OPTS with Default Values
  _install-and-configure/install-opensearch/index.md
Labels: 5 - Final Editorial Review, backport 2.15

#7284 Add documentation for the UBI plugin
  .github/vale/styles/Vocab/OpenSearch/Plugins/accept.txt
  .ruby-version
  _search-plugins/index.md
  _search-plugins/ubi/data-structures.md
  _search-plugins/ubi/dsl-queries.md
  _search-plugins/ubi/index.md
  _search-plugins/ubi/schemas.md
  _search-plugins/ubi/sql-queries.md
  _search-plugins/ubi/ubi-dashboard-tutorial.md
  assets/examples/ubi-dashboard.ndjson
  images/ubi/001_screens_side_by_side.png
  images/ubi/dashboard2.png
  images/ubi/first_dashboard.png
  images/ubi/histogram.png
  images/ubi/home.png
  images/ubi/index_pattern1.png
  images/ubi/index_pattern2.png
  images/ubi/index_pattern3.png
  images/ubi/laptop.png
  images/ubi/new_widget.png
  images/ubi/pie.png
  images/ubi/product_purchase.png
  images/ubi/query_id.png
  images/ubi/tag_cloud1.png
  images/ubi/tag_cloud2.png
  images/ubi/ubi-schema-interactions.png
  images/ubi/ubi-schema-interactions_legend.png
  images/ubi/ubi.png
  images/ubi/visualizations.png
  images/ubi/visualizations2.png
Labels: release-notes, 3 - Done, v2.15.0, backport 2.15

#7626 Update cat-nodes.md
  _api-reference/cat/cat-nodes.md
Labels: 3 - Tech Review, backport 2.15

#7636 Fix Key value table
  _data-prepper/pipelines/configuration/processors/key-value.md
Labels: backport 2.14, backport 2.15

#7631 Add fingerprint processor
  _ingest-pipelines/processors/fingerprint.md
  _ingest-pipelines/processors/index-processors.md
Labels: 4 - Doc Review, release-notes, v2.16.0

#7613 Add geo-centroid and weighted average aggregations documentation
  _aggregations/metric/geocentroid.md
  _aggregations/metric/weighted-avg.md
Labels: 3 - Tech Review, Needs SME, aggregations and analyzers, Content gap

#7400 Setting-envars-docs #3582
  _install-and-configure/configuring-opensearch/index.md
Labels: 5 - Final Editorial Review, security, backport 2.15

#7340 Document '_name' field in 'function_score' query's function definition
  _query-dsl/compound/function-score.md
Labels: 4 - Doc Review

#7657 Fix: the value of include_defaults is a boolean.
  _api-reference/index-apis/get-settings.md
Labels: backport 1.3, backport 2.15

#7663 Update detector-visualization integration documentation to specify real-time AD results only
  _observing-your-data/ad/dashboards-anomaly-detection.md
Labels: 4 - Doc Review, backport 2.15

#7518 Fixes table in Data Prepper write_json processor
  _data-prepper/pipelines/configuration/processors/write_json.md
Labels: 4 - Doc Review, backport 2.15

#7660 Quote all alphabetic defaults.
  _api-reference/cat/cat-aliases.md
  _api-reference/cat/cat-allocation.md
  _api-reference/cat/cat-health.md
  _api-reference/cat/cat-indices.md
  _api-reference/cat/cat-nodeattrs.md
  _api-reference/cat/cat-nodes.md
  _api-reference/cat/cat-pending-tasks.md
  _api-reference/cat/cat-plugins.md
  _api-reference/cat/cat-recovery.md
  _api-reference/cat/cat-repositories.md
  _api-reference/cat/cat-shards.md
  _api-reference/cat/cat-templates.md
  _api-reference/cat/cat-thread-pool.md
  _api-reference/cluster-api/cluster-allocation.md
  _api-reference/cluster-api/cluster-health.md
  _api-reference/count.md
  _api-reference/document-apis/delete-by-query.md
  _api-reference/document-apis/get-documents.md
  _api-reference/document-apis/index-document.md
  _api-reference/document-apis/multi-get.md
  _api-reference/document-apis/reindex.md
  _api-reference/document-apis/update-by-query.md
  _api-reference/document-apis/update-document.md
  _api-reference/explain.md
  _api-reference/index-apis/close-index.md
  _api-reference/index-apis/delete-index.md
  _api-reference/index-apis/exists.md
  _api-reference/index-apis/get-index.md
  _api-reference/index-apis/get-settings.md
  _api-reference/index-apis/open-index.md
  _api-reference/index-apis/update-settings.md
  _api-reference/search.md
  _api-reference/snapshots/create-repository.md
  _api-reference/snapshots/create-snapshot.md
  _api-reference/snapshots/get-snapshot-repository.md
  _api-reference/snapshots/verify-snapshot-repository.md
  _clients/javascript/helpers.md
  _dashboards/visualize/visbuilder.md
  _data-prepper/managing-data-prepper/configuring-data-prepper.md
  _im-plugin/index-rollups/rollup-api.md
  _im-plugin/index-transforms/transforms-apis.md
  _observing-your-data/notifications/api.md
  _security/audit-logs/storage-types.md
  _security/authentication-backends/openid-connect.md
  _security/authentication-backends/proxy.md
  _security/authentication-backends/saml.md
  _security/configuration/security-admin.md
  _security/configuration/tls.md
  _tuning-your-cluster/availability-and-recovery/snapshots/sm-api.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
  _tuning-your-cluster/index.md
Labels: 4 - Doc Review, backport 2.15

#7671 adding basic_auth config to ldap #907
  _security/authentication-backends/ldap.md
Labels: security, 4 - Doc Review, backport 2.15

#7668 Adding DLS with write permission recommendation #1273
  _security/access-control/document-level-security.md
Labels: security, 4 - Doc Review, backport 2.15

#7691 Update _security/configuration/tls.md
  _security/configuration/tls.md
Labels: 4 - Doc Review, backport 2.15

#7665 Add geopolygon query
  _query-dsl/geo-and-xy/geopolygon.md
  _query-dsl/geo-and-xy/index.md
  images/geopolygon-query.png
Labels: 4 - Doc Review, backport 2.15

#7702 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 4 - Doc review

#7632 Add new update_fields parameter to update workflow API
  _automating-configurations/api/create-workflow.md
Labels: 4 - Doc review, v2.16.0

#7695 Fix format issue for the split ingest processor documentation
  _ingest-pipelines/processors/split.md
Labels: 4 - Doc review, backport 2.15

#7726 Add 1.3.18 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#7637 Updates PPL description
  _search-plugins/sql/ppl/index.md
Labels: 3 - Done, backport 2.15

#7755 Remove redundant source
  _api-reference/document-apis/reindex.md
Labels: 4 - Doc review, backport 2.15

#7765 Update compare.md
  _benchmark/reference/commands/compare.md
Labels: backport 2.15

#7742 Document CreateAnomalyDetectorTool
  _ml-commons-plugin/agents-tools/tools/create-anomaly-detector.md
  _ml-commons-plugin/agents-tools/tools/index.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7745 Add strict_allow_templates option for the dynamic mapping parameter
  _field-types/dynamic.md
  _field-types/supported-field-types/nested.md
  _field-types/supported-field-types/object.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7769 Fixed typo in alerting example.
  _observing-your-data/alerting/per-cluster-metrics-monitors.md
Labels: backport 2.12, backport 2.13, backport 2.14, backport 2.15

#7774 Update kafka.md
  _data-prepper/pipelines/configuration/sources/kafka.md
Labels: backport 2.15

#7777 Fix ISM error prevention setting key is not correct
  _im-plugin/ism/api.md
  _im-plugin/ism/error-prevention/api.md
Labels: backport 2.15

#7707 Data Prepper documentation updates: autogeneration campaign
  _data-prepper/pipelines/configuration/processors/convert_entry_type.md
  _data-prepper/pipelines/configuration/processors/parse_ion.md
  _data-prepper/pipelines/configuration/processors/parse_json.md
  _data-prepper/pipelines/configuration/processors/parse_xml.md
  _data-prepper/pipelines/configuration/processors/write_json.md
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: data-prepper

#7708 Adds documentation for the Data Prepper delay processor.
  _data-prepper/pipelines/configuration/processors/delay.md
  _data-prepper/pipelines/configuration/processors/delete_entries.md
  _data-prepper/pipelines/configuration/processors/mutate-event.md
Labels: data-prepper, backport 2.15

#7779 Update install-and-configure/install-opensearch/index/#important-system-properties
  _install-and-configure/install-opensearch/index.md
Labels: 4 - Doc review, backport 2.15

#7741 Document the nested_path parameter in agent search tools
  _ml-commons-plugin/agents-tools/tools/neural-sparse-tool.md
  _ml-commons-plugin/agents-tools/tools/rag-tool.md
  _ml-commons-plugin/agents-tools/tools/vector-db-tool.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7639 Add documentation for Deprovision Workflow API allow_delete parameter
  .gitignore
  _automating-configurations/api/deprovision-workflow.md
  _search-plugins/search-pipelines/deleting-search-pipeline.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7761 Adds Documentation for dynamic query parameters for kNN search request
  _search-plugins/knn/approximate-knn.md
Labels: 4 - Doc review, release-notes, v2.16.0

#7685 Add Rollover API
  _api-reference/index-apis/rollover.md
Labels: 5 - Editorial review, backport 2.15

#7785 Fix liquid syntax errors.
  _api-reference/render-template.md
Labels: 4 - Doc review, backport 2.15

#7787 Explain ISM + link
  _im-plugin/refresh-analyzer.md
Labels: backport 2.15

#7794 Documentation Updates for plugins.query.datasources.enabled SQL Setting
  _search-plugins/sql/settings.md
Labels: release-notes, v2.16.0

#7641 Add the documentation of create or update alias API
  _api-reference/index-apis/update-alias.md
Labels: API, 5 - Editorial review, backport 2.15

#7653 Add Recovery API
  _api-reference/index-apis/recover.md
Labels: API, 5 - Editorial review, backport 2.15

#7703 Additing error details and escape method to nodes_dn #7681
  _install-and-configure/configuring-opensearch/security-settings.md
Labels: security, 4 - Doc review, backport 2.15

#7381 20240417 Adding OpenSearch demo configuration mac instructions
  _security/configuration/demo-configuration.md
Labels: security, 4 - Doc review, backport 2.15

#7697 Add documentation for configuring the password hashing algorithm and its properties
  _install-and-configure/configuring-opensearch/security-settings.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7799 Add disk free space cluster settings
  _ml-commons-plugin/cluster-settings.md
Labels: release-notes, v2.16.0

#7831 Fix alias page
  _api-reference/index-apis/update-alias.md
Labels: 4 - Doc review, backport 2.15

#7768 Add Segment API
  _api-reference/index-apis/segment.md
Labels: API, 5 - Editorial review, backport 2.15

#7797 [Doc] Lucene inbuilt scalar quantization
  .github/vale/styles/Vocab/OpenSearch/Words/accept.txt
  _search-plugins/knn/knn-vector-quantization.md
Labels: 4 - Doc review, release-notes, v2.16.0

#7829 Add geoshape query documentation
  _query-dsl/geo-and-xy/geoshape.md
  _query-dsl/geo-and-xy/index.md
Labels: 4 - Doc review, backport 2.15

#7820 Sorting and Search After in Hybrid Search
  _search-plugins/hybrid-search.md
  _search-plugins/searching-data/paginate.md
Labels: release-notes, v2.16.0

#7719 Move bulk API's batch_size parameter to processors
  _api-reference/document-apis/bulk.md
  _ingest-pipelines/processors/sparse-encoding.md
  _ingest-pipelines/processors/text-embedding.md
  _ml-commons-plugin/remote-models/batch-ingestion.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7646 Rework plugins doc and add the mapper-size plugin
  _install-and-configure/additional-plugins/index.md
  _install-and-configure/additional-plugins/mapper-size-plugin.md
  _install-and-configure/plugins.md
Labels: 3 - Done, backport 2.15

#7830 Add predefined model interface doc
  .github/vale/styles/Vocab/OpenSearch/Products/accept.txt
  _ml-commons-plugin/api/model-apis/register-model.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7837 Update index-codecs.md
  _im-plugin/index-codecs.md
Labels: backport 2.15

#7849 Update match.md
  _query-dsl/full-text/match.md
Labels: 4 - Doc review, backport 2.15

#7851 Update documentation for create / update repository api
  _api-reference/snapshots/create-repository.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7844 Add documentation on Kerberos configuration
  _security/authentication-backends/kerberos.md
  _security/configuration/configuration.md
Labels: 4 - Doc review, backport 2.15

#7868 Alerting plugin - changed default setting to true for v2.16.
  _observing-your-data/alerting/settings.md
Labels: 4 - Doc review, release-notes, v2.16.0

#7821 Add compatibility page
  _install-and-configure/install-opensearch/index.md
  _install-and-configure/install-opensearch/rpm.md
  _install-and-configure/os-comp.md
Labels: 5 - Editorial review, release-notes, v2.16.0

#7842 Update fuzzy.md
  _query-dsl/term/fuzzy.md
Labels: 4 - Doc review, backport 2.15

#7855 Add experimental feature flag to dashboard assistant
  _dashboards/dashboards-assistant/index.md
Labels: 4 - Doc review, release-notes, v2.16.0

#7713 MAINT: documentation update for certain processors
  _data-prepper/common-use-cases/log-enrichment.md
  _data-prepper/common-use-cases/trace-analytics.md
  _data-prepper/pipelines/configuration/processors/date.md
  _data-prepper/pipelines/configuration/processors/delete_entries.md
  _data-prepper/pipelines/configuration/processors/grok.md
  _data-prepper/pipelines/configuration/processors/otel_metrics.md
  _data-prepper/pipelines/configuration/processors/otel_traces.md
  _data-prepper/pipelines/configuration/processors/service_map.md
  _data-prepper/pipelines/configuration/processors/split_string.md
  _data-prepper/pipelines/configuration/processors/string_converter.md
  _data-prepper/pipelines/configuration/processors/substitute_string.md
  _data-prepper/pipelines/configuration/processors/trim_string.md
  _data-prepper/pipelines/configuration/processors/truncate.md
  _observing-your-data/trace/ta-dashboards.md
Labels: 4 - Doc review, data-prepper, backport 2.15

#7635 Add Index Template APIs
  _api-reference/index-apis/component-template.md
  _api-reference/index-apis/create-index-template.md
  _api-reference/index-apis/create-index.md
  _api-reference/index-apis/delete-index-template.md
  _api-reference/index-apis/get-index-template.md
Labels: API, 5 - Editorial review, backport 2.15

#7846 Add documentation for query insights - query metrics feature
  _observing-your-data/query-insights/index.md
  _observing-your-data/query-insights/query-metrics.md
  _observing-your-data/query-insights/top-n-queries.md
Labels: 4 - Doc review, release-notes, v2.16.0
