Repository opensearch-project/documentation-website, pull requests merged in 2024-09, with the labels that each got.

#7974 Add common operations section to User Guide.
  _benchmark/user-guide/understanding-workloads/choosing-a-workload.md
  _benchmark/user-guide/understanding-workloads/common-operations.md
Labels: 4 - Doc review, benchmark, backport 2.16

#8137 Update known limitations for kNN based indexes
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
Labels: backport 2.16

#8142 Update the default value of hasDocValues in BinaryFieldMapper
  _field-types/supported-field-types/binary.md
Labels: backport 2.16

#8113 Addition of full file paths in security documentation
  _install-and-configure/configuring-opensearch/security-settings.md
  _security/configuration/index.md
  _security/configuration/security-admin.md
  _security/configuration/yaml.md
Labels: 2 - In progress, security, 4 - Doc review

#8188 Delete graphs and copy edit
  _dashboards/query-workbench.md
Labels: backport 2.16

#8158 user accounts manipulation audit example
  _security/audit-logs/index.md
Labels: security, 4 - Doc review, backport 2.16

#8157 Add documentation for max_number_processors
  _ingest-pipelines/processors/index-processors.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, ingestion, v2.17.0

#8213 Allow copy as curl for Query DSL example in "Updating documents" section
  _getting-started/communicate.md
Labels: backport 2.13, backport 2.14, backport 2.15, backport 2.16

#8181 Doc update for concurrent search
  _search-plugins/concurrent-segment-search.md
Labels: release-notes, v2.17.0

#8176 Add new settings for remote publication
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-cluster-state.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8207 Add documentation changes for shallow snapshot v2
  _api-reference/snapshots/create-repository.md
  _api-reference/snapshots/create-snapshot.md
  _tuning-your-cluster/availability-and-recovery/remote-store/snapshot-interoperability.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#7912 Add Ascii folding token filter
  _analyzers/token-filters/asciifolding.md
  _analyzers/token-filters/index.md
Labels: 5 - Editorial review, analyzers, backport 2.16

#8196 Create documentation for snapshots with hashed prefix path type
  _api-reference/snapshots/create-repository.md
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8180 Adding new cluster search setting docs
  _install-and-configure/configuring-opensearch/search-settings.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8173 Grouping Top N queries documentation
  _observing-your-data/query-insights/grouping-top-n-queries.md
  _observing-your-data/query-insights/index.md
  _observing-your-data/query-insights/query-metrics.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8172 Document reprovision param for Update Workflow API
  _automating-configurations/api/create-workflow.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8139 Update GET top N api documentation
  _observing-your-data/query-insights/top-n-queries.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, backport 2.16

#8127 Update doc for adding new param in cat shards action for cancellation…
  _api-reference/cat/cat-shards.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8118 Add docs on skip_validating_missing_parameters in ml-commons connector
  _ml-commons-plugin/api/connector-apis/update-connector.md
  _ml-commons-plugin/remote-models/blueprints.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8171 Document use_case param for Create Workflow API, link to existing docs
  .github/vale/styles/Vocab/OpenSearch/Words/accept.txt
  _automating-configurations/api/create-workflow.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, backport 2.16

#8123 Document new experimental ingestion streaming APIs
  _api-reference/document-apis/bulk-streaming.md
  _api-reference/document-apis/bulk.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, experimental, v2.17.0

#8133 Terms query can accept encoded terms input as bitmap
  _query-dsl/term/terms.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8244 Derived field updates for 2.17
  _field-types/supported-field-types/derived.md
Labels: release-notes, v2.17.0

#8211 Add the `pipeline` subdocument to the `Sources` document
  _data-prepper/pipelines/configuration/sources/documentdb.md
  _data-prepper/pipelines/configuration/sources/dynamo-db.md
  _data-prepper/pipelines/configuration/sources/http.md
  _data-prepper/pipelines/configuration/sources/kafka.md
  _data-prepper/pipelines/configuration/sources/opensearch.md
  _data-prepper/pipelines/configuration/sources/otel-logs-source.md
  _data-prepper/pipelines/configuration/sources/otel-metrics-source.md
  _data-prepper/pipelines/configuration/sources/otel-trace-source.md
  _data-prepper/pipelines/configuration/sources/pipeline.md
  _data-prepper/pipelines/configuration/sources/s3.md
  _data-prepper/pipelines/configuration/sources/sources.md
Labels: backport 2.16

#7917 Add Cjk width token filter
  _analyzers/token-filters/cjk-width.md
  _analyzers/token-filters/index.md
Labels: 4 - Doc review, analyzers

#7916 Add Cjk bigram token filter page
  _analyzers/token-filters/cjk-bigram.md
Labels: 4 - Doc review, analyzers

#8229 Clarify doc on text_chunking processor: nested field in input and output
  _ingest-pipelines/processors/text-chunking.md
Labels: backport 2.16

#8233 Update flow framework additional fields in previous_node_inputs
  _automating-configurations/workflow-steps.md
Labels: 4 - Doc review, release-notes, v2.17.0

#8170 Add documentation for Faiss byte vector
  _field-types/supported-field-types/knn-vector.md
  _ml-commons-plugin/tutorials/semantic-search-byte-vectors.md
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/knn-score-script.md
  _search-plugins/knn/knn-vector-quantization.md
  _search-plugins/knn/painless-functions.md
  _search-plugins/vector-search.md
Labels: 3 - Tech review, release-notes, v2.17.0

#8243 Add changes for multiple signing keys
  _security/authentication-backends/jwt.md
Labels: 5 - Editorial review, release-notes, v2.17.0

#8228 Add documentation for workload management
  _install-and-configure/configuring-opensearch/availability-recovery.md
  _tuning-your-cluster/availability-and-recovery/workload-management.md
Labels: 5 - Editorial review, release-notes, v2.17.0

#8250 Fix workload formatting error
  _benchmark/user-guide/understanding-workloads/choosing-a-workload.md
Labels: 4 - Doc review, backport 2.16

#8191 Adding documentation for remote index use in AD
  _observing-your-data/ad/index.md
  _observing-your-data/ad/security.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, release-notes, v2.17.0

#8202 Add documentation for rule-based anomaly detection and imputation
  _observing-your-data/ad/dashboards-anomaly-detection.md
  _observing-your-data/ad/index.md
  _observing-your-data/ad/result-mapping.md
Labels: v2.17.0

#8246 Add documentation changes for disk-based k-NN
  .github/vale/styles/Vocab/OpenSearch/Words/accept.txt
  _field-types/supported-field-types/knn-vector.md
  _query-dsl/specialized/neural.md
  _search-plugins/knn/api.md
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/knn-vector-quantization.md
  _search-plugins/knn/nested-search-knn.md
  _search-plugins/knn/performance-tuning.md
  _search-plugins/knn/radial-search-knn.md
  _search-plugins/vector-search.md
Labels: 5 - Editorial review, release-notes, v2.17.0

#8209 Add new filters for events and blogs
  _layouts/search_layout.html
  assets/js/search.js
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16

#8234 Add Sycamore page
  _tools/index.md
  _tools/sycamore.md
Labels: backport 2.16

#8301 Update headings and punctuation in sycamore page
  _tools/sycamore.md
Labels: backport 2.16

#8197 Add documentation for context and ABC templates
  _api-reference/index-apis/create-index-template.md
  _api-reference/index-apis/create-index.md
  _im-plugin/index-context.md
Labels: 5 - Editorial review, release-notes, v2.17.0

#8235 Add documentation changes for Snapshot Status API
  _api-reference/snapshots/get-snapshot-status.md
Labels: 5 - Editorial review, release-notes, v2.17.0

#8281 Documentation for Binary Quantization Support with KNN Vector Search
  _search-plugins/knn/knn-vector-quantization.md
Labels: 5 - Editorial review, release-notes, v2.17.0

#8305 Get offline batch inference details using task API in m
  _ml-commons-plugin/api/model-apis/batch-predict.md
Labels: release-notes, v2.17.0

#8309 Add 2.17 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16

#8334 Update text about default role.yml file in default distribution
  _security/configuration/yaml.md
Labels: backport 2.17

#8268 Improved shard allocation awareness attributes documentation
  _tuning-your-cluster/index.md
Labels: 6 - Done but waiting to merge, backport 2.17

#8340 Editorial comments on #8339
  _tuning-your-cluster/index.md
Labels: backport 2.17

#8058 Enhancing Security configuration steps
  _security/configuration/index.md
Labels: 5 - Editorial review, backport 2.17

#8352 Fix broken links
  _clients/index.md
  _field-types/supported-field-types/knn-vector.md
  _install-and-configure/plugins.md
  _monitoring-your-cluster/pa/index.md
Labels: backport 2.17

#8358 Fix k-NN search json to have correct query
  _search-plugins/knn/disk-based-vector-search.md
  _search-plugins/knn/knn-vector-quantization.md
Labels: backport 2.17

#8354 Add has_child query
  _field-types/supported-field-types/join.md
  _query-dsl/geo-and-xy/geo-bounding-box.md
  _query-dsl/geo-and-xy/geodistance.md
  _query-dsl/geo-and-xy/geopolygon.md
  _query-dsl/geo-and-xy/geoshape.md
  _query-dsl/joining/has-child.md
  _query-dsl/joining/index.md
Labels: backport 2.17

#7919 Collapsing search results new page added to documentation
  _search-plugins/collapse-search.md
Labels: search-and-query, backport 2.17

#8192 [DOC] Normalizers
  _analyzers/index.md
Labels: Content gap, backport 2.17

#8363 Disambiguate statement "value defaults to a fixed percentage"
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
Labels: 4 - Doc review, backport 2.17

#8366 opensearch-benchmark execute_test -> execute-test
  _benchmark/quickstart.md
  _benchmark/user-guide/creating-custom-workloads.md
  _benchmark/user-guide/distributed-load.md
Labels: backport 2.17

#8369 Fix the k-NN train API command for disk based vector search
  _search-plugins/knn/disk-based-vector-search.md
Labels: backport 2.17

#8248 Update target-throughput.md
  _benchmark/user-guide/target-throughput.md
Labels: 4 - Doc review, benchmark, backport 2.17

#8365 Add has parent query
  _field-types/supported-field-types/join.md
  _field-types/supported-field-types/nested.md
  _query-dsl/joining/has-child.md
  _query-dsl/joining/has-parent.md
  _query-dsl/joining/index.md
  _search-plugins/searching-data/inner-hits.md
Labels: backport 2.17

#8372 Adds documentation for providing search pipeline id in the search/msearch request
  _search-plugins/search-pipelines/using-search-pipeline.md
Labels: release-notes, v2.18.0

#8374 Security analytics plugin - added more details for S3 connection setup
  _security-analytics/threat-intelligence/getting-started.md
Labels: 5 - Editorial review, backport 2.17

#8390 docs: fix typo in CCR Plugin Auto Follow documentation
  _tuning-your-cluster/replication-plugin/auto-follow.md
Labels: backport 2.17

#8307 Update documentation to reflect k-NN FAISS AVX512 support
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/settings.md
Labels: 5 - Editorial review, release-notes, v2.18.0
