Repository opensearch-project/documentation-website, pull requests merged in 2024-06, with the labels that each got.

#7254 adding details to rest API calls for role updates #7234
  _security/access-control/api.md
Labels: security, 4 - Doc Review, backport 2.14

#7180 Add ML tutorials
  .github/vale/styles/Vocab/OpenSearch/Products/accept.txt
  _dashboards/dashboards-assistant/index.md
  _ml-commons-plugin/agents-tools/index.md
  _ml-commons-plugin/index.md
  _ml-commons-plugin/tutorials/build-chatbot.md
  _ml-commons-plugin/tutorials/conversational-search-cohere.md
  _ml-commons-plugin/tutorials/generate-embeddings.md
  _ml-commons-plugin/tutorials/index.md
  _ml-commons-plugin/tutorials/rag-chatbot.md
  _ml-commons-plugin/tutorials/rag-conversational-agent.md
  _ml-commons-plugin/tutorials/reranking-cohere.md
  _ml-commons-plugin/tutorials/semantic-search-byte-vectors.md
  images/dashboards/os-assistant-chat.png
  images/dashboards/os-assistant-icon.png
Labels: backport 2.14

#7245 Add missing `weighted_routing` nodes stats
  _api-reference/nodes-apis/nodes-stats.md
Labels: 4 - Doc Review, backport 2.14

#5986 [DOC] Add pipeline processor documentation
  _ingest-pipelines/processors/pipeline.md
Labels: Content gap, backport 2.14

#7292 Fix stray `$` characters; fix some incorrect syntax rendering
  _install-and-configure/plugins.md
Labels: backport 2.14

#5982 Add JSON processor documentation
  _ingest-pipelines/processors/json.md
Labels: Content gap, backport 2.14

#7092 add documentation for use compound file setting
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: release-notes, 3 - Done, v2.15.0

#7069 Admin and Super Admin (security admin) Documentation Update
  _security/access-control/users-roles.md
  _security/configuration/tls.md
  _troubleshoot/security-admin.md
Labels: 5 - Final Editorial Review, security, backport 2.14

#5983 [DOC] Add gsub processor documentation
  _ingest-pipelines/processors/gsub.md
Labels: 5 - Final Editorial Review, Content gap, backport 2.14

#5988 [DOC] Add script processor documentation
  _ingest-pipelines/processors/script.md
Labels: 3 - Tech Review, Content gap, backport 2.14

#7304 Fix two typos
  _benchmark/quickstart.md
  _ingest-pipelines/processors/index-processors.md
Labels: backport 2.14

#5984 [DOC] Add html strip processor documentation
  _ingest-pipelines/processors/html-strip.md
Labels: Content gap, backport 2.14

#7312 Add 1.3.17 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14

#7336 Fixed broken links
  404.md
  _about/intro.md
  _about/quickstart.md
  _api-reference/snapshots/create-repository.md
  _clients/index.md
  _dashboards/discover/index-discover.md
  _dashboards/get-started/quickstart-dashboards.md
  _dashboards/reporting.md
  _dashboards/run-queries.md
  _dashboards/visualize/area.md
  _dashboards/visualize/geojson-regionmaps.md
  _dashboards/visualize/viz-index.md
  _data-prepper/common-use-cases/trace-analytics.md
  _data-prepper/pipelines/configuration/processors/otel-trace-group.md
  _install-and-configure/install-dashboards/docker.md
  _install-and-configure/install-dashboards/index.md
  _install-and-configure/plugins.md
  _install-and-configure/upgrade-opensearch/appendix/rolling-upgrade-lab.md
  _install-and-configure/upgrade-opensearch/index.md
  _observing-your-data/alerting/monitors.md
  _observing-your-data/log-ingestion.md
  _observing-your-data/notebooks.md
  _observing-your-data/trace/ta-dashboards.md
  _opensearch/configuration.md
  _opensearch/query-dsl/full-text/index.md
  _opensearch/query-dsl/geo-and-xy/index.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/term.md
  _opensearch/supported-field-types/range.md
  _search-plugins/sql/full-text.md
  _search-plugins/sql/index.md
  _security/authentication-backends/openid-connect.md
  _security/authentication-backends/saml.md
  _security/configuration/security-admin.md
  _security/configuration/yaml.md
  _security/index.md
  _tools/k8s-operator.md
  _tools/logstash/ship-to-opensearch.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-management.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 2.0, backport 2.1, backport 2.2

#7217 Add _flush API
  _api-reference/index-apis/flush.md
Labels: API, 5 - Final Editorial Review, backport 1.3, backport 2.14

#5989 [DOC] Add set processor documentation
  _ingest-pipelines/processors/set.md
Labels: Content gap, backport 2.14

#7330 Add documentation related to new settings for segment upload timeout
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7172 Add Multi-Search template API
  _api-reference/msearch-template.md
  _api-reference/multi-search.md
Labels: API, 5 - Final Editorial Review, backport 1.3, backport 2.14

#5990 [DOC] Add sort processor documentation
  _ingest-pipelines/processors/sort.md
Labels: 5 - Final Editorial Review, Content gap, backport 2.14

#7331 Update document for handle SageMaker throttling
  _ml-commons-plugin/remote-models/blueprints.md
  _search-plugins/neural-sparse-search.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7333 adding-allowlist-api-reference #571
  _security/access-control/api.md
Labels: security, 4 - Doc Review, backport 2.14

#7268 Document optional clear_status query parameter for Delete Workflow API
  _automating-configurations/api/delete-workflow.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7371 Update typo on conflicts field description of reindex.md
  _api-reference/document-apis/reindex.md
Labels: 4 - Doc Review, backport 2.14

#7271 Added documentation for Reindex workflow step
  _automating-configurations/workflow-steps.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7275 Older-version snapshots and repositories are guaranteed to work with …
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: 5 - Final Editorial Review, backport 2.14

#7296 adding security api reference #887
  _api-reference/security-apis.md
Labels: security, 4 - Doc Review, backport 2.14

#7328 [MDS] Add security analytics, alerting, feature anaywhere in the multiple data source document
  _dashboards/management/multi-data-sources.md
  images/dashboards/mds_feature_anywhere_create_alerting.gif
  images/dashboards/mds_feature_anywhere_view_alerting.gif
  images/dashboards/mds_monitor_view.gif
  images/dashboards/mds_sa_detection_rules_create.gif
  images/dashboards/mds_sa_detection_rules_view.gif
Labels: release-notes, v2.15.0

#7068 Added documentation for managed identity support in repository-azure plugin
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: 6 - Done but waiting to merge, release-notes, v2.15.0

#7251 Updating the documentation for `obfuscate` processor and fixing a issue in `opensearch` sink documentation.
  _data-prepper/pipelines/configuration/processors/obfuscate.md
  _data-prepper/pipelines/configuration/sinks/opensearch.md
Labels: 4 - Doc Review, data-prepper 2.8, backport 2.14

#7346 Added documentation for new default workflow templates
  _automating-configurations/workflow-templates.md
Labels: 4 - Doc Review, release-notes, v2.15.0

#7329 Add documentation of derived fields
  _field-types/supported-field-types/derived.md
  _field-types/supported-field-types/index.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7306 Add doc for neural-sparse-query-two-phase-processor.
  _search-plugins/neural-sparse-search.md
  _search-plugins/search-pipelines/neural-sparse-query-two-phase-processor.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7359 Add documentation related to removal of source and recovery source in k-NN performance tuning section
  _search-plugins/knn/performance-tuning.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7386 Update common-filters.md
  _tools/logstash/common-filters.md
Labels: backport 2.14

#7288 Documentation for Indices Request Cache Overview and its settings
  _install-and-configure/configuring-opensearch/index-settings.md
  _search-plugins/caching/index.md
  _search-plugins/caching/request-cache.md
Labels: 4 - Doc Review, release-notes, v2.15.0

#7378 20240131 Clarification on backend role concept in access control
  _security/access-control/index.md
Labels: security, 4 - Doc Review, backport 2.14

#7389 Changed order of Best Practices page and linked it from other relevant pages
  _getting-started/security.md
  _security/configuration/best-practices.md
  _security/index.md
Labels: security, 4 - Doc Review, backport 2.14

#7339 Add documentation for wildcard field type
  _field-types/supported-field-types/index.md
  _field-types/supported-field-types/string.md
  _field-types/supported-field-types/wildcard.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7326 Add document for top n queries improvements in 2.15
  _observing-your-data/query-insights/top-n-queries.md
Labels: 4 - Doc Review, release-notes, v2.15.0

#7404 Add documentation for innerHit on knn nested field
  _search-plugins/knn/nested-search-knn.md
Labels: release-notes, v2.15.0

#7342 Mark docrep to remote migration as GA and modify settings names
  _tuning-your-cluster/availability-and-recovery/remote-store/migrating-to-remote.md
Labels: 3 - Tech Review, 4 - Doc Review, release-notes, v2.15.0

#7405 Changed VisBuilder status from experimental to GA
  _dashboards/visualize/visbuilder.md
  images/dashboards/drag-drop-generated-viz.png
  images/dashboards/vis-builder-1.png
  images/dashboards/vis-builder-2.png
  images/drag-drop-generated-viz.png
Labels: release-notes, v2.15.0

#7360 Add doc for alerting comments
  _observing-your-data/alerting/api.md
  _observing-your-data/alerting/comments.md
  _observing-your-data/alerting/cron.md
  _observing-your-data/alerting/settings.md
Labels: release-notes, v2.15.0

#7324 Update the integration page to reflect new integration catalog features
  _integrations/index.md
  images/dashboards/integrations-assets.png
  images/integrations/cloud-integrations-filter.png
  images/integrations/empty-installed-integrations.png
  images/integrations/import-saved-objects.png
  images/integrations/integration-catalog-release-page.png
  images/integrations/integration-import-file.png
  images/integrations/integrations-observability-catalog.png
  images/integrations/nginx-installed-integration-assets.png
  images/integrations/nginx-integration-dashboard.png
  images/integrations/nginx-integration.gif
  images/integrations/nginx-integration.png
  images/integrations/select-uploaded-integration.png
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7384 Add connector tool
  _ml-commons-plugin/agents-tools/tools/connector-tool.md
  _ml-commons-plugin/agents-tools/tools/index.md
Labels: 4 - Doc Review, release-notes, v2.15.0

#7410 Alerts in correlations feature documentation
  _security-analytics/api-tools/correlation-eng.md
  _security-analytics/usage/alerts.md
Labels: release-notes, v2.15.0

#7362 Trace analytics update
  _observing-your-data/trace/ta-dashboards.md
  images/trace-analytics/service-details-tooltip.png
  images/trace-analytics/service-throughput-tooltip.png
  images/trace-analytics/services-filter-selection.png
  images/trace-analytics/services-table.png
  images/trace-analytics/single-service-RED-metrics.png
  images/trace-analytics/single-service-correlation-dialog.png
  images/trace-analytics/single-service-fly-out.png
  images/trace-analytics/span-details-fly-out.png
  images/trace-analytics/trace-group-RED-metrics.png
Labels: 6 - Done but waiting to merge, release-notes, v2.15.0

#7408 Add documentations for batch ingestion feature
  _api-reference/document-apis/bulk.md
  _ingest-pipelines/processors/index-processors.md
  _ml-commons-plugin/remote-models/batch-ingestion.md
  _ml-commons-plugin/remote-models/index.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7368 Update documentation of ml inference processors to support for local models
  _ingest-pipelines/processors/ml-inference.md
  _ingest-pipelines/processors/pipeline.md
  _ingest-pipelines/processors/script.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7377 Add remote guardrails model support
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/api/model-apis/update-model.md
  _ml-commons-plugin/remote-models/guardrails.md
Labels: 5 - Final Editorial Review, release-notes, v2.15.0

#7434 Backport/backport 7337 to 2.1
  404.md
  _about/breaking-changes.md
  _about/intro.md
  _about/quickstart.md
  _api-reference/script-apis/create-stored-script.md
  _api-reference/snapshots/create-repository.md
  _api-reference/snapshots/create-snapshot.md
  _api-reference/snapshots/delete-snapshot.md
  _clients/data-prepper/configure-logstash-data-prepper.md
  _clients/index.md
  _clients/k8s-operator.md
  _clients/logstash/index.md
  _clients/logstash/read-from-opensearch.md
  _clients/logstash/ship-to-opensearch.md
  _dashboards/discover/index-discover.md
  _dashboards/install/docker.md
  _dashboards/install/tls.md
  _dashboards/run-queries.md
  _dashboards/visualize/area.md
  _dashboards/visualize/viz-index.md
  _data-prepper/common-use-cases/trace-analytics.md
  _data-prepper/pipelines/configuration/processors/otel-trace-group.md
  _im-plugin/ism/policies.md
  _install-and-configure/configuration.md
  _install-and-configure/install-dashboards/docker.md
  _install-and-configure/install-dashboards/index.md
  _install-and-configure/install-opensearch/docker.md
  _install-and-configure/install-opensearch/tar.md
  _install-and-configure/plugins.md
  _install-and-configure/upgrade-opensearch/appendix/rolling-upgrade-lab.md
  _install-and-configure/upgrade-opensearch/index.md
  _monitoring-your-cluster/pa/index.md
  _observing-your-data/ad/security.md
  _observing-your-data/alerting/monitors.md
  _observing-your-data/alerting/security.md
  _observing-your-data/alerting/settings.md
  _observing-your-data/log-ingestion.md
  _observing-your-data/notebooks.md
  _observing-your-data/trace/ta-dashboards.md
  _opensearch/configuration.md
  _opensearch/query-dsl/full-text/index.md
  _opensearch/query-dsl/geo-and-xy/index.md
  _opensearch/query-dsl/index.md
  _opensearch/query-dsl/term.md
  _opensearch/supported-field-types/range.md
  _opensearch/ux.md
  _plugins/link-checker.rb
  _search-plugins/sql/full-text.md
  _search-plugins/sql/index.md
  _security/authentication-backends/openid-connect.md
  _security/configuration/security-admin.md
  _tuning-your-cluster/availability-and-recovery/snapshots/sm-api.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-management.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
  _tuning-your-cluster/replication-plugin/auto-follow.md
  _tuning-your-cluster/replication-plugin/getting-started.md
  _tuning-your-cluster/replication-plugin/permissions.md
Labels: backport 2.0

#7352 Update the metrics analytics documentation
  _observing-your-data/metricsanalytics.md
  _observing-your-data/prometheusmetrics.md
  images/metrics/otel-metrics-remote-cluster-selection.png
  images/metrics/otel-metrics.png
  images/metrics/prom-metrics.png
  images/metrics/remote-cluster-selection.png
Labels: v2.15.0

#7413 Update key value processor documentation with new config options
  _data-prepper/pipelines/configuration/processors/key-value.md
Labels: data-prepper

#7398 adding explanation to jwks validation #7367 #20240522
  _security/authentication-backends/jwt.md
Labels: security, 4 - Doc Review, backport 2.14

#7380 20240322 Adding absolute path for config.yml
  _security/configuration/configuration.md
Labels: security, 4 - Doc Review, backport 2.14

#7484 Add 2.15 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14

#7163 Add new s3 sink documentation for Data Prepper 2.8
  _data-prepper/pipelines/configuration/sinks/s3.md
Labels: data-prepper 2.8, backport 2.14

#7397 Adding information running script in OpenSearch
  _api-reference/document-apis/bulk.md
Labels: security, 4 - Doc Review, backport 2.14

#7372 Add oidc docker example with keycloak #1566
  _security/authentication-backends/openid-connect.md
  assets/examples/oidc_example.zip
Labels: 5 - Final Editorial Review, security, backport 2.15

#7402 Add General Guidelines for concurrent segment search
  _search-plugins/concurrent-segment-search.md
Labels: 4 - Doc Review, backport 2.15

#7534 Fixes Update compare-search-results.md
  _search-plugins/search-relevance/compare-search-results.md
Labels: 4 - Doc Review, backport 2.15

#7538 Drop repeated key/word in inverted index
  _getting-started/intro.md
Labels: backport 2.15

#7556 Remove Vale from date processor
  _data-prepper/pipelines/configuration/processors/date.md
Labels: backport 2.15

#6247 Add selective download feature to Data Prepper sources section
  _data-prepper/common-use-cases/s3-logs.md
Labels: 5 - Final Editorial Review, data-prepper, Content gap, backport 2.15

#7561 Update prometheusmetrics.md
  _observing-your-data/prometheusmetrics.md
Labels: 4 - Doc Review, backport 2.15

#7560 Update Benchmark index to reflect TOC
  _benchmark/index.md
Labels: backport 2.15

#7565 Fix broken link to wildcard field type in index.md
  _field-types/supported-field-types/index.md
Labels: backport 2.15
