Repository opensearch-project/documentation-website, pull requests merged in 2024-11, with the labels that each got.

#8634 Document setting allowing size > 0 queries into request cache
  _search-plugins/caching/request-cache.md
Labels: 6 - Done but waiting to merge, backport 2.17

#8598 Add documentation for star tree index feature
  _field-types/supported-field-types/index.md
  _field-types/supported-field-types/star-tree.md
  _search-plugins/improving-search-performance.md
  _search-plugins/star-tree-index.md
  images/star-tree-index.png
Labels: 5 - Editorial review, release-notes, v2.18.0

#8646 Update SQL/PPL multiple value field limitation
  _search-plugins/sql/limitation.md
  _search-plugins/sql/settings.md
Labels: release-notes, v2.18.0

#8652 Update reporting record limit tip
  _reporting/report-dashboard-index.md
Labels: backport 2.17

#8639 Add new use cases to ML Inference Search Response Processor
  _search-plugins/search-pipelines/ml-inference-search-response.md
Labels: 3 - Tech review, release-notes, v2.18.0

#7977 Add decimal digit token filter docs #7923
  _analyzers/token-filters/decimal-digit.md
  _analyzers/token-filters/index.md
Labels: 3 - Tech review, Needs SME, analyzers

#7988 Add delimited payload token filter #7978
  _analyzers/token-filters/delimited-payload.md
  _analyzers/token-filters/index.md
Labels: 3 - Tech review, Needs SME, analyzers

#8622 doc: add document for dashboards assistant
  _dashboards/dashboards-assistant/alert-insight.md
  _dashboards/dashboards-assistant/data-summary.md
  _dashboards/dashboards-assistant/index.md
  _dashboards/dashboards-assistant/suggest-anomaly-detector.md
  _dashboards/dashboards-assistant/text-to-visualization.md
  images/dashboards-assistant/alert-insight-insight.png
  images/dashboards-assistant/alert-insight-start.png
  images/dashboards-assistant/alert-insight-summary.png
  images/dashboards-assistant/data-summary.png
  images/dashboards-assistant/info-icon.png
  images/dashboards-assistant/sparkle-icon.png
  images/dashboards-assistant/suggestAD-UI.png
  images/dashboards-assistant/suggestAD-button.png
  images/dashboards-assistant/t2viz-ask-question.png
  images/dashboards-assistant/t2viz-edit-visual-response.png
  images/dashboards-assistant/t2viz-edit-visual.png
  images/dashboards-assistant/t2viz-select-data-source.png
  images/dashboards-assistant/t2viz-start.png
Labels: v2.18.0

#8661 Add 2.18 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17

#8643 [Workspace] Add documentation for workspace and ACL
  _config.yml
  _dashboards/management/acl.md
  _dashboards/management/management-index.md
  _dashboards/workspace/apis.md
  _dashboards/workspace/create-workspace.md
  _dashboards/workspace/index.md
  _dashboards/workspace/manage-workspace.md
  _dashboards/workspace/workspace-acl.md
  _dashboards/workspace/workspace.md
Labels: release-notes, v2.18.0, backport 2.18

#8655 AWS Lambda plugin documentation
  _data-prepper/pipelines/configuration/processors/aws-lambda.md
Labels: data-prepper, backport 2.18

#8688 Fixing Typo
  _query-dsl/term/terms.md
Labels: backport 2.18

#8618 [DOC] Installing ruby for Apple silicon missing
  CONTRIBUTING.md
Labels: 5 - Editorial review

#8702 Properly render documentation with double curly braces
  _automating-configurations/api/create-workflow.md
  _automating-configurations/api/provision-workflow.md
Labels: 4 - Doc review, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18

#8695 Navbar logo relative url change
  _includes/header.html
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18

#8712 Point top left logo to main site
  _includes/header.html
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17

#8692 [Jekyll] Spec Insert Plugin
  .github/workflows/jekyll-spec-insert.yml
  .github/workflows/update-api-components.yml
  DEVELOPER_GUIDE.md
  Gemfile
  README.md
  _config.yml
  spec-insert/.gitignore
  spec-insert/.rspec
  spec-insert/.rubocop.yml
  spec-insert/jekyll-spec-insert.gemspec
  spec-insert/lib/api/action.rb
  spec-insert/lib/api/operation.rb
  spec-insert/lib/api/parameter.rb
  spec-insert/lib/doc_processor.rb
  spec-insert/lib/insert_arguments.rb
  spec-insert/lib/jekyll-spec-insert.rb
  spec-insert/lib/renderers/base_mustache_renderer.rb
  spec-insert/lib/renderers/parameter_table_renderer.rb
  spec-insert/lib/renderers/path_parameters.rb
  spec-insert/lib/renderers/paths_and_methods.rb
  spec-insert/lib/renderers/query_parameters.rb
  spec-insert/lib/renderers/spec_insert.rb
  spec-insert/lib/renderers/table_renderer.rb
  spec-insert/lib/renderers/templates/path_parameters.mustache
  spec-insert/lib/renderers/templates/paths_and_methods.mustache
  spec-insert/lib/renderers/templates/query_parameters.mustache
  spec-insert/lib/renderers/templates/spec_insert.mustache
  spec-insert/lib/spec_hash.rb
  spec-insert/lib/spec_insert_error.rb
  spec-insert/spec/_fixtures/actual_output/.gitignore
  spec-insert/spec/_fixtures/expected_output/param_tables.md
  spec-insert/spec/_fixtures/expected_output/paths_and_http_methods.md
  spec-insert/spec/_fixtures/input/param_tables.md
  spec-insert/spec/_fixtures/input/paths_and_http_methods.md
  spec-insert/spec/_fixtures/opensearch_spec.yaml
  spec-insert/spec/doc_processor_spec.rb
  spec-insert/spec/spec_helper.rb
Labels: 5 - Editorial review

#8122 Add keep type docs #8063
  _analyzers/token-filters/index.md
  _analyzers/token-filters/keep-types.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers

#8737 Revert "Document setting allowing size > 0 queries into request cache"
  _search-plugins/caching/request-cache.md
Labels: backport 2.18

#8734 Update snapshot-restore.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 2.18

#8632 add wlm feature overview
  _tuning-your-cluster/availability-and-recovery/workload-management/wlm-feature-overview.md
Labels: 5 - Editorial review, release-notes, v2.18.0, backport 2.18

#7994 Add dictionary decompounder docs #7979
  _analyzers/token-filters/dictionary-decompounder.md
  _analyzers/token-filters/index.md
Labels: 3 - Tech review, Needs SME, analyzers

#8025 Add edge n-gram token filter docs #7980
  _analyzers/token-filters/edge-ngram.md
  _analyzers/token-filters/index.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers

#8059 Add fingerprint token filter #7982
  _analyzers/token-filters/fingerprint.md
  _analyzers/token-filters/index.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers, backport 2.18

#8026 Add elision token filter docs #7981
  _analyzers/token-filters/elision.md
  _analyzers/token-filters/index.md
Labels: 5 - Editorial review, Needs SME, Content gap, analyzers

#8070 Add hunspell token filter #8061
  _analyzers/token-filters/hunspell.md
  _analyzers/token-filters/index.md
Labels: 5 - Editorial review, Needs SME, Content gap, analyzers

#8124 Add keep words token filter docs #8064
  _analyzers/token-filters/index.md
  _analyzers/token-filters/keep-words.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers

#8120 Add hyphenation_decompounder token filter docs #8062
  _analyzers/token-filters/hyphenation-decompounder.md
  _analyzers/token-filters/index.md
Labels: 5 - Editorial review, Content gap, analyzers

#8134 Add keyword marker token filter docs #8065
  _analyzers/token-filters/elision.md
  _analyzers/token-filters/index.md
  _analyzers/token-filters/keyword-marker.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers

#8591 adding language analyzers
  _analyzers/language-analyzers.md
  _analyzers/language-analyzers/arabic.md
  _analyzers/language-analyzers/armenian.md
  _analyzers/language-analyzers/basque.md
  _analyzers/language-analyzers/bengali.md
  _analyzers/language-analyzers/brazilian.md
  _analyzers/language-analyzers/bulgarian.md
  _analyzers/language-analyzers/catalan.md
  _analyzers/language-analyzers/cjk.md
  _analyzers/language-analyzers/czech.md
  _analyzers/language-analyzers/danish.md
  _analyzers/language-analyzers/dutch.md
  _analyzers/language-analyzers/english.md
  _analyzers/language-analyzers/estonian.md
  _analyzers/language-analyzers/finnish.md
  _analyzers/language-analyzers/french.md
  _analyzers/language-analyzers/galician.md
  _analyzers/language-analyzers/german.md
  _analyzers/language-analyzers/greek.md
  _analyzers/language-analyzers/hindi.md
  _analyzers/language-analyzers/hungarian.md
  _analyzers/language-analyzers/index.md
  _analyzers/language-analyzers/indonesian.md
  _analyzers/language-analyzers/irish.md
  _analyzers/language-analyzers/italian.md
  _analyzers/language-analyzers/latvian.md
  _analyzers/language-analyzers/lithuanian.md
  _analyzers/language-analyzers/norwegian.md
  _analyzers/language-analyzers/persian.md
  _analyzers/language-analyzers/portuguese.md
  _analyzers/language-analyzers/romanian.md
  _analyzers/language-analyzers/russian.md
  _analyzers/language-analyzers/sorani.md
  _analyzers/language-analyzers/spanish.md
  _analyzers/language-analyzers/swedish.md
  _analyzers/language-analyzers/thai.md
  _analyzers/language-analyzers/turkish.md
  _analyzers/supported-analyzers/index.md
Labels: 3 - Tech review, 4 - Doc review, Content gap, backport 2.18

#8762 Fix: Correct document for dashboards assistant
  _dashboards/dashboards-assistant/alert-insight.md
  _dashboards/dashboards-assistant/data-summary.md
  _dashboards/dashboards-assistant/suggest-anomaly-detector.md
  _dashboards/dashboards-assistant/text-to-visualization.md
Labels: backport 2.18

#8697 Modify lambda processor and sink documentation
  _data-prepper/pipelines/configuration/processors/aws-lambda.md
  _data-prepper/pipelines/configuration/sinks/aws-lambda.md
Labels: data-prepper, backport 2.18

#8759 Additions to data source acceleration
  CONTRIBUTING.md
  _dashboards/management/accelerate-external-data.md
Labels: backport 2.15, backport 2.16, backport 2.17, backport 2.18

#8773 Change link in update settings
  _api-reference/index-apis/update-settings.md
Labels: backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18

#8684 Document change to size > 0 setting for request cache
  _search-plugins/caching/request-cache.md
Labels: 6 - Done but waiting to merge, release-notes, v2.19.0

#8784 Clarify master-to-cluster-manager name change
  _tuning-your-cluster/index.md
Labels: backport 2.15, backport 2.16, backport 2.17, backport 2.18

#8795 Update logging-features.md
  _search-plugins/ltr/logging-features.md
Labels: backport 2.18

#8458 add synonym graph token filter docs #8448
  _analyzers/token-filters/index.md
  _analyzers/token-filters/synonym-graph.md
Labels: analyzers, backport 2.18

#8694 Added tutorial on ML Inference processor with the by-field rerank type
  _search-plugins/search-pipelines/ml-inference-search-response.md
  _search-plugins/search-pipelines/rerank-processor.md
  _search-plugins/search-relevance/rerank-by-field-cross-encoder.md
  _search-plugins/search-relevance/rerank-by-field.md
  _search-plugins/search-relevance/rerank-cross-encoder.md
Labels: backport 2.18

#8260 Add pattern_capture token filter docs #8240
  _analyzers/token-filters/index.md
  _analyzers/token-filters/pattern-capture.md
Labels: 5 - Editorial review, Content gap, analyzers, backport 2.18

#8270 Add phonetic token filter docs #8242
  _analyzers/token-filters/index.md
  _analyzers/token-filters/phonetic.md
Labels: 5 - Editorial review, Content gap, analyzers, backport 2.18

#8279 Add predicate token filter docs #8272
  _analyzers/token-filters/index.md
  _analyzers/token-filters/predicate-token-filter.md
Labels: 5 - Editorial review, Content gap, analyzers, backport 2.18

#8253 Add multiplexer token filter docs #8237
  _analyzers/token-filters/index.md
  _analyzers/token-filters/multiplexer.md
Labels: 5 - Editorial review, Content gap, analyzers, backport 2.18

#8269 add pattern replace token filter docs #8241
  _analyzers/token-filters/index.md
  _analyzers/token-filters/pattern-replace.md
Labels: 5 - Editorial review, analyzers, backport 2.18

#8278 Add porter stem token filter docs #8271
  _analyzers/token-filters/index.md
  _analyzers/token-filters/porter-stem.md
Labels: 5 - Editorial review, Content gap, analyzers, backport 2.18

#8394 Add remove_duplicate token filter docs #8273
  _analyzers/token-filters/index.md
  _analyzers/token-filters/remove-duplicates.md
Labels: 5 - Editorial review, Content gap, analyzers, backport 2.18

#8691 Migration assistant intro
  _migrations/Solution-Overview.md
  _migrations/index.md
  _migrations/is-migration-assistant-right-for-you.md
  _migrations/meta.md
Labels: 5 - Editorial review, backport 2.18

#8797 Update MA getting started
  _migrations/getting-started-data-migration.md
  _migrations/quick-start-data-migration.md
Labels: 5 - Editorial review, migration

#8824 Fix a url
  _search-plugins/searching-data/index.md
Labels: backport 2.18
