Repository opensearch-project/documentation-website, pull requests merged in 2024-02, with the labels that each got.

#6331 Remove depracated PA metrics
  _monitoring-your-cluster/pa/reference.md
Labels: 4 - Doc Review, backport 2.11

#5909 Update exchange_key description to use different HMAC setting
  _security/authentication-backends/saml.md
Labels: 4 - Doc Review, backport 2.11

#6058 Adds documentation for security demo configuration setup
  _install-and-configure/install-dashboards/debian.md
  _install-and-configure/install-dashboards/helm.md
  _install-and-configure/install-opensearch/debian.md
  _install-and-configure/install-opensearch/docker.md
  _install-and-configure/install-opensearch/helm.md
  _install-and-configure/install-opensearch/rpm.md
  _install-and-configure/install-opensearch/tar.md
  _install-and-configure/install-opensearch/windows.md
  _install-and-configure/upgrade-opensearch/appendix/rolling-upgrade-lab.md
  _security/configuration/demo-configuration.md
  assets/examples/docker-compose.yml
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#5123 On-behalf-of token and service account authorization tokens doc
  _security/access-control/authentication-tokens.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6304 Add page on OpenSearch keystore in security configuration
  _security/configuration/opensearch-keystore.md
Labels: 6 - Done but waiting to merge, backport 1.3, backport 2.11

#6279 Update SAML tutorial with new default Admin settings
  _security/authentication-backends/saml.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#5999 Update search profile API documentation with concurrency related changes
  _api-reference/profile.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#5887 Remove admin:admin default and update instructions for demo setup
  _about/quickstart.md
  _api-reference/tasks.md
  _benchmark/quickstart.md
  _clients/javascript/index.md
  _monitoring-your-cluster/pa/index.md
  _observing-your-data/log-ingestion.md
  _observing-your-data/trace/getting-started.md
  _reporting/rep-cli-env-var.md
  _search-plugins/sql/sql/index.md
  _security/access-control/cross-cluster-search.md
  _security/access-control/impersonation.md
  _troubleshoot/index.md
  _tuning-your-cluster/availability-and-recovery/remote-store/index.md
  _tuning-your-cluster/index.md
  _tuning-your-cluster/replication-plugin/auto-follow.md
  _tuning-your-cluster/replication-plugin/getting-started.md
  _upgrade-to/upgrade-to.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#5875 Updated k-NN lucene engine dimension max count to 16k
  _search-plugins/knn/approximate-knn.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#5662 Add cluster state stats documentation
  _api-reference/nodes-apis/nodes-stats.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#5298 [DOC] Search request slow logs
  _install-and-configure/configuring-opensearch/cluster-settings.md
  _install-and-configure/configuring-opensearch/logs.md
  _query-dsl/index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#5837 Document new only expunge deletes behavior for Force Merge API
  _api-reference/index-apis/force-merge.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#5184 Update docs for remote store backpressure stats
  _api-reference/cluster-api/cluster-stats.md
  _api-reference/index-apis/stats.md
  _api-reference/nodes-apis/nodes-stats.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6309 Update remote cluster documentation for global metadata and new dynamic settings
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-cluster-state.md
Labels: 6 - Done but waiting to merge, v2.12.0

#6272 Added documentation for changing the default values of HNSW hyper parameters in k-NN plugin
  _search-plugins/knn/knn-index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6237 Add documentation for nested search in knn
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/nested-search-knn.md
Labels: 6 - Done but waiting to merge, v2.12.0

#6041 Documentation for match_only_text field
  _field-types/supported-field-types/index.md
  _field-types/supported-field-types/match-only-text.md
  _field-types/supported-field-types/string.md
  _field-types/supported-field-types/text.md
  _field-types/supported-field-types/token-count.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6028 Introduce cluster.index.restrict.replication.type setting
  _tuning-your-cluster/availability-and-recovery/segment-replication/index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6336 Add documentation for cluster-level coordination setting changes
  _install-and-configure/configuring-opensearch/cluster-settings.md
Labels: 4 - Doc Review, release-notes, v2.12.0

#6328 Update gantt chart dashboards plugin link to GitHub
  _install-and-configure/install-dashboards/plugins.md
Labels: 3 - Tech Review, 4 - Doc Review, backport 2.11

#6294 Add copy ingest processor
  _ingest-pipelines/processors/copy.md
Labels: release-notes, 3 - Done, v2.12.0

#6350 Alerting plugin - experimental cross cluster monitor support documentation
  _observing-your-data/alerting/per-cluster-metrics-monitors.md
  _observing-your-data/alerting/per-query-bucket-monitors.md
  _observing-your-data/alerting/settings.md
  images/alerting/cross-cluster-cluster-metrics-monitors.png
  images/alerting/cross-cluster-per-query-per-bucket-monitors.png
Labels: 5 - Final Editorial Review, release-notes, experimental, v2.12.0

#6366 Update availability-recovery.md
  _install-and-configure/configuring-opensearch/availability-recovery.md
Labels: backport 2.11

#6257 Add flow framework documentation
  .github/vale/styles/Vocab/OpenSearch/Plugins/accept.txt
  .github/vale/styles/Vocab/OpenSearch/Words/accept.txt
  _automating-workflows/api/create-workflow.md
  _automating-workflows/api/delete-workflow.md
  _automating-workflows/api/deprovision-workflow.md
  _automating-workflows/api/get-workflow-status.md
  _automating-workflows/api/get-workflow-steps.md
  _automating-workflows/api/get-workflow.md
  _automating-workflows/api/index.md
  _automating-workflows/api/provision-workflow.md
  _automating-workflows/api/search-workflow.md
  _automating-workflows/index.md
  _automating-workflows/workflow-settings.md
  _automating-workflows/workflow-steps.md
  _automating-workflows/workflow-tutorial.md
  _config.yml
  _install-and-configure/configuring-opensearch/plugin-settings.md
  _install-and-configure/plugins.md
  _sass/custom/custom.scss
  images/automatic-workflow-dag.png
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6355 Improve terms aggregation documentation and add concurrent segment search caveats
  _aggregations/bucket/terms.md
Labels: 3 - Tech Review, release-notes, v2.12.0

#6364 Add documentation for saved object management to support multiple datasource
  _dashboards/management/multi-data-sources.md
  images/dashboards/import_saved_objects_with_file_upload.gif
Labels: release-notes, 3 - Done, v2.12.0

#6362 Add things to know for concurrent segment search
  _search-plugins/concurrent-segment-search.md
Labels: 3 - Tech Review, release-notes, v2.12.0

#6284 Add alias support to Security Analytics
  _security-analytics/sec-analytics-config/detectors-config.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6273 Add threat intelligence for 2.12
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/usage/detectors.md
Labels: 6 - Done but waiting to merge, release-notes, security-analytics, v2.12.0

#6337 Updating documentation for new datetime format
  _field-types/supported-field-types/date.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6358 Add installing multiple plugins example
  _install-and-configure/plugins.md
Labels: 4 - Doc Review, backport 2.11

#6306 Add include_named_queries_score to docs
  _api-reference/search.md
Labels: release-notes, v2.12.0

#6356 Concurrent segment search GA and API changes
  _api-reference/index-apis/stats.md
  _api-reference/nodes-apis/nodes-stats.md
  _api-reference/profile.md
  _search-plugins/concurrent-segment-search.md
Labels: 3 - Tech Review, release-notes, v2.12.0

#6374 Clarification of Customer Comment # 20230525
  _security/multi-tenancy/multi-tenancy-config.md
Labels: extensions, backport 2.11

#5390 Add searchbp metrics to Performance Analyzer
  _monitoring-your-cluster/pa/reference.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6368 Add documentation for new reranking feature in 2.12
  _search-plugins/search-pipelines/rerank-processor.md
  _search-plugins/search-pipelines/search-processors.md
  _search-plugins/search-relevance/compare-search-results.md
  _search-plugins/search-relevance/index.md
  _search-plugins/search-relevance/reranking-search-results.md
Labels: 3 - Tech Review, release-notes, v2.12.0

#6261 Add Query Insights documentation
  .github/vale/styles/Vocab/OpenSearch/Plugins/accept.txt
  _install-and-configure/configuring-opensearch/plugin-settings.md
  _install-and-configure/plugins.md
  _observing-your-data/query-insights/index.md
  _observing-your-data/query-insights/top-n-queries.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6287 Add Running a Workload
  _benchmark/user-guide/concepts.md
  _benchmark/user-guide/running-workloads.md
Labels: 5 - Final Editorial Review, benchmark, backport 2.11

#6349 Added 1x sentence to clarify use/support for IAM Instance Profiles.
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: 3 - Tech Review, backport 2.11

#6373 Clarification of Customer Comment # 20231012
  _security/multi-tenancy/tenant-index.md
Labels: 4 - Doc Review, backport 2.11

#6140 Add use case for anomaly detection with Data Prepper
  _data-prepper/common-use-cases/anomaly-detection.md
Labels: data-prepper, 3 - Done

#6412 Add link to OpenSearch FAQ
  _tools/index.md
Labels: backport 2.11

#6415 Add documentation for Normalizers
  _analyzers/index.md
  _analyzers/normalizers.md
  _field-types/supported-field-types/keyword.md
  _install-and-configure/plugins.md
  _query-dsl/term-vs-full-text.md
Labels: backport 2.11

#6393 Adds metrics framework documentation
  _monitoring-your-cluster/index.md
  _monitoring-your-cluster/metrics/getting-started.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6406 Update index.md
  _observing-your-data/notifications/index.md
Labels: 3 - Tech Review

#6399 Add documentation for exclude_roles settings for LDAP security config
  _security/authentication-backends/ldap.md
Labels: 4 - Doc Review, backport 2.11

#6411 Add warning related to ad and concurrent segment search
  _search-plugins/concurrent-segment-search.md
Labels: 5 - Final Editorial Review, v2.12.0

#6357 Add cross-encoder model documentation
  _ml-commons-plugin/custom-local-models.md
  _ml-commons-plugin/pretrained-models.md
  _search-plugins/search-relevance/reranking-search-results.md
Labels: 3 - Tech Review, release-notes, v2.12.0

#6392 MAINT: Data Prepper opensearch source metrics
  _data-prepper/pipelines/configuration/sources/opensearch.md
Labels: 5 - Final Editorial Review, data-prepper, backport 2.11

#6387 Obfuscate processor doc
  _data-prepper/pipelines/configuration/processors/obfuscate.md
Labels: data-prepper, backport 2.11

#6243 Add update example for javascript client
  _clients/javascript/index.md
Labels: 3 - Tech Review

#6438 Fix Java client example
  _clients/java.md
Labels: backport 2.11

#6405 Updated action groups tables as per customer request #20231026
  _security/access-control/default-action-groups.md
Labels: backport 1.3, security, 4 - Doc Review, backport 2.11

#6425 Fix header in Demo configuration page
  _security/configuration/demo-configuration.md
Labels: v2.12.0

#6419 Add query assist documentation to Observability
  _observing-your-data/event-analytics.md
  images/log-explorer-query-assist.png
Labels: 5 - Final Editorial Review, release-notes, experimental, v2.12.0

#6370 Add documentation for dashboards assistant plugin
  _config.yml
  _dashboards/dashboards-assistant/index.md
  images/dashboards-assistant/conversation-history-entry.png
  images/dashboards-assistant/conversation-history-list.png
  images/dashboards-assistant/conversation-in-notebook.png
  images/dashboards-assistant/delete-conversation.png
  images/dashboards-assistant/edit-conversation-title.png
  images/dashboards-assistant/entry.png
  images/dashboards-assistant/rate.png
  images/dashboards-assistant/response.png
  images/dashboards-assistant/save-conversation-to-notebook.png
  images/dashboards-assistant/start-conversation.png
  images/dashboards-assistant/suggestions.png
  images/dashboards-assistant/traces.png
  images/dashboards/opensearch-assistant-QandA.png
  images/dashboards/opensearch-assistant-conversation-history.png
  images/dashboards/opensearch-assistant-delete-convo.png
  images/dashboards/opensearch-assistant-edit-convo.png
  images/dashboards/opensearch-assistant-full-frame.png
  images/dashboards/opensearch-assistant-how-generated.png
  images/dashboards/opensearch-assistant-notebooks.png
  images/dashboards/opensearch-assistant-regenerate.png
  images/dashboards/opensearch-assistant-save-notebook.png
  images/dashboards/opensearch-assistant-suggestions.png
  images/icons/frame-icon.png
Labels: release-notes, 3 - Done, v2.12.0

#6444 Disable concurrent search for composite agg
  _search-plugins/concurrent-segment-search.md
Labels: v2.12.0

#6445 improve wording
  _field-types/index.md
Labels: backport 2.11

#6449 Add documentation for new bloom filter settings
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 4 - Doc Review, release-notes, v2.12.0

#6452 Adds 2.12 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11

#6186 Add sampling with Data Prepper use case
  _data-prepper/common-use-cases/sampling.md
Labels: data-prepper, Content gap

#6206 Add event aggregation use case to Data Prepper documentation
  _data-prepper/common-use-cases/event-aggregation.md
Labels: 3 - Tech Review, data-prepper, Content gap

#6378 Update CSV Data Prepper processor
  _data-prepper/pipelines/configuration/processors/csv.md
Labels: 5 - Final Editorial Review, data-prepper, backport 2.11

#6403 Adds documentation for new OSB flags
  _benchmark/reference/commands/command-flags.md
Labels: 4 - Doc Review, backport 2.12

#6497 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: 4 - Doc Review

#6498 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 4 - Doc Review

#6251 Add metrics traces use case to Data Prepper
  _data-prepper/common-use-cases/metrics-traces.md
Labels: data-prepper, Content gap, 3 - Done

#6501 Update average.md to reflect aggregate name specified
  _aggregations/metric/average.md
Labels: backport 2.12

#6489 Add unsupported warning for local models
  _ml-commons-plugin/custom-local-models.md
  _ml-commons-plugin/opensearch-assistant.md
  _ml-commons-plugin/pretrained-models.md
  _ml-commons-plugin/using-ml-models.md
Labels: backport 2.12

#6490 Update Notifications doc with description of host deny list
  _observing-your-data/notifications/index.md
Labels: backport 2.12

#6492 Delete snippets from 2.11 documentation
  _ingest-pipelines/processors/kv.md
Labels: backport 2.11

#6384 [Data Prepper] MAINT: document on disable_refresh secret extension setting
  _data-prepper/managing-data-prepper/configuring-data-prepper.md
Labels: 4 - Doc Review, data-prepper 2.7

#6379 Updates to the S3 source documentation
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6385 Add-Entries Processor
  _data-prepper/pipelines/configuration/processors/add-entries.md
Labels: 5 - Final Editorial Review, data-prepper, backport 2.12

#6521 (Backport) Updates the text for all tiles on the landing page (#6427)
  _includes/cards.html
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.10, backport 2.11

#6486 Update of Configure user section in Debian installation procedure
  _install-and-configure/install-opensearch/debian.md
Labels: 3 - Tech Review, backport 2.12

#6487 Update rpm.md
  _install-and-configure/install-opensearch/rpm.md
Labels: 4 - Doc Review, backport 2.12

#6382 Update list_to_map processor in Data Prepper
  _data-prepper/pipelines/configuration/processors/list-to-map.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6527 Update windows instructions for security demo setup
  _install-and-configure/install-opensearch/windows.md
Labels: backport 2.12

#6535 Adds info about client.bulk
  _clients/javascript/helpers.md
Labels: 4 - Doc Review, backport 2.12

#6004 Update quickstart to include dashboards
  _dashboards/discover/index-discover.md
  _dashboards/discover/time-filter.md
  _dashboards/quickstart.md
  images/dashboards/add-panel2.png
  images/dashboards/add-sample-data-2.png
  images/dashboards/dark-mode.png
  images/dashboards/dashboards-home.png
  images/dashboards/dashboards-overview-page.png
  images/dashboards/discover-basics.png
  images/dashboards/discover-filter.png
  images/dashboards/discover-view.png
  images/dashboards/discover.png
  images/dashboards/opensearch-dashboards-discover.png
  images/dashboards/opensearch-dashboards-home.png
  images/icons/menu-icon.png
Labels: 3 - Done, backport 2.12

#6430 Add Contributing workloads page
  _benchmark/user-guide/contributing-workloads.md
  _benchmark/user-guide/distributed-load.md
  _benchmark/user-guide/telemetry.md
Labels: 5 - Final Editorial Review, benchmark, backport 2.11
