Repository opensearch-project/documentation-website, pull requests merged in 2024-01, with the labels that each got.

#6009 Update Replication leader permissions
  _tuning-your-cluster/replication-plugin/permissions.md
Labels: 4 - Doc Review, backport 2.10, backport 2.11

#6011 Update approximate-knn.md
  _search-plugins/knn/approximate-knn.md
Labels: 4 - Doc Review, backport 2.11

#6030 Typo fix
  _search-plugins/knn/approximate-knn.md
Labels: backport 2.11

#5998 Edit ism example policy
  _im-plugin/ism/policies.md
Labels: 6 - Done but waiting to merge

#6032 Heading capitalization fix
  .github/vale/styles/Vocab/OpenSearch/Products/accept.txt
  _benchmark/reference/commands/command-flags.md
  _benchmark/reference/commands/compare.md
  _benchmark/reference/commands/download.md
  _benchmark/reference/commands/execute-test.md
  _benchmark/reference/commands/info.md
  _benchmark/reference/commands/list.md
  _benchmark/reference/metrics/metric-records.md
  _benchmark/reference/telemetry.md
  _benchmark/reference/workloads/corpora.md
  _benchmark/reference/workloads/indices.md
  _benchmark/reference/workloads/operations.md
  _benchmark/reference/workloads/test-procedures.md
  _benchmark/user-guide/configuring-benchmark.md
  _benchmark/user-guide/installing-benchmark.md
  _monitoring-your-cluster/pa/rca/index.md
  _monitoring-your-cluster/pa/rca/shard-hotspot.md
  _security/access-control/api.md
  _security/access-control/impersonation.md
  _security/access-control/permissions.md
Labels: backport 2.11

#6020 Fix ism policy image
  images/ism.png
Labels: 4 - Doc Review

#5779 [DOC] Add workflowIds parameter
  _observing-your-data/alerting/api.md
Labels: Quick fix, backport 2.9, backport 2.10, backport 2.11

#6035 Clean up removed permissions
  _security/access-control/permissions.md
Labels: 4 - Doc Review, backport 2.11

#5706 Update tls.md
  _install-and-configure/install-dashboards/tls.md
Labels: 5 - Final Editorial Review

#6103 [DOC] _nodes/stats coordinator search stats documentation
  _api-reference/nodes-apis/nodes-stats.md
Labels: 3 - Done, backport 2.11

#6022 Clarify anonymous authentication support
  _security/access-control/anonymous-authentication.md
  _security/authentication-backends/proxy.md
  _security/configuration/configuration.md
Labels: 4 - Doc Review

#6033 Add opensearch-java version description on version 1.3
  _clients/java.md
Labels: backport 1.3, 3 - Done

#6068 Add supported processors table
  _ingest-pipelines/index.md
  _ingest-pipelines/processors/index-processors.md
Labels: 3 - Done, backport 2.11

#6082 [Doc] Add documentation for .replication-metadata-index for cross-cluster-replication.
  _tuning-your-cluster/replication-plugin/getting-started.md
Labels: 5 - Final Editorial Review, backport 2.11

#6179 Correct SA findings alerts API
  _security-analytics/api-tools/alert-finding-api.md
Labels: 5 - Final Editorial Review, backport 2.11

#6182 Update the Update and Bulk API's update/upsert sections
  _api-reference/cat/cat-nodes.md
  _api-reference/document-apis/bulk.md
  _api-reference/document-apis/update-document.md
Labels: backport 2.11

#6225 Add log enrichment use case to Data Prepper
  _data-prepper/common-use-cases/log-enrichment.md
Labels: 3 - Tech Review, data-prepper, Content gap

#6254 Update neural search documentation to include filters
  _query-dsl/specialized/neural.md
Labels: 4 - Doc Review

#5408 [Doc] Add docs for resource usage stats
  _api-reference/nodes-apis/nodes-stats.md
Labels: 6 - Done but waiting to merge, release-notes, v2.12.0

#6253 [DOC] Added documentation for admission control stats
  _api-reference/nodes-apis/nodes-stats.md
Labels: 4 - Doc Review, v2.12.0

#6134 Add max_docs_per_value to diversified sampler documentation
  _aggregations/bucket/diversified-sampler.md
  _aggregations/bucket/sampler.md
Labels: 5 - Final Editorial Review

#6244 Remove ingest processor supports excluding fields
  _ingest-pipelines/processors/remove.md
Labels: release-notes, 3 - Done, v2.12.0

#6203 Document how to configure XContent max field length and max depth constraints
  _install-and-configure/install-opensearch/index.md
Labels: 4 - Doc Review, release-notes, v2.12.0

#6250 Update bundled JDK version (January 2024 Patch releases)
  _install-and-configure/install-opensearch/index.md
Labels: backport 1.3, 4 - Doc Review, v2.12.0, backport 2.11

#5510 [DOC] Add dissect processor documentation
  _ingest-pipelines/processors/dissect.md
Labels: Content gap, backport 2.11

#6280 Fix link
  _ingest-pipelines/processors/dissect.md
Labels: 3 - Done, backport 2.11

#6265 Document new experimental HTTP transport based on Netty 4 and Project Reactor
  _install-and-configure/configuring-opensearch/network-settings.md
Labels: 5 - Final Editorial Review, release-notes, v2.12.0

#6164 Add understanding workloads section
  _benchmark/reference/workloads/index.md
  _benchmark/user-guide/concepts.md
  _benchmark/user-guide/understanding-workloads/anatomy-of-a-workload.md
  _benchmark/user-guide/understanding-workloads/choosing-a-workload.md
  _benchmark/user-guide/understanding-workloads/index.md
Labels: 6 - Done but waiting to merge, backport 2.11

#5631 [DOC]Add new dot expander processor doc
  _ingest-pipelines/processors/dot-expander.md
Labels: 5 - Final Editorial Review, Content gap

#6181 Add pattern matching (text processing) use case to Data Prepper documentation
  _data-prepper/common-use-cases/text-processing.md
Labels: 4 - Doc Review, data-prepper, Content gap

#6301 Fix Nav Order for Understanding workloads
  _benchmark/user-guide/understanding-workloads/index.md
Labels: backport 2.11

#6245 Create or Update alias API supports must_exist parameter
  _im-plugin/index-alias.md
Labels: 5 - Final Editorial Review, release-notes, v2.12.0

#6325 Fix Benchmark soft build errors
  _benchmark/user-guide/understanding-workloads/anatomy-of-a-workload.md
Labels: 4 - Doc Review, backport 2.11
