Repository opensearch-project/documentation-website, pull requests merged in 2024-03, with the labels that each got.

#6555 Update register sparse model api
  _ml-commons-plugin/api/model-apis/register-model.md
Labels: backport 2.12

#6519 Update docker.md
  _install-and-configure/install-opensearch/docker.md
Labels: 4 - Doc Review, backport 2.12

#6548 Add link to saved object
  _dashboards/management/management-index.md
Labels: 3 - Done, backport 2.12

#6520 Adds info about windows to Docker install
  _install-and-configure/install-opensearch/docker.md
Labels: 3 - Done, backport 2.12

#6561 Add copy buttons to demo configuration page
  _security/configuration/demo-configuration.md
Labels: 4 - Doc Review, backport 2.12

#6553 Updated the setting in 'certificate validation' section
  _security/authentication-backends/ldap.md
Labels: backport 2.12

#6408 Add 'DLS and multiple roles' section to DLS topic
  _security/access-control/document-level-security.md
Labels: 5 - Final Editorial Review, security, backport 2.12

#6566 Update keystore documentation to remove placeholder section
  _security/configuration/opensearch-keystore.md
Labels: 4 - Doc Review, backport 2.12

#6546 Add documentation for Search Workflow State API
  _automating-configurations/api/get-workflow-status.md
  _automating-configurations/api/index.md
  _automating-configurations/api/search-workflow-state.md
  _automating-configurations/api/search-workflow.md
Labels: 4 - Doc Review, backport 2.12

#6383 Improvements to the S3 sink documenation
  _data-prepper/pipelines/configuration/sinks/s3.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6404 Updated index permissions as per customer request #20230726
  _security/access-control/permissions.md
Labels: security, 4 - Doc Review

#6583 Copy edit title
  _data-prepper/common-use-cases/log-enrichment.md
Labels: data-prepper, backport 2.12

#6582 Add 1.3.15 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12

#6585 Add copy processor to table
  _ingest-pipelines/processors/index-processors.md
Labels: backport 2.12

#6570 Audit logging initial state description.
  _security/audit-logs/index.md
Labels: 4 - Doc Review, backport 2.12

#6576 "Linux and MacOS" => "Linux or MacOS"
  _benchmark/index.md
Labels: 4 - Doc Review, backport 2.12

#6608 Alphabetize by title
  _data-prepper/common-use-cases/anomaly-detection.md
  _data-prepper/common-use-cases/codec-processor-combinations.md
  _data-prepper/common-use-cases/event-aggregation.md
  _data-prepper/common-use-cases/log-analytics.md
  _data-prepper/common-use-cases/log-enrichment.md
  _data-prepper/common-use-cases/metrics-traces.md
  _data-prepper/common-use-cases/s3-logs.md
  _data-prepper/common-use-cases/text-processing.md
  _data-prepper/common-use-cases/trace-analytics.md
Labels: data-prepper, backport 2.12

#5767 [DOC] Add drop processor
  _ingest-pipelines/processors/date.md
  _ingest-pipelines/processors/drop.md
Labels: Content gap, 3 - Done, backport 2.12

#6380 Add permissions, metrics, and metadata attributes to Data Prepper dyn…
  _data-prepper/pipelines/configuration/sources/dynamo-db.md
Labels: 5 - Final Editorial Review, data-prepper 2.7, backport 2.12

#6629 Update HuggingFace link for neural sparse model
  _ml-commons-plugin/pretrained-models.md
Labels: 4 - Doc Review

#6640 Incorrect op_type param explanation
  _api-reference/document-apis/index-document.md
Labels: backport 2.12

#6641 Address feedback on PerfTop dashboard
  _monitoring-your-cluster/pa/dashboards.md
  images/perftop.jpg
Labels: 4 - Doc Review, backport 2.12

#6647 Remove ip data type
  _ingest-pipelines/processors/convert.md
Labels: backport 2.12

#6650 [bug]: Typo in otel-trace-raw.md
  _data-prepper/pipelines/configuration/processors/otel-trace-raw.md
Labels: 4 - Doc Review, backport 2.12

#6630 Fix copy_values processor documentation
  _data-prepper/pipelines/configuration/processors/copy-values.md
Labels: 3 - Tech Review, data-prepper, backport 2.12

#6651 Update api.md
  _security/access-control/api.md
Labels: 3 - Done, backport 2.12

#6666 Document how to configure XContent codepoint limit (YAML)
  _install-and-configure/install-opensearch/index.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6665 Add required_audience, required_issuer guide to jwt
  _security/authentication-backends/jwt.md
Labels: 4 - Doc Review, backport 2.12

#6672 Add Hadoop client to the clients list
  _clients/index.md
Labels: 3 - Done, backport 2.12

#6639 Add community_id ingest processor
  _ingest-pipelines/processors/community_id.md
  _ingest-pipelines/processors/index-processors.md
Labels: release-notes, 3 - Done, v2.13.0

#6717 Fix formatting error in Add Entries
  _data-prepper/pipelines/configuration/processors/add-entries.md
Labels: backport 2.7

#6347 Add index.query.max_nested_depth fix #6346
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 6 - Done but waiting to merge, release-notes, v2.13.0

#6703 Update documentation to support InnerProduct with k-NN Lucene Engine
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/knn-score-script.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6291 configure Content Security Policy (CSP) rules in OpenSearch Dashboards dynamically
  _dashboards/csp/csp-dynamic-configuration.md
Labels: release-notes, 3 - Done, v2.13.0

#6722 Add continue-on-error for vale checks to ignore inconsistent return status (temp fix)
  .github/workflows/vale.yml
Labels: bug, workflows

#6702 update the minimum_should_match example to be accurate
  _query-dsl/minimum-should-match.md
Labels: 4 - Doc Review, backport 2.12

#6711 Add documentation page for Vega Visualizations
  _dashboards/management/multi-data-sources.md
  _dashboards/visualize/vega.md
  images/dashboards/vega-2.png
Labels: release-notes, 3 - Done, v2.13.0

#6689 Update the multiple data source documentation [Multiple Data Source][2.13.0]
  _dashboards/management/multi-data-sources.md
  images/dashboards/multidata-hide-localcluster.gif
  images/dashboards/multidata-hide-show-auth.gif
Labels: release-notes, 3 - Done, v2.13.0

#6698 Add note about not passing 0 vector for cosine sim in k-NN
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-score-script.md
  _search-plugins/knn/painless-functions.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6699 Add documentation for kuromoji_completion filter
  _analyzers/token-filters/index.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6741 Remove experimental feature warning for Flow Framework plugin docs
  _automating-configurations/api/create-workflow.md
  _automating-configurations/api/delete-workflow.md
  _automating-configurations/api/deprovision-workflow.md
  _automating-configurations/api/get-workflow-status.md
  _automating-configurations/api/get-workflow-steps.md
  _automating-configurations/api/get-workflow.md
  _automating-configurations/api/index.md
  _automating-configurations/api/provision-workflow.md
  _automating-configurations/api/search-workflow-state.md
  _automating-configurations/api/search-workflow.md
  _automating-configurations/index.md
  _automating-configurations/workflow-settings.md
  _automating-configurations/workflow-steps.md
  _automating-configurations/workflow-tutorial.md
Labels: v2.13.0

#6725 Add Default Model Id for Neural Sparse Search Query in neural_query_enricher
  _search-plugins/neural-sparse-search.md
  _search-plugins/search-pipelines/search-processors.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6685 Add docs for flatten processor for Data Prepper
  _data-prepper/pipelines/configuration/processors/flatten.md
  _data-prepper/pipelines/configuration/processors/grok.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6683 Adds data prepper decompress processor documentation
  _data-prepper/pipelines/configuration/processors/decompress.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6740 Add documentation for new workflow steps
  _automating-configurations/workflow-steps.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6736 Add documentation for optional param for get workflow step API
  _automating-configurations/api/get-workflow-steps.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6730 Update doc for decoupling of remote cluster state with remote backed data storage
  _tuning-your-cluster/availability-and-recovery/remote-store/remote-cluster-state.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6724 Add post_filter is supported in hybrid search
  _search-plugins/hybrid-search.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6707 Add documentation for text chunking processor
  _ingest-pipelines/processors/index-processors.md
  _ingest-pipelines/processors/text-chunking.md
  _search-plugins/neural-sparse-search.md
  _search-plugins/semantic-search.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6661 Add aggregations to Search-Hybrid search section
  _search-plugins/hybrid-search.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6753 Fixed redirects
  _search-plugins/sql/ppl/index.md
Labels: 4 - Doc Review, backport 2.12

#6681 Add data prepper documentation for grok performance_metadata
  _data-prepper/pipelines/configuration/processors/grok.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6738 Documentation for data prepper dynamodb source view_on_remove feature
  _data-prepper/pipelines/configuration/sources/dynamo-db.md
Labels: data-prepper 2.7

#6733 Update plugins.md with semver range support specification
  _install-and-configure/plugins.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6386 Update Data Prepper opensearch sink documentation
  _data-prepper/pipelines/configuration/sinks/opensearch.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6746 Add client_config parameter documentation
  _ml-commons-plugin/agents-tools/agents-tools-tutorial.md
  _ml-commons-plugin/remote-models/blueprints.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6664 Add force-merge API supports primary_only parameter
  _api-reference/index-apis/force-merge.md
Labels: 5 - Final Editorial Review, release-notes, v2.13.0

#6708 Add cache plugin and tiered cache documentation
  _search-plugins/caching/index.md
  _search-plugins/caching/tiered-cache.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6770 Broken image
  _dashboards/management/index-patterns.md
Labels: 4 - Doc Review, backport 2.12

#6739 Add section on configuring anonymous login for OpenSearch Dashboards
  _security/access-control/anonymous-authentication.md
Labels: 5 - Final Editorial Review, backport 2.12

#6771 Dashboards Assistant update sidebar content
  _dashboards/dashboards-assistant/index.md
Labels: 3 - Tech Review, v2.13.0

#6773 Update trace-analytics.md
  _data-prepper/common-use-cases/trace-analytics.md
Labels: backport 2.12

#6768 Update otel-trace.md
  _data-prepper/pipelines/configuration/sources/otel-trace-source.md
Labels: 3 - Tech Review, data-prepper, backport 2.12

#6774 Adds a configuration for the Data Prepper S3 source workers field.
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: data-prepper

#6781 Fix redirect in data prepper otel trace
  _data-prepper/pipelines/configuration/sources/otel-trace-source.md
Labels: backport 2.12

#6749 Add qa model and new settings in ml-commons
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/custom-local-models.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6547 Add documentation for parameter substitution when provisioning workflows
  _automating-configurations/api/create-workflow.md
  _automating-configurations/api/provision-workflow.md
Labels: 4 - Doc Review, v2.13.0

#6761 Add parse_ion processor
  _data-prepper/pipelines/configuration/processors/parse-ion.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6680 Add docs for map_to_list processor
  _data-prepper/pipelines/configuration/processors/map-to-list.md
  _data-prepper/pipelines/configuration/processors/mutate-event.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6772 Adds documentation for the Data Prepper geoip processor and geoip_service extension
  _data-prepper/managing-data-prepper/extensions/extensions.md
  _data-prepper/managing-data-prepper/extensions/geoip_service.md
  _data-prepper/pipelines/configuration/processors/geoip.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6499 Add new parameters to findings API in security analytics
  _security-analytics/api-tools/alert-finding-api.md
Labels: release-notes, security-analytics, 3 - Done, v2.13.0

#6572 Update get-snapshot-status.md
  _api-reference/snapshots/get-snapshot-status.md
Labels: 4 - Doc Review, snapshots, backport 2.12

#6788 Fix key of system index permission configuration
  _security/access-control/permissions.md
  _security/configuration/yaml.md
Labels: backport 2.12

#6660 Added documentation for select entries, map-to-list, and trucate processors.
  _data-prepper/pipelines/configuration/buffers/kafka.md
  _data-prepper/pipelines/configuration/processors/mutate-event.md
  _data-prepper/pipelines/configuration/processors/select-entries.md
  _data-prepper/pipelines/configuration/processors/truncate.md
  _data-prepper/pipelines/configuration/sinks/file.md
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6634 Add documentation for security config upgrade feature
  _security/access-control/api.md
Labels: 5 - Final Editorial Review, release-notes, v2.13.0

#6682 Add split event processor for dataprepper
  _data-prepper/pipelines/configuration/processors/split-event.md
Labels: 5 - Final Editorial Review, data-prepper 2.7

#6763 Data Prepper 2.7 documentation
  _data-prepper/managing-data-prepper/configuring-data-prepper.md
  _data-prepper/managing-data-prepper/extensions/extensions.md
  _data-prepper/managing-data-prepper/extensions/geoip_service.md
  _data-prepper/pipelines/configuration/processors/date.md
  _data-prepper/pipelines/configuration/processors/decompress.md
  _data-prepper/pipelines/configuration/processors/delete-entries.md
  _data-prepper/pipelines/configuration/processors/dissect.md
  _data-prepper/pipelines/configuration/processors/drop-events.md
  _data-prepper/pipelines/configuration/processors/flatten.md
  _data-prepper/pipelines/configuration/processors/geoip.md
  _data-prepper/pipelines/configuration/processors/grok.md
  _data-prepper/pipelines/configuration/processors/list-to-map.md
  _data-prepper/pipelines/configuration/processors/map-to-list.md
  _data-prepper/pipelines/configuration/processors/mutate-event.md
  _data-prepper/pipelines/configuration/processors/obfuscate.md
  _data-prepper/pipelines/configuration/processors/parse-ion.md
  _data-prepper/pipelines/configuration/processors/split-event.md
  _data-prepper/pipelines/configuration/sinks/opensearch.md
  _data-prepper/pipelines/configuration/sinks/s3.md
  _data-prepper/pipelines/configuration/sources/dynamo-db.md
  _data-prepper/pipelines/configuration/sources/s3.md
  _data-prepper/pipelines/expression-syntax.md
Labels: Blocked, data-prepper 2.7

#6798 Added Eric as maintainer
  MAINTAINERS.md
Labels: 3 - Done

#6760 Add ingest pipeline to reindex.md
  _api-reference/document-apis/reindex.md
Labels: 3 - Tech Review, backport 2.12

#6606 Adding explanation for editing permissions 20230825
  _security/access-control/document-level-security.md
  _security/access-control/users-roles.md
Labels: security, 3 - Done, backport 2.12

#6745 Remove experimental feature labels and flags for OS Assistant
  _automating-configurations/index.md
  _dashboards/dashboards-assistant/index.md
  _ml-commons-plugin/agents-tools/agents-tools-tutorial.md
  _ml-commons-plugin/agents-tools/index.md
  _ml-commons-plugin/agents-tools/tools/agent-tool.md
  _ml-commons-plugin/agents-tools/tools/cat-index-tool.md
  _ml-commons-plugin/agents-tools/tools/index-mapping-tool.md
  _ml-commons-plugin/agents-tools/tools/index.md
  _ml-commons-plugin/agents-tools/tools/ml-model-tool.md
  _ml-commons-plugin/agents-tools/tools/neural-sparse-tool.md
  _ml-commons-plugin/agents-tools/tools/ppl-tool.md
  _ml-commons-plugin/agents-tools/tools/rag-tool.md
  _ml-commons-plugin/agents-tools/tools/search-alerts-tool.md
  _ml-commons-plugin/agents-tools/tools/search-anomaly-detectors.md
  _ml-commons-plugin/agents-tools/tools/search-anomaly-results.md
  _ml-commons-plugin/agents-tools/tools/search-index-tool.md
  _ml-commons-plugin/agents-tools/tools/search-monitors-tool.md
  _ml-commons-plugin/agents-tools/tools/vector-db-tool.md
  _ml-commons-plugin/agents-tools/tools/visualization-tool.md
  _ml-commons-plugin/api/agent-apis/delete-agent.md
  _ml-commons-plugin/api/agent-apis/execute-agent.md
  _ml-commons-plugin/api/agent-apis/get-agent.md
  _ml-commons-plugin/api/agent-apis/index.md
  _ml-commons-plugin/api/agent-apis/register-agent.md
  _ml-commons-plugin/api/agent-apis/search-agent.md
  _ml-commons-plugin/custom-local-models.md
  _ml-commons-plugin/ml-dashboard.md
  _ml-commons-plugin/opensearch-assistant.md
  _ml-commons-plugin/pretrained-models.md
  _ml-commons-plugin/using-ml-models.md
  _observing-your-data/event-analytics.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6750 Add guardrails for remote model
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/api/model-apis/update-model.md
  _ml-commons-plugin/remote-models/guardrails.md
  _ml-commons-plugin/remote-models/index.md
Labels: 4 - Doc Review, release-notes, v2.13.0

#6810 Fix table in S3 documentation
  _data-prepper/pipelines/configuration/sinks/opensearch.md
Labels: backport 2.12

#6794 Add example to text chunking processor documentation
  _ingest-pipelines/processors/text-chunking.md
  _search-plugins/neural-sparse-search.md
  _search-plugins/semantic-search.md
  _search-plugins/text-chunking.md
Labels: 5 - Final Editorial Review, release-notes, v2.13.0

#6767 Add documentation for default use cases
  _automating-configurations/api/create-workflow.md
  _automating-configurations/workflow-templates.md
Labels: 5 - Final Editorial Review, release-notes, v2.13.0

#6809 Tweak backport branch delete workflow to delete other merged branches
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
Labels: enhancement, workflows

#6807 Rename Creating Benchmark workloads page
  _benchmark/user-guide/creating-custom-workloads.md
Labels: 3 - Tech Review, benchmark, backport 2.12

#6814 Tweak syntax for the merged branch deletion workflow
  .github/workflows/.delete_backport_branch.yml.swp
  .github/workflows/delete_merged_branch.yml
Labels: enhancement, wontfix
