Repository opensearch-project/documentation-website, pull requests merged in 2024-04, with the labels that each got.

#6805 fix(security): explicitly add keys required in security config
  _security/authentication-backends/basic-authc.md
  _security/authentication-backends/openid-connect.md
  _security/authentication-backends/saml.md
Labels: 3 - Tech Review, backport 2.12

#6822 Add parse XML docs
  _data-prepper/pipelines/configuration/processors/parse-xml.md
Labels: 5 - Final Editorial Review, data-prepper 2.7, backport 2.12

#6816 feat: index param in async search
  _search-plugins/async/index.md
  _security/access-control/users-roles.md
Labels: 4 - Doc Review, backport 2.12

#6828 Add detail to searchable snapshot limits section
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
Labels: backport 2.12

#6831 Move deprecation warning to correct table
  _data-prepper/pipelines/configuration/sinks/opensearch.md
Labels: data-prepper 2.7, backport 2.12

#6700 Add or update boost prameter for term-level queries
  _query-dsl/term/exists.md
  _query-dsl/term/fuzzy.md
  _query-dsl/term/ids.md
  _query-dsl/term/prefix.md
  _query-dsl/term/range.md
  _query-dsl/term/regexp.md
  _query-dsl/term/term.md
  _query-dsl/term/terms-set.md
  _query-dsl/term/terms.md
  _query-dsl/term/wildcard.md
Labels: 4 - Doc Review, backport 2.13

#6865 Initial changes add backport automerge label
  .github/workflows/backport.yml
  .github/workflows/delete_merged_branch.yml
Labels: enhancement, workflows

#6871 Tweak label creation logic on backport workflows
  .github/workflows/backport.yml
Labels: enhancement, workflows

#6235 Add log types section to Security Analytics
  _security-analytics/index.md
  _security-analytics/log-types-reference/ad-ldap.md
  _security-analytics/log-types-reference/apache-access.md
  _security-analytics/log-types-reference/azure.md
  _security-analytics/log-types-reference/cloudtrail.md
  _security-analytics/log-types-reference/dns.md
  _security-analytics/log-types-reference/github.md
  _security-analytics/log-types-reference/gworkspace.md
  _security-analytics/log-types-reference/index.md
  _security-analytics/log-types-reference/linux.md
  _security-analytics/log-types-reference/m365.md
  _security-analytics/log-types-reference/netflow.md
  _security-analytics/log-types-reference/network.md
  _security-analytics/log-types-reference/okta.md
  _security-analytics/log-types-reference/other.md
  _security-analytics/log-types-reference/s3.md
  _security-analytics/log-types-reference/vpc.md
  _security-analytics/log-types-reference/waf.md
  _security-analytics/log-types-reference/windows.md
  _security-analytics/sec-analytics-config/custom-log-type.md
  _security-analytics/sec-analytics-config/detectors-config.md
  _security-analytics/sec-analytics-config/log-types.md
  images/Security/c-log-type.png
Labels: 5 - Final Editorial Review, security-analytics, backport 2.13

#6795 Add documentation for setting the OpenSearch keystore password
  _security/configuration/opensearch-keystore.md
Labels: security, backport 2.13

#6824 Made changes to create-index documentation to add copy-as-curl option
  _api-reference/index-apis/create-index.md
  _api-reference/index-apis/delete-index.md
Labels: 4 - Doc Review, backport 2.13

#6605 Adding security installation information #20231130
  _security/configuration/disable-enable-security.md
  _security/configuration/disable.md
  _security/configuration/index.md
Labels: 5 - Final Editorial Review, security, backport 2.12

#6786 Add clarification about OpenSearch ingest pipelines compared to Data …
  _data-prepper/index.md
  _ingest-pipelines/index.md
  _ingest-pipelines/processors/grok.md
Labels: 3 - Tech Review, data-prepper, documentation

#6889 [TEST BACKPORT] TEST ONLY
  .github/workflows/automerge-backport.yml
  123
Labels: enhancement, workflows, backport testmain2

#6892 Add Automerge Workflow with other smaller fixes
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
  .github/workflows/vale.yml
Labels: enhancement, workflows

#6862 Changed documentation for incorrect parameters
  _install-and-configure/configuring-opensearch/search-settings.md
Labels: 4 - Doc Review, backport 2.13

#6907 Backport main workflows to 2.13 branch
  .github/dco.yml
Labels: enhancement, workflows

#6906 Backport main workflows to 2.12 branch
  .github/dco.yml
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
  .github/workflows/vale.yml
Labels: enhancement, workflows

#6905 Backport main workflows to 2.11 branch
  .github/dco.yml
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
  .github/workflows/vale.yml
Labels: enhancement, workflows

#6904 Backport main workflows to 2.10 branch
  .github/dco.yml
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
  .github/workflows/vale.yml
Labels: enhancement, workflows

#6903 Backport main workflows to 2.9 branch
  .github/dco.yml
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
  .github/workflows/vale.yml
Labels: enhancement, workflows

#6902 Backport main workflows to 2.8 branch
  .github/dco.yml
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
  .github/workflows/vale.yml
Labels: enhancement, workflows

#6901 Backport main workflows to 2.7 branch
  .github/dco.yml
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
Labels: enhancement, workflows

#6900 Backport main workflows to 2.6 branch
  .github/dco.yml
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
Labels: enhancement, workflows

#6899 Backport main workflows to 2.5 branch
  .github/dco.yml
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
Labels: enhancement, workflows

#6756 HTTP Methods Examples Provided 20231026
  _api-reference/document-apis/index-document.md
  _security/access-control/document-level-security.md
Labels: 5 - Final Editorial Review, security, backport 2.13

#6894 Backport main workflows to 2.0 branch
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/dco.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
Labels: enhancement, workflows

#6896 Backport main workflows to 2.2 branch
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/dco.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
Labels: enhancement, workflows

#6897 Backport main workflows to 2.3 branch
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/dco.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
Labels: enhancement, workflows

#6909 Backport main workflows to 1.3 branch
  .github/workflows/automerge-backport.yml
  .github/workflows/backport.yml
  .github/workflows/dco.yml
  .github/workflows/delete_merged_branch.yml
  .github/workflows/encoding-check.yml
  .github/workflows/jekyll-build.yml
  .github/workflows/link-checker.yml
Labels: enhancement, workflows

#6657 Add more details to cross-cluster page #20230811 #20231102 #20230804
  _search-plugins/cross-cluster-search.md
  _search-plugins/sql/ppl/index.md
  images/ccs-devtools.png
Labels: 5 - Final Editorial Review, security, backport 2.13

#6783 Update requestHeadersAllowlist in openid-connect.md example settings
  _security/authentication-backends/openid-connect.md
Labels: 3 - Tech Review, v-All, backport 2.13

#6916 Fix a few issues with Data Prepper common use cases - log enrichment doc
  _data-prepper/common-use-cases/log-enrichment.md
Labels: data-prepper, backport 2.13

#6913 Fix code error on select_entries processor
  _data-prepper/pipelines/configuration/processors/select-entries.md
Labels: 3 - Tech Review, backport 2.13

#6826 5166 Updating new roles and removing old roles
  _security/access-control/users-roles.md
Labels: 5 - Final Editorial Review, security, backport 2.13

#6637 Update compatibility chart with Almalinux8 and remove CentOS8 since already deprecated
  _install-and-configure/install-opensearch/index.md
Labels: 4 - Doc Review, backport 2.13

#6939 Update language around client version compatibility
  _clients/index.md
Labels: 4 - Doc Review, backport 2.13

#6941 Update index.md
  _clients/index.md
Labels: 4 - Doc Review, backport 2.13

#6886 Add note about Data Prepper versus ingest processors
  _ingest-pipelines/processors/append.md
  _ingest-pipelines/processors/convert.md
  _ingest-pipelines/processors/copy.md
  _ingest-pipelines/processors/csv.md
  _ingest-pipelines/processors/date.md
  _ingest-pipelines/processors/dissect.md
  _ingest-pipelines/processors/drop.md
  _ingest-pipelines/processors/grok.md
  _ingest-pipelines/processors/kv.md
  _ingest-pipelines/processors/lowercase.md
  _ingest-pipelines/processors/uppercase.md
Labels: backport 2.13

#6946 Update ip2geo.md
  _ingest-pipelines/processors/ip2geo.md
Labels: 4 - Doc Review, backport 2.13

#6833 Added troubleshooting instructions for environment set up
  CONTRIBUTING.md
Labels: 4 - Doc Review

#6956 Revert "Add documentation for security config upgrade feature (#6634)"
  _security/access-control/api.md
Labels: v2.13.0, backport 2.13

#6926 Adds section on product quantization for docs
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/knn-vector-quantization.md
Labels: backport 2.13

#6920 [Doc] Add documentation for remote cluster connection mode for CCR
  _tuning-your-cluster/replication-plugin/getting-started.md
Labels: 4 - Doc Review, backport 2.13

#6961 Make edits to PR 6920
  _tuning-your-cluster/replication-plugin/getting-started.md
Labels: backport 2.13

#6910 Add throughput and latency documentation
  _benchmark/user-guide/concepts.md
  _benchmark/user-guide/index.md
  _benchmark/user-guide/target-throughput.md
  _benchmark/user-guide/understanding-workloads/anatomy-of-a-workload.md
  images/benchmark/concepts-diagram.png
Labels: 5 - Final Editorial Review, benchmark, backport 2.13

#6881 Add separate certificates section #433
  _security/configuration/tls.md
Labels: 5 - Final Editorial Review, security, backport 2.13

#6875 Add hot reload TLS certificate section #433
  _api-reference/index.md
  _security/configuration/tls.md
Labels: 5 - Final Editorial Review, security, backport 2.13

#6970 Update concurrent search docs with dynamic slice count setting
  _search-plugins/concurrent-segment-search.md
Labels: 4 - Doc Review, backport 2.13

#6917 Clarifies that Data Prepper select_entries processor does not remove events
  _data-prepper/pipelines/configuration/processors/select-entries.md
Labels: 4 - Doc Review, data-prepper, backport 2.13

#6973 [BUG] Cannot restore ES 6.x index into OpenSearch 2.x but the migration doc says it should work
  _upgrade-to/snapshot-migrate.md
Labels: 4 - Doc Review, backport 2.13

#6951 Add rename ingest processor
  _ingest-pipelines/processors/index-processors.md
  _ingest-pipelines/processors/rename.md
Labels: backport 2.13

#6982 Add missing list notification channels API
  _observing-your-data/notifications/api.md
Labels: 4 - Doc Review, backport 2.13

#6991 Add 1.3.16 to version history
  _about/version-history.md
Labels: 4 - Doc Review, backport-to-all

#6980 Fix msearch PATH methods
  _api-reference/multi-search.md
Labels: 4 - Doc Review, backport 2.13

#6966 adding audit_rest_request_method to audit log field reference #6395
  _security/audit-logs/field-reference.md
Labels: security, 4 - Doc Review, backport 2.13

#6787 Fixes to S3 config in data prepper.
  _data-prepper/pipelines/configuration/sinks/s3.md
Labels: 3 - Tech Review, data-prepper, backport 2.13

#6806 Add read-only role page to documents #5783
  _data-prepper/pipelines/configuration/sinks/opensearch.md
  _security/access-control/users-roles.md
  _security/authentication-backends/client-auth.md
  _security/configuration/yaml.md
  _tuning-your-cluster/replication-plugin/permissions.md
  images/compare_read_only_mode.png
  images/creating-user.png
  images/kibanauser.png
  images/mapping-users.png
  images/role_creation_read_only.png
Labels: 5 - Final Editorial Review, security, backport 2.13

#6964 adding datasource permissions to permissions page #6360
  _dashboards/management/data-sources.md
  _security/access-control/permissions.md
Labels: security, 4 - Doc Review, backport 2.13

#7018 Added the begin/end certificate and key comment lines
  _security/authentication-backends/ldap.md
  _security/authentication-backends/openid-connect.md
  _security/authentication-backends/saml.md
Labels: backport 2.13

#7025 Convert ingest processor supports ip type
  _ingest-pipelines/processors/convert.md
Labels: release-notes, v2.14.0

#6988 Rename ingest processor supports overriding target field if exists
  _ingest-pipelines/processors/rename.md
Labels: release-notes, v2.14.0

#7023 Update index-settings.md
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 4 - Doc Review, backport 2.13

#7046 Fix Bechmark TOC
  _benchmark/user-guide/concepts.md
  _benchmark/user-guide/index.md
  _benchmark/user-guide/target-throughput.md
Labels: backport 2.13

#7036 Update alert-finding-api.md
  _security-analytics/api-tools/alert-finding-api.md
Labels: 4 - Doc Review

#5994 [DOC] Add urldecode processor documentation
  _ingest-pipelines/processors/urldecode.md
Labels: Needs SME, Content gap

#7063 clarify "contexts"
  _api-reference/script-apis/get-script-language.md
Labels: backport 2.13

#7048 Add documentation for indices.replication.max_bytes_per_sec
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 6 - Done but waiting to merge, release-notes, v2.14.0

#7043 Update concurrent search docs with composite aggs updates
  _search-plugins/concurrent-segment-search.md
Labels: 6 - Done but waiting to merge, release-notes, v2.14.0

#7040 add query_by_tokens option in Neural Sparse Search
  _query-dsl/specialized/neural-sparse.md
  _search-plugins/neural-sparse-search.md
Labels: 6 - Done but waiting to merge, release-notes, v2.14.0

#7031 Update bundled JDK version (April 2024 Patch releases)
  _install-and-configure/install-opensearch/index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.14.0

#6987 Updating documentation for ignore_unavailable search request parameter
  _api-reference/document-apis/delete-by-query.md
  _api-reference/document-apis/update-by-query.md
  _api-reference/multi-search.md
  _api-reference/search.md
Labels: 6 - Done but waiting to merge, release-notes, v2.14.0

#6841 Add documentation for hardware-accelerated compression codecs.
  _im-plugin/index-codecs.md
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 6 - Done but waiting to merge, release-notes, v2.14.0

#6955 Correct the release version for the upgrade API feature
  _security/access-control/api.md
Labels: 6 - Done but waiting to merge, v2.14.0

#5995 [DOC] Add user agent processor documentation
  _ingest-pipelines/processors/user-agent.md
Labels: Needs SME, Content gap, backport 2.13
