Repository opensearch-project/documentation-website, pull requests merged in 2024-10, with the labels that each got.

#8420 Fix broken links
  _troubleshoot/tls.md
Labels: backport 2.17

#8423 Add 2.17.1 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17

#8373 Add 'Cleanup Snapshot' API Documentation
  _api-reference/snapshots/cleanup-snapshot-repository.md
Labels: 5 - Editorial review, backport 2.17

#8466 Change request type of k-NN clear cache api from GET to POST
  _search-plugins/knn/api.md
Labels: backport 2.17

#8266 [Feature]: add ignore missing to text chunking processor
  _ingest-pipelines/processors/text-chunking.md
Labels: 6 - Done but waiting to merge, release-notes, v2.18.0

#8483 fix typo in viz-index.md
  _dashboards/visualize/viz-index.md
Labels: backport 2.17

#7918 Add Classic token filter docs
  _analyzers/token-filters/classic.md
  _analyzers/token-filters/index.md
Labels: 5 - Editorial review, analyzers, backport 2.17

#8523 fix recovery path
  _api-reference/index-apis/recover.md
Labels: backport 2.17

#8522 Msearch template API returns status code in each search response
  _api-reference/msearch-template.md
Labels: release-notes, v2.18.0

#8526 Document cluster.default_number_of_replicas and update index.number_of_replicas
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: release-notes, v2.18.0

#7115 Add mapping parameters documentation
  _field-types/mapping-parameters/analyzer.md
  _field-types/mapping-parameters/boost.md
  _field-types/mapping-parameters/coerce.md
  _field-types/mapping-parameters/copy-to.md
  _field-types/mapping-parameters/dynamic.md
  _field-types/mapping-parameters/index.md
Labels: backport 2.17

#7645 Add children aggregation documentation
  _aggregations/bucket/children.md
  _aggregations/bucket/index.md
Labels: aggregations and analyzers, Content gap

#8206 [DOC] Character filter - Index & HTML Strip
  _analyzers/character-filters/html-character-filter.md
  _analyzers/character-filters/index.md
Labels: Content gap, analyzers

#7900 Adding documentation for filter search in OpenSearch
  _search-plugins/filter-search.md
Labels: 5 - Editorial review, search-and-query, backport 2.17

#7933 Add common_gram token filter page #7923
  _analyzers/token-filters/common_gram.md
  _analyzers/token-filters/index.md
Labels: 4 - Doc review, Needs SME, analyzers

#8521 add documentation for new aggregate command + auto aggregation
  _benchmark/reference/commands/aggregate.md
  _benchmark/reference/commands/command-flags.md
Labels: 6 - Done but waiting to merge, 5 - Editorial review, backport 2.17

#8586 Update Data Prepper copy-values processor docs
  _data-prepper/pipelines/configuration/processors/copy-values.md
Labels: data-prepper

#7630 Add auto-date histogram aggregations documentation
  _aggregations/bucket/auto-interval-date-histogram.md
Labels: 4 - Doc review, aggregations and analyzers, Content gap, backport 2.17

#8469 document the new `analysis-phonenumber` plugin
  _analyzers/supported-analyzers/index.md
  _analyzers/supported-analyzers/phone-analyzers.md
  _install-and-configure/additional-plugins/index.md
Labels: 5 - Editorial review, release-notes, v2.18.0

#8590 Add documentation changes for cluster level dynamic limit settings to block cat/indices, _cat/shards and _cat/segments
  _api-reference/cat/cat-indices.md
  _api-reference/cat/cat-segments.md
  _api-reference/cat/cat-shards.md
  _install-and-configure/configuring-opensearch/cluster-settings.md
Labels: 6 - Done but waiting to merge, release-notes, v2.18.0

#8603 Update JDK version for 2.x distributions
  _install-and-configure/install-opensearch/index.md
Labels: release-notes, v2.18.0

#8604 Update documentation for coordination settings and batch size
  _install-and-configure/configuring-opensearch/cluster-settings.md
Labels: 5 - Editorial review, release-notes, v2.18.0

#8252 Add documentation for Kinesis source in Data prepper
  CONTRIBUTING.md
  _analyzers/index.md
  _data-prepper/pipelines/configuration/sources/kinesis.md
Labels: 5 - Editorial review, data-prepper

#8588 Add doc for dynamic threadpool settings
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 4 - Doc review, release-notes, v2.18.0

#8593 Adds documentation about byField rerank processor
  _search-plugins/search-pipelines/rerank-processor.md
  _search-plugins/search-relevance/rerank-by-field.md
  _search-plugins/search-relevance/rerank-cross-encoder.md
  _search-plugins/search-relevance/reranking-search-results.md
Labels: 6 - Done but waiting to merge, release-notes, v2.18.0

#8608 Fix misleading typo
  _api-reference/index-apis/update-settings.md
Labels: backport 2.17

#8336 LTR documentation
  .github/vale/styles/Vocab/OpenSearch/Products/accept.txt
  _search-plugins/ltr/advanced-functionality.md
  _search-plugins/ltr/core-concepts.md
  _search-plugins/ltr/faq.md
  _search-plugins/ltr/feature-engineering.md
  _search-plugins/ltr/fits-in.md
  _search-plugins/ltr/index.md
  _search-plugins/ltr/logging-features.md
  _search-plugins/ltr/searching-with-your-model.md
  _search-plugins/ltr/training-models.md
  _search-plugins/ltr/working-with-features.md
Labels: 5 - Editorial review, Machine Learning, community, v2.18.0

#8620 Update default engine from nmslib to faiss
  _search-plugins/knn/knn-index.md
Labels: 4 - Doc review, release-notes, v2.18.0

#8547 Close content gap for doc_values mapping parameter
  _field-types/mapping-parameters/doc-values.md
  _field-types/mapping-parameters/dynamic.md
Labels: 3 - Tech review, Mappings and fields, Content gap

#8624 Fix capitilzation of default engine example
  _search-plugins/knn/knn-index.md
Labels: 3 - Tech review

#8595 Add URI paths for cluster stats filtering.
  _api-reference/cluster-api/cluster-stats.md
Labels: 5 - Editorial review, release-notes, v2.18.0

#8541 Add SQL PIT reference
  _search-plugins/searching-data/point-in-time.md
Labels: 6 - Done but waiting to merge, release-notes, v2.18.0

#8356 Data Stream support for Audit- Log
  _security/audit-logs/storage-types.md
Labels: 5 - Editorial review, v2.18.0

#8544 Add new rename_alias parameters for restore-snapshot
  _api-reference/snapshots/restore-snapshot.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: 5 - Editorial review, release-notes, v2.18.0

#8594 Adding documentation for _list APIs
  _api-reference/list/index.md
  _api-reference/list/list-indices.md
  _api-reference/list/list-shards.md
Labels: 5 - Editorial review, release-notes, v2.18.0

#8132 Added from and to parameters to top N queries to specify time range
  _observing-your-data/query-insights/top-n-queries.md
Labels: 6 - Done but waiting to merge, release-notes, v2.18.0

#8623 Add new indexing parameter and update performance tuning instruction
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/performance-tuning.md
Labels: 5 - Editorial review, release-notes, v2.18.0

#8631 Documentation for query field name and datatype in query shape
  _observing-your-data/query-insights/grouping-top-n-queries.md
  _observing-your-data/query-insights/index.md
Labels: 4 - Doc review, release-notes, v2.18.0

#8635 Add missing parameter to append ingest processor
  _ingest-pipelines/processors/append.md
Labels: backport 2.17

#8627 add document for Query Insights health_stats API
  _observing-your-data/query-insights/health.md
  _observing-your-data/query-insights/index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.18.0
