Repository opensearch-project/documentation-website, pull requests merged in 2024-08, with the labels that each got.

#7840 Add doc for binary format support in k-NN
  _field-types/supported-field-types/knn-vector.md
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/knn-score-script.md
  _search-plugins/knn/painless-functions.md
  _search-plugins/vector-search.md
Labels: 4 - Doc review, release-notes, v2.16.0

#7127 Edit for redundant information and sections across Data Prepper
  _data-prepper/index.md
  _data-prepper/managing-data-prepper/configuring-data-prepper.md
  _data-prepper/pipelines/cidrcontains.md
  _data-prepper/pipelines/configuration/buffers/buffers.md
  _data-prepper/pipelines/configuration/processors/add-entries.md
  _data-prepper/pipelines/configuration/processors/processors.md
  _data-prepper/pipelines/configuration/sinks/sinks.md
  _data-prepper/pipelines/configuration/sources/dynamo-db.md
  _data-prepper/pipelines/configuration/sources/sources.md
  _data-prepper/pipelines/contains.md
  _data-prepper/pipelines/dlq.md
  _data-prepper/pipelines/expression-syntax.md
  _data-prepper/pipelines/functions.md
  _data-prepper/pipelines/get-metadata.md
  _data-prepper/pipelines/has-tags.md
  _data-prepper/pipelines/join.md
  _data-prepper/pipelines/length.md
  _data-prepper/pipelines/pipelines-configuration-options.md
  _data-prepper/pipelines/pipelines.md
Labels: data-prepper, 3 - Done, backport 2.15

#7893 Update index.md
  _api-reference/index.md
Labels: backport 2.15

#7852 Add documentation for ml inference search request processor/ search response processor
  _query-dsl/geo-and-xy/xy.md
  _search-plugins/search-pipelines/collapse-processor.md
  _search-plugins/search-pipelines/filter-query-processor.md
  _search-plugins/search-pipelines/ml-inference-search-request.md
  _search-plugins/search-pipelines/ml-inference-search-response.md
  _search-plugins/search-pipelines/neural-query-enricher.md
  _search-plugins/search-pipelines/neural-sparse-query-two-phase-processor.md
  _search-plugins/search-pipelines/normalization-processor.md
  _search-plugins/search-pipelines/oversample-processor.md
  _search-plugins/search-pipelines/personalize-search-ranking.md
  _search-plugins/search-pipelines/rag-processor.md
  _search-plugins/search-pipelines/rename-field-processor.md
  _search-plugins/search-pipelines/rerank-processor.md
  _search-plugins/search-pipelines/script-processor.md
  _search-plugins/search-pipelines/search-processors.md
  _search-plugins/search-pipelines/sort-processor.md
  _search-plugins/search-pipelines/split-processor.md
  _search-plugins/search-pipelines/truncate-hits-processor.md
Labels: 4 - Doc review, release-notes, v2.16.0

#7899 Ml commons batch inference
  _ml-commons-plugin/api/index.md
  _ml-commons-plugin/api/model-apis/batch-predict.md
  _ml-commons-plugin/api/model-apis/index.md
  _ml-commons-plugin/api/train-predict/index.md
  _ml-commons-plugin/api/train-predict/predict.md
  _ml-commons-plugin/api/train-predict/train-and-predict.md
  _ml-commons-plugin/api/train-predict/train.md
Labels: 5 - Editorial review, release-notes, experimental, v2.16.0

#7906 Remove repeated sentence in distributed tracing doc
  _observing-your-data/trace/distributed-tracing.md
Labels: backport 2.15

#7884 Add apostrophe token filter page #7871
  _analyzers/token-filters/apostrophe.md
  _analyzers/token-filters/index.md
Labels: 2 - In progress, Content gap, backport 2.15

#7924 Update users-roles.md
  _security/access-control/users-roles.md
Labels: backport 2.15

#7921 Fix typo
  _ml-commons-plugin/agents-tools/index.md
  _ml-commons-plugin/api/agent-apis/register-agent.md
Labels: 4 - Doc review, backport 2.15

#7905 Add Threat Intelligence Section
  _security-analytics/threat-intelligence/api/findings.md
  _security-analytics/threat-intelligence/api/monitor.md
  _security-analytics/threat-intelligence/api/source.md
  _security-analytics/threat-intelligence/api/threat-intel-api.md
  _security-analytics/threat-intelligence/getting-started.md
  _security-analytics/threat-intelligence/index.md
  _security-analytics/usage/detectors.md
  assets/examples/all-ioc-type-examples.json
Labels: 5 - Editorial review, release-notes, v2.16.0

#7909 Add a comment regarding read/write control via HTTP verbs #863
  _security/access-control/rest-layer-authz.md
Labels: 3 - Tech review, backport 2.15

#7891 Add documentation for ingest-attachment plugin
  _install-and-configure/additional-plugins/index.md
  _install-and-configure/additional-plugins/ingest-attachment-plugin.md
Labels: 4 - Doc review, backport 2.15

#7836 Add Blocks API and add additional Get document descriptions.
  _api-reference/document-apis/get-documents.md
  _api-reference/index-apis/blocks.md
Labels: API, 5 - Editorial review, Content gap, backport 2.16

#7944 Remove missing parameter
  _api-reference/index-apis/segment.md
Labels: 4 - Doc review, backport 2.16

#7859 Add documentation for ignore_hosts config option for ip-based rate limiting
  _security/configuration/api-rate-limiting.md
Labels: 4 - Doc review, release-notes, v2.17.0

#7861 OpenJDK Update (July 2024 Patch releases)
  _install-and-configure/install-opensearch/index.md
Labels: v2.17.0

#7975 Fix links in Operations reference
  _benchmark/reference/workloads/operations.md
Labels: 4 - Doc review, backport 2.16

#7972 Add IP option to SAN certificate
  _security/configuration/generate-certificates.md
Labels: 3 - Tech review, backport 2.16

#7992 Add missing link to Get model group API
  _ml-commons-plugin/api/model-group-apis/index.md
Labels: 4 - Doc review

#7656 Adding search shard routing docs
  _install-and-configure/configuring-opensearch/cluster-settings.md
  _search-plugins/searching-data/search-shard-routing.md
Labels: 5 - Editorial review, search-and-query, backport 2.15

#7989 Correcting contradictions on SecurityAdmin.sh port
  _security/configuration/security-admin.md
  _troubleshoot/security-admin.md
Labels: 4 - Doc review, backport 2.16

#7904 Remove composite agg limitations for concurrent search
  _search-plugins/concurrent-segment-search.md
Labels: release-notes, v2.17.0

#7987 Add documentation for v2 neural sparse models
  _ml-commons-plugin/agents-tools/tools/neural-sparse-tool.md
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/pretrained-models.md
  _search-plugins/neural-sparse-with-pipelines.md
Labels: 5 - Editorial review, backport 2.16

#8040 Adding that comma seperated lists of indices are supported.
  _api-reference/cluster-api/cluster-health.md
Labels: backport 2.16

#7664 Adding retrieve specific fields docs
  _search-plugins/searching-data/index.md
  _search-plugins/searching-data/retrieve-specific-fields.md
Labels: 5 - Editorial review, search-and-query, backport 2.15

#8024 Fixed incorrect use of single quotes in the install OpenSearch guide.
  _install-and-configure/install-opensearch/docker.md
Labels: 3 - Tech review, backport 2.16

#7390 Add validate API
  _api-reference/validate.md
Labels: API, 5 - Editorial review, backport 1.3, Content gap, backport 2.16

#8051 Update Lucene max_dimension
  _search-plugins/vector-search.md
Labels: 3 - Tech review, backport 2.16

#8078 Remove Split Response Processor from 2.16 Search Pipeline docs
  _search-plugins/search-pipelines/search-processors.md
  _search-plugins/search-pipelines/split-processor.md
Labels: 4 - Doc review

#8081 Add Split Response Processor to 2.17 Search Pipeline docs
  _search-plugins/search-pipelines/search-processors.md
  _search-plugins/search-pipelines/split-processor.md
Labels: 4 - Doc review, release-notes, v2.17.0

#7677 Adding inner hits docs
  _search-plugins/searching-data/index.md
  _search-plugins/searching-data/inner-hits.md
Labels: 4 - Doc review, search-and-query, backport 2.16

#8084 Fix broken external links
  _data-prepper/pipelines/configuration/sinks/s3.md
Labels: 4 - Doc review, backport 2.16

#8090 Add 1.3.19 to version history
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16

#8076 Added documentation for FGAC for Flow Framework
  .github/vale/styles/Vocab/OpenSearch/Words/accept.txt
  _automating-configurations/api/index.md
  _automating-configurations/index.md
  _automating-configurations/workflow-security.md
Labels: release-notes, v2.17.0

#8088 Add joining queries index page
  _query-dsl/joining/index.md
  _query-dsl/term/fuzzy.md
  _query-dsl/term/prefix.md
  _query-dsl/term/range.md
  _query-dsl/term/regexp.md
  _query-dsl/term/wildcard.md
Labels: backport 2.16

#8114 Refactor OpenSearch/Dashboards front page
  _about/index.md
  _getting-started/intro.md
  _ml-commons-plugin/index.md
  _search-plugins/index.md
Labels: backport 2.16

#7800 Updating data sources docs # 7680
  _dashboards/management/connect-prometheus.md
  _dashboards/management/data-sources.md
  images/dashboards/data-source-UI.png
  images/dashboards/delete-data-source.png
Labels: 5 - Editorial review, security, backport 2.16

#6933 Add metadata fields for mappings (content gap initiative)
  _field-types/index.md
  _field-types/mappings-use-cases.md
  _field-types/metadata-fields/field-names.md
  _field-types/metadata-fields/id.md
  _field-types/metadata-fields/ignored.md
  _field-types/metadata-fields/index-metadata.md
  _field-types/metadata-fields/index.md
  _field-types/metadata-fields/meta.md
  _field-types/metadata-fields/routing.md
  _field-types/metadata-fields/source.md
Labels: 5 - Editorial review, Content gap, backport 2.16

#8126 Restructuring of the file 'Modifying the YAML files'
  _security/configuration/yaml.md
Labels: 4 - Doc review, backport 2.16

#8109 Revise Amazon S3 data source
  _dashboards/management/S3-data-source.md
Labels: 5 - Editorial review, backport 2.16
