Repository opensearch-project/documentation-website, pull requests merged in 2024-05, with the labels that each got.

#6984 Add understanding results page
  _benchmark/user-guide/understanding-results.md
Labels: 5 - Final Editorial Review, benchmark, backport 2.13

#7033 Add cluster setting for filter rewrite optimization in aggregation
  _install-and-configure/configuring-opensearch/search-settings.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7072 Fixed bug in nav pane - paginate results
  _search-plugins/searching-data/paginate.md
Labels: 4 - Doc Review, backport 2.13

#7026 Update csp configuration instructions for OSD
  _dashboards/csp/csp-dynamic-configuration.md
  images/dashboards/copy-as-curl.png
Labels: 5 - Final Editorial Review, v2.14.0

#6958 adding do_not_fail_on_forbidden section to docs #4896
  _security/access-control/permissions.md
Labels: security, backport 2.13

#7045 fix overlap_rate data type
  _ingest-pipelines/processors/text-chunking.md
Labels: 3 - Tech Review, backport 2.13

#7066 adding kibana_server role specification and explanation #4094
  _security/multi-tenancy/multi-tenancy-config.md
Labels: 5 - Final Editorial Review, backport 2.13

#7015 expanding on TrustStore and KeyStore #4578 #4060
  _security/configuration/generate-certificates.md
  _security/configuration/opensearch-keystore.md
  _security/configuration/security-admin.md
Labels: security, backport 2.13

#7059 Add documentation for primary rebalancing
  _install-and-configure/configuring-opensearch/cluster-settings.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7087 Add missing path to /stats/ API.
  _api-reference/index-apis/stats.md
Labels: backport 1.3, 4 - Doc Review, backport 2.13

#7079 Add missing OPENSEARCH_INITIAL_ADMIN_PASSWORD for both apt/deb and yum/rpm
  _install-and-configure/install-opensearch/debian.md
  _install-and-configure/install-opensearch/rpm.md
Labels: 5 - Final Editorial Review, backport 2.12, backport 2.13

#7080 Flow Framework documentation for no-op step delay
  _automating-configurations/workflow-steps.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7101 Minor documentation correction for 2.14.0
  _field-types/supported-field-types/date.md
  _install-and-configure/configuring-opensearch/network-settings.md
Labels: 4 - Doc Review, release-notes, v2.14.0

#7057 Add documentation for settings introduced in 2.14
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7078 Adding document for setting introduced : cluster.remote_store.translo…
  _tuning-your-cluster/availability-and-recovery/remote-store/index.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7030 Add documentation for k-NN clear cache api
  _field-types/supported-field-types/knn-vector.md
  _search-plugins/knn/api.md
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-index.md
  _search-plugins/multimodal-search.md
  _search-plugins/semantic-search.md
Labels: 4 - Doc Review, release-notes, v2.14.0

#7053 Updated documentation for using search pipeline for multiple indices
  _search-plugins/search-pipelines/using-search-pipeline.md
Labels: 5 - Final Editorial Review, v2.14.0

#7095 Add ml inference ingest processor documentation
  _ingest-pipelines/processors/ml-inference.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7103 feat: add index.search.default_pipeline setting
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 4 - Doc Review, backport 2.13

#7056 Add Async Batch Shard Settings
  _install-and-configure/configuring-opensearch/cluster-settings.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7109 Remove Port 9250; Change 9300 to include CCS
  _install-and-configure/install-opensearch/index.md
Labels: 4 - Doc Review, backport 2.13

#7052 Add cache plugin and tiered cache documentation
  _search-plugins/caching/index.md
  _search-plugins/caching/tiered-cache.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7086 Add draft doc for model interface
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/api/model-apis/update-model.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7083 Update documentation for automatic model undeployment
  _ml-commons-plugin/api/model-apis/undeploy-model.md
  _ml-commons-plugin/remote-models/index.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7050 Add k-NN radial search doc
  _query-dsl/specialized/neural.md
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/radial-search-knn.md
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7122 Fix broken external links
  _im-plugin/index-codecs.md
  _ml-commons-plugin/remote-models/blueprints.md
  _ml-commons-plugin/remote-models/connectors.md
Labels: 4 - Doc Review, backport 2.13

#7042 Clarify that initial_cluster_manager_nodes uses node name
  _tuning-your-cluster/index.md
Labels: 4 - Doc Review, backport 2.13

#6928 Adds advanced settings descriptions
  _dashboards/management/advanced-settings.md
  _dashboards/quickstart.md
  images/dashboards/add-dash-panel.png
  images/dashboards/add-sample.png
  images/dashboards/advanced-settings-ui.png
  images/dashboards/advanced-settings.png
  images/dashboards/airline-carrier.gif
  images/dashboards/appearance-home.png
  images/dashboards/filter-data-dash.png
  images/dashboards/home-page-nav.png
  images/dashboards/navigation-pane.png
  images/icons/theme-icon.png
  images/theme-icon.png
Labels: 5 - Final Editorial Review, release-notes, v2.14.0

#7121 Add documentation for remote store migration
  _tuning-your-cluster/availability-and-recovery/remote-store/migrating-to-remote.md
Labels: 5 - Final Editorial Review, release-notes, experimental, v2.14.0

#7136 Fix broken image
  _dashboards/management/advanced-settings.md
  images/dashboards/advanced-settings.png
Labels: v2.14.0

#6866 Added documentation for printing associated queries, and sample documents in notification message.
  _observing-your-data/alerting/triggers.md
Labels: 5 - Final Editorial Review, backport 2.13

#7039 Update the example of the multiple terms aggregation by muliple orders.
  _aggregations/bucket/multi-terms.md
Labels: 4 - Doc Review, backport 2.13

#7138 Updating security reachout email
  README.md
Labels: 4 - Doc Review, backport 2.13

#7112 add documentation for get model group API
  _ml-commons-plugin/api/model-group-apis/delete-model-group.md
  _ml-commons-plugin/api/model-group-apis/get-model-group.md
  _ml-commons-plugin/api/model-group-apis/search-model-group.md
Labels: 4 - Doc Review, backport 2.12, backport 2.13

#7149 Fix ordered list
  _security/configuration/demo-configuration.md
Labels: 4 - Doc Review, backport 2.13

#7152 Remove appearance theme home page section
  _dashboards/quickstart.md
Labels: v2.14.0

#6954 Add Refresh API
  _api-reference/index-apis/refresh.md
Labels: 5 - Final Editorial Review, backport 1.3, backport 2.13

#7159 Alerting plugin - GA cross cluster monitor support documentation
  _observing-your-data/alerting/per-cluster-metrics-monitors.md
  _observing-your-data/alerting/per-query-bucket-monitors.md
  _observing-your-data/alerting/settings.md
  _security/access-control/permissions.md
  images/alerting/cross-cluster-cluster-metrics-monitors.png
  images/alerting/cross-cluster-per-query-per-bucket-monitors.png
Labels: 4 - Doc Review, backport 2.14

#7134 adding server.host to demo dashboards configuration #3884
  _install-and-configure/install-dashboards/tls.md
Labels: 3 - Done, backport 2.14

#6952 adding proxy configuration #20231107 #20230503 in 4314 issue
  _search-plugins/cross-cluster-search.md
Labels: security, 3 - Done, backport 2.14

#7179 Fix liquid syntax errors
  _observing-your-data/alerting/triggers.md
Labels: backport 2.14

#7173 adding http.detailed_error.enabled configuration docs #3084
  _install-and-configure/configuring-opensearch/security-settings.md
Labels: security, 4 - Doc Review, backport 2.14

#7186 Fix link on workload page
  _benchmark/reference/workloads/index.md
Labels: 4 - Doc Review, backport 2.14

#7187 Add new Benchmark workflow image
  _benchmark/index.md
  images/benchmark/OSB-workflow.png
  images/benchmark/osb-workflow.jpg
Labels: 4 - Doc Review, backport 2.14

#7084 Update distributed-tracing.md
  _observing-your-data/trace/distributed-tracing.md
Labels: 3 - Done, backport 2.14

#7038 Correct docker-compose demo docs
  _security/configuration/demo-configuration.md
Labels: 3 - Tech Review, backport 2.14

#7171 Update multi-data-sources.md with valid example for connection URL
  _dashboards/management/multi-data-sources.md
Labels: 3 - Tech Review, backport 2.14

#7218 Fix hyperlink URL for monitors doc
  _observing-your-data/alerting/index.md
Labels: backport 1.3, backport 2.14

#7130 Adding missing Lucene versions
  _install-and-configure/upgrade-opensearch/index.md
Labels: 3 - Tech Review

#7223 Remove incorrectly used `cpu` prefix from nodes stats os related metrics
  _api-reference/nodes-apis/nodes-stats.md
Labels: backport 2.14

#7216 adding new zip and updaing docs for ldap #1365
  _security/authentication-backends/ldap.md
  assets/examples/ldap-example-v2.13.zip
  assets/examples/ldap-example-v2.zip
  assets/examples/ldap-example.zip
Labels: 3 - Tech Review, security, backport 2.14

#7215 Adding immutable indices docs
  _install-and-configure/configuring-opensearch/security-settings.md
Labels: security, 4 - Doc Review, backport 2.14

#7221 Update users-roles.md
  _security/access-control/users-roles.md
Labels: backport 1.3, backport 2.14

#7226 Cleanup of thread_pool metric group in nodes stats documentation
  _api-reference/nodes-apis/nodes-stats.md
Labels: 4 - Doc Review, backport 2.14

#7235 Add documentation for `constant_keyword` field type
  _field-types/supported-field-types/constant-keyword.md
  _field-types/supported-field-types/string.md
Labels: backport 2.14

#7137 Adds documentation for DocumentDB as a source.
  _data-prepper/pipelines/configuration/sources/documentdb.md
Labels: data-prepper 2.8, backport 2.14

#7256 Correct constant keyword example
  _field-types/supported-field-types/constant-keyword.md
Labels: backport 2.14

#5981 Add foreach processor documentation
  _ingest-pipelines/processors/foreach.md
Labels: 5 - Final Editorial Review, Needs SME, Content gap, backport 2.14

#7265 Add doc review changes to contributor's blocked PR #6808
  _aggregations/metric/median-absolute-deviation.md
Labels: backport 2.14

#7262 Update knn-vector-quantization.md
  _search-plugins/knn/knn-vector-quantization.md
Labels: 4 - Doc Review, backport 2.14

#7269 Update documentation to add skills plugin to bundled plugins
  _install-and-configure/plugins.md
Labels: backport 2.14

#5985 [DOC] Add join processor documentation
  _ingest-pipelines/processors/join.md
Labels: Content gap, backport 2.14

#7113 Security best practices - 10 points to consider - #5782
  _security/configuration/best-practices.md
Labels: 5 - Final Editorial Review, security, backport 2.14

#7194 Explain k in approximate k-NN
  _search-plugins/knn/approximate-knn.md
Labels: 4 - Doc Review, backport 2.14
