Repository opensearch-project/documentation-website, pull requests merged in 2025-03, with the labels that each got.

#9339 Add knn.faiss.avx512_spr.disabled to settings documentation
  _search-plugins/knn/settings.md
Labels: backport 2.19

#9347 Migration Assistant supports Elasticsearch 5.6
  _migration-assistant/is-migration-assistant-right-for-you.md
Labels: backport 2.19

#9305 Star tree documentation fixes
  _field-types/supported-field-types/star-tree.md
  _search-plugins/star-tree-index.md
Labels: 5 - Editorial review, backport 2.19

#9353 Update title for text chunking tutorial
  _vector-search/tutorials/semantic-search/long-document.md
Labels: backport 2.19

#9357 Add last ML tutorials
  _ml-commons-plugin/using-ml-models.md
  _vector-search/tutorials/conversational-search/conversational-search-claude-bedrock.md
  _vector-search/tutorials/conversational-search/conversational-search-cohere.md
  _vector-search/tutorials/conversational-search/conversational-search-openai.md
  _vector-search/tutorials/conversational-search/index.md
  _vector-search/tutorials/index.md
Labels: backport 2.19

#9356 Vector Search Tutorials: fix link of RAG Chatbot not working
  _vector-search/tutorials/index.md
Labels: backport 2.19

#9355 Fix Anamoly detection JSON formatting.
  _observing-your-data/ad/index.md
Labels: 4 - Doc review, backport 2.19

#9361 Refactor ML landing pages
  _ml-commons-plugin/agents-tools/index.md
  _ml-commons-plugin/algorithms.md
  _ml-commons-plugin/api/index.md
  _ml-commons-plugin/cluster-settings.md
  _ml-commons-plugin/index.md
  _ml-commons-plugin/integrating-ml-models.md
  _ml-commons-plugin/ml-dashboard.md
  _ml-commons-plugin/remote-models/index.md
  _ml-commons-plugin/using-ml-models.md
Labels: backport 2.19

#9343 Add tutorial for creating Bedrock connector using Cloud Formation template
  _vector-search/tutorials/index.md
  _vector-search/tutorials/semantic-search/index.md
  _vector-search/tutorials/semantic-search/semantic-search-cfn-bedrock.md
  images/vector-search-tutorials/semantic_search_bedrock_integration_1.png
  images/vector-search-tutorials/semantic_search_bedrock_integration_2.png
Labels: backport 2.19

#9376 nit: Fix typos. Update field-masking.md
  _security/access-control/field-masking.md
Labels: backport 2.19

#9384 Fix link and reorder pages in the tutorials section
  _tutorials/index.md
  _tutorials/vector-search/rag/conversational-search-claude-bedrock.md
  _tutorials/vector-search/rag/conversational-search-cohere.md
  _tutorials/vector-search/rag/conversational-search-openai.md
Labels: backport 2.19

#9363 Update for MIGRATIONS-2268
  _migration-assistant/migration-phases/planning-your-migration/handling-type-mapping-deprecation.md
Labels: backport 2.19

#9362 Adding reference to predefined templates in AI search
  _automating-configurations/workflow-templates.md
  _ingest-pipelines/processors/sparse-encoding.md
  _ingest-pipelines/processors/text-embedding.md
  _ingest-pipelines/processors/text-image-embedding.md
  _query-dsl/compound/hybrid.md
  _search-plugins/search-pipelines/explanation-processor.md
  _search-plugins/search-pipelines/normalization-processor.md
  _search-plugins/search-pipelines/rag-processor.md
  _search-plugins/search-pipelines/score-ranker-processor.md
  _tutorials/gen-ai/ai-search-flows/building-flows.md
  _tutorials/gen-ai/model-controls/bedrock-guardrails.md
  _tutorials/reranking/reranking-by-field.md
  _tutorials/vector-search/neural-search-tutorial.md
  _tutorials/vector-search/semantic-search/semantic-search-asymmetric.md
  _tutorials/vector-search/semantic-search/semantic-search-bedrock-cohere.md
  _tutorials/vector-search/semantic-search/semantic-search-bedrock-titan-other.md
  _tutorials/vector-search/semantic-search/semantic-search-bedrock-titan.md
  _tutorials/vector-search/semantic-search/semantic-search-cfn-bedrock.md
  _tutorials/vector-search/semantic-search/semantic-search-cfn-sagemaker.md
  _tutorials/vector-search/semantic-search/semantic-search-cohere.md
  _tutorials/vector-search/semantic-search/semantic-search-openai.md
  _tutorials/vector-search/semantic-search/semantic-search-sagemaker.md
  _tutorials/vector-search/vector-operations/generate-embeddings.md
  _tutorials/vector-search/vector-operations/semantic-search-byte-vectors.md
  _vector-search/ai-search/conversational-search.md
  _vector-search/ai-search/hybrid-search/index.md
  _vector-search/ai-search/multimodal-search.md
  _vector-search/ai-search/semantic-search.md
  _vector-search/ai-search/workflow-builder.md
  _vector-search/optimizing-storage/disk-based-vector-search.md
Labels: backport 2.19

#9429 fix typo
  DEVELOPER_GUIDE.md
Labels: backport 2.19

#9382 Remove references to PLUGGABLE_CACHING feature flag
  _search-plugins/caching/index.md
  _search-plugins/caching/tiered-cache.md
Labels: v3.0.0

#9302 Add target_index_settings to rollup documentation
  _im-plugin/index-rollups/rollup-api.md
  _im-plugin/ism/policies.md
Labels: v3.0.0, 6 - Done but waiting to merge

#9154 Remove transport-nio plugin documentation
  _install-and-configure/additional-plugins/index.md
  _install-and-configure/configuring-opensearch/network-settings.md
Labels: v3.0.0, 6 - Done but waiting to merge, release-notes

#9433 Add canonical links to top-level files
  breaking-changes.md
  version-history.md
Labels: backport 1.1, backport 1.0

#9369 Update API rate limiting docs with support for CIDR ranges in ignore_hosts
  _security/configuration/api-rate-limiting.md
Labels: v3.0.0, 3 - Tech review

#6715 Add index.query.max_nested_depth=20 in 3.0
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: v3.0.0

#9438 Fix link for sparse search
  _vector-search/index.md
Labels: backport 2.19

#9393 Expands on which queries are cacheable in RC
  _search-plugins/caching/request-cache.md
Labels: 5 - Editorial review, backport 2.19

#9374 Adds documentation for new tiered spillover cache policy setting
  _search-plugins/caching/tiered-cache.md
Labels: v3.0.0, 5 - Editorial review

#9375 Added lower_bounds param to normalization processor section
  .vale.ini
  _search-plugins/search-pipelines/normalization-processor.md
Labels: v3.0.0, 5 - Editorial review

#9432 Add derived setting for knn indices
  _query-dsl/specialized/k-nn.md
  _vector-search/settings.md
Labels: 5 - Editorial review, backport 2.19

#9425 adding stemming docs #9423
  _analyzers/stemming.md
Labels: 4 - Doc review, Content gap, backport 2.19

#9440 Add 3.0 breaking changes
  _about/breaking-changes.md
  _vector-search/settings.md
Labels: v3.0.0

#9373 Add tasks API section
  _api-reference/tasks.md
  _api-reference/tasks/cancel-tasks.md
  _api-reference/tasks/get-tasks.md
  _api-reference/tasks/list-tasks.md
  _api-reference/tasks/tasks.md
Labels: 5 - Editorial review, backport 2.19

#9420 Update extended_stats aggregation.
  _aggregations/metric/extended-stats.md
Labels: 5 - Editorial review, Content gap, backport 2.19

#9141 Add Vector Search workload to benchmark
  _benchmark/workloads/vectorsearch.md
Labels: 5 - Editorial review, benchmark, backport 2.19

#9419 Update cardinality aggregation.
  _aggregations/metric/cardinality.md
Labels: Content gap, backport 2.19

#9456 Explicitly call cardinality aggregation metric aggregation
  _aggregations/metric/cardinality.md
Labels: backport 2.19

#9461 Add a command quick reference to DQL page
  _dashboards/dql.md
  images/dashboards/dql-interface.png
Labels: backport 2.19

#9464 Add analysis paragraph to the DQL page
  _dashboards/dql.md
Labels: backport 2.19

#9471 Add redirects to remaining vector pages
  _tutorials/index.md
  _vector-search/ai-search/workflow-builder.md
Labels: backport 2.19

#9437 Updated min and max aggregations.
  _aggregations/metric/maximum.md
  _aggregations/metric/minimum.md
Labels: Content gap, backport 2.19

#9394 Update avg aggregation
  _aggregations/metric/average.md
Labels: Content gap, backport 2.19

#9486 Update minimum length of `plugins.security.compliance.salt` parameter as in implementation
  _security/access-control/field-masking.md
Labels: backport 2.19

#9487 Fix 'stored_fields' parameter on GetDocument API
  _api-reference/document-apis/get-documents.md
Labels: 4 - Doc review, backport 2.19

#9480 Adds documentation for z score
  _search-plugins/search-pipelines/normalization-processor.md
Labels: v3.0.0

#9483 add documentation for skip_existing feature for text embedding processor
  _ingest-pipelines/processors/text-embedding.md
Labels: v3.0.0

#9492 Update ML inference processor pipeline syntax
  _search-plugins/search-pipelines/ml-inference-search-request.md
  _search-plugins/search-pipelines/ml-inference-search-response.md
Labels: backport 2.16, backport 2.17, backport 2.18, backport 2.19

#9496 Fix error in Query Insights health stats sample response
  _observing-your-data/query-insights/health.md
Labels: backport 2.19

#9498 add documentation for skip_existing feature for sparse encoding processor
  _ingest-pipelines/processors/sparse-encoding.md
Labels: v3.0.0

#9502 Pretty print JSON examples in _list APIs
  _api-reference/list/index.md
  _api-reference/list/list-indices.md
  _api-reference/list/list-shards.md
Labels: backport 2.19

#9504 Typo fix - Replace LDAP with internal
  _security/configuration/index.md
Labels: backport 2.19

#9463 Add performance testing best practices
  _benchmark/user-guide/optimizing-benchmarks/performance-testing-best-practices.md
Labels: 5 - Editorial review, benchmark, backport 2.19

#9510 Remove tutorials section from Benchmark
  _benchmark/index.md
  _benchmark/tutorials/index.md
  _benchmark/tutorials/sigv4.md
  _benchmark/user-guide/install-and-configure/configuring-benchmark.md
Labels: 4 - Doc review, benchmark, backport 2.19

#9427 Add additional workloads to choosing a workload page
  _benchmark/user-guide/understanding-workloads/choosing-a-workload.md
Labels: 5 - Editorial review, backport 2.19

#8371 Add 'Clone Snapshot' API Documentation
  _api-reference/snapshots/clone-snapshot.md
Labels: 5 - Editorial review, backport 2.19

#9453 Update median_absolute_deviation aggregation.
  _aggregations/metric/median-absolute-deviation.md
Labels: Content gap, backport 2.19

#9519 Fix URI paths for cluster stats filtering
  _api-reference/cluster-api/cluster-stats.md
Labels: backport 2.19
