Repository opensearch-project/documentation-website, pull requests merged in 2025-05, with the labels that each got.

#9791 Added documentation for settings limiting total shards and primary shards per node at both cluster and index level.
  _install-and-configure/configuring-opensearch/cluster-settings.md
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: v3.0.0, 4 - Doc review, release-notes

#9797 Improve percentiles agg documentation
  _aggregations/metric/percentile-ranks.md
  _aggregations/metric/percentile.md
Labels: backport 2.19

#9768 remove experimental for batch_predict and deprecate the async batch i…
  _ml-commons-plugin/api/async-batch-ingest.md
  _ml-commons-plugin/api/model-apis/batch-predict.md
  _ml-commons-plugin/remote-models/async-batch-ingestion.md
Labels: v3.0.0, 4 - Doc review, release-notes

#9762 Add new `_scale` API as part of OpenSearch Reader/Writer Separation
  _api-reference/index-apis/scale.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9804 Add Warm node role for searchable snapshots
  _about/breaking-changes.md
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
  _tuning-your-cluster/index.md
Labels: breaking, v3.0.0, 3 - Tech review, release-notes

#9739 Enable concurrent segment search by default for 3.0 release
  _search-plugins/concurrent-segment-search.md
Labels: v3.0.0, release-notes

#9810 Add transport-grpc to list of additional plugins
  _install-and-configure/additional-plugins/index.md
Labels: v3.0.0

#9603 Add semantic highlighter related docs
  _ml-commons-plugin/pretrained-models.md
  _search-plugins/searching-data/highlight.md
  _tutorials/vector-search/index.md
  _tutorials/vector-search/semantic-highlighting-tutorial.md
Labels: v3.0.0, 6 - Done but waiting to merge, release-notes

#9800 Add mcp server in opensearch documentation
  _ml-commons-plugin/agents-tools/tools/index.md
  _ml-commons-plugin/agents-tools/tools/list-index-tool.md
  _ml-commons-plugin/api/agent-apis/index.md
  _ml-commons-plugin/api/async-batch-ingest.md
  _ml-commons-plugin/api/controller-apis/index.md
  _ml-commons-plugin/api/execute-algorithm.md
  _ml-commons-plugin/api/index.md
  _ml-commons-plugin/api/mcp-server-apis/index.md
  _ml-commons-plugin/api/mcp-server-apis/register-mcp-tools.md
  _ml-commons-plugin/api/mcp-server-apis/remove-mcp-tools.md
  _ml-commons-plugin/api/mcp-server-apis/sse-message.md
  _ml-commons-plugin/api/mcp-server-apis/sse-session.md
  _ml-commons-plugin/api/memory-apis/index.md
  _ml-commons-plugin/api/profile.md
  _ml-commons-plugin/api/stats.md
  _ml-commons-plugin/api/tasks-apis/index.md
Labels: v3.0.0, 6 - Done but waiting to merge, release-notes

#9795 Adding reader writer separation doc page
  _tuning-your-cluster/seperate-index-and-search-workloads.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9813 [Workload Management] Rename query group to workload group
  _about/breaking-changes.md
  _tuning-your-cluster/availability-and-recovery/workload-management/query-group-lifecycle-api.md
  _tuning-your-cluster/availability-and-recovery/workload-management/wlm-feature-overview.md
  _tuning-your-cluster/availability-and-recovery/workload-management/workload-group-lifecycle-api.md
Labels: breaking, v3.0.0, 4 - Doc review, release-notes

#9812 keyword/numeric terms and range aggregation support
  _search-plugins/star-tree-index.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9801 [rule-based autotagging] Add rule lifecycle api documentation
  _tuning-your-cluster/availability-and-recovery/rule-based-autotagging/rule-lifecycle-api.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9598 Refactor pipeline aggregations
  .github/workflows/.delete_backport_branch.yml.swp
  _aggregations/pipeline-agg.md
  _aggregations/pipeline/index.md
Labels: Content gap, backport 2.19

#9815 More updates on 3.0 keys and versions
  _install-and-configure/install-dashboards/debian.md
  _install-and-configure/install-opensearch/debian.md
Labels: upcoming release, v3.0.0

#9809 Adding documentation for append only indices
  _im-plugin/append-only-index.md
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: v3.0.0, 4 - Doc review, release-notes

#9825 Add boolean query support by star tree
  _search-plugins/star-tree-index.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9827 Update the doc with `search_only` block which is part of OpenSearch Reader/Writer Separation
  _api-reference/index-apis/blocks.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9706 Add behavior of delete snapshot for an in progress snapshot
  _api-reference/snapshots/delete-snapshot.md
Labels: backport 2.19

#9832 Fix MCP API navigation
  _ml-commons-plugin/api/mcp-server-apis/register-mcp-tools.md
  _ml-commons-plugin/api/mcp-server-apis/remove-mcp-tools.md
  _ml-commons-plugin/api/mcp-server-apis/sse-message.md
  _ml-commons-plugin/api/mcp-server-apis/sse-session.md
Labels: backport 3.0

#9764 Add LogPatternTool document
  _ml-commons-plugin/agents-tools/tools/log-pattern-tool.md
Labels: backport 3.0

#9838 Point version history for previous versions to latest version
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 1.2, backport 1.1, backport 1.0, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18

#9851 Point version history to latest for 2.5
  _about/version-history.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 1.2, backport 1.1, backport 1.0, backport 2.3, backport 2.4

#9858 Propagate 9851 to 1.2
  version-history.md
Labels: backport 1.1, backport 1.0

#9862 Remove plugin verbiage and fix image links in query insights
  _observing-your-data/query-insights/query-insights-dashboard.md
Labels: backport 3.0

#9799 Update Query Insights grouping setting names
  _observing-your-data/query-insights/grouping-top-n-queries.md
Labels: release-notes, v3.1.0

#9828 Update the `search_only` mode section with more details and recovery scenarios
  _tuning-your-cluster/seperate-index-and-search-workloads.md
Labels: 5 - Editorial review, backport 3.0

#9875 Add back Rule Lifecycle API to main
  _tuning-your-cluster/availability-and-recovery/rule-based-autotagging/rule-lifecycle-api.md
Labels: 4 - Doc review, release-notes, v3.1.0

#9877 Remove OSB abbreviation from creating custom workloads
  _benchmark/user-guide/working-with-workloads/creating-custom-workloads.md
Labels: benchmark, backport 3.0

#9885 Fix Spec insert bug
  _api-reference/security/authentication/change-password.md
Labels: backport 3.0

#9886 Update Migration Assistant support for OpenSearch 3.0
  _data/migration-assistant/breaking-changes.yml
  _data/migration-assistant/valid_migrations.yml
Labels: backport 3.0

#9889 Update blueprints.md
  _ml-commons-plugin/remote-models/blueprints.md
Labels: backport 3.0

#9871 Add more security configuration APIs
  _api-reference/security/configuration/get-configuration.md
  _api-reference/security/configuration/index.md
  _api-reference/security/configuration/patch-configuration.md
  _api-reference/security/configuration/update-configuration.md
Labels: API, 5 - Editorial review, backport 3.0

#9864 add documentation for redline QPS feature in OSB
  _benchmark/reference/commands/redline-test.md
  images/benchmark/osb-actor-system.png
Labels: 4 - Doc review, benchmark, backport 3.0

#9896 Fix liquid syntax error
  _benchmark/reference/commands/redline-test.md
Labels: backport 3.0

#9637 Add derivative pipeline aggregation.
  _aggregations/pipeline/derivative.md
Labels: 6 - Done but waiting to merge, Content gap, backport 3.0

#9905 removing alerting comments experimental banner
  _observing-your-data/alerting/api.md
  _observing-your-data/alerting/comments.md
Labels: 4 - Doc review, backport 3.0

#9910 Add redirect for file name change
  _tuning-your-cluster/separate-index-and-search-workloads.md
Labels: backport 3.0

#9923 Fix an incorrect url path
  _vector-search/creating-vector-index.md
Labels: backport 3.0

#9625 adding conditional execution in ingest pipeline docs
  _ingest-pipelines/conditional-execution.md
  _ingest-pipelines/index.md
Labels: Content gap, backport 3.0

#9569 adding position_increment_gap mapping parameter docs
  _field-types/mapping-parameters/position-increment-gap.md
Labels: Content gap, backport 3.0

#9541 adding index prefix mapping parameter documentation
  _field-types/mapping-parameters/index-prefixes.md
Labels: Content gap, backport 3.0

#9538 adding index phrases mapping parameter docs
  _field-types/mapping-parameters/index-phrases.md
  _field-types/mapping-parameters/index.md
Labels: Content gap, backport 3.0

#9931 [DOC] Add query-insights-dashboards plugin
  _install-and-configure/install-dashboards/plugins.md
Labels: 4 - Doc review, backport 3.0

#9738 Add bucket_script and bucket_selector pipeline aggregations.
  _aggregations/pipeline/bucket-script.md
  _aggregations/pipeline/bucket-selector.md
Labels: 3 - Tech review, Content gap, backport 3.0

#9922 Custom weights in rrf processor
  _search-plugins/search-pipelines/score-ranker-processor.md
Labels: release-notes, v3.1.0

#9942 add redline test flags to documentation
  _benchmark/reference/commands/redline-test.md
Labels: backport 3.0

#9673 Add serial_diff pipeline aggregation.
  _aggregations/pipeline/index.md
  _aggregations/pipeline/serial-diff.md
  images/serial-diff-agg-result.png
Labels: 6 - Done but waiting to merge, Content gap, backport 3.0

#9915 Add neural sparse new models to doc
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/pretrained-models.md
  _query-dsl/specialized/neural-sparse.md
  _vector-search/ai-search/neural-sparse-with-pipelines.md
Labels: backport 3.0

#9826 Add rare_terms bucket aggregation
  _aggregations/bucket/index.md
  _aggregations/bucket/rare-terms.md
  _aggregations/bucket/terms.md
  _aggregations/pipeline/bucket-script.md
  _aggregations/pipeline/bucket-selector.md
  _aggregations/pipeline/serial-diff.md
  _aggregations/pipeline/stats-bucket.md
Labels: 6 - Done but waiting to merge, Content gap

#9796 Add moving_fn pipeline aggregation
  _aggregations/pipeline/moving-function.md
Labels: 6 - Done but waiting to merge, Content gap, backport 3.0

#9599 Add basic (single) pipeline bucket stats.
  _aggregations/pipeline/avg-bucket.md
  _aggregations/pipeline/max-bucket.md
  _aggregations/pipeline/min-bucket.md
  _aggregations/pipeline/sum-bucket.md
Labels: 3 - Tech review, Content gap, backport 3.0

#9793 Document that the unified highlighter supports matched_field
  _search-plugins/searching-data/highlight.md
Labels: release-notes, v3.1.0

#9657 Add moving_avg pipeline aggregation.
  _aggregations/pipeline/index.md
  _aggregations/pipeline/moving-avg.md
Labels: 3 - Tech review, Content gap, backport 3.0

#9636 Add cumulative_sum pipeline aggregation.
  _aggregations/pipeline/cumulative-sum.md
Labels: 3 - Tech review, Content gap, backport 3.0

#9605 Add bucket_sort pipeline aggregation.
  _aggregations/pipeline/bucket-sort.md
  _aggregations/pipeline/index.md
Labels: 3 - Tech review, Content gap, backport 3.0

#9917 Add feedback on Parse JSON processor
  _data-prepper/pipelines/configuration/processors/parse-json.md
Labels: 5 - Editorial review, data-prepper, backport 3.0

#9963 Add editorial comments to bucket sort aggregation
  _aggregations/pipeline/bucket-sort.md
Labels: backport 3.0

#9966 Add Parse JSON editorial review
  _data-prepper/pipelines/configuration/processors/parse-json.md
Labels: backport 3.0

#9881 Add new thread pool settings for Flow Framework
  _automating-configurations/workflow-settings.md
Labels: 4 - Doc review, v3.1.0

#9894 Add content to Routes Processor
  _data-prepper/pipelines/configuration/processors/routes.md
Labels: 3 - Tech review, data-prepper, backport 3.0

#9938 adding script dsl query docs
  _query-dsl/specialized/index.md
  _query-dsl/specialized/script.md
Labels: Content gap, backport 3.0

#9984 Add a Search APIs section and refactor documentation
  _api-reference/analyze-apis.md
  _api-reference/analyze-apis/terminology.md
  _api-reference/cluster-api/remote-info.md
  _api-reference/index-apis/index.md
  _api-reference/search-apis/count.md
  _api-reference/search-apis/explain.md
  _api-reference/search-apis/index.md
  _api-reference/search-apis/msearch-template.md
  _api-reference/search-apis/multi-search.md
  _api-reference/search-apis/profile.md
  _api-reference/search-apis/rank-eval.md
  _api-reference/search-apis/render-template.md
  _api-reference/search-apis/scroll.md
  _api-reference/search-apis/search-template.md
  _api-reference/search-apis/search.md
  _api-reference/search-apis/validate.md
  _api-reference/security/index.md
Labels: backport 3.0

#9918 Add ef_ defaults for binary-quantized faiss index
  _field-types/supported-field-types/knn-methods-engines.md
Labels: 4 - Doc review, backport 3.0

#9990 Refactor ingest processor documentation
  _ingest-pipelines/processors/append.md
  _ingest-pipelines/processors/bytes.md
  _ingest-pipelines/processors/community_id.md
  _ingest-pipelines/processors/convert.md
  _ingest-pipelines/processors/copy.md
  _ingest-pipelines/processors/csv.md
  _ingest-pipelines/processors/date-index-name.md
  _ingest-pipelines/processors/date.md
  _ingest-pipelines/processors/dissect.md
  _ingest-pipelines/processors/dot-expander.md
  _ingest-pipelines/processors/drop.md
  _ingest-pipelines/processors/fail.md
  _ingest-pipelines/processors/fingerprint.md
  _ingest-pipelines/processors/foreach.md
  _ingest-pipelines/processors/grok.md
  _ingest-pipelines/processors/gsub.md
  _ingest-pipelines/processors/html-strip.md
  _ingest-pipelines/processors/join.md
  _ingest-pipelines/processors/json.md
  _ingest-pipelines/processors/kv.md
  _ingest-pipelines/processors/lowercase.md
  _ingest-pipelines/processors/ml-inference.md
  _ingest-pipelines/processors/pipeline.md
  _ingest-pipelines/processors/remove-by-pattern.md
  _ingest-pipelines/processors/remove.md
  _ingest-pipelines/processors/rename.md
  _ingest-pipelines/processors/script.md
  _ingest-pipelines/processors/set.md
  _ingest-pipelines/processors/sort.md
  _ingest-pipelines/processors/sparse-encoding.md
  _ingest-pipelines/processors/split.md
  _ingest-pipelines/processors/text-embedding.md
  _ingest-pipelines/processors/text-image-embedding.md
  _ingest-pipelines/processors/trim.md
  _ingest-pipelines/processors/uppercase.md
  _ingest-pipelines/processors/urldecode.md
  _ingest-pipelines/processors/user-agent.md
Labels: backport 3.0

#9975 Fix: The description of max_chunk_limit parameter in chunking
  _ingest-pipelines/processors/text-chunking.md
Labels: backport 3.0

#9995 Updated building-flows.md json that seems to be invalid while trying to build it
  _tutorials/gen-ai/ai-search-flows/building-flows.md
Labels: backport 3.0

#9998 Add missing plugin information to docs website
  _install-and-configure/plugins.md
Labels: enhancement, backport 3.0
