Repository opensearch-project/documentation-website, pull requests merged in 2025-07, with the labels that each got.

#10178 Update plugin list
  _install-and-configure/additional-plugins/index.md
Labels: backport 3.0, backport 3.1

#9747 updating standard analyzer docs
  _analyzers/supported-analyzers/standard.md
  _analyzers/token-filters/stop.md
  _api-reference/index-apis/alias.md
  _im-plugin/index-transforms/transforms-apis.md
  _search-plugins/sql/datatypes.md
  _search-plugins/sql/ppl/index.md
  _search-plugins/sql/sql-ppl-api.md
Labels: Content gap, backport 3.1

#9746 adding more_like_this query dsl docs
  _query-dsl/specialized/index.md
  _query-dsl/specialized/more-like-this.md
Labels: Content gap, backport 3.1

#9479 Add Composite aggregation page.
  _aggregations/bucket/composite.md
  _aggregations/bucket/date-histogram.md
  _aggregations/bucket/histogram.md
Labels: Content gap, backport 3.1

#10148 [Rule based auto tagging] Update 'Create workload group rules'
  _tuning-your-cluster/availability-and-recovery/rule-based-autotagging/rule-lifecycle-api.md
  _tuning-your-cluster/availability-and-recovery/workload-management/create-workload-group-rules-api.md
Labels: backport 3.1

#9798 adding percolate query dsl docs
  _field-types/supported-field-types/percolator.md
  _query-dsl/specialized/percolate.md
Labels: Content gap, backport 3.1

#10082 MigrationAssistant - Feature: Set desired count for proxies
  _migration-assistant/deploying-migration-assistant/configuration-options.md
Labels: backport 3.1

#9954 adding rewrite parameter docs
  _query-dsl/rewrite-parameter.md
Labels: Content gap, backport 3.1

#10196 Documented compression option for data prepper otel-logs-source sink
  _data-prepper/pipelines/configuration/sources/otel-logs-source.md
Labels: data-prepper, backport 3.1

#9927 adding rank_feature dsl query docs
  _query-dsl/specialized/index.md
  _query-dsl/specialized/rank-feature.md
Labels: Content gap, backport 3.1

#10124 adding docs for shard_stores api
  _api-reference/cluster-api/shard-stores.md
Labels: Done but waiting to merge, backport 3.1

#10159 adding voting_configuration_exclusion-api-docs
  _api-reference/cluster-api/cluster-voting-configuration-exclusions.md
Labels: Done but waiting to merge, Content gap, backport 3.1

#10252 Update field specified in query of hybrid search with search after
  _vector-search/ai-search/hybrid-search/search-after.md
Labels: backport 3.1

#10266 Add scripted_upsert to bulk and update document APIs
  _api-reference/document-apis/bulk.md
  _api-reference/document-apis/update-document.md
Labels: backport 3.1

#10261 Fix external links
  _about/index.md
  _developer-documentation/index.md
  _ml-commons-plugin/remote-models/supported-connectors.md
  _observing-your-data/prometheusmetrics.md
  _observing-your-data/trace/ta-dashboards.md
  _plugins/link-checker.rb
  _security/authentication-backends/openid-connect.md
  _tutorials/gen-ai/rag/rag-deepseek-r1-bedrock.md
  _tutorials/vector-search/semantic-search/semantic-search-cohere.md
Labels: backport 3.1

#10290 Correct parameter table for analyze API
  _api-reference/analyze-apis.md
Labels: backport 3.1

#10296 Consistently order term query pages
  _query-dsl/term/exists.md
  _query-dsl/term/fuzzy.md
  _query-dsl/term/ids.md
  _query-dsl/term/prefix.md
  _query-dsl/term/regexp.md
  _query-dsl/term/term.md
  _query-dsl/term/terms-set.md
  _query-dsl/term/terms.md
  _query-dsl/term/wildcard.md
Labels: backport 3.1

#10295 Add mapping parameters to completion fields
  _field-types/supported-field-types/completion.md
Labels: backport 3.1

#10286 Add security TLS settings to dashboards documentation
  _install-and-configure/install-dashboards/tls.md
Labels: backport 3.1

#10309 Update PHP client documentation, removing the ClientBuilder deprecated class
  _clients/php.md
Labels: backport 3.1

#10276 Add min and max threads parameters to tiered cache
  _search-plugins/caching/tiered-cache.md
Labels: backport 3.1

#10318 Reword installing tiered cache plugins
  _search-plugins/caching/tiered-cache.md
Labels: backport 3.1

#10322 Update semantic search examples
  _tutorials/vector-search/index.md
  _tutorials/vector-search/neural-search-tutorial.md
  _vector-search/getting-started/auto-generated-embeddings.md
Labels: backport 3.1

#10329 Fix typo with stage name in iam roles
  _migration-assistant/deploying-migration-assistant/iam-and-security-groups-for-existing-clusters.md
Labels: backport 3.1

#10332 adding obo permission to docs
  _security/access-control/authentication-tokens.md
Labels: backport 3.1

#10374 Fix collection links
  _layouts/default.html
Labels: backport 3.1

#10382 Add 2.19.3 to version history
  _about/version-history.md
Labels: backport 3.1

#10339 adding refresh request behavior
  _api-reference/index-apis/refresh.md
Labels: backport 3.1

#10321 Update documentation for the configurability of the semantic field.
  _field-types/supported-field-types/semantic.md
Labels: release-notes, v3.2.0

#10381 Add documentation for upper bound in hybrid query feature
  _search-plugins/search-pipelines/normalization-processor.md
Labels: release-notes, v3.2.0

#10390 Update introduction to UBI to emphasize that it is a schema, not a pl…
  _search-plugins/ubi/index.md
Labels: backport 3.1

#10388 Add `false_allow_templates` as a dynamic mapping option
  _field-types/mapping-parameters/dynamic.md
  _field-types/supported-field-types/nested.md
  _field-types/supported-field-types/object.md
Labels: release-notes, v3.2.0

#10201 adding percentile and percentile rank docs
  _aggregations/metric/percentile-ranks.md
  _aggregations/metric/percentile.md
Labels: Content gap, backport 3.1

#10333 Add faceted search tutorial
  _field-types/supported-field-types/index.md
  _tutorials/faceted-search.md
  images/faceted-search/faceted-search-exlclude.png
  images/faceted-search/faceted-search-filter.png
  images/faceted-search/faceted-search-hierarchical-flat.png
  images/faceted-search/faceted-search-hierarchical-nested.png
  images/faceted-search/faceted-search-maintain.png
Labels: backport 3.1

#10313 Revise OpenSearch authentication explanation
  _security/authentication-backends/openid-connect.md
Labels: backport 3.1

#10391 Document more openid settings
  _security/authentication-backends/openid-connect.md
Labels: backport 3.1

#10538 Add plugin dependency information
  _install-and-configure/install-dashboards/plugins.md
  _install-and-configure/plugins.md
Labels: backport 3.1

#10537 Update the document of the semantic field for a new parameter skip_existing_embedding
  _field-types/supported-field-types/semantic.md
Labels: release-notes, v3.2.0

#10278 Update source field descriptions in update by query API
  _api-reference/document-apis/update-by-query.md
Labels: backport 3.1
