Repository opensearch-project/documentation-website, pull requests merged in 2025-09, with the labels that each got.

#10187 Multi-Language Support for Spec-Insert -> Python
  DEVELOPER_GUIDE.md
  _api-reference/cat/cat-aliases.md
  _api-reference/cat/cat-allocation.md
  _api-reference/cat/cat-cluster_manager.md
  _api-reference/cat/cat-count.md
  _api-reference/cat/cat-field-data.md
  _api-reference/cat/cat-health.md
  _api-reference/cat/cat-indices.md
  _api-reference/cat/cat-nodeattrs.md
  _api-reference/cat/cat-nodes.md
  _api-reference/cat/cat-pending-tasks.md
  _api-reference/cat/cat-pit-segments.md
  _api-reference/cat/cat-plugins.md
  _api-reference/cat/cat-recovery.md
  _api-reference/cat/cat-repositories.md
  _api-reference/cat/cat-segment-replication.md
  _api-reference/cat/cat-segments.md
  _api-reference/cat/cat-shards.md
  _api-reference/cat/cat-snapshots.md
  _api-reference/cat/cat-tasks.md
  _api-reference/cat/cat-templates.md
  _api-reference/cat/cat-thread-pool.md
  _api-reference/document-apis/mtermvectors.md
  _api-reference/security/authentication/auth-info.md
  _api-reference/snapshots/clone-snapshot.md
  _api-reference/tasks/cancel-tasks.md
  _api-reference/tasks/get-tasks.md
  _api-reference/tasks/list-tasks.md
  spec-insert/lib/api/action.rb
  spec-insert/lib/doc_processor.rb
  spec-insert/lib/insert_arguments.rb
  spec-insert/lib/jekyll-spec-insert.rb
  spec-insert/lib/renderers/example_code.rb
  spec-insert/lib/renderers/example_code_python.rb
  spec-insert/lib/renderers/spec_insert.rb
  spec-insert/lib/renderers/templates/example_code.mustache
  spec-insert/lib/renderers/templates/example_code.python.mustache
  spec-insert/lib/utils.rb
  spec-insert/spec/_fixtures/expected_output/example_code.md
  spec-insert/spec/_fixtures/input/example_code.md
  spec-insert/spec/_fixtures/opensearch_spec.yaml
  spec-insert/spec/doc_processor_spec.rb
Labels: Tech review

#10868 fix: wrong default value for shard_path_type
  _api-reference/snapshots/create-repository.md
Labels: backport 3.2

#10881 Update link to vector search documentation
  _about/index.md
Labels: backport 3.2

#10870 Fix add agentic memory API
  _ml-commons-plugin/api/agentic-memory-apis/add-memory.md
Labels: backport 3.2

#10869 Update docker.md
  _install-and-configure/install-opensearch/docker.md
Labels: backport 3.2

#10888 Update documentation for msearch and search include_named_queries_score
  _api-reference/search-apis/multi-search.md
  _api-reference/search-apis/search.md
Labels: release-notes, v3.3.0

#10879 Add custom docker build option to logstash documentation
  _tools/logstash/index.md
Labels: backport 3.2

#10939 Add sparse_embedding_format param for sparse_encoding/sparse_tokenize model
  _ml-commons-plugin/pretrained-models.md
Labels: release-notes, v3.3.0

#10944 Add notes for dynamically updateable field params
  _field-types/supported-field-types/boolean.md
  _field-types/supported-field-types/completion.md
  _field-types/supported-field-types/date.md
  _field-types/supported-field-types/ip.md
  _field-types/supported-field-types/keyword.md
  _field-types/supported-field-types/numeric.md
  _field-types/supported-field-types/range.md
  _field-types/supported-field-types/text.md
  _field-types/supported-field-types/token-count.md
  _field-types/supported-field-types/wildcard.md
Labels: backport 3.2

#10953 adding info api docs
  _api-reference/cluster-api/info.md
Labels: backport 3.2

#10963 Renumber steps in dashboards index management
  _dashboards/im-dashboards/index.md
Labels: backport 3.2

#10949 chore: update Ruby to 3.4.5
  .github/workflows/jekyll-build.yml
  .github/workflows/jekyll-spec-insert.yml
  .github/workflows/link-checker.yml
  .github/workflows/update-api-components.yml
  CONTRIBUTING.md
  DEVELOPER_GUIDE.md
  Gemfile
  docker-compose.dev.yml
Labels: Doc review

#10958 Add capture_all_matches parameter for grok ingest processor
  _ingest-pipelines/processors/grok.md
Labels: release-notes, v3.3.0

#10980 Add link to tutorial from UBI index page
  _search-plugins/ubi/index.md
Labels: backport 3.2

#10989 Add more information to the analyzer mapping parameter
  _field-types/mapping-parameters/analyzer.md
Labels: backport 3.2

#10991 Refactor boost mapping parameter documentation
  _field-types/mapping-parameters/boost.md
Labels: backport 3.2

#10995 Refactor documentation for the enabled mapping parameter
  _field-types/mapping-parameters/enabled.md
Labels: backport 3.2

#11042 Refactor the 404 page
  404.md
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19, backport 3.0, backport 3.1, backport 3.2

#11049 Include latest in the URL of the older version warnings
  _layouts/default.html
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19, backport 3.0, backport 3.1, Code change, backport 3.2

#11043 Corrects the documentation for the otel_trace processor
  _data-prepper/pipelines/configuration/processors/otel-traces.md
Labels: backport 3.2

#11097 Update latest version in the warning link
  _layouts/default.html
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18

#11125 Add missing redirects
  _api-reference/analyze-apis.md
  _api-reference/cluster-api/cluster-decommission.md
  _api-reference/security/index.md
  _benchmark/reference/commands/index.md
  _benchmark/user-guide/index.md
  _dashboards/discover/index-discover.md
  _dashboards/management/advanced-settings.md
  _dashboards/quickstart.md
  _data-prepper/pipelines/configuration/processors/csv.md
  _data-prepper/pipelines/configuration/processors/processors.md
  _data-prepper/pipelines/configuration/sources/sources.md
  _ingest-pipelines/create-ingest.md
  _migrate-or-upgrade/index.md
  _migrate-or-upgrade/rolling-upgrade/index.md
  _ml-commons-plugin/agents-tools/tools/index.md
  _search-plugins/sql/ppl/functions.md
  _security/configuration/disable-enable-security.md
  _security/multi-tenancy/tenant-index.md
  _tuning-your-cluster/availability-and-recovery/remote-store/index.md
  _tuning-your-cluster/availability-and-recovery/workload-management/workload-group-rules.md
  _vector-search/api/index.md
  _vector-search/api/knn.md
Labels: Code change, backport 3.2

#11129 Add not working link to link checker
  _plugins/link-checker.rb
Labels: Code change, backport 3.2

#11037 Add docs for new item_count API for field data cache
  _api-reference/cluster-api/cluster-stats.md
  _api-reference/index-apis/stats.md
  _api-reference/nodes-apis/nodes-stats.md
  _search-plugins/caching/field-data-cache.md
Labels: release-notes, v3.3.0

#11039 adding links for password requirements
  _install-and-configure/install-opensearch/debian.md
  _install-and-configure/install-opensearch/helm.md
  _install-and-configure/install-opensearch/rpm.md
  _install-and-configure/install-opensearch/tar.md
  _install-and-configure/install-opensearch/windows.md
  _security/configuration/demo-configuration.md
Labels: backport 3.2

#10681 add OSB instructions to use session credentials
  _benchmark/user-guide/install-and-configure/configuring-benchmark.md
Labels: backport 3.2

#11117 Add documentation for agentic search processors
  _query-dsl/specialized/agentic.md
  _query-dsl/specialized/index.md
  _query-dsl/specialized/k-nn/index.md
  _search-plugins/search-pipelines/agentic-context-processor.md
  _search-plugins/search-pipelines/agentic-query-translator-processor.md
  _search-plugins/search-pipelines/search-processors.md
  _vector-search/ai-search/agentic-search.md
  _vector-search/api/neural.md
Labels: release-notes, v3.3.0
