Repository opensearch-project/documentation-website, pull requests merged in 2025-06, with the labels that each got.

#10006 fix instruction for terms query with roaring bitmap #8379
  _query-dsl/term/terms.md
Labels: backport 3.0

#9993 [Pull-based Ingestion] Update pull-based ingestion metrics and reset settings
  _api-reference/document-apis/pull-based-ingestion-management.md
  _api-reference/document-apis/pull-based-ingestion.md
Labels: 6 - Done but waiting to merge, release-notes, v3.1.0

#10017 Update sentence transformer pre-trained model version
  _ml-commons-plugin/agents-tools/agents-tools-tutorial.md
  _ml-commons-plugin/agents-tools/tools/vector-db-tool.md
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/pretrained-models.md
  _tutorials/gen-ai/chatbots/rag-conversational-agent.md
  _tutorials/vector-search/neural-search-tutorial.md
  _tutorials/vector-search/semantic-highlighting-tutorial.md
  _vector-search/getting-started/auto-generated-embeddings.md
  _vector-search/index.md
Labels: backport 3.0

#10028 Fix destructive name default
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: 4 - Doc review, backport 2.19, backport 3.0

#10032 Add editorial review for MA tweaks
  _migration-assistant/is-migration-assistant-right-for-you.md
Labels: backport 3.0

#10034 Backport 10017 to 2.19
  _ml-commons-plugin/agents-tools/agents-tools-tutorial.md
  _ml-commons-plugin/agents-tools/tools/vector-db-tool.md
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/pretrained-models.md
  _tutorials/gen-ai/chatbots/rag-conversational-agent.md
  _tutorials/vector-search/neural-search-tutorial.md
  _vector-search/getting-started/auto-generated-embeddings.md
  _vector-search/index.md
Labels: backport 2.17, backport 2.18

#10035 Backport 10017 to 2.18
  _ml-commons-plugin/agents-tools/agents-tools-tutorial.md
  _ml-commons-plugin/agents-tools/tools/vector-db-tool.md
  _ml-commons-plugin/api/model-apis/register-model.md
  _ml-commons-plugin/pretrained-models.md
  _ml-commons-plugin/tutorials/rag-conversational-agent.md
  _search-plugins/neural-search-tutorial.md
Labels: backport 2.17

#10011 Add Query Insights excluded_indices section
  _observing-your-data/query-insights/top-n-queries.md
Labels: 6 - Done but waiting to merge, release-notes, v3.1.0

#10042 Enforce Least Privilege in S3 Snapshot IAM Policy Example
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
Labels: backport 3.0

#10058 Add "aggregations" to weighted average aggregation page
  _aggregations/metric/weighted-avg.md
Labels: backport 3.0

#10052 Add CLI information to semantic search tutorials
  _tutorials/vector-search/semantic-search/long-document.md
  _tutorials/vector-search/semantic-search/semantic-search-bedrock-cohere.md
  _tutorials/vector-search/semantic-search/semantic-search-bedrock-titan.md
  _tutorials/vector-search/semantic-search/semantic-search-cohere.md
  _tutorials/vector-search/semantic-search/semantic-search-openai.md
  _tutorials/vector-search/semantic-search/semantic-search-sagemaker.md
Labels: backport 3.0

#10043 Introduce `fixed_char_length` algorithm in Text Chunking
  _ingest-pipelines/processors/text-chunking.md
Labels: release-notes, v3.1.0

#10012 Add zero-configure tools request body to document
  _ml-commons-plugin/api/mcp-server-apis/register-mcp-tools.md
Labels: backport 3.0

#10060 Add SSE-KMS and bucket owner verification docs
  _api-reference/snapshots/create-repository.md
Labels: release-notes, v3.1.0

#10054 Update searchable_snapshot.md
  _tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot.md
Labels: backport 3.0

#10072 Add clarity to Migration Assistant documentation by aligning contextId in example with default in deployed solution
  _migration-assistant/deploying-migration-assistant/getting-started-data-migration.md
Labels: backport 3.0

#10070 Update faiss-16-bit-quantization.md
  _vector-search/optimizing-storage/faiss-16-bit-quantization.md
Labels: backport 2.19, backport 3.0

#9836 add documentation for Rule lifecycle API for workload group
  _tuning-your-cluster/availability-and-recovery/workload-management/create-workload-group-rules-api.md
Labels: v3.1.0

#10064 Update opensearch-keystore.md - #8964
  _security/configuration/opensearch-keystore.md
Labels: security

#9985 Update supported methods for faiss
  _field-types/supported-field-types/knn-methods-engines.md
Labels: 4 - Doc review, backport 3.0

#9794 add rule based auto tagging user guide
  _tuning-your-cluster/availability-and-recovery/rule-based-autotagging/autotagging.md
Labels: release-notes, v3.1.0

#10010 Document how to handle breaking changes with mapping types
  _migration-assistant/migration-phases/planning-your-migration/handling-field-type-breaking-changes.md
  _migration-assistant/migration-phases/planning-your-migration/handling-type-mapping-deprecation.md
Labels: backport 3.0

#10062 Add doc for neural sparse search with 2 new analyzers
  _analyzers/supported-analyzers/dl-model-analyzers.md
  _analyzers/supported-analyzers/index.md
  _ingest-pipelines/processors/sparse-encoding.md
  _query-dsl/specialized/neural-sparse.md
  _vector-search/ai-search/neural-sparse-custom.md
  _vector-search/ai-search/neural-sparse-with-pipelines.md
  _vector-search/ai-search/neural-sparse-with-raw-vectors.md
Labels: release-notes, v3.1.0

#10073 Add collapse in hybrid query documentation
  _vector-search/ai-search/hybrid-search/collapse.md
Labels: release-notes, v3.1.0

#10102 Fix table formatting in register snapshot repository
  _api-reference/snapshots/create-repository.md
Labels: backport 3.0

#10110 Update documentation of parse json processor and few expression functions
  _data-prepper/pipelines/cidrcontains.md
  _data-prepper/pipelines/configuration/processors/parse-json.md
  _data-prepper/pipelines/contains.md
  _data-prepper/pipelines/expression-syntax.md
  _data-prepper/pipelines/functions.md
  _data-prepper/pipelines/get-metadata.md
  _data-prepper/pipelines/has-tags.md
  _data-prepper/pipelines/length.md
  _data-prepper/pipelines/pipelines.md
  _data-prepper/pipelines/startswith.md
Labels: backport 3.0

#10113 added ML agent update API
  _ml-commons-plugin/api/agent-apis/index.md
  _ml-commons-plugin/api/agent-apis/update-agent.md
Labels: release-notes, v3.1.0

#10079 Update neural stats API for 3.1
  _vector-search/api/neural.md
Labels: release-notes, v3.1.0

#10119 Introduce memory optimized vector search (LuceneOnFaiss) in 3.1.
  _field-types/supported-field-types/knn-memory-optimized.md
  _vector-search/optimizing-storage/memory-optimized-search.md
  _vector-search/performance-tuning-search.md
  _vector-search/settings.md
Labels: 6 - Done but waiting to merge, release-notes, v3.1.0

#10004 adding termvector and mtermvector api docs
  _api-reference/document-apis/mtermvectors.md
  _api-reference/document-apis/termvector.md
Labels: Content gap, backport 3.0

#10135 MCP connector is GA in 3.1
  _ml-commons-plugin/agents-tools/mcp/index.md
  _ml-commons-plugin/agents-tools/mcp/mcp-connector.md
Labels: release-notes, v3.1.0

#10132 [Star-tree] Support for nested aggs & Removing experimental flag.
  _field-types/supported-field-types/star-tree.md
  _search-plugins/star-tree-index.md
Labels: 3 - Tech review, release-notes, v3.1.0

#10155 Rewrite Dev Tools section
  _dashboards/dev-tools/index-dev.md
  _dashboards/dev-tools/run-queries.md
Labels: backport 3.1

#10156 Remove OpenSearch 3 as valid migration source in Migration Assistant Documentation
  _data/migration-assistant/valid_migrations.yml
Labels: backport 3.1
