Repository opensearch-project/documentation-website, pull requests merged in 2025-08, with the labels that each got.

#10549 Modify docker compose reference in quickstart and correct curl to http
  _getting-started/quickstart.md
  _vector-search/getting-started/index.md
Labels: backport 3.1

#10169 Refactor Migrations and Upgrades Documentation
  .github/vale/styles/Vocab/OpenSearch/Plugins/accept.txt
  .github/vale/styles/Vocab/OpenSearch/Products/accept.txt
  _api-reference/snapshots/index.md
  _benchmark/quickstart.md
  _config.yml
  _data/migration-scenarios.yml
  _includes/home_cards.html
  _includes/migration-scenarios.html
  _includes/nav.html
  _install-and-configure/configuring-opensearch/index.md
  _install-and-configure/index.md
  _install-and-configure/upgrade-opensearch/appendix/index.md
  _install-and-configure/upgrade-opensearch/index.md
  _layouts/default.html
  _migrate-or-upgrade/index.md
  _migrate-or-upgrade/migration-assistant/index.md
  _migrate-or-upgrade/rolling-upgrade/index.md
  _migrate-or-upgrade/rolling-upgrade/rolling-upgrade-lab.md
  _migrate-or-upgrade/snapshot-restore/index.md
  _migration-assistant/architecture.md
  _migration-assistant/deploying-migration-assistant/index.md
  _migration-assistant/index.md
  _migration-assistant/is-migration-assistant-right-for-you.md
  _migration-assistant/key-components.md
  _migration-assistant/migration-console/accessing-the-migration-console.md
  _migration-assistant/migration-console/index.md
  _migration-assistant/migration-console/migration-console-commands-references.md
  _migration-assistant/migration-phases/assessment/index.md
  _migration-assistant/migration-phases/backfill.md
  _migration-assistant/migration-phases/create-snapshot.md
  _migration-assistant/migration-phases/deploy/configuration-options.md
  _migration-assistant/migration-phases/deploy/iam-and-security-groups-for-existing-clusters.md
  _migration-assistant/migration-phases/deploy/index.md
  _migration-assistant/migration-phases/deploy/verifying-backfill-components.md
  _migration-assistant/migration-phases/deploy/verifying-live-capture-components.md
  _migration-assistant/migration-phases/index.md
  _migration-assistant/migration-phases/live-traffic-migration/index.md
  _migration-assistant/migration-phases/migrate-metadata/handling-field-type-breaking-changes.md
  _migration-assistant/migration-phases/migrate-metadata/handling-type-mapping-deprecation.md
  _migration-assistant/migration-phases/migrate-metadata/index.md
  _migration-assistant/migration-phases/planning-your-migration/assessing-your-cluster-for-migration.md
  _migration-assistant/migration-phases/planning-your-migration/index.md
  _migration-assistant/migration-phases/remove-migration-infrastructure.md
  _migration-assistant/migration-phases/replay-captured-traffic.md
  _migration-assistant/migration-phases/reroute-source-to-proxy.md
  _migration-assistant/migration-phases/reroute-traffic-from-capture-proxy-to-target.md
  _migration-assistant/overview/architecture.md
  _migration-assistant/overview/index.md
  _migration-assistant/overview/key-components.md
  _sass/custom/custom.scss
  _tuning-your-cluster/availability-and-recovery/remote-store/migrating-to-remote.md
  _tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore.md
  assets/js/nav-scroll.js
Labels: migration, backport 3.1

#10545 correct ISM job_interval description and default
  _im-plugin/ism/settings.md
Labels: Doc review, backport 3.1

#10542 adding index.sort options to the list
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: backport 3.1

#10543 adding new settings for hostname_verification
  _install-and-configure/configuring-opensearch/security-settings.md
  _install-and-configure/install-opensearch/docker.md
  _security/configuration/generate-certificates.md
  _security/configuration/tls.md
  _security/configuration/yaml.md
Labels: backport 3.1

#10554 10553 - [DOC]- Fix the Links Under Resources on the Footer
  _data/footer.yml
Labels: backport 1.3, backport 2.0, Doc review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19, backport 3.0, backport 3.1

#10591 Temporarly increase automerge timeout due to #10169 increase jekyll build time
  .github/workflows/automerge-backport.yml
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19, backport 3.1, enhancement

#10624 Fix more footer links
  _data/footer.yml
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19, backport 3.0, backport 3.1

#10386 Migration Assistant documentation for supporting ES 1.x and ES 2.x as source cluster versions
  _data/migration-assistant/breaking-changes.yml
  _data/migration-assistant/valid_migrations.yml
  _migration-assistant/assets/js/breaking-changes-data.js
  _migration-assistant/assets/js/breaking-changes-index.js
  _migration-assistant/assets/js/breaking-changes-module.js
  _migration-assistant/assets/js/breaking-changes-ui.js
  _migration-assistant/is-migration-assistant-right-for-you.md
  _migration-assistant/migration-console/migration-console-commands-references.md
  _migration-assistant/migration-phases/assessment/index.md
  _migration-assistant/migration-phases/deploy/configuration-options.md
  _migration-assistant/migration-phases/deploy/verifying-backfill-components.md
  _migration-assistant/migration-phases/index.md
  _migration-assistant/migration-phases/migrate-metadata/handling-field-type-breaking-changes.md
  _migration-assistant/migration-phases/migrate-metadata/handling-type-mapping-deprecation.md
  _migration-assistant/migration-phases/migrate-metadata/index.md
  _migration-assistant/migration-phases/remove-migration-infrastructure.md
Labels: migration, backport 3.1

#10667 Adding star-tree related stats documentation.
  _api-reference/nodes-apis/nodes-stats.md
Labels: release-notes, v3.2.0

#10512 Updating the index-parameter page
  _field-types/mapping-parameters/doc-values.md
  _field-types/mapping-parameters/index-parameter.md
Labels: release-notes, v3.2.0

#10672 Update the document of the semantic field to remove a limitation.
  _field-types/supported-field-types/semantic.md
Labels: release-notes, v3.2.0

#10673 Update workload management topic and doc review of workload management in dashboards
  _install-and-configure/additional-plugins/index.md
  _install-and-configure/configuring-opensearch/plugin-settings.md
  _tuning-your-cluster/availability-and-recovery/rule-based-autotagging/autotagging.md
  _tuning-your-cluster/availability-and-recovery/rule-based-autotagging/rule-lifecycle-api.md
  _tuning-your-cluster/availability-and-recovery/workload-management/create-workload-group-rules-api.md
  _tuning-your-cluster/availability-and-recovery/workload-management/wlm-feature-overview.md
  _tuning-your-cluster/availability-and-recovery/workload-management/workload-group-lifecycle-api.md
  _tuning-your-cluster/availability-and-recovery/workload-management/workload-group-rules.md
  _tuning-your-cluster/availability-and-recovery/workload-management/workload-groups.md
  _tuning-your-cluster/availability-and-recovery/workload-management/workload-management-dashboard.md
  images/Workload-Management/BoxplotTooltip.png
  images/Workload-Management/Create1.png
  images/Workload-Management/Create2.png
  images/Workload-Management/Overview.png
Labels: release-notes, v3.2.0

#10678 Remove underscore in copy_to heading
  _field-types/mapping-parameters/copy-to.md
Labels: backport 3.1

#10683 Fix Breadcrumb navigation for collections and reduce build time
  _config.yml
  _includes/nav.html
  _layouts/default.html
  _migration-assistant/migration-console/index.md
Labels: backport 3.1

#10657 k-NN Add ADC and Random Rotation documentation to binary quantization
  _vector-search/optimizing-storage/binary-quantization.md
Labels: release-notes, v3.2.0

#10653 TLS settings for gRPC
  _security/configuration/tls.md
Labels: release-notes, v3.2.0

#10684 adding docker examples for custom configuration
  _install-and-configure/configuring-opensearch/availability-recovery.md
  _install-and-configure/configuring-opensearch/index.md
  _install-and-configure/install-dashboards/docker.md
  _install-and-configure/install-dashboards/helm.md
  _install-and-configure/install-opensearch/docker.md
  _install-and-configure/install-opensearch/helm.md
Labels: backport 3.1

#10698 Update ACORN filtering optimization section in efficient filtering.
  _vector-search/filter-search-knn/efficient-knn-filtering.md
  _vector-search/filter-search-knn/index.md
Labels: backport 3.1

#10716 Updating helm commands to work with latest version
  _install-and-configure/install-dashboards/helm.md
  _install-and-configure/install-opensearch/helm.md
Labels: backport 3.1

#10722 adding clarification on quick start docs
  _getting-started/quickstart.md
Labels: backport 3.1

#10727 Trace analytics update for 3.2
  _observing-your-data/trace/ta-dashboards.md
  images/ta-application-setting-services.png
Labels: release-notes, v3.2.0

#10674 Add documentation for derived source in source field metadata
  _field-types/metadata-fields/source.md
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: release-notes, v3.2.0

#8800 Revamp docs as UBI has evolved.
  _search-plugins/ubi/data-structures.md
  _search-plugins/ubi/dsl-queries.md
  _search-plugins/ubi/index.md
  _search-plugins/ubi/schemas.md
  _search-plugins/ubi/sql-queries.md
  _search-plugins/ubi/ubi-dashboard-tutorial.md
  _search-plugins/ubi/ubi-javascript-collector.md
Labels: release-notes, v3.2.0

#10559 add explain pf key_name parameter for json codec of s3 source
  _data-prepper/pipelines/configuration/sources/s3.md
Labels: backport 3.1

#10747 Add field data cache page
  _search-plugins/caching/field-data-cache.md
Labels: backport 3.1

#10794 Edits to additional parameters
  _security/authentication-backends/openid-connect.md
Labels: backport 3.1

#10744 Add unsupported warning to 3.1
  _config.yml
Labels: release-3.2

#10742 Add 3.2 to version selector
  _data/versions.json
Labels: release-3.2

#10741 Add 3.2 to version history
  _about/version-history.md
Labels: release-3.2

#10749 Add `false_allow_templates` as a dynamic mapping option
  _field-types/mapping-parameters/dynamic.md
  _field-types/supported-field-types/nested.md
  _field-types/supported-field-types/object.md
Labels: release-notes, v3.3.0

#10756 expanding on the Discovery and gateway settings docs
  _install-and-configure/configuring-opensearch/discovery-gateway-settings.md
  _install-and-configure/install-opensearch/rpm.md
Labels: backport 3.2

#10785 Add queryPlanningTool
  _ml-commons-plugin/agents-tools/tools/query-planning-tool.md
Labels: release-notes, v3.2.0, backport 3.2

#10806 Remove experimental from grpc settings
  _api-reference/grpc-apis/index.md
Labels: backport 3.2

#10788 expanding on windows install docs
  _install-and-configure/install-dashboards/windows.md
  _install-and-configure/install-opensearch/windows.md
Labels: backport 3.2

#10803 adding cluster.no_cluster_manager_block docs
  _install-and-configure/configuring-opensearch/cluster-settings.md
Labels: backport 3.2

#10824 Fix errors in the pipeline code
  _data-prepper/common-use-cases/trace-analytics.md
Labels: backport 3.2

#10825 Add announcements/news search types based on latest posts index
  _layouts/search_layout.html
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19, backport 3.0, backport 3.1, enhancement, backport 3.2

#10805 Phase navigation for Migration Assistant
  _data/migration-scenarios.yml
  _includes/migration-phase-navigation.html
  _includes/migration-scenarios.html
  _migration-assistant/index.md
  _migration-assistant/is-migration-assistant-right-for-you.md
  _migration-assistant/key-components.md
  _migration-assistant/migration-phases/assessment/index.md
  _migration-assistant/migration-phases/backfill.md
  _migration-assistant/migration-phases/create-snapshot.md
  _migration-assistant/migration-phases/deploy/configuration-options.md
  _migration-assistant/migration-phases/deploy/iam-and-security-groups-for-existing-clusters.md
  _migration-assistant/migration-phases/deploy/index.md
  _migration-assistant/migration-phases/deploy/verifying-backfill-components.md
  _migration-assistant/migration-phases/deploy/verifying-live-capture-components.md
  _migration-assistant/migration-phases/index.md
  _migration-assistant/migration-phases/migrate-metadata/index.md
  _migration-assistant/migration-phases/remove-migration-infrastructure.md
  _migration-assistant/migration-phases/replay-captured-traffic.md
  _migration-assistant/migration-phases/reroute-source-to-proxy.md
  _migration-assistant/migration-phases/reroute-traffic-from-capture-proxy-to-target.md
Labels: migration, backport 3.2

#10861 Improve tiered spillover cache docs
  _search-plugins/caching/tiered-cache.md
Labels: backport 3.2

#10859 adding steps to cover debian and tarball install
  _migrate-or-upgrade/rolling-upgrade/index.md
Labels: backport 3.2
