Repository opensearch-project/documentation-website, pull requests merged in 2025-04, with the labels that each got.

#9523 Add documentation for Common Filter in HybridQueryBuilder
  _query-dsl/compound/hybrid.md
Labels: v3.0.0, 4 - Doc review

#9532 Add video and steps to vector search page
  _vector-search/index.md
Labels: backport 2.19

#9527 Remove Gantt charts in version 3.0
  _dashboards/management/multi-data-sources.md
  _dashboards/visualize/gantt.md
  _dashboards/visualize/viz-index.md
  _install-and-configure/install-dashboards/plugins.md
Labels: v3.0.0

#9546 Alerting plugin - Callout that per doc monitors don't support cross-cluster search.
  _observing-your-data/alerting/per-document-monitors.md
Labels: backport 2.19

#9550 Fix API URL in threat-intelligence/getting-started
  _security-analytics/threat-intelligence/getting-started.md
Labels: security, backport 2.19

#9549 Update security-settings.md
  _install-and-configure/configuring-opensearch/security-settings.md
Labels: security, backport 2.19

#9431 Update geocentroid aggregation.
  _aggregations/metric/geocentroid.md
Labels: Content gap, backport 2.19

#9536 ML Commons Neural Embeddings Tutorial update
  _about/breaking-changes.md
  _tutorials/vector-search/vector-operations/generate-embeddings.md
Labels: backport 2.19

#9499 adding token graph docs
  _analyzers/token-graph.md
  images/nyc-token-graph.png
  images/ssd-token-graph.png
Labels: Content gap, backport 2.19

#9561 Correct approximate k-NN training example
  _vector-search/vector-search-techniques/approximate-knn.md
Labels: backport 2.19

#9511 Add Supported Connectors
  _ml-commons-plugin/remote-models/blueprints.md
  _ml-commons-plugin/remote-models/connectors.md
  _ml-commons-plugin/remote-models/supported-connectors.md
Labels: backport 2.19

#9564 Remove deprecated `batch_size` from `_bulk` API
  _api-reference/document-apis/bulk.md
Labels: v3.0.0, 4 - Doc review, release-notes

#9565 Remove `type` parameter from `_bulk` documentation
  _api-reference/document-apis/bulk.md
Labels: backport 2.19

#9443 Add Breaking Changes viewer to assessing-your-cluster-for-migration.md
  _data/migration-assistant/breaking-changes.yml
  _data/migration-assistant/valid_migrations.yml
  _migration-assistant/assets/css/breaking-changes-selector.css
  _migration-assistant/assets/js/breaking-changes-data.js
  _migration-assistant/assets/js/breaking-changes-filter.js
  _migration-assistant/assets/js/breaking-changes-index.js
  _migration-assistant/assets/js/breaking-changes-module.js
  _migration-assistant/assets/js/breaking-changes-ui.js
  _migration-assistant/is-migration-assistant-right-for-you.md
  _migration-assistant/migration-phases/planning-your-migration/assessing-your-cluster-for-migration.md
Labels: 4 - Doc review, backport 2.19

#9581 add documentation on ML model states
  _ml-commons-plugin/api/model-apis/get-model.md
Labels: v3.0.0

#9584 docs(go.md): fix an error in the sample code between aws-sdk-go-v2 and opensearch-go/v4 that caused code to not compile.
  _clients/go.md
Labels: backport 2.19

#9588 Remove unused openssl security settings for 3.0.0
  _install-and-configure/configuring-opensearch/security-settings.md
  _security/configuration/tls.md
Labels: v3.0.0, release-notes

#9548 Documentation of inner hits with hybrid query
  _vector-search/ai-search/hybrid-search/aggregations.md
  _vector-search/ai-search/hybrid-search/explain.md
  _vector-search/ai-search/hybrid-search/inner-hits.md
  _vector-search/ai-search/hybrid-search/pagination.md
  _vector-search/ai-search/hybrid-search/post-filtering.md
  _vector-search/ai-search/hybrid-search/search-after.md
  _vector-search/ai-search/hybrid-search/sorting.md
Labels: v3.0.0, release-notes

#9371 Adding stop_replication action to ism documentation
  _im-plugin/ism/policies.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9585 Update kinesis.md to add documentation for new configuration
  _data-prepper/pipelines/configuration/sources/kinesis.md
Labels: backport 2.19

#9568 adding null_value mapping parameter docs
  _field-types/mapping-parameters/null-value.md
Labels: Content gap, backport 2.19

#9606 [DOC] document download URL for core plugins
  _install-and-configure/plugins.md
Labels: backport 2.19

#9609 Typo fix in plugins
  _install-and-configure/plugins.md
Labels: backport 2.19

#9578 adding store mapping parameter docs
  _field-types/mapping-parameters/store.md
Labels: Content gap, backport 2.19

#9616 Refactor vector search API section
  _api-reference/index.md
  _field-types/supported-field-types/knn-methods-engines.md
  _field-types/supported-field-types/knn-vector.md
  _search-plugins/search-pipelines/index.md
  _vector-search/ai-search/multimodal-search.md
  _vector-search/ai-search/semantic-search.md
  _vector-search/api/index.md
  _vector-search/api/knn.md
  _vector-search/vector-search-techniques/approximate-knn.md
Labels: backport 2.19

#9558 adding normalizer mapping parameter docs
  _field-types/mapping-parameters/normalizer.md
Labels: Content gap, backport 2.19

#9513 adding ignore_malformed field parameter
  _field-types/mapping-parameters/ignore-malformed.md
  _field-types/mapping-parameters/index.md
Labels: Content gap, backport 2.19

#9507 adding format mapping parameter docs
  _field-types/mapping-parameters/format.md
  _field-types/mapping-parameters/index.md
Labels: Content gap, backport 2.19

#9623 Match title of Benchmark page
  _benchmark/user-guide/optimizing-benchmarks/performance-testing-best-practices.md
Labels: backport 2.19

#9592 adding resolve index api docs #2114
  _api-reference/index-apis/resolve-index.md
Labels: Content gap, backport 2.19

#9559 adding norms mapping parameter docs
  _field-types/mapping-parameters/norms.md
Labels: Content gap, backport 2.19

#9611 adding docs on how to access data in pipeline
  _api-reference/ingest-apis/index.md
  _ingest-pipelines/accessing-data.md
Labels: Content gap, backport 2.19

#9579 adding term_vector mapping parameter docs
  _field-types/mapping-parameters/term-vector.md
Labels: Content gap, backport 2.19

#9512 adding index mapping parameter docs
  _field-types/mapping-parameters/doc-values.md
  _field-types/mapping-parameters/enabled.md
  _field-types/mapping-parameters/index-parameter.md
  _field-types/mapping-parameters/index.md
Labels: Content gap, backport 2.19

#9572 adding properties mapping parameter docs
  _field-types/mapping-parameters/properties.md
Labels: Content gap, backport 2.19

#9508 adding ignore_above mapping parameter docs
  _field-types/mapping-parameters/ignore-above.md
  _field-types/mapping-parameters/index.md
Labels: Content gap, backport 2.19

#9551 adding meta mapping parameter docs
  _field-types/mapping-parameters/meta.md
Labels: Content gap, backport 2.19

#9514 adding index_options mapping parameter docs
  _field-types/mapping-parameters/index-options.md
  _field-types/mapping-parameters/index.md
Labels: Content gap, backport 2.19

#9656 Reorder ingest pages and fix liquid error
  _ingest-pipelines/accessing-data.md
  _ingest-pipelines/pipeline-failures.md
  _ingest-pipelines/processors/index-processors.md
Labels: backport 2.19

#9655 Update the base URL in the config file
  _config.yml
Labels: backport 2.19

#9654 Use variables for doc links
  _aggregations/metric/geobounds.md
  _benchmark/user-guide/optimizing-benchmarks/performance-testing-best-practices.md
Labels: backport 2.19

#9165 Replace Ubuntu 20.04 with Ubuntu 24.04 as it will be deprecated soon
  _install-and-configure/os-comp.md
Labels: v3.0.0, documentation, backport 2.19, v2.19.2

#9651 Migration Assistant: Add info about managed service snapshots
  _migration-assistant/deploying-migration-assistant/configuration-options.md
Labels: 5 - Editorial review, backport 2.19

#9624 Add neural search stats API docs
  _vector-search/api/neural.md
Labels: v3.0.0, release-notes

#9678 Remove polyfill.io link from head custom
  _includes/head_custom.html
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 1.2, backport 1.1, backport 1.0, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19

#9674 Query Insights delete after & verbose param updates
  _observing-your-data/query-insights/top-n-queries.md
Labels: backport 2.19

#9672 Update 3.0.0 to use new pgp key for deb and rpm
  _install-and-configure/install-dashboards/debian.md
  _install-and-configure/install-dashboards/rpm.md
  _install-and-configure/install-opensearch/debian.md
  _install-and-configure/install-opensearch/rpm.md
Labels: upcoming release, v3.0.0

#9660 add link to blueprint doc
  _ml-commons-plugin/remote-models/supported-connectors.md
Labels: backport 2.19

#9677 Update terms.md re #17714
  _query-dsl/term/terms.md
Labels: backport 2.19

#9709 Add documentation for http.max_header_size
  _install-and-configure/configuring-opensearch/network-settings.md
Labels: v3.0.0, 4 - Doc review, release-notes

#9635 Add new Benchmark home pages
  _benchmark/index.md
  _benchmark/user-guide/index.md
  _benchmark/user-guide/optimizing-benchmarks/index.md
  _benchmark/user-guide/understanding-workloads/index.md
Labels: 5 - Editorial review, backport 2.19

#9721 Minor update for additional field with bring your own snapshot options
  _migration-assistant/deploying-migration-assistant/configuration-options.md
Labels: backport 2.19

#9658 Add live queries doc and update top queries doc
  _install-and-configure/configuring-opensearch/plugin-settings.md
  _observing-your-data/query-insights/index.md
  _observing-your-data/query-insights/live-queries.md
  _observing-your-data/query-insights/top-n-queries.md
Labels: v3.0.0, release-notes

#9728 Benchmark homepage bug
  _benchmark/user-guide/index.md
Labels: backport 2.19

#9737 Move Benchmark diagram to concepts
  _benchmark/user-guide/concepts.md
  _benchmark/user-guide/index.md
  _benchmark/user-guide/optimizing-benchmarks/index.md
  _benchmark/user-guide/understanding-workloads/index.md
  _benchmark/user-guide/working-with-workloads/index.md
Labels: backport 2.19

#9752 Fix bug on Migration Assistant page
  _migration-assistant/is-migration-assistant-right-for-you.md
Labels: 4 - Doc review, backport 2.19

#9749 Update cluster manager task throttling documentation to reflect enabled-by-default behavior (previously disabled)
  _tuning-your-cluster/cluster-manager-task-throttling.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9741 Add explain documentation for knn query
  _query-dsl/specialized/k-nn/index.md
  _query-dsl/specialized/k-nn/k-nn-explain.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9756 Add documentation about AD contextual launch feature
  _observing-your-data/ad/index.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9666 Updated the Doc for Dynamic Column Change
  _observing-your-data/query-insights/query-insights-dashboard.md
  images/Query-Insights/BothColDisplay.png
  images/Query-Insights/OnlyGroupColDisplay.png
  images/Query-Insights/OnlyQueryColDisplay.png
Labels: v3.0.0, 5 - Editorial review

#9761 Derived Source is Enabled By Default from 3.0.0
  _vector-search/settings.md
Labels: v3.0.0, release-notes

#9649 [GRPC] Add documentation for GRPC plugin, and Bulk+Search GRPC APIs
  _api-reference/document-apis/bulk.md
  _api-reference/grpc-apis/bulk.md
  _api-reference/grpc-apis/index.md
  _api-reference/grpc-apis/search.md
  _api-reference/index.md
  _ingest-pipelines/accessing-data.md
Labels: v3.0.0, release-notes, experimental

#9634 Added index and cluster settings related to RW separation
  _install-and-configure/configuring-opensearch/cluster-settings.md
  _install-and-configure/configuring-opensearch/index-settings.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9675 Update the similarity algorithm details
  _search-plugins/keyword-search.md
Labels: v3.0.0, 5 - Editorial review, release-notes

#9575 Add vectorsearch Remote Index Build docs
  _vector-search/api/knn.md
  _vector-search/remote-index-build.md
  _vector-search/settings.md
Labels: v3.0.0, 5 - Editorial review, release-notes, experimental

#9792 Replace CatIndexTool with ListIndexTool
  _about/breaking-changes.md
  _automating-configurations/workflow-tutorial.md
  _ml-commons-plugin/agents-tools/index.md
  _ml-commons-plugin/agents-tools/tools/index.md
  _ml-commons-plugin/agents-tools/tools/list-index-tool.md
  _ml-commons-plugin/api/agent-apis/register-agent.md
  _ml-commons-plugin/api/memory-apis/get-message-traces.md
  _tutorials/gen-ai/chatbots/build-chatbot.md
Labels: v3.0.0, release-notes
