Repository opensearch-project/documentation-website, pull requests merged in 2025-01, with the labels that each got.

#8984 Add documentation for pruning neural sparse vectors
  _ingest-pipelines/processors/sparse-encoding.md
  _search-plugins/neural-sparse-with-pipelines.md
  _search-plugins/search-pipelines/neural-sparse-query-two-phase-processor.md
Labels: 5 - Editorial review, release-notes, v2.19.0

#8986 Add documentation for search_idle_reactivate_count_total
  _api-reference/nodes-apis/nodes-stats.md
Labels: 5 - Editorial review, backport 2.18

#8350 [DOC] Tokenizers - Character group
  _analyzers/tokenizers/character-group.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers, backport 2.18

#8998 Update rollover.md
  _api-reference/index-apis/rollover.md
Labels: backport 2.15, backport 2.16, backport 2.17, backport 2.18

#8378 [DOC] Tokenizer - Edge-n-gram
  _analyzers/tokenizers/edge-n-gram.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers, backport 2.18

#8357 [DOC] Tokenizers - Classic
  _analyzers/tokenizers/classic.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers

#8396 [DOC] Tokenizer - Keyword
  _analyzers/tokenizers/keyword.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers

#8556 [DOC] Character filters - Mapping
  _analyzers/character-filters/html-character-filter.md
  _analyzers/character-filters/mapping-character-filter.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers

#8498 [DOC] Tokenizer - Letter
  _analyzers/tokenizers/letter.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers, backport 2.18

#8557 [DOC] Character filters - Pattern replace
  _analyzers/character-filters/pattern-replace-character-filter.md
Labels: 3 - Tech review, Needs SME, Content gap, analyzers

#9023 Fix index mapping parameter option
  _field-types/mapping-parameters/index.md
Labels: backport 1.3, 4 - Doc review, backport 2.18

#9017 Add supported regions for Migration Assistant
  _migration-assistant/is-migration-assistant-right-for-you.md
Labels: 4 - Doc review, backport 2.18

#9031 Update permissions.md
  _security/access-control/permissions.md
Labels: backport 2.18

#8985 Update knn-vector-quantization.md
  _search-plugins/knn/knn-vector-quantization.md
Labels: 4 - Doc review, backport 2.18

#9035 Update parameter name in k-NN vector quantization
  _search-plugins/knn/knn-vector-quantization.md
Labels: backport 2.18

#8982 Update Linear and Logistic Regression Parameters & Improve Documentation
  _ml-commons-plugin/algorithms.md
Labels: backport 2.18

#9029 Add support for Bedrock Rerank API #9027
  _ml-commons-plugin/tutorials/index.md
  _ml-commons-plugin/tutorials/reranking-bedrock.md
Labels: release-notes, v2.19.0

#9021 Fix incorrect documentation about query cache stats
  _api-reference/nodes-apis/nodes-stats.md
Labels: backport 2.18

#8990 Add documentation for OSB query randomization
  _benchmark/user-guide/optimizing-benchmarks/randomizing-queries.md
Labels: 5 - Editorial review, benchmark

#9043 Fix HTTP verb and path for snapshot restore API docs
  _api-reference/snapshots/restore-snapshot.md
Labels: backport 2.18

#9055 Add a clarifying statement to search getting started
  _getting-started/search-data.md
Labels: backport 2.18

#9057 Correct formatting for retrieve specific fields
  _search-plugins/searching-data/retrieve-specific-fields.md
Labels: backport 2.18

#9061 [Doc] Update Ada Grad as the default optimiser.
  _ml-commons-plugin/algorithms.md
Labels: release-notes, v2.19.0

#9052 Add Query Insights local index delete after documentation
  _observing-your-data/query-insights/top-n-queries.md
Labels: release-notes, v2.19.0

#9054 Add guardrails tutorial
  _ml-commons-plugin/remote-models/guardrails.md
  _ml-commons-plugin/tutorials/bedrock-guardrails.md
  _ml-commons-plugin/tutorials/index.md
Labels: backport 2.18

#9068 Fix incorrect data summary agent configuration
  _dashboards/dashboards-assistant/data-summary.md
Labels: backport 2.18

#9066 Branch9065
  _search-plugins/knn/knn-vector-quantization.md
Labels: backport 2.17, backport 2.18

#9072 Correct formatting for nodes-stats.md
  _api-reference/nodes-apis/nodes-stats.md
Labels: backport 2.18

#9053 Adding documentation about explain in hybrid query and hybrid_score_explanation processor
  _search-plugins/hybrid-search.md
  _search-plugins/search-pipelines/explanation-processor.md
  _search-plugins/search-pipelines/personalize-search-ranking.md
  _search-plugins/search-pipelines/rag-processor.md
  _search-plugins/search-pipelines/search-processors.md
Labels: release-notes, v2.19.0

#8994 Add documentation for workspace privacy
  _dashboards/workspace/workspace-acl.md
Labels: 5 - Editorial review, release-notes, v2.19.0

#9075 Update _search query match field in Documentation
  _field-types/supported-field-types/text.md
Labels: backport 2.18

#9078 Update k-NN Cosine formula
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/knn-score-script.md
Labels: release-notes, v2.19.0

#9085 Refactor the search section
  _config.yml
  _search-plugins/collapse-search.md
  _search-plugins/filter-search.md
  _search-plugins/searching-data/autocomplete.md
  _search-plugins/searching-data/did-you-mean.md
  _search-plugins/searching-data/highlight.md
  _search-plugins/searching-data/index.md
  _search-plugins/searching-data/inner-hits.md
  _search-plugins/searching-data/paginate.md
  _search-plugins/searching-data/point-in-time-api.md
  _search-plugins/searching-data/point-in-time.md
  _search-plugins/searching-data/retrieve-specific-fields.md
  _search-plugins/searching-data/search-shard-routing.md
  _search-plugins/searching-data/sort.md
Labels: backport 2.18

#9095 Fix an invalid markdown style in _security/configuration/yaml.md
  _security/configuration/yaml.md
Labels: backport 2.18

#9060 CAT API automation (Part II)
  _api-reference/cat/cat-aliases.md
  _api-reference/cat/cat-allocation.md
  _api-reference/cat/cat-cluster_manager.md
  _api-reference/cat/cat-count.md
  _api-reference/cat/cat-field-data.md
  _api-reference/cat/cat-health.md
  _api-reference/cat/cat-indices.md
  _api-reference/cat/cat-nodeattrs.md
  _api-reference/cat/cat-nodes.md
  _api-reference/cat/cat-pending-tasks.md
  _api-reference/cat/cat-pit-segments.md
  _api-reference/cat/cat-plugins.md
  _api-reference/cat/cat-recovery.md
  _api-reference/cat/cat-repositories.md
  _api-reference/cat/cat-segment-replication.md
  _api-reference/cat/cat-segments.md
  _api-reference/cat/cat-shards.md
  _api-reference/cat/cat-snapshots.md
  _api-reference/cat/cat-tasks.md
  _api-reference/cat/cat-templates.md
  _api-reference/cat/cat-thread-pool.md
  spec-insert/lib/renderers/parameter_table_renderer.rb
  spec-insert/lib/renderers/table_renderer.rb
  spec-insert/lib/renderers/templates/path_parameters.mustache
  spec-insert/lib/renderers/templates/query_parameters.mustache
  spec-insert/spec/_fixtures/expected_output/param_tables.md
Labels: 4 - Doc review, backport 2.18

#9079 Update hot reload documentation to show how DN validation can be skipped
  _security/configuration/tls.md
Labels: 5 - Editorial review, release-notes, v2.19.0

#9113 Update Kafka topics param auto_offset_reset default value
  _data-prepper/pipelines/configuration/sources/kafka.md
Labels: backport 2.18

#9133 Update pipeline.md - Source mistakenly described as sink
  _data-prepper/pipelines/configuration/sources/pipeline.md
Labels: backport 2.18

#9119 Add template query
  _query-dsl/specialized/template.md
  _search-plugins/querqy/index.md
  _search-plugins/search-relevance/index.md
  _search-plugins/search-relevance/query-rewriting.md
  _search-plugins/search-relevance/template-query.md
Labels: release-notes, v2.19.0

#9102 Add binary Lucene vector updates for 2.19
  _search-plugins/knn/knn-index.md
Labels: release-notes, v2.19.0

#9109 Adding documentation for Pagination in hybrid query
  _search-plugins/hybrid-search.md
Labels: release-notes, v2.19.0

#9117 Add RRF documentation for hybrid search
  _search-plugins/hybrid-search.md
  _search-plugins/search-pipelines/score-ranker-processor.md
Labels: 4 - Doc review, release-notes, v2.19.0

#9130 Add verbose_pipeline documentation section in using-search-pipeline
  _search-plugins/search-pipelines/debugging-search-pipeline.md
Labels: release-notes, v2.19.0
