Repository opensearch-project/documentation-website, pull requests merged in 2025-02, with the labels that each got.

#9120 Query Insights 2.19 documentation
  _observing-your-data/query-insights/grouping-top-n-queries.md
  _observing-your-data/query-insights/health.md
  _observing-your-data/query-insights/top-n-queries.md
Labels: release-notes, v2.19.0

#9138 Add Documentation for `wait_for_completion_timeout` Parameter
  _automating-configurations/api/create-workflow.md
  _automating-configurations/api/provision-workflow.md
Labels: release-notes, v2.19.0

#9103 Add in-place SSL certs hot reload documentation
  _security/configuration/tls.md
Labels: 5 - Editorial review, release-notes, v2.19.0

#9137 Add feature direction to AD docs
  _observing-your-data/ad/index.md
  images/anomaly-detection/add-feature-with-relative-rules.png
  images/anomaly-detection/add-suppression-rules-absolute.png
Labels: 5 - Editorial review, release-notes, v2.19.0

#9107 Mark nmslib references for vector search as deprecated
  _field-types/supported-field-types/knn-vector.md
  _ml-commons-plugin/remote-models/async-batch-ingestion.md
  _search-plugins/knn/api.md
  _search-plugins/knn/approximate-knn.md
  _search-plugins/knn/filter-search-knn.md
  _search-plugins/knn/knn-index.md
  _search-plugins/knn/knn-vector-quantization.md
  _search-plugins/vector-search.md
Labels: release-notes, v2.19.0

#9151 Update threshold for 2.19
  _search-plugins/knn/knn-index.md
Labels: release-notes, v2.19.0

#9144 documentation for plugin as a service
  _config.yml
  _developer-documentation/index.md
  _developer-documentation/plugin-as-a-service/index.md
Labels: release-notes, v2.19.0

#9140 add documentation for AD flatten result index feature
  _observing-your-data/ad/index.md
  _observing-your-data/ad/result-mapping.md
Labels: 5 - Editorial review, release-notes, v2.19.0

#9152 Updated docs to provide details for using index_thread_qty for Lucene library
  _search-plugins/knn/settings.md
Labels: release-notes, v2.19.0

#9156 Add Convert Index to remote documentation
  _im-plugin/ism/policies.md
Labels: 5 - Editorial review, release-notes, v2.19.0

#9167 Update Kafka Buffer's auto_offset_reset default value
  _data-prepper/pipelines/configuration/buffers/kafka.md
Labels: backport 2.18

#9148 Add avx512_spr documentation
  _search-plugins/knn/knn-index.md
Labels: 6 - Done but waiting to merge, release-notes, v2.19.0

#9157 [Doc] QueryInsightsDashboard
  _observing-your-data/query-insights/query-insights-dashboard.md
  images/Query-Insights/Configuration.png
  images/Query-Insights/GroupQueryDetails.png
  images/Query-Insights/IndividualQueryDetails.png
  images/Query-Insights/Querieslist.png
  images/Query-Insights/QueryInsights.png
Labels: 5 - Editorial review, release-notes, v2.19.0

#9175 Add 2.19 documentation release notes
  release-notes/opensearch-documentation-release-notes-2.19.0.md
Labels: backport 2.19

#9173 Add 2.19 to version history.
  _about/version-history.md
Labels: backport 1.3, backport 2.0, 4 - Doc review, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, v2.19.0, backport 2.18, backport 2.19

#9199 Fix latest version
  _data/versions.json
Labels: backport 2.19

#9200 Fix query insights image link error
  _observing-your-data/query-insights/query-insights-dashboard.md
Labels: backport 2.19

#9206 Add description for safely deleting model
  _ml-commons-plugin/api/model-apis/delete-model.md
  _ml-commons-plugin/cluster-settings.md
Labels: v2.19.0, backport 2.19

#9205 float and double field type don’t accept special values like NaN nor Infinity
  _field-types/index.md
Labels: backport 2.19

#9210 Add blog post link to score ranker processor for hybrid search
  _search-plugins/search-pipelines/score-ranker-processor.md
Labels: backport 2.19

#9211 Cross-reference wildcard field type; correct URL for Expensive queries
  _query-dsl/term/wildcard.md
Labels: backport 2.19

#9209 Add if paramter to text-embedding processor doc
  _ingest-pipelines/processors/text-embedding.md
Labels: backport 2.19

#9221 Fix command formatting on Data Prepper page
  _data-prepper/pipelines/configuration/sources/http.md
Labels: 4 - Doc review, backport 2.19

#9222 Add missing ISM permission
  _security/access-control/permissions.md
Labels: backport 1.3, 4 - Doc review, backport 2.19

#9225 Fix table in trim processor
  _ingest-pipelines/processors/trim.md
Labels: backport 2.19

#9227 Update docker compose commands to docker commands
  _getting-started/quickstart.md
  _install-and-configure/install-dashboards/docker.md
  _install-and-configure/install-opensearch/docker.md
  _observing-your-data/log-ingestion.md
  _observing-your-data/trace/getting-started.md
  _search-plugins/cross-cluster-search.md
  _security/authentication-backends/ldap.md
  _security/authentication-backends/openid-connect.md
  _security/authentication-backends/saml.md
  _security/configuration/demo-configuration.md
  _security/configuration/disable-enable-security.md
  _tuning-your-cluster/replication-plugin/getting-started.md
  _upgrade-to/docker-upgrade-to.md
Labels: backport 2.19

#8606 Remove obsolete compose version specifier in Example docker-compose.yaml
  _install-and-configure/install-opensearch/docker.md
Labels: backport 2.19

#9229 Fix the trim processor table
  _ingest-pipelines/processors/trim.md
Labels: backport 2.19

#9219 Extract major version in installation section into a variable
  _install-and-configure/install-opensearch/docker.md
Labels: backport 2.19

#9032 Fix index name in bitmap filtering docs
  _query-dsl/term/terms.md
Labels: backport 2.19

#8821 version definition is no longer used by Docker Compose
  assets/examples/docker-compose.yml
  docker-compose.dev.yml
Labels: On hold

#9213 Add doc for update model interface
  _ml-commons-plugin/api/model-apis/update-model.md
Labels: backport 2.19

#9217 Update text-embedding processor parameters list
  _ingest-pipelines/processors/text-embedding.md
Labels: backport 2.19

#9202 Update exampe metric aggregation query
  _search-plugins/star-tree-index.md
Labels: 4 - Doc review, backport 2.19

#9239 Clarify fetch_size support for SQL
  _search-plugins/sql/sql-ppl-api.md
Labels: backport 2.19

#9271 Correct footer text per the Linux Foundation
  _includes/footer.html
Labels: backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 1.2, backport 1.1, backport 1.0, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19

#9270 Update datatypes.md
  _search-plugins/sql/datatypes.md
Labels: backport 2.19

#9304 Clarify how a boolean query's must_not works with multiple clauses
  _query-dsl/compound/bool.md
Labels: backport 2.19

#9308 Add semantic search tutorials
  .github/vale/styles/Vocab/OpenSearch/Products/accept.txt
  _ml-commons-plugin/remote-models/guardrails.md
  _ml-commons-plugin/tutorials/chatbots/build-chatbot.md
  _ml-commons-plugin/tutorials/chatbots/index.md
  _ml-commons-plugin/tutorials/chatbots/rag-chatbot.md
  _ml-commons-plugin/tutorials/chatbots/rag-conversational-agent.md
  _ml-commons-plugin/tutorials/conversational-search/conversational-search-cohere.md
  _ml-commons-plugin/tutorials/conversational-search/index.md
  _ml-commons-plugin/tutorials/index.md
  _ml-commons-plugin/tutorials/model-controls/bedrock-guardrails.md
  _ml-commons-plugin/tutorials/model-controls/index.md
  _ml-commons-plugin/tutorials/rag/index.md
  _ml-commons-plugin/tutorials/rag/rag-deepseek-chat.md
  _ml-commons-plugin/tutorials/rag/rag-deepseek-r1-bedrock.md
  _ml-commons-plugin/tutorials/rag/rag-deepseek-r1-sagemaker.md
  _ml-commons-plugin/tutorials/reranking/index.md
  _ml-commons-plugin/tutorials/reranking/reranking-bedrock.md
  _ml-commons-plugin/tutorials/reranking/reranking-cohere.md
  _ml-commons-plugin/tutorials/reranking/reranking-cross-encoder.md
  _ml-commons-plugin/tutorials/semantic-search/index.md
  _ml-commons-plugin/tutorials/semantic-search/semantic-search-bedrock-cohere.md
  _ml-commons-plugin/tutorials/semantic-search/semantic-search-bedrock-titan-other.md
  _ml-commons-plugin/tutorials/semantic-search/semantic-search-bedrock-titan.md
  _ml-commons-plugin/tutorials/semantic-search/semantic-search-cfn-sagemaker.md
  _ml-commons-plugin/tutorials/semantic-search/semantic-search-cohere.md
  _ml-commons-plugin/tutorials/semantic-search/semantic-search-openai.md
  _ml-commons-plugin/tutorials/semantic-search/semantic-search-sagemaker.md
  _ml-commons-plugin/tutorials/vector-operations/generate-embeddings.md
  _ml-commons-plugin/tutorials/vector-operations/index.md
  _ml-commons-plugin/tutorials/vector-operations/semantic-search-byte-vectors.md
  images/vector-search-tutorials/mapping_iam_role_arn.png
  images/vector-search-tutorials/semantic_search_remote_model_Integration_1.png
  images/vector-search-tutorials/semantic_search_remote_model_Integration_2.png
  images/vector-search-tutorials/semantic_search_remote_model_Integration_3.png
Labels: backport 2.19

#9246 fix ml inference parameters description
  _ingest-pipelines/processors/ml-inference.md
  _ml-commons-plugin/api/model-apis/update-model.md
  _search-plugins/search-pipelines/ml-inference-search-request.md
  _search-plugins/search-pipelines/ml-inference-search-response.md
Labels: backport 2.19

#9310 Add 2.19.1 version
  _config.yml
Labels: backport 2.19

#9311 Add 2.19.1 to version history
  _about/version-history.md
Labels: backport 2.19

#9224 Execution hint documentation added to cardinality agg
  _aggregations/metric/cardinality.md
Labels: 6 - Done but waiting to merge, v2.19.1, backport 2.19
